### PR TITLE
GitHub: fix issues/pr searching

### LINKED ISSUE #6: brew search : 422 Unprocessable Entity
when i try to search for a formula it returns with an error : 

brew search dsniff
No formula found for "dsniff".
==> Searching pull requests...
Error: 422 Unprocessable Entity
Validation Failed

### PR DESCRIPTION
**Pull request by xu-cheng**
Closes #6.

### CODE REVIEW

File: Library/Homebrew/utils.rb [hunk 1]
```diff
@@ -663,7 +663,7 @@ def build_query_string(query, qualifiers)
 
   def build_search_qualifier_string(qualifiers)
     {
-      :repo => "Homebrew/homebrew",
+      :repo => "Homebrew/brew",
```
Comment (UniqMartin) [inline Library/Homebrew/utils.rb]: If I understand correctly, this is invoked on a failed search for a formula (at least judging from the referenced issue), so searching in `Homebrew/homebrew-core` seems to make more sense. `Homebrew/brew` is not going to yield any sensible results for searching involving formula names, right?

Comment (xu-cheng) [inline Library/Homebrew/utils.rb]: You are right.
