### PR TITLE
cli/parser: Don't treat args with `--cask` as formulae

### LINKED ISSUE #14438: Formula renames are checked even when `--cask` is given
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-122-g1c85a71
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c85a717ccd49fa0900379896284012b3f43f920
Last commit: 35 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### What were you trying to do (and why)?

Run `brew install --cask racket` to install the cask `racket`.

Why not just `brew install racket`? Because it will install formula `minimal-racket` according to an entry `"racket": "minimal-racket"` in [`formula_renames.json`](https://github.com/Homebrew/homebrew-core/blob/820fbff6f3655f536ccc3abeb06b6197bee9bae5/formula_renames.json#L131).

### What happened (include all command output)?

A warning is thrown,
```
Warning: Use minimal-racket instead of deprecated racket
```
This warning is so misleading that I'm not the only one that believed the formula `minimal-racket` will be installed. But actually it still installs cask `racket`. See https://github.com/orgs/Homebrew/discussions/3510.

```
Warning: Use minimal-racket instead of deprecated racket
==> Downloading https://mirror.racket-lang.org/installers/8.7/racket-8.7-x86_64-macosx-cs.
######################################################################## 100.0%
==> Installing Cask racket
==> Moving App Suite 'Racket v8.7' to '/Applications/Racket v8.7'
==> Linking Binary 'drracket' to '/usr/local/bin/drracket'
...
==> Linking Manpage 'drracket.1' to '/usr/local/share/man/man1/drracket.1'
...
🍺  racket was successfully installed!
```

### What did you expect to happen?

When `--cask` is used, don't check and prompt about formula renaming.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run `brew install --cask --dry-run racket` and you'll see

Warning: Use minimal-racket instead of deprecated racket
```

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- Fixes #14438.

- For the command `brew install --cask racket`, a user was reporting the behaviour where despite `--cask` in the command, they were getting output about the `racket` formula having been renamed:

```
$ brew install --cask racket
Warning: Use minimal-racket instead of deprecated racket
==> Downloading https://mirror.racket-lang.org/installers/8.7/racket-8.7-x86_64-macosx-cs.
==> Installing Cask racket
[...]
racket was successfully installed!
```

- The "instead of deprecated ..." messaging comes from the `TapLoader` class `formula_name_path` method, so _something_ must be assuming that everything is initially a formula before _later_ learning from further args parsing that there's a `--cask` qualifier to scope to only casks.

- There are always `@formula_options` and args parsing is recursive, going through each option, so we check that the original `argv` items include a `--cask` and don't descend into the `if` that calls the `formulae` method (and hence the other formula-related checks) if that's the case.

- After this change, the "formula renames" words no longer show up.

```
$ brew install --cask racket
==> Downloading https://mirror.racket-lang.org/installers/8.7/racket-8.7-aarch64-macosx-cs.dmg
==> Installing Cask racket
[...]
racket was successfully installed!
```

### CODE REVIEW

File: Library/Homebrew/cli/parser.rb [hunk 1]
```diff
@@ -298,9 +298,10 @@ def parse_remaining(argv, ignore_invalid_options: false)
       def parse(argv = ARGV.freeze, ignore_invalid_options: false)
         raise "Arguments were already parsed!" if @args_parsed
 
-        # If we accept formula options, parse once allowing invalid options
-        # so we can get the remaining list containing formula names.
-        if @formula_options
+        # If we accept formula options, but the command isn't scoped only
+        # to casks, parse once allowing invalid options so we can get the
+        # remaining list containing formula names.
+        if @formula_options && argv.exclude?("--cask")
```
Comment (apainintheneck) [inline Library/Homebrew/cli/parser.rb:304]: Probably would be a good idea to check for `--casks` as well.

**Review by apainintheneck — COMMENTED** [review]
This looks good once `--casks` is covered as well.

When I was looking into this yesterday I went down the rabbit hole trying to understand why this extra parsing pass was necessary and it seems to be related to preloading custom options before validating them.

https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies

This seems like it isn't used at all in `homebrew-core` since it makes it harder to test formulae on CI. I wonder if there is some way to either move this check out of the parser or even deprecate the ability to create custom options if they aren't widely used (I honestly have no idea right now). Of course, that is way beyond the scope of this PR.

**Comment by issyl0** [comment]
> When I was looking into this yesterday I went down the rabbit hole

Yeah, same, I was like 🤯 ⁉️. 😆

> [Options] seems like it isn't used at all in homebrew-core since it makes it harder to test formulae on CI.

Yeah, options were removed from core formulae some years ago, but they're still allowed in third-party taps as we don't have to test those.

**Review by apainintheneck — APPROVED** [review]

**Comment by muzimuzhi** [comment]
many thanks!

**Review by MikeMcQuaid — COMMENTED** [review]
Great work, thanks again @issyl0!
