### PR TITLE
dependency_collector: distinguish macOS deps by OS

### LINKED ISSUE #15907: `uses_from_macos` bounds sometimes not being included in API
### `brew doctor` output

```shell
vagrant@ubuntu2004:~$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.6-16-g3c8b494
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3c8b4949baefb1f8166749ff1a3f0665afadedda
Last commit: 33 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c8e9f2ee933344b4603d983eb6db650f3edc359f
Core tap last commit: 17 minutes ago
Core tap branch: master
Core tap JSON: 24 Aug 16:23 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.4.0-122-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: 2.35_1
gcc@11: N/A
gcc: 13.1.0
xorg: N/A
```

### What were you trying to do (and why)?

Seeing some oddities in how some `uses_from_macos` dependencies are being presented in the API, and I'm unsure how to reproduce locally. Take a look at `glib`: 
```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info glib --json | jq '.[0].uses_from_macos_bounds'
[
  {
    "since": "catalina"
  },
  {
    "since": "catalina"
  }
]
```
This correctly reflects the formula definition. However, https://formulae.brew.sh/api/formula/glib.json shows the constraint only applying to python, but not libffi. 

Other formulae that define `uses_from_macos` with `since:` seem to consistently be output correctly or not, depending on the dependency, e.g. the API is correct for `bowtie2` (uses python), `git-filter-repo` (uses git) and `gnustep-base` (uses icu4c); but not for `braid` (uses ruby), `git` (uses curl and zlib), `gnupg` (uses sqlite), `vapor` (uses swift), `micromamba` (uses libarchive), `rex` (uses perl) and `tkdiff` (uses tcl-tk). 

### What happened (include all command output)?

See above.

### What did you expect to happen?

The output of `brew info glib --json | jq '.[0].uses_from_macos_bounds'` should be consistent whether the API is being used or not.

### Step-by-step reproduction instructions (by running `brew` commands)

Compare the results of: 
```shell
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info glib --json | jq '.[0].uses_from_macos_bounds'
[
  {
    "since": "catalina"
  },
  {
    "since": "catalina"
  }
]
```
with:
```
$ HOMEBREW_NO_INSTALL_FROM_API= brew info glib --json | jq '.[0].uses_from_macos_bounds'
[
  {},
  {
    "since": "catalina"
  }
]
```

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
`uses_from_macos` dependencies need to indicate their OS bounds when being cached. Fixes #15907. 

```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info gitless glib --json | jq '.[].uses_from_macos_bounds'
[
  {}
]
[
  {
    "since": "catalina"
  },
  {
    "since": "catalina"
  }
]

$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info glib gitless --json | jq '.[].uses_from_macos_bounds'
[
  {
    "since": "catalina"
  },
  {
    "since": "catalina"
  }
]
[
  {}
]
```

### CODE REVIEW

File: Library/Homebrew/dependency_collector.rb [hunk 1]
```diff
@@ -65,6 +65,8 @@ def fetch(spec)
   def cache_key(spec)
     if spec.is_a?(Resource) && spec.download_strategy <= CurlDownloadStrategy
       File.extname(spec.url)
+    elsif spec.is_a?(UsesFromMacOSDependency)
+      "#{spec.name}-#{spec.bounds}"
```
Comment (EricFromCanada) [inline Library/Homebrew/dependency_collector.rb:69]: There's probably a better way to do this, but this seems to work.

**Review by MikeMcQuaid — APPROVED** [review]
Great catch @EricFromCanada, thanks!

File: Library/Homebrew/dependency_collector.rb (hunk 1 above)
Comment (Bo98) [reply Library/Homebrew/dependency_collector.rb:69]: I think a better way is to fix `def hash` and `def ==` in `UsesFromMacOSDependency`

Comment (MikeMcQuaid) [reply Library/Homebrew/dependency_collector.rb:69]: Sorry, enabled auto-merge before I saw your comment @Bo98.
