### PR TITLE
Fix "undefined method 'name' for an instance of FormulaInstaller"

### LINKED ISSUE #20199: brew install -n $PKG raises NoMethodError on #name
### `brew doctor` output

```shell
I'm currently tier 2 because I haven't updated xcode, but this is not related
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.5.8-117-g019a799
ORIGIN: https://github.com/Homebrew/brew
HEAD: 019a799fae067b539390c2e594e8536bb8f6ec8b
Last commit: 23 hours ago
Branch: master
Core tap HEAD: 8d88a443b6822781e1ffe9d9a4839642fb9e5bc5
Core tap last commit: 42 minutes ago
Core tap JSON: 30 Jun 22:12 UTC
Core cask tap HEAD: 88ef2fb90b4b8190094fb74c9dba0799b46bac8e
Core cask tap last commit: 19 minutes ago
Core cask tap JSON: 30 Jun 22:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_EDITOR: emacsclient -t
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTOREMOVE: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_COLOR: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_UPGRADE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.4/bin/ruby
CPU: deca-core 64-bit arm_donan
Clang: 16.0.0 build 1600
Git: 2.50.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.5-arm64
CLT: 26.0
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

see the steps involved for an install, using `-n` flag.

### What happened (include all command output)?

```
10007 $ brew install -n lua
Error: undefined method 'name' for an instance of FormulaInstaller
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Array#map'
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Homebrew::Install.install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:359:in 'Homebrew::Cmd::InstallCmd#run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in '<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

this happens with any uninstalled package I've tried so far

/opt/homebrew/Library/Homebrew/install.rb:330 probably needs to be changed to:

```ruby
          if (formulae_name_to_install = formula_installers.map(&:formula).map(&:name))
```

this seems to work

### What did you expect to happen?

no errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install -n lua
```

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

- Fixes #20199.
- Because `name` is not a method on `FormulaInstaller`, instead `formula` shows the name.

Before:

```
$ brew install -n hello
Error: undefined method 'name' for an instance of FormulaInstaller
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Array#map'
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Homebrew::Install.install_formulae'
```

After:

```
$ brew install -n hello
==> Would install 1 formula:
hello
```

### CODE REVIEW

File: Library/Homebrew/install.rb [hunk 1]
```diff
@@ -327,7 +327,7 @@ def install_formulae(
         end
 
         if dry_run
-          if (formulae_name_to_install = formula_installers.map(&:name))
+          if (formulae_name_to_install = formula_installers.map(&:formula))
```
Comment (issyl0) [inline Library/Homebrew/install.rb]: Maybe this is better, more explicit that we're wanting the name?

```suggestion
          if (formulae_name_to_install = formula_installers.map { |fi| fi.formula.name })
```

Comment (Bo98) [reply Library/Homebrew/install.rb]: probably, yeah

**Comment by MikeMcQuaid** [comment]
Thanks @issyl0!
