### PR TITLE
exceptions.rb: avoid failure if no arguments

### LINKED ISSUE #5266: Test failure leads to confusing error message
When a test fails because a `system` called did not succeed, we get a strange error: ```undefined method `map' for nil:NilClass```.

This can be reproduce on any test block which fails, either because the process called by `system` returns a non-zero exit code, or because the executable could not be found. For example, modifying the `gmp.rb` formula like this:

```
diff --git a/Formula/gmp.rb b/Formula/gmp.rb
index 39ac54a9e7..61058e7392 100644
--- a/Formula/gmp.rb
+++ b/Formula/gmp.rb
@@ -36,7 +36,7 @@ class Gmp < Formula
         mpz_init (k);
         mpz_sqrtrem (j, k, i);
         if (mpz_get_si (j) != 5 || mpz_get_si (k) != 1) abort();
-        return 0;
+        return 1;
       }
     EOS
 
```

or like this:

```
index 39ac54a9e7..f7eb2c7a5b 100644
--- a/Formula/gmp.rb
+++ b/Formula/gmp.rb
@@ -45,6 +45,6 @@ class Gmp < Formula
 
     # Test the static library to catch potential linking issues
     system ENV.cc, "test.c", "#{lib}/libgmp.a", "-o", "test"
-    system "./test"
+    system "./wrongname"
   end
 end
```

The full backtrace from `brew test --verbose gmp` is the following:

```
==> ./wrongname
Failed to execute: ./wrongname
Error: gmp: failed
undefined method `map' for nil:NilClass
Did you mean?  tap
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:363:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:13:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:13:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:102:in `block in test'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:50:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:50:in `test'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

----

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

```
rmeur ~ $ brew config
HOMEBREW_VERSION: 1.8.2-13-ga93b5c4
ORIGIN: https://github.com/Homebrew/brew
HEAD: a93b5c45da978df8d0414ad6e541b386ec0ee30e
Last commit: 40 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3efc2827a16b807d0babbf7d0c61fa129a90cecb
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_KEY: set
HOMEBREW_BINTRAY_USER: fxcoudert
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
rmeur ~ $ brew doctor
Your system is ready to brew.
```

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes #5266

### CODE REVIEW

File: Library/Homebrew/exceptions.rb [hunk 1]
```diff
@@ -360,8 +360,12 @@ def initialize(formula, cmd, args, env)
     @cmd = cmd
     @args = args
     @env = env
-    pretty_args = args.map { |arg| arg.to_s.gsub " ", "\\ " }.join(" ")
```
Comment (MikeMcQuaid) [inline Library/Homebrew/exceptions.rb]: `pretty_args = Array(args).map ...` might be simpler as it can avoid the `if`.

Comment (fxcoudert) [reply Library/Homebrew/exceptions.rb]: But then it prints an extra space in that case… not sure how much we care about that

Comment (woodruffw) [reply Library/Homebrew/exceptions.rb]: Haven't tested it yet, but given `args` and `env` default values of `[]` and `{}` in the exception's constructor would also probably work here.
