### PR TITLE
unpack `.dmg`: ignore `.HFS+ Private*` metadata directories

### LINKED ISSUE #19518: brew seems to struggle with locked folder
### `brew doctor` output

```shell
(Not applicable - happens on GitHub runners too)
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.24-217-g8c1e9c7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8c1e9c7c338c681b7f7088ce5cc69e9c0e87cea0
Last commit: 54 minutes ago
Branch: master
Core tap HEAD: 7407416baa15d0e011459886e0ae47a03410c1b8
Core tap last commit: 37 minutes ago
Core tap JSON: 17 Mar 21:46 UTC
Core cask tap HEAD: b9b509b188dd08cc455be2ec3e37029de42cea26
Core cask tap last commit: 2 minutes ago
Core cask tap branch: safari-technology-preview-215
Core cask tap JSON: 17 Mar 21:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.49.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3.1-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I was installing the cask `5kplayer` (do not worry - this is a bug that could happen to other Casks, see notes at the bottom) and got the following error message:
`Error: Operation not permitted @ apply2files - /private/tmp/homebrew-unpack-20250317-47220-bcg4vr/.HFS+ Private Directory Data`

### What happened (include all command output)?

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
==> Downloading https://formulae.brew.sh/api/cask.jws.json
==> Caveats
5kplayer is built for Intel macOS and so requires Rosetta 2 to be installed.
You can install Rosetta 2 with:
  softwareupdate --install-rosetta --agree-to-license
Note that it is very difficult to remove Rosetta 2 once it is installed.

==> Downloading https://www.5kplayer.com/download/5kplayer.dmg
Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/89ed9e1091bc3a43a890136ba6ada5d4d6a1a8e8f3abdbb48c35d7cbde7c32d5--5kplayer.dmg
Warning: Cannot verify integrity of '89ed9e1091bc3a43a890136ba6ada5d4d6a1a8e8f3abdbb48c35d7cbde7c32d5--5kplayer.dmg'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "6271400b83d17e4b8c26840b2e7add291ecdc22b662f0af7a9635c324c021669"
==> Installing Cask 5kplayer
==> Purging files for version 6.9.0 of Cask 5kplayer
Error: Operation not permitted @ apply2files - /private/tmp/homebrew-unpack-20250317-47220-bcg4vr/.HFS+ Private Directory Data
```

### What did you expect to happen?

I expected the cask to install normally.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run `brew install 5kplayer`
2. See the installation fail because of the aformentioned error
```
Side notes for the poor maintainer who will stumble upon this - to save you time.

I investigated and found that in the disk image provided by 5kplayer, a folder named `.HFS+ Private Directory Data?` is located. This folder is locked by default on the disk image. What I believe is that brew copied the entire disk image to a folder and kept the locked attribute - which prevented the deletion of the locked folder. This then caused the error.

Note that the temp folder `homebrew-unpack-20250317-47220-bcg4vr` still exists and isn't deleted after this error.

It seems likely that this error could happen with other casks with files with locked attributes - this is why I'm reporting this here.

### PR DESCRIPTION
**Pull request by botantony**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Closes #19518

Before APFS, Apple used HFS+. `.HFS+ Private Directory Data` and `.HFS+ Private Data` directories were used for storing metadata (kinda like `.DS_Store` today). Because these directories contain spaces I wasn't able to add them to `DMG_METADATA` set so I used regex instead

Tests: `test.dmg.gz` includes `.HFS+ Private Directory Data` directory (also you can try to install `5kplayer` cask with and w/o this patch)

### CODE REVIEW

File: Library/Homebrew/unpack_strategy/dmg.rb [hunk 1]
```diff
@@ -41,7 +41,10 @@ def initialize(path)
       # Check if path is considered disk image metadata.
       sig { params(pathname: Pathname).returns(T::Boolean) }
       def self.dmg_metadata?(pathname)
-        DMG_METADATA.include?(pathname.cleanpath.ascend.to_a.last.to_s)
+        pathname_string = pathname.cleanpath.ascend.to_a.last.to_s
+        return true if /^.HFS\+ Private+/.match?(pathname_string)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/unpack_strategy/dmg.rb:45]: I think it'd be nicer to add this to `DMG_METADATA` and refactor it to not use `%w`

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks @botantony! One style change.

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again @botantony!

**Comment by eleanordoesntcode** [comment]
Thanks a lot!
