### PR TITLE
Automatically upgrade installed but out of date formulae with `brew install`

### LINKED ISSUE #11393: `brew install` and `brew upgrade` should be idempotent
### Provide a detailed description of the proposed feature

Repeatedly running `brew install` or `brew upgrade` should produce the same exit code and not output any `Error:`s. 

This could be done initially with an `--idempotent` flag or just made the default (which I think it should be eventually). Potentially a `HOMEBREW_NO_IDEMPOTENT` could be added to allow short-term workarounds but this should not stick around forever.

### What is the motivation for the feature?

People have asked for this for a long time. We've pushed back arguing that the exit code consistency is important but I'm less convinced that's the case (and if it is: we can use our deprecation/disable cycle) 

### How will the feature be relevant to at least 90% of Homebrew users?

Homebrew works more like how people expect.

### What alternatives to the feature have been considered?

- The status quo.
- Telling people to use `brew bundle` for idempotent behaviour.

### PR DESCRIPTION
**Pull request by cnnrmnn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Closes #11393.

Currently, `brew install` prints an error and exits with code `1` if it is passed an installed but out of date formula. These changes make `brew install` automatically upgrade any installed but out of date formulae passed to it. It exists so that users don't have to do something like `brew install <formula> || brew upgrade <formula>`.

I'm not well-acquainted with all of the details of the installation/upgrading process, so I'd appreciate it if a maintainer with more knowledge here could confirm that I haven't missed any edge cases.

### CODE REVIEW

File: Library/Homebrew/env_config.rb [hunk 1]
```diff
@@ -257,6 +257,10 @@ module EnvConfig
                      "`HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS` days.",
         boolean:     true,
       },
+      HOMEBREW_NO_INSTALL_UPGRADE:            {
+        description: "If set, `brew install` will not automatically upgrade installed and out of date formulae",
```
Comment (MikeMcQuaid) [inline Library/Homebrew/env_config.rb:261]:
```suggestion
        description: "If set, `brew install` will not automatically upgrade installed and outdated formulae",
```

File: Library/Homebrew/formula_installer.rb [hunk 2]
```diff
@@ -351,7 +351,7 @@ def install
       message = <<~EOS
         #{formula.name} #{formula.linked_version} is already installed
       EOS
-      if formula.outdated? && !formula.head?
+      if Homebrew::EnvConfig.no_install_upgrade? && formula.outdated? && !formula.head?
         message += <<~EOS
           To upgrade to #{formula.pkg_version}, run:
             brew upgrade #{formula.full_name}
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula_installer.rb:357]: I think there may be other cases where this kicks in. Perhaps worth searching the codebase for `brew upgrade`. There was the one I linked you to in `cmd/install.rb`, I think?

File: Library/Homebrew/cmd/install.rb [hunk 3]
```diff
@@ -396,6 +396,20 @@ def install_formula(f, args:)
     f.print_tap_action
     build_options = f.build
 
+    if f.outdated? && !f.head?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:399]:
```suggestion
    if Homebrew::EnvConfig.no_install_upgrade? && f.outdated? && !f.head?
```

just to avoid running this logic unnecessarily?

File: Library/Homebrew/cmd/install.rb [hunk 4]
```diff
@@ -396,6 +396,20 @@ def install_formula(f, args:)
...
+      formulae = [f] + f.old_installed_formulae
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:400]:
```suggestion
      formulae = [f, *f.old_installed_formulae]
```

**Review by MikeMcQuaid — COMMENTED** [review]
Looking good so far, nice work @cnnrmnn!

File: Library/Homebrew/env_config.rb (hunk 1 above)
Comment (carlocab) [reply Library/Homebrew/env_config.rb:261]: How about `installed but outdated` rather than `installed and outdated`? Seems a bit clearer to be.

Comment (cnnrmnn) [reply Library/Homebrew/env_config.rb:261]: Agree. Had this same thought when I wrote the PR title, but didn't remember it here. Thanks!

File: Library/Homebrew/cmd/install.rb (hunk 4 above)
Comment (cnnrmnn) [reply Library/Homebrew/cmd/install.rb:400]: What's the reason for this change? Just curious, they seem functionally equivalent to me.

File: Library/Homebrew/cmd/install.rb (hunk 3 above)
Comment (cnnrmnn) [reply Library/Homebrew/cmd/install.rb:399]: Yep, but `Homebrew::EnvConfig.no_install_upgrade?` should be negated. Forgot to add this. Thanks for pointing out.

File: Library/Homebrew/formula_installer.rb (hunk 2 above)
Comment (cnnrmnn) [reply Library/Homebrew/formula_installer.rb:357]: Correct, this is a special case handling keg-only formulae. I've fixed it now.

Comment (cnnrmnn) [reply Library/Homebrew/formula_installer.rb:357]: I grep'd for "To upgrade to" and only found the two cases that I've now addressed. Resolving this, but let me know if you suspect I'm missing something.

File: Library/Homebrew/cmd/install.rb (hunk 4 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/install.rb:404]: The latter avoids creating a two new arrays/mutating any in favour of just creating one.

**Review by MikeMcQuaid — COMMENTED** [review]
Looking good so far!

File: Library/Homebrew/cmd/install.rb (hunk 4 above)
Comment (cnnrmnn) [reply Library/Homebrew/cmd/install.rb]: Makes sense, thanks for the explanation!

**Review by MikeMcQuaid — APPROVED** [review]
Looks good (once conflicts resolved)

**Comment by cnnrmnn** [comment]
Could someone who isn't on M1 Mac regenerate the hidden definitions `rbi` file? That's where all of the `Homebrew::EnvConfig` type declarations seem to be. `Homebrew::EnvConfig.no_install_upgrade?` doesn't have a type declaration, so `brew typecheck` is failing at the moment. I didn't want to manually modify it because it says not to.

File: Library/Homebrew/install.rb [hunk 5]
```diff
@@ -247,6 +249,18 @@ def install_formula(
...
 
+      if !Homebrew::EnvConfig.no_install_upgrade? && f.outdated? && !f.head?
+        outdated_formulae = [f, *f.old_installed_formulae]
+        version_upgrade = "#{f.linked_version} -> #{f.pkg_version}"
+
+        oh1 <<~EOS
+          #{f.name} #{f.linked_version} is installed but outdated
+            Upgrading #{Formatter.identifier(f.name)} #{version_upgrade}
+        EOS
+        outdated_kegs = outdated_formulae.map(&:linked_keg).select(&:directory?).map { |k| Keg.new(k.resolved_path) }
```
Comment (MikeMcQuaid) [inline Library/Homebrew/install.rb:260]:
```suggestion
        outdated_kegs = outdated_formulae.map(&:linked_keg)
                                         .select(&:directory?)
                                         .map { |k| Keg.new(k.resolved_path) }
```

File: Library/Homebrew/install.rb [hunk 6]
```diff
@@ -247,6 +249,18 @@ def install_formula(
       f.print_tap_action
       build_options = f.build
 
+      if !Homebrew::EnvConfig.no_install_upgrade? && f.outdated? && !f.head?
+        outdated_formulae = [f, *f.old_installed_formulae]
+        version_upgrade = "#{f.linked_version} -> #{f.pkg_version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/install.rb:254]: Can any of this logic be shared with `upgrade.rb`? It feels like having a consistent function that's used for both places would be desirable. Thoughts?

Comment (cnnrmnn) [reply Library/Homebrew/install.rb:254]: Agreed. Where should such a function go?

Comment (MikeMcQuaid) [reply Library/Homebrew/install.rb:254]: In `upgrade.rb` I think.

File: Library/Homebrew/formula_installer.rb [hunk 7]
```diff
@@ -351,7 +351,7 @@ def install
       message = <<~EOS
         #{formula.name} #{formula.linked_version} is already installed
       EOS
-      if formula.outdated? && !formula.head?
+      if Homebrew::EnvConfig.no_install_upgrade? && formula.outdated? && !formula.head?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula_installer.rb:354]: Sorry to be a pain: I wonder if this logic could/should be in `upgrade.rb` and called from `formula_installer` too? Feels weird to have this messaging scattered across files.

**Review by MikeMcQuaid — COMMENTED** [review]
This is 😍, really loving the cleanup here!

File: Library/Homebrew/formula_installer.rb (hunk 7 above)
Comment (cnnrmnn) [reply Library/Homebrew/formula_installer.rb:354]: I've moved all of that code into `install.rb` as it all only used with `brew install`.

**Review by MikeMcQuaid — APPROVED** [review]
This looks great to me now, fantastic work here @cnnrmnn. Note that we'll probably make the next release be `3.2.0` to account for this major change.

**Comment by vitorgalvao** [comment]
Not saying the behaviour should change, but I’ve bumped into a case which might warrant consideration. Or at the very least this comment will serve as future reference.

`--HEAD` formulae don’t upgrade as (I) expected. Neither `install --HEAD` nor `install --fetch-HEAD` do it, though `install --fetch-HEAD --HEAD` works. Seeing as [the goal was idempotence](https://github.com/Homebrew/brew/issues/11393), I would’ve expected `install --HEAD` to have also done `--fetch-HEAD`.
