### PR TITLE
audit: avoid python symlink conflict

### LINKED ISSUE #8949: Audit to avoid conflict in python symlinks
This is a tracking issue so we can discuss what is needed to avoid reproduction of the problem reported in https://github.com/Homebrew/homebrew-core/issues/62911 and partly fixed in https://github.com/Homebrew/homebrew-core/pull/62949

The author of the `python@3.9` formula (aka me) included wrong unversioned symlinks in `HOMEBREW_PREFIX`. Suggested solutions to prevent this mistake from happening in the future include:

- @SMillerDev _“audit/rubocop to make sure only one formula has these”_
- @MikeMcQuaid _“no python formula except PYTHON_ALLOWED_FORMULA has these symlinks”_

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

Resolves #8949

Only allow one python formula to create `pip3` and `wheel3` symlinks

CC: @fxcoudert, @SMillerDev and @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Thanks for this @Rylan12! I think this is a good test but I wonder if it's overly specific and we'd be better looking at the actually written symlinks in `brew audit` instead. Thoughts? ✅ because this is better than the status quo and we could consider having both approaches.

**Comment by Rylan12** [comment]
I think the benefit of checking the actual symlinks in `brew audit` is it checks the actual links rather than the code that generates the links (which could change rendering this check pretty useless). So, going with an audit is probably a better solution. I'll look into it in about an hour when I've got some more time.

In terms of specificity, what would the less specific audit be? As far as I know, this is the only formula with this kind of symlink issue. The problem is inherently specific because we _do_ want to allow some symlinks (e.g. `pip3.x`) but not _all_ symlinks (e.g. `pip3`)

**Comment by MikeMcQuaid** [comment]
> In terms of specificity, what would the less specific audit be?

Sorry, to be clear, I thought this RuboCop was overly specific (due to the reasons you stated yourself) but any `brew audit` checking these symlinks would not be problematically specific 👍🏻

File: Library/Homebrew/formula_cellar_checks.rb [hunk 1]
```diff
@@ -265,6 +265,20 @@ def check_plist(prefix, plist)
     EOS
   end
 
+  PYTHON_SYMLINK_ALLOWED_FORMULA = "python@3.8"
```
Comment (SMillerDev) [inline Library/Homebrew/formula_cellar_checks.rb:268]: Do we have this defined somewhere else? Or can we infer it from the keg_only status?

Comment (Rylan12) [reply Library/Homebrew/formula_cellar_checks.rb:268]: > Do we have this defined somewhere else?

Not that I can find

> Or can we infer it from the keg_only status?

Probably. This would be ideal to avoid needing to update the blocklist for every new python version.

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/formula_cellar_checks.rb (hunk 1 above)
Comment (SMillerDev) [reply Library/Homebrew/formula_cellar_checks.rb:268]: Yeah, that was exactly what I was worried about.

Comment (Rylan12) [reply Library/Homebrew/formula_cellar_checks.rb]: Done! I think it clarifies the check anyway 👍

**Review by MikeMcQuaid — APPROVED** [review]
