### PR TITLE
SBOM: more fixes.

### LINKED ISSUE #17281: SBOMs break bottle reproducibility
### `brew doctor` output

```shell
❯ brew dr
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.2.21-109-g71c4bfa
ORIGIN: https://github.com/Homebrew/brew
HEAD: 71c4bfae79852b28d299de51a3007149bfe44073
Last commit: 4 hours ago
Core tap HEAD: 70912b0a1127e1b4fb3f50298b6f843b495a19fb
Core tap last commit: 18 minutes ago
Core tap JSON: 10 May 16:11 UTC
Core cask tap HEAD: 5be9a58d025d2db4fe8dd96089c9bd65600cba24
Core cask tap last commit: 34 minutes ago
Core cask tap JSON: 10 May 16:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GIT_EMAIL: 30379873+carlocab@users.noreply.github.com
HOMEBREW_GIT_NAME: Carlo Cabrera
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_CLEANUP_FORMULAE: zsh
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_PRY: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.0 => /opt/homebrew/opt/git/bin/git
Curl: 8.7.1 => /opt/homebrew/opt/curl/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Figure out why we don't have an `:all` bottle at https://github.com/Homebrew/homebrew-core/commit/0894397822dcdba3facaf90055f450b2dc741647 (because `:all` bottles are nice).

To examine the differences between the bottles, I used `diffoscope`.

### What happened (include all command output)?

`diffoscope` showed that the bottles have differing `sbom.spdx.json` files.

<details>
<summary>diffoscope output</summary>

```diff
--- bottles_ubuntu-22.04/osinfo-db--20240510.x86_64_linux.bottle.tar.gz
+++ bottles_14-arm64-9046359873/osinfo-db--20240510.arm64_sonoma.bottle.tar.gz
│   --- osinfo-db--20240510.x86_64_linux.bottle.tar
├── +++ osinfo-db--20240510.arm64_sonoma.bottle.tar
│ ├── file list
│ │ @@ -1,12 +1,12 @@
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/.brew/
│ │  -rw-r--r--   0        0        0      667 2024-05-10 10:31:02.000000 osinfo-db/20240510/.brew/osinfo-db.rb
│ │  -rw-r--r--   0        0        0    17987 2024-05-10 10:31:02.000000 osinfo-db/20240510/LICENSE
│ │ --rw-r--r--   0        0        0     2727 2024-05-10 10:31:02.000000 osinfo-db/20240510/sbom.spdx.json
│ │ +-rw-r--r--   0        0        0     2719 2024-05-10 10:31:02.000000 osinfo-db/20240510/sbom.spdx.json
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/
│ │  -rw-r--r--   0        0        0    17987 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/LICENSE
│ │  -rw-r--r--   0        0        0        8 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/VERSION
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/datamap/
│ │  drwxr-xr-x   0        0        0        0 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/datamap/microsoft.com/
│ │  -rw-r--r--   0        0        0     1691 2024-05-10 10:31:02.000000 osinfo-db/20240510/share/osinfo/datamap/microsoft.com/win-7-l10n-language.xml
│ ├── osinfo-db/20240510/sbom.spdx.json
│ │ ├── Pretty-printed
│ │ │ @@ -1,11 +1,11 @@
│ │ │  {
│ │ │      "SPDXID": "SPDXRef-DOCUMENT",
│ │ │      "creationInfo": {
│ │ │ -        "created": "2024-05-11T20:59:00+00:00",
│ │ │ +        "created": "2024-05-11T17:00:13-04:00",
│ │ │          "creators": [
│ │ │              "Tool: https://github.com/homebrew/brew@4.2.21-109-g71c4bfa"
│ │ │          ]
│ │ │      },
│ │ │      "dataLicense": "CC0-1.0",
│ │ │      "documentDescribes": [
│ │ │          "SPDXRef-Archive-osinfo-db-src",
│ │ │ @@ -14,15 +14,15 @@
│ │ │      ],
│ │ │      "documentNamespace": "https://formulae.brew.sh/spdx/osinfo-db-20240510.json",
│ │ │      "files": [],
│ │ │      "name": "SBOM-SPDX-osinfo-db-20240510",
│ │ │      "packages": [
│ │ │          {
│ │ │              "SPDXID": "SPDXRef-Archive-osinfo-db-src",
│ │ │ -            "builtDate": "2024-05-10 10:31:02 +0000",
│ │ │ +            "builtDate": "2024-05-10 06:31:02 -0400",
│ │ │              "checksums": [
│ │ │                  {
│ │ │                      "algorithm": "SHA256",
│ │ │                      "checksumValue": "08a2d521c485687f6be39940d5b3f61bc0f583bb7e3655a131c658385eb7e5ca"
│ │ │                  }
│ │ │              ],
│ │ │              "copyrightText": "NOASSERTION",
│ │ │ @@ -39,20 +39,20 @@
│ │ │              "checksums": [],
│ │ │              "copyrightText": "NOASSERTION",
│ │ │              "downloadLocation": "NOASSERTION",
│ │ │              "externalRefs": [],
│ │ │              "filesAnalyzed": false,
│ │ │              "licenseConcluded": "NOASSERTION",
│ │ │              "licenseDeclared": "NOASSERTION",
│ │ │ -            "name": "gcc-11",
│ │ │ -            "versionInfo": "NOASSERTION"
│ │ │ +            "name": "clang",
│ │ │ +            "versionInfo": "15.3"
│ │ │          },
│ │ │          {
│ │ │              "SPDXID": "SPDXRef-Bottle-osinfo-db",
│ │ │ -            "builtDate": "2024-05-10 10:31:02 +0000",
│ │ │ +            "builtDate": "2024-05-10 06:31:02 -0400",
│ │ │              "checksums": [
│ │ │                  {
│ │ │                      "algorithm": "SHA256",
│ │ │                      "checksumValue": "a8c86aee5fd157554d85aa0a28d4c12bc5bdf03ccb5e67ac5c8c524d78bd1971"
│ │ │                  }
│ │ │              ],
│ │ │              "copyrightText": "NOASSERTION",
```

</details>

### What did you expect to happen?

These bottles are identical, so they should not have different contents.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
gh run download 9046359873 -p 'bottles*' -R Homebrew/homebrew-core
diffoscope bottles_ubuntu-22.04/osinfo-db--20240510.x86_64_linux.bottle.tar.gz bottles_14-arm64-9046359873/osinfo-db--20240510.arm64_sonoma.bottle.tar.gz
```

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- Remove use of (unused) `Cachable` module.
- Pass whether we're bottling to determine whether to create reproducible SBOM or not. A reproducible SBOM omits the time and compiler.
- Remove bottle information when bottling: we cannot know what e.g. the checksum (and, with GitHub Packages, therefore also the download location) will be before we've created the tarball contents.
- Always write a bottle on installation (unless we're bottling) to provide new bottle information or freshen the existing one with the information we stripped out for reproducibility e.g. the time and compiler.
- Don't need to handle a `nil` `@source_modified_time` as it's always set.

Fixes #17281

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
```
Cannot convert NillClass into an exact number
     # ./sbom.rb:367:in `to_spdx_sbom'
```

File: Library/Homebrew/sbom.rb [hunk 1]
```diff
@@ -342,21 +358,21 @@ def to_spdx_sbom
...
 
-    packages = generate_packages_json(runtime_full, compiler_info)
+    packages = generate_packages_json(runtime_full, compiler_info, bottling:)
     {
       SPDXID:            "SPDXRef-DOCUMENT",
       spdxVersion:       "SPDX-2.3",
       name:              "SBOM-SPDX-#{name}-#{stable_version}",
       creationInfo:      {
-        created:  DateTime.now.to_s,
+        created:  (Time.at(time).utc unless bottling),
```
Comment (SMillerDev) [inline Library/Homebrew/sbom.rb:367]: Time does actually seem to be `Nil` here

**Review by SMillerDev — APPROVED** [review]
