### PR TITLE
os/mac: prefer newest Xcode when searching using `mdfind`

### LINKED ISSUE #18736: Homebrew requires Xcode when sufficient Command Line Tools is installed and selected (and can also fail randomly even if a sufficient Xcode is installed)
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 824efa8836dc226aa92dbbf7404c1b4a66707cca
Last commit: 4 days ago
Core tap JSON: 08 Nov 11:00 UTC
Core cask tap JSON: 08 Nov 11:00 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_ARTIFACT_DOMAIN: https://artifactory.klarna.net/artifactory/r-docker-ghcr-io
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOCKER_REGISTRY_BASIC_AUTH_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_PIP_INDEX_URL: https://artifactory.klarna.net/artifactory/api/pypi/r-pypi-pypi-org/packages
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 15.4 => /Applications/Xcode-15.4.0.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I'm trying to install a formula which does not have a bottle. Sometimes it will succeed and sometimes it will fail.

My setup may seem strange but is a pretty common case when upgrading macOS versions. Basically – imagine that I am a user who has installed Xcode 15.4 before upgrading to macOS 16. Rather than download/install the massive Xcode package (which hey – maybe I don't even need anymore), I just install the latest Command Line Tools and xcode-select it. I would expect all build from source to work, since I wouldn't expect Xcode to be used at all. Instead, Homebrew will require the Xcode to be the latest supported version.

### What happened (include all command output)?

sometimes I get:
```
Error: Your Xcode (14.3.1 => /Applications/Xcode-14.3.1.app/Contents/Developer) at /Applications/Xcode-14.3.1.app is too outdated.
Please update to Xcode 15.4 (or delete it).
Xcode can be updated from the App Store.

Error: Kernel.exit
```
and sometimes I get this warning and it succeeds:
```
Warning: Your Xcode (15.2) is outdated.
Please update to Xcode 15.4 (or delete it).
Xcode can be updated from the App Store.
```
and sometimes I get no warnings and it all succeeds!

### What did you expect to happen?

My first expectation is that if I have a functional Xcode CLT installed and selected via `xcode-select`  _and I don't need Xcode_, then things would "just work", regardless of if I have had Xcode installed before or not.

My second expectation is that _if_ Homebrew is needing Xcode yet I haven't selected it via `xcode-select`, then Homebrew would use the _latest_ version of Xcode which I have installed. Today it will choose the first result of Spotlight, which is random. (in my case, the `.first` result will be either 14.3.1 or 15.2 or 15.4)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`xcodes` makes this pretty simple to test:

* install an outdated version of Xcode. So in my case I'm on macOS 14 so I installed `xcodes install 14.3.1`
* install a recent version of Xcode. So, `xcodes install 15.4` or `xcodes install 16.1` _note that this is only necessary for the "random failure" use case_. If you have no other Xcode installed than the outdated one, then it will fail every time.
* install the latest Xcode Command Line Tools
* `sudo xcode-select -s /Library/Developer/CommandLineTools`
* install a formula building from source

I tracked the randomness down to [app_with_bundle_id](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac.rb#L197-L202). Ideally this just chooses the latest.

As for why Homebrew checks Xcode version _always_, I don't know the answer to that. I would expect that it only cares about the thing-that-is-xcode-selected.
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

We're currently returning the first match for `com.apple.dt.Xcode`,
which could be any version if a user has multiple installed.

Instead, let's try to find the newest if all our results have an
`Info.plist` that we can interrogate for the version.

Maybe resolves #18736?

For reference, on my system, before this change:
```
❯ brew ruby -e 'puts MacOS.app_with_bundle_id("com.apple.dt.Xcode")'
/Applications/Xcode-14.3.1.app
```
after this change:
```
❯ brew ruby -e 'puts MacOS.app_with_bundle_id("com.apple.dt.Xcode")'
/Applications/Xcode.app
```

### CODE REVIEW

File: Library/Homebrew/os/mac.rb [hunk 1]
```diff
@@ -195,10 +195,15 @@ def self.macports_or_fink
...
-      path = mdfind(*ids)
-             .reject { |p| p.include?("/Backups.backupdb/") }
-             .first
-      Pathname.new(path) if path.present?
+      require "bundle_version"
+
+      paths = mdfind(*ids).filter_map do |bundle_path|
+        Pathname.new(bundle_path) if bundle_path.exclude?("/Backups.backupdb/")
+      end
+      return paths.first if paths.any? { |bp| !(bp/"Contents/Info.plist").exist? }
```
Comment (MikeMcQuaid) [inline Library/Homebrew/os/mac.rb:203]:
```suggestion
      return paths.first if paths.none? { |bp| (bp/"Contents/Info.plist").exist? }
```
maybe?

**Review by MikeMcQuaid — APPROVED** [review]
Nice, people have complained about this a lot for ages. Looks good as-is but may want a tweak for readability and/or correctness.

File: Library/Homebrew/os/mac.rb (hunk 1 above)
Comment (carlocab) [reply Library/Homebrew/os/mac.rb:203]: I think that's not equivalent, unfortunately. In particular, suppose we have an `Foo.app/Contents/Info.plist` but no `Foo_debug.app/Contents/Info.plist`.

Before your suggestion, we would take the first `Foo*.app` that `mdfind` returns. After your suggestion, we would try to check the `Info.plist`s for the newest one, but fail (because `Foo_debug.app` has no `Info.plist`).

For a change that is equivalent, we can do:
```suggestion
      return paths.first unless paths.all? { |bp| (bp/"Contents/Info.plist").exist? }
```

Comment (MikeMcQuaid) [reply Library/Homebrew/os/mac.rb:203]: Yeh, suggested work makes sense!
