### PR TITLE
install: prune build-only deps of deps

### LINKED ISSUE #1272: Needlessly building ":build" deps for formulas that are already installed
[Transferred from Homebrew/homebrew-core#5740 at @MikeMcQuaid's request]

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I noticed this problem with `diff-pdf`, but it's probably because of a bug in `brew`'s deciding which deps need to be installed.

`brew install --build-from-source diff-pdf` will incorrectly try to build and install `:build` deps for `openjpeg`, even when `openjpeg` has already been poured from a bottle.

Reproduce: Pour the bottles for `diff-pdf`'s dependencies: `brew install wxmac cairo poppler`  Notice that `openjpeg` is now installed, since it's a recursive dep.  Other recursive deps are poured too.

Now, do `brew install --build-from-source diff-pdf`.  What should happen is that `diff-pdf` starts being built forthwith (all of its deps are already installed).  What actually happens is that `brew` starts trying to build `cmake`, `doxygen`, and `sphinx-doc`, because those are deps of `openjpeg`.  But, those are *:build* deps of `openjpeg`, and `openjpeg` has already been poured and is therefore already built.

My *guess* is that `brew` is simply failing to filter out the ":build" deps from its list of things it needs to do before it can build `diff-pdf`.  Even though `diff-pdf` is going to be built rather than poured, that doesn't mean that all of its deps need to be :built.

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [X] Have you successfully run `brew tests` with your changes locally?

-----

This avoids needlessly installing `:build` dependencies of dependencies which are not themselves being built from source.

Fixes #1272. See it for details of the problematic behavior.

Before:

```
$ brew info diff-pdf | grep Build:
Build: pkg-config, automake, autoconf
$ brew info openjpeg | grep Build:
Build: cmake, doxygen
$ brew install -s diff-pdf
==> Installing dependencies for diff-pdf: cmake, doxygen
==> Installing diff-pdf dependency: cmake
```

`cmake` and `doxygen` are `:build` deps of `openjpeg`, which is not being built from source in this scenario, so they shouldn't be picked up.

After:

```
$ brew install -s diff-pdf
==> Using the sandbox
```

(No attempt to install `cmake` or `doxygen`.)

### CODE REVIEW

File: Library/Homebrew/formula_installer.rb [hunk 1]
```diff
@@ -393,7 +393,8 @@ def expand_dependencies(deps)
 
       if (dep.optional? || dep.recommended?) && build.without?(dep)
         Dependency.prune
-      elsif dep.build? && install_bottle_for?(dependent, build)
+      elsif dep.build? && (install_bottle_for?(dependent, build) ||
+           !ARGV.build_formula_from_source?(dependent))
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula_installer.rb]: May be worth pulling this and other `(...||...)` into a separate function or variable.

Comment (MikeMcQuaid) [inline Library/Homebrew/formula_installer.rb]: Yeh, that sounds more correct.

**Comment by ilovezfs** [comment]
Will this cause it not to install missing run-time deps? :(

File: Library/Homebrew/formula_installer.rb [hunk 2]
```diff
@@ -114,7 +114,7 @@ def pour_bottle?(install_bottle_options = { warn: false })
 
   def install_bottle_for?(dep, build)
     return pour_bottle? if dep == formula
-    return false if build_from_source?
+    return false if ARGV.build_formula_from_source?(dep)
```
Comment (apjanke) [inline Library/Homebrew/formula_installer.rb]: I don't know. The existing `build_from_source?` method is an accessor on `@build_from_source`, which is twiddled from `cmd/install.rb` and the `DependencyInstaller` subclass. So unifying them would be a more extensive refactor of `FormulaInstaller` and `cmd/install.rb`. Could simplify things, but I'm reluctant to do the refactoring here, because it would change the control flow pattern for `Homebrew#install` a bit. The context in which they're used (the main formula vs a discovered dependency) is different enough that the existing control flow seems more readable to me.

**Comment by apjanke** [comment]
> Will this cause it not to install missing run-time deps? :(

No, they still get picked up. They just no longer look like they're being built from source inside the dependency expansion logic (unless they have explicitly been requested to be built from source).

Here's an example with `diff-pdf`'s dependency `wxmac` locally converted to a run-time dependency.

```
$ brew rm wxmac jpeg
Uninstalling /usr/local/Cellar/wxmac/3.0.2_3... (809 files, 23.6M)
Uninstalling /usr/local/Cellar/jpeg/8d... (19 files, 731.5K)
[/usr/local/Homebrew on ⇄ prune-build-deps-of-deps]
$ brew install -s diff-pdf
==> Installing dependencies for diff-pdf: jpeg, wxmac
==> Installing diff-pdf dependency: jpeg
```

Or is there something else I'm overlooking?

File: Library/Homebrew/formula_installer.rb (hunk 2 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/formula_installer.rb]: Ok, that seems fine, thanks.

**Comment by MikeMcQuaid** [comment]
Thanks @apjanke!
