### PR TITLE
bundle: dump full cask names

### LINKED ISSUE #21416: `brew bundle install` should install taps first
### `brew config` AND `brew doctor` output OR `brew gist-logs <formula>` link

Originally posted in https://github.com/orgs/Homebrew/discussions/6657, suggested by @SMillerDev to repost as an issue.

I believe the following output has nothing to do with the issue I am reporting.

```console
> brew config
HOMEBREW_VERSION: 5.0.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: bf65f9c19a7a62abcbdac9c30cf3ff844d0fd633
Last commit: 10 days ago
Branch: stable
Core tap JSON: 08 Jan 08:40 UTC
Core cask tap JSON: 08 Jan 08:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: base16-256
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 20
HOMEBREW_EDITOR: nvim
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: deca-core 64-bit arm_donan
Clang: 17.0.0 build 1700
Git: 2.52.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.2-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: N/A
Rosetta 2: false

> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  font-ibm-plex
  librewolf

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  cargo-watch
  icu4c@77
  postgresql@14

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /opt/homebrew/bin/rustup
  /opt/homebrew/bin/rustup-init
```

### Verification

- [ ] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

Using `brew bundle install` to automatically install dependencies.

### What happened (include all command output)?

Given a fresh installation with just the default taps, and the Brewfile (minimal viable reproduction from a `brew bundle dump` output) as follows:

```rb
tap "rami3l/tap"
cask "font-dseg"
```

`brew bundle install` will cause the following error:

```console
Error: No available formula with the name "font-dseg". Did you mean fonts-encodings?
```

However, if I comment out the `cask` line, run once, and then uncomment the line and run for a second time, everything will work flawlessly.

The conclusion seems to be that somehow `brew bundle` has forgotten to install the taps before their dependents.

It should be noted that `font-dseg` is a cask in `rami3l/tap`:

```console
> brew info font-dseg
==> font-dseg: 0.46
https://github.com/keshikan/DSEG
Installed
/opt/homebrew/Caskroom/font-dseg/0.46 (750.7KB)
  Installed on 2025-11-10 at 12:08:27
From: https://github.com/rami3l/homebrew-tap/blob/HEAD/Casks/font-dseg.rb
[...]
```

### What did you expect to happen?

The install completes normally.

### Step-by-step reproduction instructions (by running `brew` commands)

1. `printf 'tap "rami3l/tap"\ncask "font-dseg"\n' > Brewfile`
2. `brew bundle install --file Brewfile`
3. Observe the error.

### PR DESCRIPTION
**Pull request by gromgit**
This mirrors existing 3rd-party formulae disambiguation. 

Fixes #21416.

Before:
```
% brew bundle dump --file=- | grep -E '(jq|pup|font)'
tap "colindean/fonts-nonfree"
brew "jq"
brew "gromgit/tap/pup"
cask "font-dseg"
cask "font-lato"
cask "font-microsoft-office"
```

After:
```
% brew bundle dump --file=- | grep -E '(jq|pup|font)'
tap "colindean/fonts-nonfree"
brew "jq"
brew "gromgit/tap/pup"
cask "rami3l/tap/font-dseg"
cask "font-lato"
cask "colindean/fonts-nonfree/font-microsoft-office"
```

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

### CODE REVIEW

File: Library/Homebrew/bundle/cask_dumper.rb [hunk 1]
```diff
@@ -37,9 +37,10 @@ def self.cask_is_outdated_using_greedy?(cask_name)
       sig { params(describe: T::Boolean).returns(String) }
       def self.dump(describe: false)
         casks.map do |cask|
+          name = cask.respond_to?(:full_name) ? cask.full_name : cask.to_s
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle/cask_dumper.rb:40]: This is a little weird but not a blocker; when doesn't it respond to `full_name`?

**Review by MikeMcQuaid — APPROVED** [review]
Thanks @gromgit!

File: Library/Homebrew/bundle/cask_dumper.rb (hunk 1 above)
Comment (gromgit) [reply Library/Homebrew/bundle/cask_dumper.rb:40]: Yup. `brew install dump` works just fine if I just do `cask.full_name`, but `brew tests` kept throwing errors like:

```
Failures:

  1) Homebrew::Bundle::CaskDumper when casks `foo`, `bar` and `baz` are installed, with `baz` being a formula requirement dumps as `cask 'baz'` and `cask 'foo' cask 'bar'` plus descriptions and config values
     Got 4 failures:

     1.1) Failure/Error: expect(dumper.dump(describe: true)).to eql(expected.chomp)
            #<InstanceDouble(Cask::Cask) (anonymous)> received unexpected message :full_name with (no args)
          # ./bundle/cask_dumper.rb:42:in 'block in Homebrew::Bundle::CaskDumper.dump'
          # ./bundle/cask_dumper.rb:39:in 'Array#map'
          # ./bundle/cask_dumper.rb:39:in 'Homebrew::Bundle::CaskDumper.dump'
          # ./test/bundle/cask_dumper_spec.rb:80:in 'block (3 levels) in <main>'

     1.2) Failure/Error: expect(dumper.dump(describe: true)).to eql(expected.chomp)
            #<InstanceDouble(Cask::Cask) (anonymous)> received unexpected message :full_name with (no args)
          # ./bundle/cask_dumper.rb:42:in 'block in Homebrew::Bundle::CaskDumper.dump'
          # ./bundle/cask_dumper.rb:39:in 'Array#map'
          # ./bundle/cask_dumper.rb:39:in 'Homebrew::Bundle::CaskDumper.dump'
          # ./test/bundle/cask_dumper_spec.rb:80:in 'block (3 levels) in <main>'

     1.3) Failure/Error: expect(dumper.dump(describe: true)).to eql(expected.chomp)
            #<InstanceDouble(Cask::Cask) (anonymous)> received unexpected message :full_name with (no args)
          # ./bundle/cask_dumper.rb:42:in 'block in Homebrew::Bundle::CaskDumper.dump'
          # ./bundle/cask_dumper.rb:39:in 'Array#map'
          # ./bundle/cask_dumper.rb:39:in 'Homebrew::Bundle::CaskDumper.dump'
          # ./test/bundle/cask_dumper_spec.rb:80:in 'block (3 levels) in <main>'

     1.4) Failure/Error: expect(dumper.dump(describe: true)).to eql(expected.chomp)

            expected: "cask \"foo\"\ncask \"bar\", args: { fontdir: \"/Library/Fonts\", language: \"zh-TW\" }\n# Software\ncask \"baz\""
                 got: "cask \"#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>\"\ncask \"#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>\", args: { fontdir: \"/Library/Fonts\", language: \"zh-TW\" }\n# Software\ncask \"#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>\""

            (compared using eql?)

            Diff:

            @@ -1,4 +1,4 @@
            -cask "foo"
            -cask "bar", args: { fontdir: "/Library/Fonts", language: "zh-TW" }
            +cask "#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>"
            +cask "#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>", args: { fontdir: "/Library/Fonts", language: "zh-TW" }
             # Software
            -cask "baz"
            +cask "#<RSpec::Expectations::FailureAggregator::AggregatedFailure:0x0000000121e50c00>"

          # ./test/bundle/cask_dumper_spec.rb:80:in 'block (3 levels) in <main>'
```

I think it's because the test cask objects aren't fully populated like actual cask objects.

Comment (MikeMcQuaid) [reply Library/Homebrew/bundle/cask_dumper.rb:40]: @gromgit Thanks! If you can be bothered: ideally populate those test cask double objects in the `cask_dumper_spec` instead so it always provides a `full_name`? No worries if not.

Comment (gromgit) [reply Library/Homebrew/bundle/cask_dumper.rb:40]: I'll see what I can do.
