### PR TITLE
help: show help text for tapped external command

### LINKED ISSUE #8641: `brew help bundle` runs `brew bundle` after tapping
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was looking for some solutions on my problem with brew, and found some commands started with `brew bundle`.
Well, I never do copy&paste, so first I wanted to know what is the bundle. So, I simply typed: `brew help bundled` and all this happened...

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew help bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 5158 (delta 4), reused 1 (delta 0), pack-reused 5145
Receiving objects: 100% (5158/5158), 1.15 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (3019/3019), done.
Tapped 1 command (104 files, 1.5MB).
Error: No Brewfile found
  </pre>
</details>

## What you expected to happen

I expected to get some information about a command bundle. Now, I know I should use `brew bundle --help`. I won't argue if this is convenient or not.
However, let me answer what I did not expect: Auto installation of the bundle!
This definitely should never happed for a `help` command.
 
## Step-by-step reproduction instructions (by running `brew` commands)

`brew help bundle`

## Output of `brew config` and `brew doctor` commands

doctor: `Your system is ready to brew.`

<pre>
HOMEBREW_VERSION: 2.4.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2a4c9f610e69b9fed1eec61ac2c53e4b11a32e4c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 642b748a2f1029ee2afb0188a5ced5d543be4456
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: 11.7
</pre>

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #8641

Previously, running e.g. `brew help bundle` when homebrew-bundle was not tapped would tap homebrew-bundle and then run `brew bundle` showing `Error: No Brewfile found` instead of the expected help text.

I also added a message that lets the user know how to remove a tap that was automatically added. This was briefly discussed in #8641 but no conclusion was made so if this isn't wanted it can be easily removed.

Before:

```console
$ brew help bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 5159 (delta 4), reused 1 (delta 0), pack-reused 5145
Receiving objects: 100% (5159/5159), 1.15 MiB | 795.00 KiB/s, done.
Resolving deltas: 100% (3019/3019), done.
Tapped 1 command (104 files, 1.5MB).
Error: No Brewfile found
```

After:

```console
$ brew help bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 5159 (delta 4), reused 1 (delta 0), pack-reused 5145
Receiving objects: 100% (5159/5159), 1.15 MiB | 5.13 MiB/s, done.
Resolving deltas: 100% (3019/3019), done.
Tapped 1 command (104 files, 1.5MB).
Usage: brew bundle [subcommand]

Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask, Mac App Store
and Whalebrew.
...
```

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I know this is not within the scope of this PR, but... it seems strange that `brew help` taps things instead of reporting back to the user that there is nothing to display unless they tap X.

**Comment by Rylan12** [comment]
@maxim-belkin take a look at #8641 for some discussion (feel free to chime in as well). That was proposed but it was decided that the best option was to add a message letting the user know what happened after the fact.

File: Library/Homebrew/brew.rb [hunk 1]
```diff
@@ -141,9 +141,14 @@ class MissingEnvironmentVariables < RuntimeError; end
       end
       tap_commands += %W[#{HOMEBREW_BREW_FILE} tap #{possible_tap.name}]
       safe_system(*tap_commands)
+      ohai "Automatically tapped #{possible_tap.name}. To remove, run `brew untap #{possible_tap.name}`"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/brew.rb:144]: The output indicates it was tapped so don't think this is necessary.

File: Library/Homebrew/brew.rb [hunk 2]
```diff
@@ -141,9 +141,14 @@ class MissingEnvironmentVariables < RuntimeError; end
...
     end
 
-    exec HOMEBREW_BREW_FILE, cmd, *ARGV
+    if help_flag
```
Comment (MikeMcQuaid) [inline Library/Homebrew/brew.rb:147]: Could also consider adding `--help` to `ARGV` (or another splatted array) if it's set to avoid a bit of minor duplication?

**Comment by MikeMcQuaid** [comment]
> I know this is not within the scope of this PR, but... it seems strange that `brew help` taps things instead of reporting back to the user that there is nothing to display unless they tap X.

These are "official external commands" so this behaviour is intentional. Perhaps they should/could be migrated to Homebrew/brew instead but until then allowing `brew bundle` or `brew services` to work without extra intervention is desirable.

File: Library/Homebrew/brew.rb (hunk 1 above)
Comment (Rylan12) [reply Library/Homebrew/brew.rb:144]: Fair, but it does sound like there is some confusion based on the linked issue. However, it's only one person (that I've seen) so I'm willing to remove it. If it comes up more in the future I'd ask that we take another look.

File: Library/Homebrew/brew.rb (hunk 2 above)
Comment (Rylan12) [reply Library/Homebrew/brew.rb:147]: 👍 Good idea

**Comment by MikeMcQuaid** [comment]
Very nice and simple 👏🏻 . Thanks for the fix, @Rylan12!
