### PR TITLE
Bye `byebug`, hi `debug`!

### LINKED ISSUE #16708: Fix byebug when running tests
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  llvm@11
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.9-42-gc355461
ORIGIN: https://github.com/Homebrew/brew
HEAD: c35546167da22c3c00d34332ff84a1bb40153766
Last commit: 10 hours ago
Core tap HEAD: b0cbf72d8dfb4b17daf988b4cb48ca01f1a72052
Core tap last commit: 7 hours ago
Core tap JSON: 19 Feb 21:36 UTC
Core cask tap HEAD: 10b89b8ddeac7513b77c0d19afe6b759146b6d65
Core cask tap last commit: 8 hours ago
Core cask tap JSON: 19 Feb 21:36 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.A51IW62L7n/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
```

### What were you trying to do (and why)?

This was something that came up in the team Slack channel. @dduugg first noticed that `byebug` wasn't working in tests even when running `brew tests --byebug` and setting breakpoints. I was able to reproduce the bug afterwards.

### What happened (include all command output)?

I set a breakpoint with `byebug` and expected the tests to stop when I hit the breakpoint. That didn't work. I then added the `:byebug` tag to the test itself and saw the byebug prompt but it wasn't interactive and the rest of the test continued to run after that point immediately.

### What did you expect to happen?

I expected to be able to set `brew tests --byebug` and set breakpoints and for the test suit to stop when they hit those breakpoints. This is helpful for debugging weird test failures.

### Step-by-step reproduction instructions (by running `brew` commands)

1. Change the tests to add a breakpoint.

```diff
diff --git a/Library/Homebrew/test/resource_spec.rb b/Library/Homebrew/test/resource_spec.rb
index e509902bd..4df9ed094 100644
--- a/Library/Homebrew/test/resource_spec.rb
+++ b/Library/Homebrew/test/resource_spec.rb
@@ -82,7 +82,8 @@ RSpec.describe Resource do
   end
 
   describe "#version" do
-    it "sets the version" do
+    it "sets the version", :byebug do
+      byebug
       resource.version("1.0")
       expect(resource.version).to eq(Version.parse("1.0"))
       expect(resource.version).not_to be_detected_from_url
```

2. Run `brew tests --byebug --only=resource`

```
Randomized with seed 45405
1 process for 1 spec, ~ 1 spec per process
...
[82, 91] in /usr/local/Homebrew/Library/Homebrew/test/resource_spec.rb
   82:   end
   83: 
   84:   describe "#version" do
   85:     it "sets the version", :byebug do
   86:       byebug
=> 87:       resource.version("1.0")
   88:       expect(resource.version).to eq(Version.parse("1.0"))
   89:       expect(resource.version).not_to be_detected_from_url
   90:     end
   91: 
.......................



Took 5 seconds
```

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- Fixes #16708.
- Byebug - added in 2020 by a GSoC student for test debugging - was not working and also old and hadn't had any commits in a while, also only reported support for Ruby 2. The `debug` gem, from the `ruby/debug` repository, supports our version of Ruby and is "official".
- A slight issue was it has a dependency on `psych`, which smarter people than me [worked out that we don't support - but if we pin it to an earlier version then it works](https://github.com/Homebrew/brew/issues/16708#issuecomment-1953483970).
- Add a bunch of dependencies to `.gitignore` etc, otherwise this diff was massive and we don't need +80k lines.

-----

image

But the (minimal, basic) testing I did seems to drop me at a prompt that I can use.

```
❯ git diff
diff --git a/Library/Homebrew/test/migrator_spec.rb b/Library/Homebrew/test/migrator_spec.rb
index 87fadd5e95..db4700810a 100644
--- a/Library/Homebrew/test/migrator_spec.rb
+++ b/Library/Homebrew/test/migrator_spec.rb
@@ -69,6 +69,8 @@ RSpec.describe Migrator do
       tab.source["tap"] = "homebrew/core"
       tab.write

+      binding.break
+
       expect do
         described_class.new(new_formula, "oldname")
       end.to raise_error(Migrator::MigratorDifferentTapsError)

issyl0 at pictor in /opt/homebrew on bye-byebug
❯ brew tests --only=migrator --debug
Randomized with seed 59158
1 process for 1 spec, ~ 1 spec per process
.==> Relinking newname
.==> Unlinking oldname
...==> Moving oldname versions to /private/tmp/homebrew-tests-20240403-85464-3uogqr/cellar/newname
....==> Migrating formula oldname to newname
==> Unlinking oldname
==> Moving oldname versions to /private/tmp/homebrew-tests-20240403-85464-3uogqr/cellar/newname
==> Relinking newname
....[67, 76] in ~/migrator_spec.rb
    67|       tab = Tab.empty
    68|       tab.tabfile = HOMEBREW_CELLAR/"oldname/0.1/INSTALL_RECEIPT.json"
    69|       tab.source["tap"] = "homebrew/core"
    70|       tab.write
    71|
=>  72|       binding.break
    73|
    74|       expect do
    75|         described_class.new(new_formula, "oldname")
    76|       end.to raise_error(Migrator::MigratorDifferentTapsError)
=>#0    block in <top (required)> (3 levels) at ~/migrator_spec.rb:72
  #1    [C] BasicObject#instance_exec at /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263
  # and 68 frames (use `bt' command for all frames)
(rdbg@/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/rspec#85464) p tab
(rdbg@/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/rspec#85464) p    # command(rdbg@/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/rspec#85464) p     # command t    # command ta    # command tab    # command(rdbg@/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/rspec#85464) p tab    # command
=> #<Tab:0x0000000107156be0 @Aliases=[], @Arch=nil, @built_as_bottle=false, @built_on={"os"=>"Macintosh", "os_version"=>"macOS 14", "cpu_family"=>"arm_firestorm_icestorm"}, @Compiler=:clang, @homebrew_version="4.2.16-55-gc8f60ec-dirty", @installed_as_dependency=false, @installed_on_request=false, @loaded_from_api=false, @poured_from_bottle=false, @runtime_dependencies=nil, @source={"path"=>nil, "tap"=>"homebrew/core", "tap_git_head"=>nil, "spec"=>"stable", "versions"=>{"stable"=>nil, "head"=>nil, "version_scheme"=>0}}, @source_modified_time=0, @stdlib=nil, @tabfile=#<Pathname:/private/tmp/homebrew-tests-20240403-85464-3uogqr/cellar/oldname/0.1/INSTALL_RECEIPT.json>, @time=nil, @unused_options=[], @used_options=[]>
(rdbg@/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/rspec#85464)
```

### CODE REVIEW

**Comment by Bo98** [comment]
> * A slight issue was it has a dependency on `psych`, which smarter people than me [worked out that we don't support - but if we pin it to an earlier version then it works](https://github.com/Homebrew/brew/issues/16708#issuecomment-1953483970).

Hmm, I wonder if instead of the debug dependency we can do (in `standalone/init.rb` just before the stuff at line 42):

```
if RUBY_PATH.to_s.include?("/vendor/portable-ruby/")
  $LOAD_PATH.unshift "#{RbConfig::CONFIG["rubylibprefix"]}/gems/debug-1.6.3/lib"
end
```

(I'll figure out a way to do this more magically rather than a hardcoded version - maybe on the Portable Ruby side)

This does limit it to Portable Ruby only, but for such a niche feature I'm OK thatwith given it avoids juggling more native gems.

**Comment by apainintheneck** [comment]
@issyl0 You got to it before I did. This will be helpful when working on https://github.com/Homebrew/brew/issues/16895.

@Bo98 If we could handle the debug dependency on the portable Ruby side, that would be ideal.

**Comment by MikeMcQuaid** [comment]
Great work @issyl0 and good idea!

> This does limit it to Portable Ruby only, but for such a niche developer-only feature I'm OK with that given it avoids juggling more native gems.

Same, as long as it gets a nice error message 👍🏻

File: Library/Homebrew/dev-cmd/tests.rb [hunk 1]
```diff
@@ -21,8 +21,8 @@ class Tests < AbstractCommand
         switch "--online",
                description: "Include tests that use the GitHub API and tests that use any of the taps for " \
                             "official external commands."
-        switch "--byebug",
-               description: "Enable debugging using byebug."
+        switch "--debug",
```
[the remark this answers is not in the document]
Comment (issyl0) [reply Library/Homebrew/dev-cmd/tests.rb:24]: Yeah, I thought that `--debug` can trigger both (ie, interactive debugging if a breakpoint is set, "normal" `odebug` things otherwise) without the cognitive load of having to remember that interactive debugging is another option.

**Comment by issyl0** [comment]
> (I'll figure out a way to do this more magically rather than a hardcoded version - maybe on the Portable Ruby side.)

@Bo98 Did you figure this out? Or can we ship this and do that in the future? Not that it's urgent, of course.

**Comment by Bo98** [comment]
well, hardcoded version will be fine as it won't change until we update Portable Ruby

**Comment by issyl0** [comment]
If anyone's got any suggestions for why this [doesn't work](https://github.com/Homebrew/brew/pull/17010/commits/561d4295d24b490807b7abe5acc6a0483720a58b) with the `debug` from portable Ruby, I'm marking this as non-draft, so please comment and/or push commits!

**Comment by Bo98** [comment]
Ah in addition to the `gems/debug-1.6.3/lib` path you will also need `extensions/#{RUBY_PLATFORM}/debug-1.6.3`

**Comment by issyl0** [comment]
Oooh, because `.so` is libraries, and those are "extensions"? Thanks again, Bo!

**Comment by issyl0** [comment]
🤔 I don't have an `extensions`?

```
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/extensions/arm64-darwin20/3.1.0-static/debug-1.6.3: No such file or directory

❯ ls /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/
3.1.0   gems
```

**Comment by Bo98** [comment]
`portable-ruby/3.1.4/lib/ruby/gems/3.1.0/extensions/...`

**Comment by issyl0** [comment]
That's weird...

```
❯ ls /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/gems/3.1.0/extensions/arm64-darwin20/3.1.0-static/debug-1.6.3
ls: /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/gems/3.1.0/extensions/arm64-darwin20/3.1.0-static/debug-1.6.3: No such file or directory
```

but

```
❯ ls /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/gems/3.1.0/extensions/arm64-darwin-20/3.1.0-static           
debug-1.6.3     rbs-2.7.0
```

So `RUBY_PLATFORM` is reporting `arm64-darwin20` when the path is actually `arm64-darwin-20`? What am I doing wrong?

I refer once again to the confused dog in the PR description. 😆

**Comment by Bo98** [comment]
Ah, right. `Gem::Platform.local` should work instead of `RUBY_PLATFORM`

**Comment by Bo98** [comment]
> if I add `require "debug"` to the spec_helper again it gives:
>
> ```
> LoadError:
>  cannot load such file -- debug
> ```

The require in `dev-cmd/tests` is useless and can go. The one in spec_helper will need to be _after_ the `../global` require.

**Comment by issyl0** [comment]
Thanks for the extra guidance, Bo! I made `brew tests --debug` set `ENV["HOMEBREW_DEBUG"]` and then `require`d the "debug" gem in `spec_helper.rb` based on that.

File: Library/Homebrew/standalone/init.rb [hunk 2]
```diff
@@ -39,6 +39,14 @@
   ENV["HOMEBREW_SKIP_INITIAL_GEM_INSTALL"] = "1"
 end
 
+if Pathname.new(RbConfig.ruby).to_s.include?("/vendor/portable-ruby/")
+  ruby_version = RbConfig::CONFIG["ruby_version"]
+  ruby_path = "#{RbConfig::CONFIG["rubylibprefix"]}/gems/#{ruby_version}"
+
+  $LOAD_PATH.unshift "#{ruby_path}/extensions/#{Gem::Platform.local}/#{ruby_version}-static/debug-1.6.3"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/standalone/init.rb:46]: Might be nice to glob or use a `Gem` method here so the version isn't hardcoded.

**Review by MikeMcQuaid — APPROVED** [review]
Looks good to me, thanks @issyl0! Only non-blocking feedback is on the hardcoded `debug` gem version; feels likely we'll forget to update that when portable Ruby is updated.

File: Library/Homebrew/test/spec_helper.rb [hunk 3]
```diff
@@ -38,6 +37,8 @@
 
 require_relative "../global"
 
+require "debug" if ENV["HOMEBREW_DEBUG"]
```
Comment (dduugg) [inline Library/Homebrew/test/spec_helper.rb:40]: i wonder if we should just do this for any command run with `--debug`?

Comment (Bo98) [reply Library/Homebrew/test/spec_helper.rb:40]: We ask end users to run `--debug` so I don't think so. Or if we do then it should catch a `LoadError` and fail silently.
