### PR TITLE
extend/os/mac: ensure writable file for codesign

### LINKED ISSUE #13903: Codesigning should ensure writability of relevant ancillary files
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8b195cc64a29595797651720ebb2ea09affb682
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f890e2444f92abb7dc791ebef23637556902828f
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config
  /usr/local/opt/curl/bin/curl-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libctxfuse.2.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  protobuf

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Chisel

### What happened (include all command output)?

Installation failed:

```
% brew reinstall chisel --debug
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/chisel.rb
==> Downloading https://ghcr.io/v2/homebrew/core/chisel/manifests/2.0.1
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.2\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/chisel/manifests/2.0.1
Already downloaded: /Users/nick/Library/Caches/Homebrew/downloads/752478f3c3981568c1e9509755a9022487f6d2a37ea65142f3c1958c9d8c755b--chisel-2.0.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/chisel/blobs/sha256:bd381685bf1bf3682e51c355acbca980b35659b8161f226329b3a0196aab55df
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.2\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/chisel/blobs/sha256:bd381685bf1bf3682e51c355acbca980b35659b8161f226329b3a0196aab55df
Already downloaded: /Users/nick/Library/Caches/Homebrew/downloads/73a2de687fad93f0f09593cb03592031d01c11b6e735bd249b7ce3f0ff2b9120--chisel--2.0.1.arm64_big_sur.bottle.tar.gz
==> Reinstalling chisel 
/opt/homebrew/Library/Homebrew/shims/shared/git --version
==> Pouring chisel--2.0.1.arm64_big_sur.bottle.tar.gz
tar --extract --no-same-owner --file /Users/nick/Library/Caches/Homebrew/downloads/73a2de687fad93f0f09593cb03592031d01c11b6e735bd249b7ce3f0ff2b9120--chisel--2.0.1.arm64_big_sur.bottle.tar.gz --directory /private/tmp/d20220920-59959-c69d3d
cp -pR /private/tmp/d20220920-59959-c69d3d/chisel/. /opt/homebrew/Cellar/chisel
==> Changing dylib ID of /opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel
  from @@HOMEBREW_PREFIX@@/opt/chisel/lib/Chisel.framework/Chisel
    to /opt/homebrew/opt/chisel/lib/Chisel.framework/Chisel
==> Codesigning /opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel
==> Codesigning (2nd try) /opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel
codesign --sign - --force --preserve-metadata=entitlements,requirements,flags,runtime /opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel:
/opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel: replacing existing signature
/opt/homebrew/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel: Permission denied

/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/opt/chisel/.brew/chisel.rb
```

### What did you expect to happen?

Installation would succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install chisel`
```

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This should fix #13903. I don't have an ARM machine at the moment so would appreciate some more eyes on this. Regarding test coverage, I'm not sure this is currently covered by existing tests. If we do want to add tests for this change, I'd be happy to add some if someone can point me to where/which file the tests should be added in.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Makes sense to me, thanks @alebcay!

**Comment by Bo98** [comment]
It'll be caused by GitHub gradually migrating `macos-latest` to be `macos-12`.

If we want a quick fix, can make the CI use `macos-11`. I'll take a look at reproducing the macOS 12 issues later this week.

**Comment by MikeMcQuaid** [comment]
> It'll be caused by GitHub gradually migrating `macos-latest` to be `macos-12`.
> 
> If we want a quick fix, can make the CI use `macos-11`. I'll take a look at reproducing the macOS 12 issues later this week, but it looks to be various issues such as the default `git` branch defaulting to `main` rather than `master`.

Works for me 👍🏻

File: Library/Homebrew/extend/os/mac/keg.rb [hunk 1]
```diff
@@ -31,36 +31,38 @@ def codesign_patched_binary(file)
     return unless Hardware::CPU.arm?
 
     odebug "Codesigning #{file}"
-    # Use quiet_system to squash notifications about resigning binaries
-    # which already have valid signatures.
-    return if quiet_system("codesign", "--sign", "-", "--force",
-                           "--preserve-metadata=entitlements,requirements,flags,runtime",
-                           file)
+    file.ensure_writable do
```
Comment (carlocab) [inline Library/Homebrew/extend/os/mac/keg.rb:34]: I don't think this fixes #13903. The problem in #13903 is not that the file we want to `codesign` is not writeable, but that files next to it that `codesign` needs to modify are not writeable.

In particular, when doing `codesign ... Chisel.framework/Chisel`, what we need to be writeable is actually `Chisel.framework/_CodeSignature/CodeResources` and not `Chisel.framework/Chisel`.

See Homebrew/discussions#3669 for more details.

**Review by carlocab — CHANGES_REQUESTED** [review]

**Comment by Bo98** [comment]
#13979 will fix CI.

File: Library/Homebrew/extend/os/mac/keg.rb (hunk 1 above)
Comment (alebcay) [reply Library/Homebrew/extend/os/mac/keg.rb:34]: Ah, thanks for the additional context. Are such ancillary files only present when codesigning a framework? From the `chisel` example so far, I take it that codesigning a dylib or other single binary is still self-contained with no ancillary files.

File: Library/Homebrew/extend/os/mac/keg.rb [hunk 2]
```diff
@@ -31,36 +31,60 @@ def codesign_patched_binary(file)
...
-    # Try signing again
-    odebug "Codesigning (2nd try) #{file}"
-    result = system_command("codesign", args: [
-      "--sign", "-", "--force",
-      "--preserve-metadata=entitlements,requirements,flags,runtime",
-      file
+  def prepare_codesign_writable_files(file)
+    tmppath = Tempfile.new("changed_files")
+    system_command("codesign", args: [
+      "--display", "--file-list", tmppath, file
```
Comment (carlocab) [inline Library/Homebrew/extend/os/mac/keg.rb:71]: I wonder if we can avoid the temporary file if we dumped this to stdout by passing `-` to `--file-list` instead.

**Review by carlocab — APPROVED** [review]

File: Library/Homebrew/extend/os/mac/keg.rb (hunk 2 above)
Comment (alebcay) [reply Library/Homebrew/extend/os/mac/keg.rb:71]: Yes, this does seem to work since the actual output from `codesign` goes to `stderr`. I'll have a patch later today.

File: Library/Homebrew/extend/os/mac/keg.rb [hunk 3]
```diff
@@ -31,36 +31,57 @@ def codesign_patched_binary(file)
...
 
-    # Try signing again
-    odebug "Codesigning (2nd try) #{file}"
+  def prepare_codesign_writable_files(file)
     result = system_command("codesign", args: [
-      "--sign", "-", "--force",
-      "--preserve-metadata=entitlements,requirements,flags,runtime",
-      file
+      "--display", "--file-list", "-", file
     ], print_stderr: false)
```
Comment (carlocab) [inline Library/Homebrew/extend/os/mac/keg.rb:71]: I think
```ruby
result.success?
```
is `false` here whenever the file list is empty.

If so we can probably return early.

**Review by carlocab — APPROVED** [review]

File: Library/Homebrew/extend/os/mac/keg.rb (hunk 3 above)
Comment (alebcay) [reply Library/Homebrew/extend/os/mac/keg.rb:71]: Is there ever a case where we would expect the file list to be empty? The path of the dylib or executable itself is still included in the ilst.

For instance, for the `chisel` example, the list is:
```
/usr/local/Cellar/chisel/2.0.1/lib/Chisel.framework/Chisel
/usr/local/Cellar/chisel/2.0.1/lib/Chisel.framework/_CodeSignature/CodeResources
```

Comment (carlocab) [reply Library/Homebrew/extend/os/mac/keg.rb:71]: It will be empty if the binary is not signed.

**Comment by carlocab** [comment]
Thanks @alebcay!
