### PR TITLE
list.sh: support column output

### LINKED ISSUE #18232: [Intentional or bug?] v4.3.19 `brew list` now outputs single column lists
### `brew doctor` output

```shell
➜  brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
➜  brew config
HOMEBREW_VERSION: 4.3.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f9bd2de89883ec9a59db3eab0f5475bce06d5bc
Last commit: 12 hours ago
Core tap JSON: 02 Sep 21:09 UTC
Core cask tap JSON: 02 Sep 21:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

Use `brew list` to view installed formulae and casks

### What happened (include all command output)?

`brew list` shows single column lists since version 4.3.19

Screenshot 2024-09-02 at 22 24 35

### What did you expect to happen?

Expected to see multi-column lists as displayed with `brew ls`

Screenshot 2024-09-02 at 22 24 42

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew list`
Run `brew ls`
```

### PR DESCRIPTION
**Pull request by Bo98**
Fixes #18232

### CODE REVIEW

File: Library/Homebrew/list.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ homebrew-list() {
     *) ;;
   esac
 
-  local ls_args=()
+  local ls_args=(-C)
```
Comment (cho-m) [inline Library/Homebrew/list.sh:12]: Just noting this may not work as expected unless `COLUMNS` has been set as environment variable. This isn't guaranteed to be set. For portability, would need some `stty` or `tput` workaround.

Comment (Bo98) [reply Library/Homebrew/list.sh]: I've fixed this to only apply to a TTY so that fixes your first example there to return just `actionlint`. Does that cover the rest?

Comment (cho-m) [reply Library/Homebrew/list.sh]: There is still the situation of this being `COLUMN` environment variable dependent and not portable across user setups. My setup doesn't include the variable, e.g.
```console
❯ zsh

❯ env | rg COLUMNS

❯ echo $COLUMNS
120

❯ tput cols
120
```
```console
❯ bash

❯ env | rg COLUMNS

❯ echo $COLUMNS
120

❯ tput cols
120
```

Perhaps doing something like `COLUMNS=${COLUMNS:-$(tput cols)} ls` to fall back to [`tput`](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/tput.html)

Comment (cho-m) [reply Library/Homebrew/list.sh]: Fast path:
```
❯ brew list
==> Formulae
actionlint			libtiff
aom				libtool
...
```

Slow path:
```
❯ brew ls
==> Formulae
actionlint			gron				libunibreak			pixman
aom				harfbuzz			libunistring			pkg-config
...
```

Comment (Bo98) [reply Library/Homebrew/list.sh]: Ah ok, I understand what you're saying. I think I've fixed that now.

File: Library/Homebrew/list.sh [hunk 2]
```diff
@@ -35,7 +36,9 @@ homebrew-list() {
   if [[ -t 1 ]]
   then
     tty=1
+    ls_args+=("-Cq")
```
Comment (cho-m) [inline Library/Homebrew/list.sh:39]: Sadly this happens too late now so overrides args like `-1`

Comment (Bo98) [reply Library/Homebrew/list.sh]: Fortunately, this block can easily be lifted up. I've done so now.

**Review by cho-m — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
