### PR TITLE
atomic_write: repair permissions after writing

### LINKED ISSUE #5916: inreplace is changing file permissions
Let's consider the following minimal formula:

```
$ cat libspatialite.rb
class Libspatialite < Formula
  url "https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz"
  sha256 "88900030a4762904a7880273f292e5e8ca6b15b7c6c3fb88ffa9e67ee8a5a499"

  patch do
   url "https://raw.githubusercontent.com/Homebrew/formula-patches/27a0e51936e01829d0a6f3c75a7fbcaf92bb133f/libspatialite/sqlite310.patch"
   sha256 "459434f5e6658d6f63d403a7795aa5b198b87fc9f55944c714180e7de662fce2"
  end

  def install
    system "stat", "configure"
    inreplace "configure",
              "shrext_cmds='`test .$module = .yes && echo .so || echo .dylib`'",
              "shrext_cmds='.dylib'"
    system "stat", "configure"
    system "false"
  end
end
```

The `inreplace` statement is changing the permissions of the `configure` file, as a verbose install reveals:

```
==> stat configure
16777220 29422446 -rwxr-xr-x 1 fx wheel 0 651938 "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" 4096 1280 0 configure
==> stat configure
16777220 29422455 -rw------- 1 fx admin 0 651852 "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" 4096 1280 0 configure
==> false
```

In the first `stat`, `configure` was `-rwxr-xr-x`, in the second one it's `-rw-------`.

This issue is making `libspatialite` in Homebrew core fail to build, while it works working a while ago… so it is actually a `brew` regression.

### PR DESCRIPTION
**Pull request by amyspark**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

This restores the original file uid, gid and permissions separately.
(ActiveSupport does it in a single step - atomically. This is not
useful in our use case because it may lead to ACL changes.)

Fixes #5916

### CODE REVIEW

File: Library/Homebrew/extend/pathname.rb [hunk 1]
```diff
@@ -163,9 +163,29 @@ def append_lines(content, *open_args)
 
   # NOTE: This always overwrites.
   def atomic_write(content)
+    old_stat = (stat if exist?)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/pathname.rb]: Can remove the `(``)` here.

File: Library/Homebrew/extend/pathname.rb [hunk 2]
```diff
@@ -163,9 +163,29 @@ def append_lines(content, *open_args)
...
+
+    # Try to restore original file's permissions separately
+    # atomic_write does it itself, but it actually erases
+    # them if chown fails
+    begin
+      # Set correct permissions on new file
+      chown(old_stat.uid, nil)
+      chown(nil, old_stat.gid)
+    rescue Errno::EPERM, Errno::EACCES # rubocop:disable Lint/HandleExceptions
+      # Changing file ownership failed, moving on.
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/pathname.rb]: Add a `nil` below this line instead of `# rubocop:disable Lint/HandleExceptions`

File: Library/Homebrew/extend/pathname.rb [hunk 3]
```diff
@@ -163,9 +163,29 @@ def append_lines(content, *open_args)
...
+    end
+    begin
+      # This operation will affect filesystem ACL's
+      chmod(old_stat.mode)
+    rescue Errno::EPERM, Errno::EACCES # rubocop:disable Lint/HandleExceptions
+      # Changing file permissions failed, moving on.
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/pathname.rb]: Add a `nil` below this line instead of `# rubocop:disable Lint/HandleExceptions`

**Comment by amyspark** [comment]
@MikeMcQuaid done!

**Comment by MikeMcQuaid** [comment]
Great work, thanks again @amyspark!
