### PR TITLE
Return standard output in `popen_write`

### LINKED ISSUE #8244: Error handler prints number of bytes instead of actual output
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? **Error seems unrelated, and I have no idea how to fix this anyway.**
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to version bump a formula whose inline (`:DATA`) patch would no longer apply to the newer version.

## What happened (include command output)

An error message is printed along with the **length** of the output.

(To make the case reproducible with minimal effort, I’m using the `rp` formula in the following output.)

<details>
  <summary>Command output</summary>
  <pre>

==> Patching
patching file CMakeLists.txt
Hunk #1 FAILED at 36.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
==> Kept temporary files
Temporary files retained at /private/tmp/rp-20200807-70880-1k3vn48
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
707

  </pre>
</details>

## What you expected to happen

An error message is printed along with the **actual output** of the failed command.

## Step-by-step reproduction instructions (by running `brew` commands)

1. To simulate a failing patch, run `brew edit rp`.
2. In the formula, change the word `BeaEngine` to `BeerEngine`.
3. Save the modified formula.
4. Run the following command line:

```
brew install -i --ignore-dependencies rp
```

(Note that neither `-i` nor `--ignore-dependencies` are needed for the error to occur, it’s just to make reproduction easier.)

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.9-294-g934e70c
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 934e70c8ee5693df6f47a9bada3bb7b57227e121
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ed3856d30e7e818f88ec4d82e8b8444e6f10cb1f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: '/usr/local/bin/code' -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1100
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.2, 12.0.2, 11.0.8, 10.0.2, 9, 1.8.0_262, 1.8.0_202
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1

$ brew doctor
Error: Cask 'tm-ledger' is unreadable: undefined method `method_missing_message' for Cask::Utils:Module
</pre>

### PR DESCRIPTION
**Pull request by claui**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

## Expected behaviour

We expect the `popen_write` method to return the standard output of the child process.

This expectation is evident in how `safe_popen_write` is written:

```ruby
  def self.safe_popen_write(*args, **options, &block)
    output = popen_write(*args, **options, &block)
    return output if $CHILD_STATUS.success?

    raise ErrorDuringExecution.new(args, status: $CHILD_STATUS, output: [[:stdout, output]])
  end
```

## Actual behaviour

Contrary to what the above code suggests, no code has been written to actually obtain any output from the child process. Newly-written tests show that `popen_write` only returns a number ("4") instead of the expected standard output.

For example, given a file `foo` with the content `Foo\n`, one of the tests calls `popen_write` with `cat foo -` and an input of `Bar`. The expected output would be `Foo\nBar\n` but the actual output is the number 4 (which is what Ruby’s `IO#write` method returns).

## Fix

By having `popen_write` transparently capture standard output, we restore the intended semantics.

The practical purpose of this PR is that when an [embedded formula patch](https://github.com/Homebrew/brew/blob/56ed27af15dafb8e8f2e884656ccad546d784482/Library/Homebrew/patch.rb#L72) fails, it now displays the actual output of the `patch` binary (instead of the length of the patch).

Fixes #8244.

### CODE REVIEW

File: Library/Homebrew/utils/popen.rb [hunk 1]
```diff
@@ -12,8 +12,27 @@ def self.safe_popen_read(*args, **options, &block)
     raise ErrorDuringExecution.new(args, status: $CHILD_STATUS, output: [[:stdout, output]])
   end
 
-  def self.popen_write(*args, **options, &block)
-    popen(args, "wb", options, &block)
+  def self.popen_write(*args, **options)
+    popen(args, "w+b", options) do |pipe|
+      output = +""
+      buffer = +""
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:18]: Does this definitely need to be a non-mutable string?

File: Library/Homebrew/utils/popen.rb [hunk 2]
```diff
@@ -12,8 +12,27 @@ def self.safe_popen_read(*args, **options, &block)
...
+
+      # Before we yield to the block, capture as much output as we can
+      loop do
+        pipe.read_nonblock(4096, buffer)
+        output.concat(buffer)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:23]:
```suggestion
        output += buffer
```

File: Library/Homebrew/utils/popen.rb [hunk 3]
```diff
@@ -12,8 +12,27 @@ def self.safe_popen_read(*args, **options, &block)
...
+      rescue IO::WaitReadable, EOFError
+        break
+      end
+
+      yield pipe
+      pipe.close_write
+      IO.select([pipe])
+
+      # Capture the rest of the output
+      output.concat(pipe.read)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:33]:
```suggestion
      output.concat += pipe.read
```

**Review by MikeMcQuaid — COMMENTED** [review]
Nice work @claui!

File: Library/Homebrew/utils/popen.rb (hunk 1 above)
Comment (claui) [reply Library/Homebrew/utils/popen.rb:18]: (I assume you meant to ask *Does this definitely need to be a mutable string?*)

Using a buffer is not really important here so I’m fine with dropping the buffer.

Comment (MikeMcQuaid) [reply Library/Homebrew/utils/popen.rb:18]: Yeh, makes sense to me 👍🏻

File: Library/Homebrew/utils/popen.rb [hunk 4]
```diff
@@ -12,8 +12,25 @@ def self.safe_popen_read(*args, **options, &block)
...
 
-  def self.popen_write(*args, **options, &block)
-    popen(args, "wb", options, &block)
+  def self.popen_write(*args, **options)
+    popen(args, "w+b", options) do |pipe|
+      output = ""
+
+      # Before we yield to the block, capture as much output as we can
+      loop do
+        output += pipe.read_nonblock(4096)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:21]: Sorry, last thing: why 4096? Can/should this be a variable or comment or the default?

Comment (claui) [reply Library/Homebrew/utils/popen.rb:21]: That’s the standard buffer size used throughout the [API documentation of Ruby’s IO class](https://docs.ruby-lang.org/en/2.6.0/IO.html).

It doesn’t really matter which (reasonable) buffer size we use here. We just need to specify one because Ruby doesn’t offer a default for `#read_nonblock`.

File: Library/Homebrew/utils/popen.rb [hunk 5]
```diff
@@ -1,46 +1,70 @@
...
+          rescue SystemCallError
+            $stderr.puts "brew: exec failed: #{args[0]}" unless options[:err] == :close
+            exit! 1
+          end
         end
       end
     end
   end
+
+  extend Popen
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:69]: Feels a bit weird to define the module and then immediately add it to a wider namespace?

File: Library/Homebrew/utils/popen.rb [hunk 6]
```diff
@@ -1,46 +1,70 @@
...
 module Utils
-  def self.popen_read(*args, **options, &block)
-    popen(args, "rb", options, &block)
-  end
-
-  def self.safe_popen_read(*args, **options, &block)
-    output = popen_read(*args, **options, &block)
-    return output if $CHILD_STATUS.success?
+  module Popen
+    DEFAULT_BUFFER_SIZE = 4096
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/popen.rb:5]: Perfect, thanks!

**Review by MikeMcQuaid — APPROVED** [review]
No blocking comments, thanks @claui.

File: Library/Homebrew/utils/popen.rb (hunk 5 above)
Comment (claui) [reply Library/Homebrew/utils/popen.rb:69]: That was to preserve the `Utils.popen_foo` syntax (rather than the somewhat awkward `Utils::Popen.popen_foo`).

Maybe we can extract the module outside `Utils`, for example to `Homebrew::Open`.
Then we can call the methods like so:

```
Open.popen_foo(…)
```

What do you think?

Comment (MikeMcQuaid) [reply Library/Homebrew/utils/popen.rb:69]: I'd be tempted to just leave modules as-is from before?

Comment (claui) [reply Library/Homebrew/utils/popen.rb:69]: Not sure where to put the constant then without bleeding into namespaces.

Comment (MikeMcQuaid) [reply Library/Homebrew/utils/popen.rb:69]: Doesn't matter if the constant bleeds in. If you really are concerned: can make it a named variable instead.

Comment (claui) [reply Library/Homebrew/utils/popen.rb:69]: Fair enough 👍

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @claui!
