### PR TITLE
Test do fix for HEAD versions.

### LINKED ISSUE #535: test block still uses old-style HEAD prefixes
`test do` blocks are currently broken for head specs for basically all formulae since the test block code is still using the old-style prefixes:

```
iMac-TMP:Formula joe$ brew install --HEAD wget
==> Cloning git://git.savannah.gnu.org/wget.git
Updating /Users/joe/Library/Caches/Homebrew/wget--git
==> Checking out branch master
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/wget/HEAD-ef372a4 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/openssl --disable-iri --disable-pcre
==> make install
🍺  /usr/local/Cellar/wget/HEAD-ef372a4: 48 files, 2.7M, built in 1 minute 59 seconds
iMac-TMP:Formula joe$ brew test -v wget
Testing wget
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160716-90573-8amf4j.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb -v --HEAD
==> /usr/local/Cellar/wget/HEAD/bin/wget -O - https://google.com
Failed to execute: /usr/local/Cellar/wget/HEAD/bin/wget
Error: wget: failed
Failed executing: /usr/local/Cellar/wget/HEAD/bin/wget -O - https://google.com
/usr/local/Library/Homebrew/formula.rb:1515:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1452:in `open'
/usr/local/Library/Homebrew/formula.rb:1452:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb:69:in `block in <class:Wget>'
/usr/local/Library/Homebrew/formula.rb:1356:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1350:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
iMac-TMP:Formula joe$ which wget
/usr/local/bin/wget
iMac-TMP:Formula joe$ readlink `which wget`
../Cellar/wget/HEAD-ef372a4/bin/wget
```

### PR DESCRIPTION
**Pull request by vladshablinsky**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #535

### CODE REVIEW

**Comment by vladshablinsky** [comment]
cc @xu-cheng @ilovezfs .

File: Library/Homebrew/formula.rb [hunk 1]
```diff
@@ -166,6 +166,10 @@ def initialize(name, path, spec)
     validate_attributes!
     @build = active_spec.build
     @pin = FormulaPin.new(self)
+
+    if head && head_pkg_version = latest_head_pkg_version
```
Comment (ilovezfs) [inline Library/Homebrew/formula.rb]: do you mean `==`?

Comment (vladshablinsky) [inline Library/Homebrew/formula.rb]: No, this checks whether `latest_head_pkg_version` is `nil` or not i.e. there is at least one  `HEAD` installed.

File: Library/Homebrew/formula.rb [hunk 2]
```diff
@@ -166,6 +166,10 @@ def initialize(name, path, spec)
...
+      head.version.update_version(head_pkg_version.version)
+    end
```
Comment (xu-cheng) [inline Library/Homebrew/formula.rb]: This is definitely incorrect. You should never update head commit to the `latest_head_pkg_version` unconditionaly, because it's quite possible that current active version is not `latest_head_pkg_version`.

File: Library/Homebrew/formula.rb (hunk 1 above)
Comment (ilovezfs) [inline Library/Homebrew/formula.rb]: OK, in that case you should probably do the assignment on its own line.

**Comment by xu-cheng** [comment]
As I explained in the above comment, this is an incorrect fix. 

What you really to do is to update commit inside `ARGV.resolved_formulae` and `Formulary.from_keg`, that's the place the resolution logic lies in. Therefore, here is my thought of solution:
```diff
diff --git a/Library/Homebrew/extend/ARGV.rb b/Library/Homebrew/extend/ARGV.rb
index beee470..2da6141 100644
--- a/Library/Homebrew/extend/ARGV.rb
+++ b/Library/Homebrew/extend/ARGV.rb
@@ -32,6 +32,10 @@ module HomebrewArgvExtension
           resolved_spec = spec(nil) || tab.spec
           f.set_active_spec(resolved_spec) if f.send(resolved_spec)
           f.build = tab
+          if f.head? && tab.tabfile
+            k = Keg.new(tab.tabfile.parent)
+            f.version.update_commit(k.version.version.commit)
+          end
         end
         f
       else
diff --git a/Library/Homebrew/formulary.rb b/Library/Homebrew/formulary.rb
index 4254437..20f115f 100644
--- a/Library/Homebrew/formulary.rb
+++ b/Library/Homebrew/formulary.rb
@@ -246,6 +246,7 @@ class Formulary
       end
     end
     f.build = tab
+    f.version.update_commit(keg.version.version.commit) if f.head?
     f
   end
 
diff --git a/Library/Homebrew/postinstall.rb b/Library/Homebrew/postinstall.rb
index 14e5781..0b6d8f6 100644
--- a/Library/Homebrew/postinstall.rb
+++ b/Library/Homebrew/postinstall.rb
@@ -11,7 +11,7 @@ begin
 
   trap("INT", old_trap)
 
-  formula = ARGV.formulae.first
+  formula = ARGV.resolved_formulae.first
   formula.extend(Debrew::Formula) if ARGV.debug?
   formula.run_post_install
 rescue Exception => e
diff --git a/Library/Homebrew/test.rb b/Library/Homebrew/test.rb
index 796ce09..ffffa18 100644
--- a/Library/Homebrew/test.rb
+++ b/Library/Homebrew/test.rb
@@ -19,7 +19,7 @@ begin
 
   trap("INT", old_trap)
 
-  formula = ARGV.formulae.first
+  formula = ARGV.resolved_formulae.first
   formula.extend(Homebrew::Assertions)
   formula.extend(Debrew::Formula) if ARGV.debug?
 
```

**Comment by vladshablinsky** [comment]
Agreed.

**Comment by mariusk** [comment]
When I try to build emacs with --HEAD, the build fails with:
````
Error: undefined method `commit' for #<Version:0x007fb931c24a10 @version="25.1-rc1">
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:249:in `from_keg'
/usr/local/Library/Homebrew/formulary.rb:225:in `from_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:43:in `block in resolved_formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/usr/local/Library/Homebrew/cmd/reinstall.rb:11:in `reinstall'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
````
I do not know much about homebrew internals, but by looking at this commit it seems ARGV.rb does a bit more before calling `update_commit` than formulary.rb, leading me to speculate that maybe some additional checks and updates are needed for formulary.rb as well (if I just comment out the line calling update_commit the build seems build fine)?

**Comment by ilovezfs** [comment]
@mariusk I think you need to `brew update`.

**Comment by mariusk** [comment]
I could have sworn I did it already, but now that I tested and rebuilt emacs it seems to work. Thanks, my bad!

**Comment by UniqMartin** [comment]
> I think you need to `brew update`.

However, if updating doesn't resolve this build failure, I suspect this is another manifestation of the bug that is about to be fixed in PR #644.

**Comment by UniqMartin** [comment]
Yes, indeed. Now that #644 is merged, this should be fixed after a `brew update`. But prior to that, this sequence of commands would have triggered the failure:

```console
$ brew install emacs --without-librsvg --devel
[…]
🍵   /opt/brewery/dummy/Cellar/emacs/25.1-rc1: 4,038 files, 97.6M, built in 3 minutes 6 seconds
$ brew reinstall emacs --HEAD
Error: undefined method `commit' for #<Version:0x007fd3e32c5538 @version="25.1-rc1">
Please report this bug:
    https://git.io/brew-troubleshooting
/opt/brewery/dummy/Library/Homebrew/formulary.rb:249:in `from_keg'
/opt/brewery/dummy/Library/Homebrew/formulary.rb:225:in `from_rack'
/opt/brewery/dummy/Library/Homebrew/extend/ARGV.rb:43:in `block in resolved_formulae'
/opt/brewery/dummy/Library/Homebrew/extend/ARGV.rb:27:in `map'
/opt/brewery/dummy/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/opt/brewery/dummy/Library/Homebrew/cmd/reinstall.rb:11:in `reinstall'
/opt/brewery/dummy/Library/Homebrew/brew.rb:87:in `<main>'
```
