### PR TITLE
gist-logs: close temp file before passing to curl, to ensure output availability

### LINKED ISSUE #417: gist-logs erroring for some formulae
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`? _N/A_

----------

`brew gist-logs` is breaking for me on some files today.

```
[✘ /usr/local on ⇄ master]
$ brew-gist-logs couchdb
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: ["gist", "notifications", "useremail"]
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: Problems parsing JSON
[✘ /usr/local on ⇄ master]
$ brew-gist-logs ditaa
https://gist.github.com/b2f6385979b2681fe463636443a98952
[/usr/local on ⇄ master]
$ brew-gist-logs anjuta
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: ["gist", "notifications", "useremail"]
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: Problems parsing JSON
[✘ /usr/local on ⇄ master]
$ brew-gist-logs vim
https://gist.github.com/58618d9f77f0c607ec9862e7b2731928
[/usr/local on ⇄ master]
$
```

The `brew-gist-logs` command is just a little wrapper function I use that loads the token in a subshell before calling `brew gist-logs`, so I don't have it in my environment all the time.

```
$ which brew-gist-logs
brew-gist-logs () {
	if [[ -e ~/.github-token ]]
	then
		(
			export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.github-token)
			brew gist-logs $*
		)
	else
		echo "~/.github-token not found" >&2
		return 1
	fi
}
```

I think the "token does not have sufficient scope" error here is spurious. The token does have the `gist` scope (I regenerated it just to make sure, and you can see that some gist posts succeed with the same token). I did a little debugging, and the error being returned is an HTTP 400 "bad request" error, and the "Problems parsing JSON" message is coming back from the server. The `api_credentials_error_message` method is getting called for any error response, when maybe it should only be called for 401 and 403 responses.

I reran it for these formula a few times, and it seems to be consistent with respect to which succeed and which error out. I don't see any apparent pattern based on which files the logs have, or the contents of those files.

```
[~/Library/Logs/Homebrew]
$ ls couchdb
01.couchjs
[~/Library/Logs/Homebrew]
$ ls ditaa
01.ant  01.ditaa
[~/Library/Logs/Homebrew]
$ ls anjuta
01.glib-compile-schemas  02.gtk3-update-icon-cache  03.update-mime-database
[~/Library/Logs/Homebrew]
$ ls vim
01.configure  01.configure.cc  02.make  02.make.cc  03.make
```

This is on OS X Mavericks.

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [X] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #417 

Looks like there's a race condition with I/O buffering when `gist-logs` is passing a temporary data file to `curl`. `close` is not called on the tempfile handle, so the data isn't guaranteed to be flushed to the filesystem and visible to external processes. This appears to be behind the intermittent JSON parsing errors during gist creations on one of my machines: adding the earlier `close` made them go away.

This adds a close, ensuring that the data gets written to disk so curl can see it, avoiding intermittent JSON parsing errors in gist creation.

Strictly speaking, there may be a similar race condition with the reading of the header temp file, which is opened in the `brew` Ruby process before `curl` writes out to it. But I don't think it'll ever get hit, because no `read` is done before `curl` runs, so it probably doesn't have a chance to buffer any output from the "before" state of the file.

### CODE REVIEW

File: Library/Homebrew/utils/github.rb [hunk 1]
```diff
@@ -140,6 +140,7 @@ def open(url, data=nil)
     begin
       if data
         data_tmpfile.write data
+        data_tmpfile.close
```
Comment (UniqMartin) [inline Library/Homebrew/utils/github.rb]: Could it create problems that the same file is closed a second time further down? Would using `IO#flush` instead of `IO#close` also fix the problem?

**Comment by UniqMartin** [comment]
Nice find! This could be causing all kinds of issues when accessing the GitHub API and it's good to get this fixed (though I believe only `gist-logs` actually posts data, so might be the only one affected).

File: Library/Homebrew/utils/github.rb (hunk 1 above)
Comment (apjanke) [inline Library/Homebrew/utils/github.rb]: Repeated `close`s are a no-op. (It's not really clear from the documentation, but it worked without error when I tested it, and the source code for `Tempfile#close` shows the implementation is happy with repeated closes.)

`IO#flush` might fix it, too; I'm not sure of the semantics. I'm thinking maybe not necessarily: the [IO#flush doco](http://ruby-doc.org/core-1.9.2/IO.html#method-i-flush) says that "this is Ruby internal buffering only; the OS may buffer the data as well". I'm not sure what that means with respect to visibility to external processes doing an `open`.

Regardless, I prefer `close`, because that makes it clear that you're not going to do any more writing to the file and are completely done with it before the reader starts reading, so you won't be doing interleaved reads and writes. I think that's the only way to be sure you always get a complete and consistent data transfer with plain files (otherwise the reader might do a buffered read ahead of the writer and get a premature EOF). The way we're using it here, `flush` could work too because we never actually do another write to that filehandle. But using `close` ensures we stick with that safe behavior.

Maybe that's not the most idiomatic Ruby way, though.

**Comment by apjanke** [comment]
Thanks!

BTW, I was able to reproduce it on my other Mavericks machine, too, using a different formula.

```
$ brew-gist-logs gdk-pixbuf
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: ["gist", "notifications", "useremail"]
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: Problems parsing JSON
```

Anything with a total log size of < 4K seems to trigger it for me. Which makes some sense, as that's the size of a page, so staying under that could affect buffering behavior.

File: Library/Homebrew/utils/github.rb (hunk 1 above)
Comment (UniqMartin) [inline Library/Homebrew/utils/github.rb]: I think the only concern with `IO#flush` is that this doesn't guarantee the data is written to disk. That's what `IO#fsync` is for. But despite the buffering by the OS, the OS should be offering the same consistent view of the file if any process-specific buffers have been flushed.

But that's just for context and my understanding of these methods. It makes a lot of sense to close the file as soon as we're done writing to it, and I'd leave it as-is. I'm not sure either what the most idiomatic Ruby code is to do what is done here, but the change seems fine to me.

**Comment by UniqMartin** [comment]
> Anything with a total log size of < 4K seems to trigger it for me. Which makes some sense, as that's the size of a page, so staying under that could affect buffering behavior.

This sounds quite plausible. It would also explain why this is usually not an issue for Gists posted due to build errors, as then the logs will usually be much larger. (At least I'm not aware of any problems users might have experienced with using `brew gist-logs` in recent times.)

**Comment by MikeMcQuaid** [comment]
Nice work here and thanks for fixing my 🐛. 🚢ing so users get it.
