### PR TITLE
cmd/--prefix: add --installed flag

### LINKED ISSUE #10261: Fresh brew install returns incorrect value for --prefix openssl
# Bug report

It seems a fresh installation of `brew` reports a value for `brew --prefix openssl` despite the keg not being installed.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to `cargo install cargo-generate`, which uses `brew` to find the "system" openssl installation. The install failed saying it could not find openssl. 

## What happened (include command output)
I doubled checked and ran:

```
% brew --prefix openssl
/opt/homebrew/Cellar/openssl@1.1/1.1.1i
```

## What you expected to happen

I expected no path to be reported. And when I tried to list the directory it did not exist:
```
% ls -lah $(brew --prefix openssl)
ls: /opt/homebrew/Cellar/openssl@1.1/1.1.1i: No such file or directory
% ls /opt/homebrew/Cellar/openssl@1.1
ls: /opt/homebrew/Cellar/openssl@1.1: No such file or directory
% ls /opt/homebrew/Cellar/
%
```

After installing openssl via `brew install openssl`, a different prefix is reported:
```
brew --prefix openssl
/opt/homebrew/opt/openssl@1.1
```
*note the missing `/1.1.1i` suffix.

Anyway, the installation of `cargo-generate` succeeds after `brew install openssl`. But I suspect there is something up here. Should brew be reporting a prefix for a cask that does not exist on the system? It looks like it does that for other formula that have not been installed when I check just now, so perhaps that is intended behavior. But why would the prefix _change_ once the formula has been installed?

## Step-by-step reproduction instructions (by running `brew` commands)

I believe simply installing homebrew using the install script and then running the command above yields the incorrect path.

## Output of `brew config` and `brew doctor` commands

<pre>
% brew doctor
Your system is ready to brew.
% brew config
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff9062c21bd1491b03541c62bb04a767f9957de2
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
Rosetta 2: false
</pre>

### PR DESCRIPTION
**Pull request by gromgit**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----
This changes the output for uninstalled formulae from Cellar prefix to empty string, so:
```sh
$ brew --prefix abcde python@3.9 tcl-tk
/usr/local/Cellar/abcde/2.9.3_1
/usr/local/opt/python@3.9
/usr/local/Cellar/tcl-tk/8.6.10
$ brew --prefix --installed abcde python@3.9 tcl-tk

/usr/local/opt/python@3.9

$
```
Fixes #10261. I chose to print an empty string instead of not printing anything at all, because `brew --prefix` supports multiple formulae input, so this lets the user tell both visually and programmatically which formulae aren't installed.

~~For the same reason, "not installed" still returns success as before, so that "no such formula" remains the only error condition~~ After a second think, since the switch is called `--installed`, it should return failure (to indicate that not everything requested is in place) but not an error message, since it's not an exceptional condition like "no such formula":
```sh
$ brew --prefix --installed abcde python@3.9 tlc-tk
Error: No available formula with the name "tlc-tk".
$ brew --prefix --installed abcde python@3.9 tcl-tk || echo "--> Returned failure."

/usr/local/opt/python@3.9

--> Returned failure.
```

### CODE REVIEW

File: Library/Homebrew/cmd/--prefix.rb [hunk 1]
```diff
@@ -39,7 +43,13 @@ def __prefix
       puts HOMEBREW_PREFIX
     else
       puts args.named.to_resolved_formulae.map { |f|
-        f.opt_prefix.exist? ? f.opt_prefix : f.latest_installed_prefix
+        if f.opt_prefix.exist?
+          f.opt_prefix
+        elsif args.installed?
+          ""
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:49]: What's the output if this is `nil`?

Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:49]:
```suggestion
          Homebrew.failed = true
          ""
```

to set the exit code to non-0

**Review by MikeMcQuaid — COMMENTED** [review]
Nice work so far @gromgit!

**Comment by MikeMcQuaid** [comment]
> ```shell
> $ brew --prefix --installed abcde python@3.9 tlc-tk
> Error: No available formula with the name "tlc-tk".
> ```

Could even consider raising a `NotAKegError` here if it's not installed.

File: Library/Homebrew/cmd/--prefix.rb (hunk 1 above)
Comment (gromgit) [reply Library/Homebrew/cmd/--prefix.rb:49]: Hmmm. Now that I've had a second think, I can see the logic of returning failure, given the name of the new option.

Comment (gromgit) [reply Library/Homebrew/cmd/--prefix.rb:49]: Exactly the same:
```sh
# ""
$ brew --prefix --installed abcde python@3.9 tcl-tk | od -t cx1 
0000000   \n   /   u   s   r   /   l   o   c   a   l   /   o   p   t   /
           0a  2f  75  73  72  2f  6c  6f  63  61  6c  2f  6f  70  74  2f
0000020    p   y   t   h   o   n   @   3   .   9  \n  \n                
           70  79  74  68  6f  6e  40  33  2e  39  0a  0a                
0000034

# nil
$ brew --prefix --installed abcde python@3.9 tcl-tk | od -t cx1 
0000000   \n   /   u   s   r   /   l   o   c   a   l   /   o   p   t   /
           0a  2f  75  73  72  2f  6c  6f  63  61  6c  2f  6f  70  74  2f
0000020    p   y   t   h   o   n   @   3   .   9  \n  \n                
           70  79  74  68  6f  6e  40  33  2e  39  0a  0a                
0000034
```

**Comment by gromgit** [comment]
> > ```shell
> > $ brew --prefix --installed abcde python@3.9 tlc-tk
> > Error: No available formula with the name "tlc-tk".
> > ```
> 
> Could even consider raising a `NotAKegError` here if it's not installed.

I'm not sure about that. "Formula not installed" is not an exceptional condition, and it's certainly not an unrecoverable one, unlike "no such formula". In fact, I can see a build script doing something like the following:
```bash
#!/usr/bin/env bash
shopt -s lastpipe
set -o pipefail
deps=(abcde python@3.9 tcl-tk)
prefixes=()

# Let's see what's already installed
brew --prefix --installed "${deps[@]}" | readarray -t prefixes
for n in "${!deps[@]}"; do
  if [[ -z "${prefixes[$n]}" ]]; then
    # Install what's missing
    brew install "${deps[$n]}"
  fi
done

# Get all the prefixes again, so we can use them for real
brew --prefix --installed "${deps[@]}" | readarray -t prefixes

[...]
```

File: Library/Homebrew/cmd/--prefix.rb (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/--prefix.rb:51]: > Is `nil` preferred in this context?

Yeh, I think so 👍🏻

File: Library/Homebrew/cmd/--prefix.rb [hunk 2]
```diff
@@ -25,12 +25,17 @@ def __prefix_args
       EOS
       switch "--unbrewed",
              description: "List files in Homebrew's prefix not installed by Homebrew."
+      switch "--installed",
+             description: "Display an empty string if <formula> is not installed."
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:29]:
```suggestion
             description: "Outputs nothing and returns a failing status code if <formula> is not installed."
```

**Comment by MikeMcQuaid** [comment]
> I'm not sure about that. "Formula not installed" is not an exceptional condition, and it's certainly not an unrecoverable one, unlike "no such formula". In fact, I can see a build script doing something like the following:

It feels weird to return an non-zero status code and not say why, is my only concern. We get to define what this outputs/does as we're creating a new flag (and hiding it is only a `2>/dev/null` away).

**Comment by gromgit** [comment]
> It feels weird to return an non-zero status code and not say why, is my only concern.

Fair enough. I've altered the output to list the missing formulae on stderr:
```bash
$ brew --prefix --installed abcde python@3.9 tcl-tk 

/usr/local/opt/python@3.9

Warning: The following formulae are not installed:
abcde tcl-tk

$ brew --prefix --installed abcde python@3.9 tcl-tk 2>/dev/null || echo Missing stuff

/usr/local/opt/python@3.9

Missing stuff
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> Warning: The following formulae are not installed:
> abcde tcl-tk
> ```

I feel like at that point `NotAKegError` is going to provide more consistent behaviour and output. Thoughts?

**Comment by gromgit** [comment]
> I feel like at that point `NotAKegError` is going to provide more consistent behaviour and output. Thoughts?

You mean like:
```ruby
      if args.installed? 
        missing_formulae = formulae.reject { |f| f.opt_prefix.exist? }
                                   .map(&:name)
        return if missing_formulae.empty?

        raise NotAKegError, <<~EOS
          The following formulae are not installed:
          #{missing_formulae.join(" ")}
        EOS
      end
```
which does this:
```bash
$ brew --prefix --installed abcde python@3.9 tcl-tk 

/usr/local/opt/python@3.9

Error: The following formulae are not installed:
abcde tcl-tk
```
? I don't have a strong opinion either way, but I'd rather respect existing semantics where possible, if only to make it easier for the next person to comprehend the code.

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/cmd/--prefix.rb [hunk 3]
```diff
@@ -25,22 +25,44 @@ def __prefix_args
...
+      formulae = args.named.to_resolved_formulae
+      puts formulae.map { |f|
+        if f.opt_prefix.exist?
+          f.opt_prefix
+        elsif args.installed?
+          nil
+        else
+          f.latest_installed_prefix
+        end
       }
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:55]:
```suggestion
     prefixes = formulae.map do |f|
        if f.opt_prefix.exist?
          f.opt_prefix
        elsif args.installed?
          nil
        else
          f.latest_installed_prefix
        end
      end.compact
      puts prefixes
```

Otherwise `brew --prefix --installed $SOMETHING_NOT_INSTALLED` will always have a blank line before the error.

File: Library/Homebrew/cmd/--prefix.rb [hunk 4]
```diff
@@ -25,22 +25,44 @@ def __prefix_args
...
+      if args.installed?
+        missing_formulae = formulae.reject { |f| f.opt_prefix.exist? }
+                                   .map(&:name)
+        return if missing_formulae.empty?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:59]:
```suggestion
        return if missing_formulae.blank?
```

File: Library/Homebrew/cmd/--prefix.rb [hunk 5]
```diff
@@ -25,22 +25,44 @@ def __prefix_args
...
+        if f.opt_prefix.exist?
+          f.opt_prefix
+        elsif args.installed?
+          nil
+        else
+          f.latest_installed_prefix
+        end
       }
+      if args.installed?
+        missing_formulae = formulae.reject { |f| f.opt_prefix.exist? }
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/--prefix.rb:57]:
```suggestion
        missing_formulae = formulae.reject(&:optlinked?)
```

**Comment by MikeMcQuaid** [comment]
Thanks again @gromgit, great work here!
