### PR TITLE
Don't tap user-untapped official taps

### LINKED ISSUE #10303: brew taps homebrew/cask on user typos
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ NA] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [NA] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install or remove a package, but I made a typo. For example:

```shell
brew install mpmtp # typo: this should be msmtp
brew rm mpmtp # same typo
```

## What happened (include command output)

<summary>Homebrew started to tap `homebrew/cask`.</summary>

<pre>

 Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'
…
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "nobodyhome".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
  </pre>

</details>

## What you expected to happen

I would expect Homebrew to say "Can't install mpmtp because there is no such formula" or "Can't remove mpmtp because it is not currently installed."

## Clarification and expansion

After seeing the questions below and doing some more experimentation, I see that there are two (probably related) issues here:

1. If you ask `brew` to install a package that does not exist (perhaps because you make a typo), `brew` will tap `homebrew/cask`. This seems to be by design: it's part of the process where `brew` goes looking for what the user asked for in other places (cask, recently deleted formulas, etc.). I don't think that this should be the default. (I'd rather be told "Did you mean a cask? If so, tap that repo, etc.") But this may be bikeshedding.
2. If you ask `brew` to remove a package that does not exist (perhaps because you make a typo) *or even a package that does exist but that you don't have installed*, `brew` will tap `homebrew/cask`. This  doesn't make sense to me: it takes a significant amount of time to tap `homebrew/cask`, but it's pointless in this case. If I run `brew remove newt`, `brew` taps `homebrew/cask` only to tell me `Error: No available formula or cask with the name "newt".` But `newt` is a formula in `homebrew-core`. There was no need to tap `homebrew/cask` in this case at all. I wonder if `brew remove` shares too much code or logic with `brew install`.
3. On my machine, `brew remove <typo>` takes a minute and a half because of the addition of `brew tap homebrew/cask`. So, I hope that it doesn't seem to be bikeshedding to want to change the default behavior for `brew remove` even if not for `brew install`.

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [x] Have you successfully run `brew man` locally and committed any changes?

-----

Fixes #10303

This PR modifies the logic for when to automatically tap official taps.

As a refresher, there are two times where an official tap would be automatically tapped:
1. When running the `bundle`, `test-bot`, or `services` command and the respective repo isn't tapped
2. When `args.named.to_casks` (or other similar methods that convert named args to casks) is unable to match a name to a formula or cask. This is seen mostly when running `brew install <invalid_formula_or_cask>` or `brew uninstall <invalid_formula_or_cask>`.

Now, if a user has untapped an official tap, we will remember this in the Homebrew settings. If a user does one of the above actions that would normally tap the repo, we will first check to see whether they have already untapped the repo. If so, we assume that they genuinely do not want that repo, so we don't re-tap.

A few comments:
- There is one more spot where `Tap.install_default_cask_tap_if_necessary` is used in [`Library/Homebrew/cask/cmd.rb`](https://github.com/Homebrew/brew/blob/152eac333b3cfed6801d26a30183954d8a3d5c1b/Library/Homebrew/cask/cmd.rb#L170). Should this be modified to _always_ tap the cask repo, even if the user has explicitly untapped it? I'm not sure if this file will even have a use after Homebrew 2.8.0 (where `brew cask` commands are removed).
- If there are other places where a similar thing is done that should be modified, let me know.
- I will probably refactor some of this logic out to an e.g. `Tap.untapped_official_taps` to avoid repeating the `untapped = Settings.read(:untapped) || []` line in many places. I didn't for now simply because I wanted to get this PR up for feedback.

CC: @carlocab, @fxcoudert, and @jonchang

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Nice idea here! I think it might be nicer to reduce the situations in which `install_default_cask_tap_if_necessary` is run to only when a e.g. `--cask` option or similar is specifically run. Otherwise, if we're looking up "formula or a cask" and it's not tapped: we should simply skip all cask logic. Thoughts?

**Comment by Rylan12** [comment]
> Nice idea here! I think it might be nicer to reduce the situations in which `install_default_cask_tap_if_necessary` is run to only when a e.g. `--cask` option or similar is specifically run. Otherwise, if we're looking up "formula or a cask" and it's not tapped: we should simply skip all cask logic. Thoughts?

I think it depends on whether we can assume that the only reason the cask tap wouldn't be installed is that a user actively uninstalled it (if that makes sense).

Does the Homebrew installer always tap the cask tap (on macOS)? If so, for how long has it done this?

If the answer is no, I don't think we should do that. We want `brew install <cask>` to work out of the box, so keeping the auto-tap feature is important.

If the answer is yes, I'd be more on-board. I think that means that we can assume that the cask tap being uninstalled indicates an active user choice to untap. We may still want to show a message reminding users (who don't have `homebrew/cask` in the `homebrew.untapped` setting) to `brew tap homebrew/cask` if they want casks.

**Comment by MikeMcQuaid** [comment]
> Does the Homebrew installer always tap the cask tap (on macOS)?

It does not.

> We want `brew install <cask>` to work out of the box, so keeping the auto-tap feature is important.

Agreed but I don't think it is in any case other than `brew install`.

**Comment by Rylan12** [comment]
> Agreed but I don't think it is in any case other than `brew install`.

Ah, I see. Yeah, we can probably move the `retry if Tap. install_default_cask_tap_if_necessary` line to the actual `install` command itself.

**Comment by Rylan12** [comment]
Okay, I updated so it will only attempt to tap on `brew install`. I also decided to override the `homebrew.untapped` setting if `--cask` is passed, assuming that if a user passes `--cask` they are okay with homebrew/cask being tapped.

**Comment by Rylan12** [comment]
I've seen this failure many times recently. Not sure what's going on. It seems that simply rerunning the tests fixes it.

```
  1) Homebrew::Cleanup::cleanup_logs cleans up logs if older than 30 days
     Failure/Error: expect(path).not_to exist
       expected #<Pathname:/tmp/homebrew-tests-20210120-8897-1khwbac/logs/delete_me> not to exist
     # ./test/cleanup_spec.rb:215:in `block (3 levels) in <top (required)>'
     # ./test/cleanup_spec.rb:43:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:207:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:206:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

**Comment by MikeMcQuaid** [comment]
> I've seen this failure many times recently. Not sure what's going on. It seems that simply rerunning the tests fixes it.

Yeh, it's either order-dependent or failing based on another test that's running. Could ideally try to fix that or bump the retries?

File: Library/Homebrew/cmd/install.rb [hunk 1]
```diff
@@ -153,8 +153,14 @@ def install
       EOS
     end
 
-    formulae, casks = args.named.to_formulae_and_casks
-                          .partition { |formula_or_cask| formula_or_cask.is_a?(Formula) }
+    begin
+      formulae, casks = args.named.to_formulae_and_casks
+                            .partition { |formula_or_cask| formula_or_cask.is_a?(Formula) }
+    rescue FormulaOrCaskUnavailableError, Cask::CaskUnavailableError => e
+      retry if Tap.install_default_cask_tap_if_necessary(force: args.cask?)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:160]: Perfect 🎉

File: Library/Homebrew/brew.rb [hunk 2]
```diff
@@ -132,7 +132,9 @@ class MissingEnvironmentVariables < RuntimeError; end
     possible_tap = OFFICIAL_CMD_TAPS.find { |_, cmds| cmds.include?(cmd) }
     possible_tap = Tap.fetch(possible_tap.first) if possible_tap
 
-    odie "Unknown command: #{cmd}" if !possible_tap || possible_tap.installed?
+    if !possible_tap || possible_tap.installed? || Tap.untapped_official_taps.include?(possible_tap.name)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/brew.rb:135]: So this logic (and everything related) means that if you untap it: it'll never be automatically retapped?

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/brew.rb (hunk 2 above)
Comment (Rylan12) [reply Library/Homebrew/brew.rb:135]: Yes, that's the idea. Although, if you retap using `brew tap homebrew/cask`, it removes homebrew/cask from the `homebrew.untapped` setting meaning that it would be retapped automatically in the future if needed (assuming the reason it became untapped was not done using `tap.uninstall`. tbh I'm not sure how that would happen).

Actually, now that I'm thinking about it, are there any instances where a tap could be uninstalled and we _wouldn't_ want to write to the setting? Maybe we should only write if a user untaps via the `brew untap` command...

Comment (MikeMcQuaid) [reply Library/Homebrew/brew.rb:135]: > Yes, that's the idea. Although, if you retap using `brew tap homebrew/cask`, it removes homebrew/cask from the `homebrew.untapped` setting meaning that it would be retapped automatically in the future if needed (assuming the reason it became untapped was not done using `tap.uninstall`. tbh I'm not sure how that would happen).

Seems good!

> Maybe we should only write if a user untaps via the `brew untap` command...

Yeh, maybe?

Comment (Rylan12) [reply Library/Homebrew/brew.rb:135]: This line, in particular, is saying "raise an error saying unknown command if there is no tap found with the given command, the tap with the given command is already installed, or the tap with the given command has been manually uninstalled by the user. Otherwise, continue and autotap"
