### PR TITLE
tab: fix typing of versions

### LINKED ISSUE #15401: Error: Version must not be empty
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  libgit2@1.5
  rtx

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  jsonschema

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjack.0.dylib
  /usr/local/lib/libjacknet.0.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  minikube
  rust
  kubernetes-cli
  six
  python@3.8
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.17-46-g5806772
ORIGIN: https://github.com/Homebrew/brew
HEAD: 58067727f4209f5e8d51a365d77fe1e04b4cb440
Last commit: 22 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e724a19598ac7e8774a5608197a17cbfa60beaad
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 11 May 00:30 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 14.0.3 build 1403
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: N/A
Xcode: 14.3
```

### What were you trying to do (and why)?

`brew cleanup`

### What happened (include all command output)?

```
Error: Version must not be empty
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/version.rb:498:in `initialize'
/usr/local/Homebrew/Library/Homebrew/tab.rb:318:in `new'
/usr/local/Homebrew/Library/Homebrew/tab.rb:318:in `then'
/usr/local/Homebrew/Library/Homebrew/tab.rb:318:in `stable_version'
/usr/local/Homebrew/Library/Homebrew/formula.rb:608:in `head_version_outdated?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:622:in `latest_installed_prefix'
/usr/local/Homebrew/Library/Homebrew/formula.rb:568:in `latest_version_installed?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2583:in `eligible_kegs_for_cleanup'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:318:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:261:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:260:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:260:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:56:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

No error.

### Step-by-step reproduction instructions (by running `brew` commands)

1. Run `brew cleanup`.
2. The command returns the error message.

### PR DESCRIPTION
**Pull request by Bo98**
This is a nearly 5 year old bug that only revealed itself now that we've tightened up typing and validation in `version.rb` (for the better IMO - empty string versions do not make sense, can hide genuine bugs, have indeterminate behaviour in terms of comparisons, and fails to satisfy any `Version#null?` check).

This did _not_ affect bottles installed from GitHub Packages, so most users were unaffected.

Fixes #15401.

### CODE REVIEW

File: Library/Homebrew/tab.rb [hunk 1]
```diff
@@ -45,8 +45,8 @@ def self.create(formula, compiler, stdlib)
         "tap_git_head" => nil, # Filled in later if possible
         "spec"         => formula.active_spec_sym.to_s,
         "versions"     => {
-          "stable"         => formula.stable&.version.to_s,
-          "head"           => formula.head&.version.to_s,
+          "stable"         => formula.stable&.version&.to_s,
+          "head"           => formula.head&.version&.to_s,
```
Comment (reitermarkus) [inline Library/Homebrew/tab.rb:49]: `to_s` shouldn't be needed since `Version#to_str` exists.

**Review by reitermarkus — CHANGES_REQUESTED** [review]

File: Library/Homebrew/tab.rb (hunk 1 above)
Comment (reitermarkus) [reply Library/Homebrew/tab.rb:49]: I guess `to_str` should actually error for `NULL` versions. Similar to `nil.to_s` vs `nil.to_str`.

Also `Version::NULL.to_json` should output `null` instead of `""`.

Comment (Bo98) [reply Library/Homebrew/tab.rb:49]: It's going to be a string when reading from the JSON so won't exactly make it make the code simpler having to adjust for that.

But I see what you mean about `Version::NULL`, so will likely indeed need to handle it that way.

Comment (reitermarkus) [reply Library/Homebrew/tab.rb:49]: Yeah, makes sense. I didn't check how this is used elsewhere in this file. I thought this is just a `Hash` that ends up with `to_json` being called on it.

File: Library/Homebrew/tab.rb [hunk 2]
```diff
@@ -108,6 +108,13 @@ def self.from_file_content(content, path)
       }
     end
 
+    # Tabs created with Homebrew 1.5.13 through 4.0.17 inclusive created empty string versions in some cases.
+    ["stable", "head"].each do |spec|
+      next if attributes["source"]["versions"][spec].nil?
+
+      attributes["source"]["versions"][spec] = nil if attributes["source"]["versions"][spec].empty?
```
Comment (reitermarkus) [inline Library/Homebrew/tab.rb:115]:
```suggestion
      attributes["source"]["versions"][spec] = attributes["source"]["versions"][spec].presence
```

File: Library/Homebrew/tab.rb [hunk 3]
```diff
@@ -45,8 +45,8 @@ def self.create(formula, compiler, stdlib)
         "tap_git_head" => nil, # Filled in later if possible
         "spec"         => formula.active_spec_sym.to_s,
         "versions"     => {
-          "stable"         => formula.stable&.version.to_s,
-          "head"           => formula.head&.version.to_s,
+          "stable"         => formula.stable&.version&.to_s.presence,
+          "head"           => formula.head&.version&.to_s.presence,
```
[the remark this answers is not in the document]
Comment (Bo98) [reply Library/Homebrew/tab.rb:49]: To cover the `Version::NULL` case.

[the remark this answers is not in the document]
Comment (reitermarkus) [reply Library/Homebrew/tab.rb:49]: I don't think we can get to that point since we we check for empty versions in `Formula#validate_attributes!`.

[the remark this answers is not in the document]
Comment (Bo98) [reply Library/Homebrew/tab.rb:49]: Ah ok didn't see that.

**Review by reitermarkus — APPROVED** [review]
