### PR TITLE
Fix `{MacOS,Xcode}Requirement` handling and improve output

### LINKED ISSUE #14563: Consider merging required OS and minimum OS version, and displaying a checkmark consistent for your OS
Opening the issue as requested by @nandahkrishna in https://github.com/Homebrew/homebrew-core/pull/122364#issuecomment-1418365739

### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.21-5-gb761344
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7613444287405c8a853bae980e1883c6899ec69
Last commit: 27 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b16ea1b58663e6284bf4f9d2808ecdd826d1fcd4
Core tap last commit: 23 hours ago
Core tap branch: master
Core tap JSON: 06 Feb 23:19 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.39.1 => /bin/git
Curl: 7.87.0 => /bin/curl
Kernel: Linux 6.1.7-arch1-1 x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.37
/usr/bin/gcc: 12.2.1
/usr/bin/ruby: 3.0.5
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

I was just checking information with `brew info`

### What happened (include all command output)?

It displayed this:

```
$ brew info tart
==> tart: stable 0.37.0
macOS and Linux VMs on Apple Silicon to use in CI and other automations
[…]]
Required: arm64 architecture ✘, macOS ✔, macOS ✘
```

### What did you expect to happen?

Considering the command was ran from a Linux computer, macOS should be written only once and the checkmark should be a red cross.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew info tart` on a Linux computer to see an example, but that could happen on many other formulas.
```

### PR DESCRIPTION
**Pull request by nandahkrishna**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Closes #14563.

This PR fixes some issues with `MacOSRequirement` handling and related `brew info`/`brew unbottled` output on Linux. I have not (yet) added tests but would be happy to if we feel that it is important to add some for these cases.

Prior to this PR, on Linux:
```
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew info tart
...
==> Requirements
Build: Xcode >= 14.1 ✔
Required: arm64 architecture ✘, macOS ✔, macOS ✘
...

linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew unbottled --tag big_sur tart
==> Populating dependency tree...
==> :big_sur bottle status
tart: requires Linux
```

After this PR, on Linux:
```
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew info tart
...
==> Requirements
Build: Xcode >= 14.1 (on macOS) ✔
Required: arm64 architecture ✘, macOS >= 12 (or Linux) ✔, macOS ✘
...

linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew unbottled --tag big_sur tart
==> Populating dependency tree...
==> :big_sur bottle status
tart: doesn't support this macOS
```

Some problems that remain (on macOS and Linux):
```
➜ brew unbottled --tag arm64_monterey tart
==> Populating dependency tree...
==> :arm64_monterey bottle status
tart: doesn't support this macOS
```
However, there is an `arm64_monterey` bottle for this formula. This has to do with the `Xcode.latest_version` and the fact that `tart`'s minimum Xcode requirement of 14.1 is satisfied only from Monterey 12.5.

Questions:
* How do we handle the `XcodeRequirment` inaccuracies?
* Would it be easier to just remove some functionality of `brew info/unbottled` on Linux for macOS-only formulae?

### CODE REVIEW

File: Library/Homebrew/dev-cmd/unbottled.rb [hunk 1]
```diff
@@ -186,6 +186,15 @@ def output_unbottled(formulae, deps_hash, noun, hash, any_named_args)
...
 
       requirements = f.recursive_requirements
+
+      # On Linux, a LinuxRequirement could be added to requirements due to any
+      # Linux-specific Linux-only dependents. This will conflict with a
+      # MacOSRequirement, and incorrectly output that the formula requires
+      # Linux for a macOS bottle tag. Such a LinuxRequirement must be removed.
+      if requirements.any?(MacOSRequirement) && requirements.any?(LinuxRequirement)
+        requirements.reject! { |r| r.is_a?(LinuxRequirement) }
+      end
```
Comment (Bo98) [inline Library/Homebrew/dev-cmd/unbottled.rb:196]: This should not happen unless `on_linux` blocks are being evalauted, no?

Sounds like something's gone wrong if those blocks are being evaluated.

**Comment by Bo98** [comment]
>  This has to do with the Xcode.latest_version and the fact that tart's minimum Xcode requirement of 14.1 is satisfied only from Monterey 12.5.

Ah yes, that's an easy fix. We chose not to bump to 14.0 due to bugs, but 14.1 should be ok.

File: Library/Homebrew/dev-cmd/unbottled.rb (hunk 1 above)
Comment (nandahkrishna) [reply Library/Homebrew/dev-cmd/unbottled.rb:196]: Yeah seems like those blocks are being evaluated because the formula is loaded as it normally would be on Linux, despite specifying a macOS bottle tag. So the command output could be incorrect because we recursively check potentially Linux-only dependencies for a macOS tag.

Comment (Bo98) [reply Library/Homebrew/dev-cmd/unbottled.rb:196]: Hmm odd given we have `Homebrew::SimulateSystem` wrapping all this. Seems like a bad bug if so given we rely on that for audits and readall checks.

Comment (Bo98) [reply Library/Homebrew/dev-cmd/unbottled.rb:196]: Actually is this with or without `HOMEBREW_NO_INSTALL_FROM_API` or is it no difference?

Comment (nandahkrishna) [reply Library/Homebrew/dev-cmd/unbottled.rb:196]: Ah this is using the API on Linux. Here's some hopefully relevant output:
```
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew/Library/Homebrew$ brew unbottled --tag big_sur tart
==> Populating dependency tree...
==> :big_sur bottle status
tart: requires Linux
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew/Library/Homebrew$ HOMEBREW_NO_INSTALL_FROM_API=1 brew unbottled --tag big_sur tart
==> Populating dependency tree...
==> :big_sur bottle status
Error: undefined method `latest_version' for OS::Mac::Xcode:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:208:in `block (2 levels) in output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/set.rb:338:in `each_key'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/set.rb:338:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/delegate.rb:83:in `all?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:199:in `block in output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:180:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:180:in `output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:93:in `unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
So it seems like that `LinuxRequirement` is added only for the API. To confirm, I tried printing `f.recursive_dependencies` with and without the API, and it prints Linux-only dependencies for a simulated macOS only on the API.

Comment (Bo98) [reply Library/Homebrew/dev-cmd/unbottled.rb:196]: Yes, simulation is not supported with the API yet.

File: Library/Homebrew/dev-cmd/unbottled.rb [hunk 2]
```diff
@@ -205,6 +214,8 @@ def output_unbottled(formulae, deps_hash, noun, hash, any_named_args)
           when XcodeRequirement
             next true unless r.version
 
+            require "os/mac/xcode" if OS.linux?
```
Comment (nandahkrishna) [inline Library/Homebrew/dev-cmd/unbottled.rb:217]: I didn't run `brew style` after https://github.com/Homebrew/brew/pull/14870/commits/7586c368cf989de2a4fbfef59dcc350cab960bc5 but it seems I have a style failure for exactly that change:
```
Library/Homebrew/dev-cmd/unbottled.rb:217:39: C: Move OS.linux? and OS.mac? calls to extend/os.
            require "os/mac/xcode" if OS.linux?
                                      ^^^^^^^^^
```
Would it be okay to unconditionally `require "os/mac/xcode"` (in a new `extend/os/linux/dev-cmd/unbottled.rb` file if required, which would then be `require`d in this file, similar to `update-test`)?

File: Library/Homebrew/dev-cmd/unbottled.rb (hunk 1 above)
Comment (nandahkrishna) [reply Library/Homebrew/dev-cmd/unbottled.rb]: This seems to have worked, thanks Bo!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Looks good to me!

**Comment by MikeMcQuaid** [comment]
Good to merge when CI is 🟢

**Comment by Porkepix** [comment]
From what I see here, macOS is still shown twice in the info on Linux, with the second being red; isn't this still confusing to read? Shouldn't this be factored in only one macOS mention?

**Comment by nandahkrishna** [comment]
Cross-posted from the issue:

>It isn't really confusing, in my opinion. It states the requirements exactly as they have been specified in the formula. I will admit that this is also the lazier solution, but I think it does the job of conveying things better than previously.
>
> I'll try to work on improving this further sometime this week, but feel free to open a PR if you'd like to.

**Comment by MikeMcQuaid** [comment]
> I'll try to work on improving this further sometime this week, but feel free to open a PR if you'd like to.

Agreed. Will happily review improvements here but I don't think they are essential
