### PR TITLE
Ignore renamed formulae when checking for unversioned formulae

### LINKED ISSUE #13772: brew audit postgresql@14 throws spurious warning
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.10-60-g98999cc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 98999cc51033c6f1b2aae662024cba8544dcd3fd
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d9833b17d911e922ab5a74e9ac07df9720f06469
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xtMG3ORoTy/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/xrisk/.pyenv/shims/python3.7-config
  /Users/xrisk/.pyenv/shims/python3.10-config
  /Users/xrisk/.pyenv/shims/python3.7m-config
  /Users/xrisk/.pyenv/shims/python-config
  /Users/xrisk/.pyenv/shims/python3-config
  /Users/xrisk/.pyenv/shims/python3.8-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `brew audit postgresql@14` before making a PR.

### What happened (include all command output)?

```
❯ brew audit --strict postgresql@14
Warning: Use postgresql@14 instead of deprecated postgresql
```

### What did you expect to happen?

No warning since I used the versioned Postgres.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew audit postgresql@142. 
```
If I understand correctly, the problem stems from https://github.com/Homebrew/brew/blob/98999cc51033c6f1b2aae662024cba8544dcd3fd/Library/Homebrew/formula_auditor.rb#L62 but I’m not sure what a good way to resolve this is.

### PR DESCRIPTION
**Pull request by apainintheneck**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This fixes #13772.

There is an audit for versioned formulae that makes sure an unversioned formula of the same name exists already. This ignores that check when we explicitly removed the unversioned formula by checking if it was renamed first.

Also, there is no need to check for `formula.tap` because `formula.core_formula?` guarantees the presence of `formula.tap`.

### CODE REVIEW

File: Library/Homebrew/formula_auditor.rb [hunk 1]
```diff
@@ -52,14 +52,16 @@ def audit_style
 
     def audit_file
       if formula.core_formula? && @versioned_formula
+        unversioned_name = formula.name.gsub(/@.*$/, "")
+
+        # ignore when an unversioned formula doesn't exist after an explicit rename
+        return if formula.tap.formula_renames.key?(unversioned_name)
+
+        # build this ourselves as we want e.g. homebrew/core to be present
+        full_name = "#{formula.tap}/#{unversioned_name}"
```
Comment (carlocab) [inline Library/Homebrew/formula_auditor.rb:61]: Do we want to get rid of the `if formula.tap` check?

Comment (apainintheneck) [reply Library/Homebrew/formula_auditor.rb:61]: It's not functionally necessary because it's inside an if statement that requires `formula.core_formula?` to be true and that means that `formula.tap` must not be nil.

https://github.com/Homebrew/brew/blob/f765382cb6d312e3cdebd955a2601998390fe0b0/Library/Homebrew/formula.rb#L1943-L1947

Comment (carlocab) [reply Library/Homebrew/formula_auditor.rb:61]: Ah, of course. Sounds fine then!

**Review by carlocab — APPROVED** [review]

**Review by Rylan12 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great work, thanks @apainintheneck!
