### PR TITLE
cask: gate auto-updates behind opt-in

### LINKED ISSUE #21981: new auto-updates cask behavior: android-studio and osu version not recognized
### `brew doctor` output

```shell
▷ brew dr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  dosbox-x-app
  dungeon-crawl-stone-soup-console
  fontforge-app
  openemu
  qbittorrent
  qmk-toolbox
  rar
  tales-of-majeyal
  vial

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmetalirconverter.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected header files:
  /usr/local/include/metal_irconverter/*
  /usr/local/include/metal_irconverter_runtime/*

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
▷ brew config
HOMEBREW_VERSION: 5.1.5-69-g9e6cb58
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9e6cb58062b4f5fc3854ebd2c6a90a0e379574dc
Last commit: 2 hours ago
Branch: main
Core tap JSON: 10 Apr 11:05 UTC
Core cask tap JSON: 10 Apr 11:05 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_AUTO_UPDATE_SECS: 1
HOMEBREW_AUTO_UPDATE_SECS: 1
HOMEBREW_BAT_THEME: Dracula
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 24
HOMEBREW_EDITOR: nvim
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 4.0.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.2_1/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 21.0.0 build 2100
Git: 2.53.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.4.1-arm64
CLT: 26.4.0.0.1774242506
Xcode: 26.4
Metal Toolchain: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

When running `brew upgrade`, it should recognize these `auto-updates` casks have been upgraded to latest.

### What happened (include all command output)?

```
▷ brew upgrade -n
==> Auto-updating Homebrew...
✔︎ JSON API formula.jws.json                                                                                    Downloaded   32.0MB/ 32.0MB
✔︎ JSON API cask.jws.json                                                                                       Downloaded   15.4MB/ 15.4MB
==> Would upgrade 2 outdated packages:
android-studio 2024.3.2.15 -> 2025.3.3.6,panda3
osu 2025.816.0-lazer -> 2026.406.0-lazer
```

Proof that I have the latest versions already installed:

```
▷ studio --version
Android Studio Panda 3 | 2025.3.3
Build #AI-253.31033.145.2533.15113396
```

Image

### What did you expect to happen?

brew doesn't try to upgrade `android-studio` or `osu`, because they have already been auto-updated to latest.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install a older version of these casks somehow?
Update to latest using the app's own auto-updater
Run brew upgrade
```

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- switch `auto_updates true` upgrades to `HOMEBREW_UPGRADE_AUTO_UPDATES_CASKS` so users keep the current behavior until Homebrew 5.2.0
- keep hidden `HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS` support for developer overrides and reject conflicting env settings early in `brew upgrade`
- ignore bad bundle versions such as `0.0` so broken `Info.plist` metadata does not trigger false upgrades

Fixes https://github.com/Homebrew/brew/issues/21981

-----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests (excluding integration tests) for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

Used OpenAI Codex with local editing, testing and review.

-----

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]

File: Library/Homebrew/cask/cask.rb [hunk 1]
```diff
@@ -550,6 +550,9 @@ def to_h
     HASH_KEYS_TO_SKIP = T.let(%w[outdated installed versions].freeze, T::Array[String])
     private_constant :HASH_KEYS_TO_SKIP
 
+    AUTO_UPDATES_BAD_BUNDLE_VERSIONS = %w[0.0].freeze
```
Comment (bevanjkay) [inline Library/Homebrew/cask/cask.rb:553]: I think we should expand this to knock out versions from `installed_short_version`, but I'm happy to take a look at this in a follow up PR with some other additional logic (probably on Monday).

**Review by bevanjkay — APPROVED** [review]

File: Library/Homebrew/cask/cask.rb (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cask/cask.rb:553]: @bevanjkay Aye sounds good. Less pressing now it's not applying to everyone any more.
