### PR TITLE
Fix `DSL#env` override covariance error

### LINKED ISSUE #22022: brew cleanup (and brew doctor) fail with Sorbet covariance error: incompatible return type override of env in requirement.rb
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  gstreamer-runtime
  mark-text
  wine-stable

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pup

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  git-flow
  icu4c@76
  icu4c@77
  neofetch
  pup
  speedtest-cli
  tldr

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/*

Warning: Found Ruby file outside gittower/tap tap formula directory.
(/opt/homebrew/Library/Taps/gittower/homebrew-tap/Formula):
  /opt/homebrew/Library/Taps/gittower/homebrew-tap/update_formula.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  putty
  pycparser
  cffi
Error: Incompatible return type in signature for override of method `env`:
* Base: `BuildEnvironment` (in BuildEnvironment::DSL at /opt/homebrew/Library/Homebrew/build_environment.rb:41)
* Override: `T.nilable(BuildEnvironment)` (in #<Class:Requirement> at /opt/homebrew/Library/Homebrew/requirement.rb:259)
(The types must be covariant.)
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.1.6-61-g7cc11da
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7cc11daaba9da8e2bb825470731ae320a8c96042
Last commit: 16 hours ago
Branch: main
Core tap JSON: 15 Apr 06:04 UTC
Core cask tap HEAD: fdd0ddfee0914825e4ecaabcfca46b4e2fb86572
Core cask tap last commit: 60 minutes ago
Core cask tap JSON: 15 Apr 06:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: Monokai Extended
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /var/run/com.apple.launchd.CpXGsqGxZH/org.xquartz:0
HOMEBREW_DOWNLOAD_CONCURRENCY: 16
HOMEBREW_EDITOR: micro
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 4.0.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.2_1/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 21.0.0 build 2100
Git: 2.53.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.4.1-arm64
CLT: 26.4.0.0.1774242506
Xcode: 26.4
Metal Toolchain: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Run brew cleanup to remove old cached downloads and outdated formula versions.

### What happened (include all command output)?

Both brew cleanup and brew doctor abort with:

```txt
Error: Incompatible return type in signature for override of method `env`:
* Base: `BuildEnvironment` (in BuildEnvironment::DSL at /opt/homebrew/Library/Homebrew/build_environment.rb:41)
* Override: `T.nilable(BuildEnvironment)` (in #<Class:Requirement> at /opt/homebrew/Library/Homebrew/requirement.rb:259)
(The types must be covariant.)
```

### What did you expect to happen?

brew cleanup should complete successfully without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew cleanup
`Error: Incompatible return type in signature for override of method `env` ...`

Workaround that succeeds:
`HOMEBREW_NO_SORBET_RUNTIME=1 brew cleanup`
```

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- `typed: strict` on `build_environment.rb` tightened `DSL#env` to `returns(BuildEnvironment)` but the `Requirement` override legitimately returns `nil`
- Mark `DSL#env` as `overridable` with nilable return
- Replace `T.must` with explicit `ArgumentError` guard
- Add missing `override.` to `Requirement.env` sig

Fixes https://github.com/Homebrew/brew/issues/22022

-----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them? Performance claims (e.g. "this is faster") must include [Hyperfine](https://github.com/sharkdp/hyperfine) benchmarks.
- [x] Have you written new tests (excluding integration tests) for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*. Non-maintainers may only have one AI-assisted/generated PR open at a time.

Worked with Claude Code with manual review and testing.

-----

### CODE REVIEW

File: Library/Homebrew/build_environment.rb [hunk 1]
```diff
@@ -37,9 +37,12 @@ def inherited(child)
...
     end
 
-    sig { params(settings: Symbol).returns(BuildEnvironment) }
+    sig { overridable.params(settings: Symbol).returns(T.nilable(BuildEnvironment)) }
     def env(*settings)
-      T.must(@env).merge(settings)
+      env = @env
+      Kernel.raise ArgumentError, "#{self} has not been initialized with a BuildEnvironment" if env.nil?
+
+      env.merge(settings)
```
Comment (dduugg) [inline Library/Homebrew/build_environment.rb:45]: The lvar isn't needed, i believe:
```suggestion
      Kernel.raise ArgumentError, "#{self} has not been initialized with a BuildEnvironment" if @env.nil?

      @env.merge(settings)
```

**Review by dduugg — APPROVED** [review]

**Review by krehel — APPROVED** [review]

File: Library/Homebrew/build_environment.rb (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/build_environment.rb:45]: @dduugg yeh, fair, just shipping as-is for now to unblock CI
