### PR TITLE
items.sh: return early when no Taps directory

### LINKED ISSUE #14254: `brew info [TAB]` completion in ZSH prints errors but suggests nothing
### `brew doctor` output

```shell
Warning: Your Cellar and TEMP directories are on different volumes.
macOS won't move relative symlinks across volumes unless the target file already
exists. Brews known to be affected by this are Git and Narwhal.

You should set the "HOMEBREW_TEMP" environment variable to a suitable
directory on the same volume as your Cellar.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11cdffb4fef84828a7e02860212b30ce4fac85f5
Last commit: 7 days ago
Core tap: N/A
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CACHE: /Users/brew/.cache/Homebrew
HOMEBREW_CASK_OPTS: ["--appdir=/Applications", "--colorpickerdir=/Users/kentzo/Library/ColorPickers", "--prefpanedir=/Users/kentzo/Library/PreferencePanes", "--qlplugindir=/Users/kentzo/Library/QuickLook", "--mdimporterdir=/Users/kentzo/Library/Spotlight", "--dictionarydir=/Users/kentzo/Library/Dictionaries", "--fontdir=/Users/kentzo/Library/Fonts", "--servicedir=/Users/kentzo/Library/Services", "--input-methoddir=/Users/kentzo/Library/Input Methods", "--internet-plugindir=/Users/kentzo/Library/Internet Plug-Ins", "--audio-unit-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/Components", "--vst-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/VST", "--vst3-plugindir=/Users/kentzo/Library/Audio/Plug-Ins/VST3", "--screen-saverdir=/Users/kentzo/Library/Screen Savers"]
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_LOGS: /Users/brew/.cache/Homebrew/Logs
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to auto-complete `brew info [TAB]` in ZSH 5.8.1

### What happened (include all command output)?

$ brew info find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory
find: /opt/homebrew/Library/Taps: No such file or directory

### What did you expect to happen?

Suggest a formula for completion or do nothing without printing errors.

It seems like current autocompletion function requires the "Taps" directory to exist, but it was not created by Homebrew installation. I did not delete this directory manually. Adding this directory removes the errors but there is still no completion.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew info [TAB]` in ZSH 5.8.1
```

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Workaround for removing errors output in #14254. Will need API usage for actual completion support, but haven't had chance to look into this.

EDIT: Updated to allow completion from cached JSON to fix #14254

Haven't tested on `HOMEBREW_INSTALL_FROM_API` setup, but seemed to work when I changed Taps in following line to invalid directory:
https://github.com/Homebrew/brew/blob/884c4bec14073314ac6e8e9a6a64bc3b26161ab6/Library/Homebrew/items.sh#L21

---

e.g. changing above to `Taps2` and trying without this PR:
```console
❯ brew formulae
find: /opt/homebrew/Library/Taps2: No such file or directory

❯ brew info find: /opt/homebrew/Library/Taps2: No such file or directory
find: /opt/homebrew/Library/Taps2: No such file or directory
brew
```

with PR:
```console
❯ brew formulae


❯ brew info <TAB>
<NOTHING>
```

### CODE REVIEW

File: Library/Homebrew/items.sh [hunk 1]
```diff
@@ -27,7 +27,7 @@ homebrew-items() {
       -name spec -o \
       -name vendor \
       \) \
-      -prune -false -o -path "${find_include_filter}" |
+      -prune -false -o -path "${find_include_filter}" 2>/dev/null |
```
Comment (MikeMcQuaid) [inline Library/Homebrew/items.sh:30]: Instead of hiding `stderr`: how about an early `return` if `${HOMEBREW_REPOSITORY}/Library/Taps` does not exist? Should be more performant that way. Note: probably worth adding a `# TODO` for that, too, that it should eventually use (e.g. shelling out to raw Ruby or something?) to extract these values from the JSON.

File: Library/Homebrew/items.sh [hunk 2]
```diff
@@ -17,6 +17,7 @@ homebrew-items() {
 
   # HOMEBREW_REPOSITORY is set by brew.sh
   # shellcheck disable=SC2154
+  [[ -d "${HOMEBREW_REPOSITORY}/Library/Taps" ]] || return
```
Comment (cho-m) [inline Library/Homebrew/items.sh:20]: I wonder if we can use `Homebrew::API::Formula.all_formulae.keys`. Alternatively, could run a hack and extract through shell script (grep, sed, etc.) if cache file exists.

File: Library/Homebrew/cmd/formulae.sh [hunk 3]
```diff
@@ -8,5 +8,17 @@
...
+  local formulae
+  formulae="$(homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core')"
+
+  # HOMEBREW_CACHE is set by brew.sh
+  # shellcheck disable=SC2154
+  if [[ -n "${HOMEBREW_INSTALL_FROM_API}" && -f "${HOMEBREW_CACHE}/api/formula.json" ]]
+  then
+    local api_formulae
+    api_formulae="$(ruby -e "require 'json'; JSON.parse(File.read('${HOMEBREW_CACHE}/api/formula.json')).each { |f| puts f['name'] }")"
+    formulae=$(echo -e "${formulae}\n${api_formulae}" | sort -uf | grep .)
```
Comment (cho-m) [inline Library/Homebrew/cmd/formulae.sh:20]: Concept idea for reading cached JSON using ruby without brew libraries.

This currently doesn't handle any error inside Ruby. Particularly, a corrupt JSON file ends up dumping the entire contents of formula.json to terminal which can be quite lengthy.

I had added `grep .` since `${formulae}` can be `""` so it leads to blank line. Not sure if there is better way to handle this.

File: Library/Homebrew/items.sh (hunk 1 above)
Comment (cho-m) [reply Library/Homebrew/items.sh]: Updated to handle this and adding initial attempt at getting `brew formulae` from JSON.

**Review by MikeMcQuaid — APPROVED** [review]
This makes sense! Happy to try it out.

File: Library/Homebrew/cmd/formulae.sh [hunk 4]
```diff
@@ -8,5 +8,17 @@
...
-  homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core'
+  local formulae
+  formulae="$(homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core')"
+
+  # HOMEBREW_CACHE is set by brew.sh
+  # shellcheck disable=SC2154
+  if [[ -n "${HOMEBREW_INSTALL_FROM_API}" && -f "${HOMEBREW_CACHE}/api/formula.json" ]]
+  then
+    local api_formulae
+    api_formulae="$(ruby -e "require 'json'; JSON.parse(File.read('${HOMEBREW_CACHE}/api/formula.json')).each { |f| puts f['name'] }" 2>/dev/null)"
```
Comment (Rylan12) [inline Library/Homebrew/cmd/formulae.sh:19]: I wonder if we should do this calculation when we download `HOMEBREW_CACHE/api/formula.json`, instead. That way we only need to do it once per unique cache file (I'm assuming this line is relatively slow)

Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/formulae.sh:19]: @Rylan12 That seems like a good idea! Let's merge as-is for now and iterate to improve performance here 💪🏻

**Comment by MikeMcQuaid** [comment]
Thanks again @cho-m!
