### PR TITLE
autoremove: cross-check candidates against formula definitions

### LINKED ISSUE #21511: brew cleanup says libthai can be removed, but at the same time it is needed by pango
### `brew config` AND `brew doctor` output OR `brew gist-logs <formula>` link

```shell
brew config
HOMEBREW_VERSION: 5.0.13-26-g7788a02
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7788a02932f30f66b18b1caecbc239c4d954d88f
Last commit: 3 hours ago
Branch: main
Core tap JSON: 03 Feb 09:13 UTC
Core cask tap JSON: 03 Feb 09:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.NNI39sRQTP/org.xquartz:0
HOMEBREW_DOWNLOAD_CONCURRENCY: 16
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.18.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 26.2-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: N/A
Rosetta 2: false



brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  fontsmoothingadjuster
  zeronet

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  antigen
  icu4c@77
  tldr
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

I try to clean unnecessary packages. I think it is related to this commit:

https://github.com/Homebrew/homebrew-core/commit/d00616124646e6547a82839883c8a3c5aa6f3dd3

### What happened (include all command output)?

```
brew cleanup
==> Autoremoving 4 unneeded formulae:
cyrus-sasl
libdatrie
libthai
pydantic
Error: Refusing to uninstall /opt/homebrew/Cellar/libdatrie/0.2.14 and /opt/homebrew/Cellar/libthai/0.1.30
because they are required by pango, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies
```

### What did you expect to happen?

That will remove the unnecessary packages

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew cleanup
```

### PR DESCRIPTION
**Pull request by costajohnt**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Claude Code was used to assist with the refactoring after @MikeMcQuaid's review feedback. All changes were manually tested by simulating a stale-tab scenario (editing INSTALL_RECEIPT.json to remove a dependency, then verifying `brew autoremove`, `brew missing`, and `brew uninstall` behave consistently).*

-----

Fixes #21511

## Problem

`brew autoremove` suggests removing formulae (e.g. `libthai`) that `brew uninstall` then refuses to remove because they're still needed by installed formulae (e.g. `pango`).

The root cause: when homebrew-core adds a new dependency to a formula, the installed bottle's tab (`INSTALL_RECEIPT.json`) doesn't reflect this — the tab is written at install time and never updated. `autoremove` reads from the tab and thinks the package is unused. But `missing_dependencies` (used by `uninstall`) falls back to formula definitions when tab data is nil, sees the new dependency, and blocks removal.

## Approach

Per @MikeMcQuaid's [feedback](https://github.com/Homebrew/brew/pull/21725#issuecomment-3075780850): fix `uninstall` rather than `autoremove`. If a dependency isn't in the tab, there isn't actually a dependency from the tab's perspective.

**Changes:**

1. **`formula.rb` — `missing_dependencies`**: Read directly from tab data (`any_installed_keg.runtime_dependencies`) instead of calling `runtime_dependencies(read_from_tab: true, undeclared: true)` which falls back to formula definitions. When tab data is nil, return empty rather than falling back. This prevents stale or missing tab data from incorrectly blocking uninstalls.

2. **`utils/autoremove.rb`**: Remove the cross-check against formula definitions (reverted to the simpler pre-PR logic). No longer needed since `uninstall` and `autoremove` now agree on the data source.

3. **Error handling**: The `FormulaUnavailableError` rescue is now per-entry inside `filter_map` (not method-level), so one unavailable formula doesn't discard all other results. Added `is_a?(Hash)` guard for corrupted tab entries and `meta !== null` check to avoid misclassifying schema-only FKs.

4. **Tests**: Updated `installed_dependents_spec.rb` with 3 new test cases (stale tab, tab with dependency, renamed dependency with tab data) and updated 4 existing tests to match tab-only behavior. Updated `missing_spec.rb` integration test.

## Test plan

- `brew tests --only installed_dependents` — 13 examples, 0 failures
- `brew tests --only utils/autoremove` — 8 examples, 0 failures
- `brew tests --only cmd/missing` — 2 examples, 0 failures
- Manual test: edited `actionlint`'s INSTALL_RECEIPT.json to remove `shellcheck` from `runtime_dependencies`, verified `brew autoremove --dry-run`, `brew missing`, and `brew uninstall shellcheck` all agree that shellcheck can be removed

### CODE REVIEW

**Comment by costajohnt** [comment]
BEFORE fix:
Screenshot 2026-03-12 at 6 34 01 PM

AFTER fix applied:
Screenshot 2026-03-12 at 6 34 17 PM

File: Library/Homebrew/utils/autoremove.rb [hunk 1]
```diff
@@ -14,7 +18,38 @@ class << self
...
-        unused_formulae - formulae_with_cask_dependents(casks)
+        candidates = unused_formulae - formulae_with_cask_dependents(casks)
+
+        return candidates if candidates.empty?
+
+        # Cross-check candidates against current formula definitions.
+        # The forward check uses tab data (INSTALL_RECEIPT.json) which can
+        # become stale after upgrades. Formula definitions are always current.
+        begin
+          loop do
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/autoremove.rb]: Would like to avoid an unbounded loop here.

File: Library/Homebrew/test/cmd/missing_spec.rb [hunk 2]
```diff
@@ -6,15 +6,15 @@
 RSpec.describe Homebrew::Cmd::Missing do
   it_behaves_like "parseable arguments"
 
-  it "prints missing dependencies", :integration_test, :no_api do
+  it "does not report missing deps when tab has no runtime dependency data", :integration_test, :no_api do
```
Comment (MikeMcQuaid) [inline Library/Homebrew/test/cmd/missing_spec.rb]: This test should be changed back to how it was before.

File: Library/Homebrew/formula.rb [hunk 3]
```diff
@@ -2803,16 +2803,27 @@ def runtime_installed_formula_dependents
...
+  # has no runtime dependency data (nil), treats the dependency list as
+  # unknown and returns empty rather than falling back to formula definitions.
+  # This prevents stale or missing tab data from incorrectly blocking
+  # uninstalls.
   sig { params(hide: T::Array[String]).returns(T::Array[Dependency]) }
   def missing_dependencies(hide: [])
-    runtime_dependencies(read_from_tab: true, undeclared: true).select do |f|
-      hide.include?(f.name) || f.to_installed_formula.installed_prefixes.none?
+    tab_deps = any_installed_keg&.runtime_dependencies
+    return [] if tab_deps.nil?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula.rb]:
```suggestion
    return [] if tab_deps.blank?
```

File: Library/Homebrew/formula.rb [hunk 4]
```diff
@@ -2803,16 +2803,27 @@ def runtime_installed_formula_dependents
...
+
+    tab_deps.filter_map do |d|
+      next unless d.is_a?(Hash)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula.rb]: When is it/is it not a Hash?

File: Library/Homebrew/formula.rb [hunk 5]
```diff
@@ -2803,16 +2803,27 @@ def runtime_installed_formula_dependents
...
+
+      full_name = d["full_name"]
+      next unless full_name
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula.rb]:
```suggestion
      next if full_name.blank?
```

**Comment by MikeMcQuaid** [comment]
@costajohnt CI failing. Good to merge when 🟢

**Comment by costajohnt** [comment]
Thanks for the approval! The two CI failures look unrelated to the PR:

- **tests (macOS)**: `pypi_repo_url` test in `source_spec.rb` makes a live curl to pypi.org and got nil back (likely a transient network issue on the runner). Passes consistently locally.
- **bundle and services (macOS)**: VS Code CDN download timed out.

Could you re-run the failed jobs when you get a chance? @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Thanks again @costajohnt!
