### PR TITLE
github_runner_matrix: fix skipped runner creation

### LINKED ISSUE #19838: `brew determine-test-runners` may exclude runners for supported architectures
### `brew doctor` output

```shell
irrelevant
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
irrelevant
```

### What were you trying to do (and why)?

I was trying to update ibex formula (Homebrew/homebrew-core#221747). It used to have bottles for all supported configurations. After ARM Linux Homebrew support was added, cho-m added `on_linux` block with `depends_on arch: :x86_64` dependency (https://github.com/Homebrew/homebrew-core/commit/146de3429be63069e32d15d4cdfe7fb101908604)

CI jobs started runners only for x86 runners, even though this limit exists only for Linux.

### What happened (include all command output)?

[`CI / setup_tests (pull_request)`](https://github.com/Homebrew/homebrew-core/actions/runs/14712241279/job/41287306278?pr=221747) job had started only x86 runners (missing `macOS <version>-arm64` runners)

### What did you expect to happen?

I expected CI job to start all runners except ARM Linux

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# update any formula with `on_macos` or `on_linux` block that has `depends_on arch:`
# if you can run `determine-test-runners` command on your machine try to
# modify any formula
```

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Need to create a new TestRunnerFormula instance under SimulateSystem to get a fresh read of its OS/arch requirements. Fixes #19838. 

E.g. with `intercal`, which sets `depends_on arch: :x86_64` only for macOS:

Before: 
```console
$ brew determine-test-runners intercal -d
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
==> Runners
[
  {
    "name": "Linux x86_64",
    "runner": "ubuntu-22.04",
    "container": {
      "image": "ghcr.io/homebrew/ubuntu22.04:main",
      "options": "--user=linuxbrew -e GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED"
    },
    "workdir": "/github/home",
    "timeout": 2160,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 15-x86_64",
    "runner": "15-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 14-x86_64",
    "runner": "14-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 13-x86_64",
    "runner": "13-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  }
]
```

After:
```console
$ brew determine-test-runners intercal -d
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading intercal
==> Runners
[
  {
    "name": "Linux x86_64",
    "runner": "ubuntu-22.04",
    "container": {
      "image": "ghcr.io/homebrew/ubuntu22.04:main",
      "options": "--user=linuxbrew -e GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED"
    },
    "workdir": "/github/home",
    "timeout": 2160,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "Linux arm64",
    "runner": "ubuntu-22.04-arm",
    "container": {
      "image": "ghcr.io/homebrew/ubuntu22.04:main",
      "options": "--user=linuxbrew -e GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED"
    },
    "workdir": "/github/home",
    "timeout": 2160,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 15-x86_64",
    "runner": "15-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 14-x86_64",
    "runner": "14-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  },
  {
    "name": "macOS 13-x86_64",
    "runner": "13-x86_64-ASDF",
    "timeout": 120,
    "cleanup": false,
    "testing_formulae": "intercal"
  }
]
```

### CODE REVIEW

File: Library/Homebrew/simulate_system.rb [hunk 1]
```diff
@@ -10,6 +10,11 @@ class SimulateSystem
     class << self
       attr_reader :arch, :os
 
+      sig { returns(T::Hash[Symbol, Symbol]) }
+      def arch_symbols
+        { arm64: :arm, x86_64: :intel }
```
Comment (Bo98) [inline Library/Homebrew/simulate_system.rb]:
```suggestion
        { arm64: :arm, x86_64: :intel }.freeze
```

**Review by Bo98 — APPROVED** [review]
Looks good - thanks!

File: Library/Homebrew/github_runner_matrix.rb [hunk 2]
```diff
@@ -255,17 +255,10 @@ def compatible_testing_formulae(runner)
...
-        when :arm64
-          :arm
-        else
-          :dunno
-        end
-        Homebrew::SimulateSystem.with(os: platform, arch: simulate_arch) do
-          formula.public_send(:"#{platform}_compatible?") &&
-            formula.public_send(:"#{arch}_compatible?")
+        Homebrew::SimulateSystem.with(os: platform, arch: Homebrew::SimulateSystem.arch_symbols.fetch(arch)) do
+          simulated_formula = TestRunnerFormula.new(Formulary.factory(formula.name))
```
Comment (EricFromCanada) [inline Library/Homebrew/github_runner_matrix.rb:259]: `Formulary.factory(formula.name)` is preventing the tests from passing. How would I modify `github_runner_matrix_spec.rb` to register `testball` so that `Formulary.factory` is able to generate it by name?

Comment (Bo98) [reply Library/Homebrew/github_runner_matrix.rb:259]: Adding `stub_formula_loader f` to `setup_test_runner_formula` should hopefully work

Comment (EricFromCanada) [reply Library/Homebrew/github_runner_matrix.rb:259]: Not this time, it seems

Comment (Bo98) [reply Library/Homebrew/github_runner_matrix.rb:259]: Oh and adjust the `let(:testball)` one that doesn't use `setup_test_runner_formula` to either call `stub_formula_loader` on `Testball` instance it creates or to be honest you can probably just swap it out for `setup_test_runner_formula("testball")` as we don't really need to use the predefined fixture.

**Review by carlocab — APPROVED** [review]
