### PR TITLE
fix(bundle): prevent autoremove from removing Brewfile packages during cleanup

### LINKED ISSUE #21350: [Bug]`brew bundle --cleanup` triggers autoremove which ignores Brewfile
### `brew doctor` output

```shell
Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  chromedriver
  inkscape
  prowlarr
  radarr
  sonarr
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.0.8-15-g7543440
ORIGIN: https://github.com/Homebrew/brew
HEAD: 754344022ff6b44f759c04b828fed0e9a76e3216
Last commit: 35 hours ago
Branch: main
Core tap JSON: 02 Jan 00:33 UTC
Core cask tap JSON: 02 Jan 00:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 20
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.2-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I'm using `brew bundle --cleanup` to keep my system in sync with a Brewfile (declarative package management). The `--cleanup` flag should remove packages not in the Brewfile while preserving packages that *are* in the Brewfile.

### What happened (include all command output)?

Packages explicitly listed in my Brewfile were removed by `brew bundle --cleanup`.

Specifically, `tree` was removed even though it was in my Brewfile:
```
brew "tree"
```

After investigation, I found this happens when:
1. A package is explicitly in the Brewfile
2. That package has `installed_on_request: false` (was originally installed as a dependency)
3. The package it was a dependency of is *not* in the Brewfile

The `--cleanup` operation removes the "parent" package, which triggers `autoremove`. The `autoremove` process doesn't know about the Brewfile, so it removes packages that appear to be orphaned dependencies, even if they're explicitly listed in the Brewfile.

### What did you expect to happen?

Packages explicitly listed in the Brewfile should *not* be removed by `brew bundle --cleanup`, regardless of how they were originally installed (on request vs as dependency).

## Step-by-step reproduction instructions (by running `brew` commands)

```bash
# 1. Install a package that has dependencies
brew install yt-dlp

# 2. Verify deno was installed as a dependency
brew info --json=v2 deno | jq '.formulae[0].installed[0].installed_on_request'
# Returns: false

# 3. Verify deno is only used by yt-dlp
brew uses --installed deno
# Returns: yt-dlp

# 4. Create a test Brewfile that has deno but not yt-dlp
echo 'brew "deno"' > /tmp/test-brewfile

# 5. Run cleanup dry-run to see what would be removed
brew bundle cleanup --file=/tmp/test-brewfile
# Output shows "Would uninstall formulae: yt-dlp" (correct - not in Brewfile)
# Note: deno does NOT appear here because the dry-run only shows direct removals,
# not the cascade effect of autoremove that happens afterward.

# 6. TRIGGER THE BUG - run with --force
# WARNING: This will uninstall everything not in the test Brewfile!
# Only run this if you're prepared to reinstall your packages afterward.
brew bundle cleanup --file=/tmp/test-brewfile --force
# Output: "Uninstalled 1 formula" (yt-dlp)
# But then autoremove kicks in and silently removes deno too!

# 7. Verify deno was incorrectly removed
brew list deno
# Error: No such keg: /opt/homebrew/Cellar/deno
# BUG: deno was in the Brewfile but got removed anyway!
```

**Why the dry-run is misleading:** The dry-run only shows what `brew bundle cleanup` will directly uninstall. It cannot predict what `autoremove` will do afterward. The bug is a cascade effect: removing `yt-dlp` makes `deno` appear "orphaned" to autoremove, which then removes it despite being in the Brewfile.

**Note:** The bug also affects `brew bundle --cleanup` and `brew bundle install --cleanup` because these flags run cleanup with `force: true` hardcoded (no dry-run).

## Root Cause Analysis

The issue is in the interaction between `brew bundle cleanup` and Homebrew's autoremove:

1. `brew bundle --cleanup` calls `brew uninstall` for packages not in Brewfile
2. Uninstalling triggers Homebrew's install cleanup (autoremove)
3. `autoremove` looks at `installed_on_request` flag to find orphans
4. `autoremove` has no knowledge of the Brewfile
5. Packages with `installed_on_request: false` are removed even if in Brewfile

---

## Workaround

```shell
HOMEBREW_NO_INSTALL_CLEANUP=1 brew bundle --cleanup --file=~/.Brewfile
```

---

## Suggested Fix

**Option 1:** `brew bundle` sets `HOMEBREW_NO_AUTOREMOVE=1` during cleanup operations
- Pros: Simple, self-contained change in bundle code
- Cons: Disables autoremove entirely, so genuinely orphaned dependencies (not in Brewfile) won't be cleaned up either

**Option 2:** `brew bundle` marks Brewfile packages as `installed_on_request: true` before running cleanup
- Pros: Uses existing Homebrew mechanism
- Cons: Persists metadata changes to disk, which is a side effect cleanup shouldn't have

**Option 3:** `autoremove` accepts a "protected packages" list that `brew bundle` can pass
- Pros: Surgical fix that lets autoremove still clean up truly orphaned packages while respecting the Brewfile
- Cons: Requires changes to core autoremove logic, not just bundle

Option 3 is the cleanest solution as it addresses the root cause: autoremove has no knowledge of the Brewfile. By passing the Brewfile packages as a protected list, autoremove can make informed decisions rather than being disabled entirely.

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
Fixes #21350

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

### CODE REVIEW

File: Library/Homebrew/bundle/commands/cleanup.rb [hunk 1]
```diff
@@ -44,7 +44,9 @@ def self.run(global: false, file: nil, force: false, zap: false, dsl: nil,
             end
 
             if formulae.any?
-              Kernel.system HOMEBREW_BREW_FILE, "uninstall", "--formula", "--force", *formulae
+              with_brewfile_formulae_protected(global:, file:) do
+                Kernel.system HOMEBREW_BREW_FILE, "uninstall", "--formula", "--force", *formulae
+              end
```
[the remark this answers is not in the document]
Comment (AbdelrahmanHafez) [reply Library/Homebrew/bundle/commands/cleanup.rb]: `brew cleanup` only removes old versions and cache, it doesn't trigger autoremove. The problematic autoremove call is in `cmd/uninstall.rb:87`, which is already wrapped.

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks for the PR!

I'd prefer Option 2 in https://github.com/Homebrew/brew/issues/21350.

`brew bundle cleanup` already has side-effects and there will be other issues with having things in a `Brewfile` that are not marked as installed-on-request so having `cleanup` handle this seems appropriate. `brew bundle (install)` should also handle this, if it doesn't already.

Happy to rereview after that.

Not at all a big deal but for future reference, no need to open an issue if you're going to soon afterwards open a PR to fix your own issue: skip straight to opening a PR in that case.

Thanks again!

File: Library/Homebrew/bundle/commands/cleanup.rb [hunk 2]
```diff
@@ -37,6 +37,12 @@ def self.run(global: false, file: nil, force: false, zap: false, dsl: nil,
           vscode_extensions = vscode ? vscode_extensions_to_uninstall(global:, file:) : []
           flatpaks = flatpak ? flatpaks_to_uninstall(global:, file:) : []
           if force
+            # Mark Brewfile formulae as installed_on_request to prevent autoremove
+            # from removing them when their dependents are uninstalled
+            require "bundle/brewfile"
+            @dsl ||= Brewfile.read(global:, file:)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle/commands/cleanup.rb]: When is `dsl` unset?

File: Library/Homebrew/bundle.rb [hunk 3]
```diff
@@ -173,6 +173,30 @@ def reset!
         @formula_versions_from_env = T.let(nil, T.nilable(T::Hash[String, String]))
         @upgrade_formulae = T.let(nil, T.nilable(T::Array[String]))
       end
+
+      # Marks Brewfile formulae as installed_on_request to prevent autoremove
+      # from removing them when their dependents are uninstalled.
+      sig { params(dsl: Dsl).void }
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb]: Passing `dsl_entries` Would be a bit nicer I think.

File: Library/Homebrew/bundle.rb [hunk 4]
```diff
@@ -173,6 +173,30 @@ def reset!
...
+      def mark_as_installed_on_request(dsl)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb]:
```suggestion
      def mark_as_installed_on_request!(dsl)
```
might be nicer

File: Library/Homebrew/bundle.rb [hunk 5]
```diff
@@ -173,6 +173,30 @@ def reset!
...
+        require "tab"
+
+        brewfile_formulae = dsl.entries.select { |e| e.type == :brew }.map(&:name)
+
+        brewfile_formulae.each do |name|
+          formula = Formulary.factory(name)
+          next unless formula.any_version_installed?
+
+          tab = Tab.for_formula(formula)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb]:
```suggestion
        installed_formulae = Formula.installed_formula_names
        dsl.entries do |name|
          next if e.type != :brew

					name = e.name
          next if installed_formulae.exclude?(name)

          tab = Tab.for_name(name)
```

File: Library/Homebrew/bundle/commands/cleanup.rb (hunk 2 above)
Comment (AbdelrahmanHafez) [reply Library/Homebrew/bundle/commands/cleanup.rb]: `@dsl` could be nil if all type flags are disabled, not sure if this is a valid method call or not. I also noticed that every usage of `@dsl` in this file defensively uses `||=` so I followed the existing pattern. Should I keep it consistent, or refactor to read the Brewfile once at the top of `run()`?

**Comment by AbdelrahmanHafez** [comment]
Thanks for the quick feedback @MikeMcQuaid!

I've implemented Option 2 and addressed your comments. Let me know if there's anything else you'd like changed.

> no need to open an issue if you're going to soon afterwards open a PR

Noted, will skip straight to PRs next time. 👍

File: Library/Homebrew/bundle/commands/cleanup.rb (hunk 2 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/bundle/commands/cleanup.rb]: > not sure if this is a valid method call or not.

I'd say unless it's causing existing test failures (preferably integration test failures) without: it's not. 

Open to refactoring if it makes things clearer/cleaner!

File: Library/Homebrew/bundle.rb [hunk 6]
```diff
@@ -173,6 +173,31 @@ def reset!
...
+
+          tab = Tab.for_name(name)
+          next if tab.tabfile.blank? || !tab.tabfile.exist?
+          next if tab.installed_on_request
+
+          tab.installed_on_request = true
+          tab.write
+        rescue FormulaUnavailableError
+          # Formula not found, skip it
+          nil
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb]: Not a blocker but note if https://github.com/Homebrew/brew/pull/21354 ends up merged first: this `rescue` can be removed.

File: Library/Homebrew/bundle/commands/cleanup.rb (hunk 2 above)
Comment (AbdelrahmanHafez) [reply Library/Homebrew/bundle/commands/cleanup.rb]: I'd like keep it as-is in this PR to match the existing pattern in this file. Happy to do a follow-up refactor PR if you'd like, but will avoid scope creep here.
What do you think?

Comment (MikeMcQuaid) [reply Library/Homebrew/bundle/commands/cleanup.rb]: Fine with me!

File: Library/Homebrew/test/bundle/commands/cleanup_spec.rb [hunk 7]
```diff
@@ -165,6 +167,8 @@
                                                  taps_to_untap:                  [],
                                                  vscode_extensions_to_uninstall: [],
                                                  flatpaks_to_uninstall:          [])
+      allow(Homebrew::Bundle).to receive(:mark_as_installed_on_request!)
+      allow_any_instance_of(Pathname).to receive(:read).and_return("")
```
Comment (MikeMcQuaid) [inline Library/Homebrew/test/bundle/commands/cleanup_spec.rb]: Feels like this shouldn't be necessary without any `formulae_to_uninstall`? Same likely on other cases without `formulae_to_uninstall` set.

File: Library/Homebrew/bundle.rb [hunk 8]
```diff
@@ -173,6 +173,31 @@ def reset!
...
         @upgrade_formulae = T.let(nil, T.nilable(T::Array[String]))
       end
+
+      # Marks Brewfile formulae as installed_on_request to prevent autoremove
+      # from removing them when their dependents are uninstalled.
+      sig { params(entries: T::Array[Dsl::Entry]).void }
+      def mark_as_installed_on_request!(entries)
+        require "tab"
+
+        installed_formulae = Formula.installed_formula_names
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb:185]:
```suggestion
        return if entries.empty?
        require "tab"

        installed_formulae = Formula.installed_formula_names
        return if installed_formulae.empty?
```
this should remove the need for a bunch of the `allow` I mentioned above.

File: Library/Homebrew/test/bundle/bundle_spec.rb [hunk 9]
```diff
@@ -46,4 +47,52 @@
       expect(described_class.mas_installed?).to be(true)
     end
   end
+
+  describe ".mark_as_installed_on_request!", :no_api do
+    before do
+      allow(DevelopmentTools).to receive_messages(needs_libc_formula?: false, needs_compiler_formula?: false)
+    end
+
```
Comment (MikeMcQuaid) [inline Library/Homebrew/test/bundle/bundle_spec.rb:63]: Would be nice to use more `before` and `let` and `subject` here to DRY up below.

File: Library/Homebrew/bundle/commands/cleanup.rb [hunk 10]
```diff
@@ -37,6 +37,12 @@ def self.run(global: false, file: nil, force: false, zap: false, dsl: nil,
...
+            Homebrew::Bundle.mark_as_installed_on_request!(@dsl.entries)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle/commands/cleanup.rb]: Feels like this should probably be in `if formulae.any?` below as it only affects formulae?

**Comment by AbdelrahmanHafez** [comment]
Good points @MikeMcQuaid, all addressed. Let me know if there's anything else we can do better.

File: Library/Homebrew/bundle.rb [hunk 11]
```diff
@@ -173,6 +173,35 @@ def reset!
...
+
+          tab = Tab.for_name(name)
+          next if tab.tabfile.blank? || !tab.tabfile.exist?
+          next if tab.installed_on_request
+
+          tab.installed_on_request = true
+          tab.write
+        rescue FormulaUnavailableError
+          # Formula not found, skip it
+          nil
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle.rb]:
```suggestion
```
