### PR TITLE
Show casks in install not found output

### LINKED ISSUE #14183: brew install --cask: search casks if not found
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.12-20-g9c88c39
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c88c39baead6bbc40b12ab1eae9b63bcb5a8042
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9f38328ae25b296117d2d0d19445f8a442d647a1
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
Rosetta 2: false
```

### What were you trying to do (and why)?

**What were you trying to do:** Install a cask with the wrong name.

**Why were you trying to do it:** Sometimes I mistype the name of a cask, or am fairly confident in guessing the name of the cask. Usually I concurrently run a `brew search` while I am typing out the install command, but this feels redundant, as the failsafe search feature is already available for formulas and appears to have once been available for casks (#3829).

**Why are you opening this issue:**

I am opening this issue at the recommendation of @SMillerDev, from [Homebrew/discussions/3986](https://github.com/orgs/Homebrew/discussions/3986#discussioncomment-4245273).

This issue looks similar to #3829 (please reference this issue if my explanation is unclear), but the fix implemented there does not appear to have lasted through 2022.

### What happened (include all command output)?

```
$ brew install --cask microsoft-edg
Error: Cask 'microsoft-edg' is unavailable: No Cask with this name exists.
```

### What did you expect to happen?

I expected Brew to search for "similarly named formula" or offer a "did you mean" suggestion, as it does with formulas.
Here I am omitting the `--cask` argument to `brew install` so as to demonstrate how this works with formulas:
```
$ brew install microsoft-edg
Warning: No available formula with the name "microsoft-edg". Did you mean microsocks?
==> Searching for similarly named formulae...
This similarly named formula was found:
microsocks
To install it, run:
  brew install microsocks
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask microsoft-edg
brew install --cask google-chroome
```

### PR DESCRIPTION
**Pull request by apainintheneck**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This closes #14183. Essentially, it uses `Search.search_names` to print suggestions in `brew install` if the cask/formula doesn't exist. This shouldn't actually be a lot more work because we were already hitting the Github API and getting the cask and formula info before. This just means that we'll display that info to the user.

Changes:
- Move `search_names` and `print_missing_formula_help` out of `cmd/search.rb` to `search.rb`
- Change to using those functions in `cmd/install.rb` when a formula or cask doesn't exist

Examples:
```
$ brew install -n --formula virtuabox
Warning: No available formula with the name "virtuabox". Did you mean virtuoso or virtualpg?
==> Searching for similarly named formulae and casks...
==> Formulae
virtuoso                                                                        virtualpg

To install one of them, run:
  brew install 'package_name'
```
```
$ brew install -n --cask virtuabox
Warning: Cask 'virtuabox' is unavailable: No Cask with this name exists.
==> Searching for similarly named formulae and casks...
==> Casks
virtualbox ✔                                                                    virtualgl

To install one of them, run:
  brew install 'package_name'
```
```
$ brew install -n virtuabox
Warning: No available formula with the name "virtuabox". Did you mean virtuoso or virtualpg?
==> Searching for similarly named formulae and casks...
==> Formulae
virtuoso                                                                        virtualpg

==> Casks
virtualbox ✔                                                                    virtualgl

To install one of them, run:
  brew install 'package_name'
```
```
$ brew install -n not_a_package
Warning: No available formula with the name "not_a_package".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for "not_a_package".
```

### CODE REVIEW

File: Library/Homebrew/cmd/install.rb [hunk 1]
```diff
@@ -278,48 +278,26 @@ def install
...
-    end
+    ohai "Searching for similarly named formulae and casks..."
 
-    if (reason = MissingFormula.reason(e.name))
-      $stderr.puts reason
-      return
-    end
+    # Don't treat formula/cask name as a regex
+    query = string_or_regex = name
+    if search_names(query, string_or_regex, args)
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/install.rb:295]: Some of these variables aren't functionally necessary but they help improve readability.

File: Library/Homebrew/search.rb [hunk 2]
```diff
@@ -114,6 +114,61 @@ def search_formulae(string_or_regex)
...
+        else
+          puts all_casks
+        end
+        count += all_casks.count
+      end
+
+      print_missing_formula_help(query, count.positive?) if local_casks.exclude?(query)
+
+      odie "No formulae or casks found for #{query.inspect}." if count.zero?
+      !count.zero?
```
Comment (apainintheneck) [inline Library/Homebrew/search.rb:157]: This was changed to return a boolean based upon whether any formulae or casks were found.

**Comment by apainintheneck** [comment]
Also, there's a part of me that wants to make `search.rb` a module function instead of mixing it in with modules since it's included in a few different places. I think it'd make the code easier to reason about. That being said I decided it really wasn't necessary for this PR so I decided not to include it here.

File: Library/Homebrew/cmd/install.rb [hunk 3]
```diff
@@ -278,48 +278,26 @@ def install
...
-    when 1
-      puts "This formula was found in a tap:"
-      puts taps_search_results
-      puts "To install it, run:\n  brew install #{taps_search_results.first}"
-    else
-      puts "These formulae were found in taps:"
-      puts Formatter.columns(taps_search_results)
-      puts "To install one of them, run (for example):\n  brew install #{taps_search_results.first}"
+        To install one of them, run:
+          brew install 'package_name'
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:299]: Can we use the `taps_search_results` like before to make this less generic?

File: Library/Homebrew/search.rb (hunk 2 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/search.rb:157]:
```suggestion
      true
```

would work, right, given that you're doing `odie` above? Feels a bit weird to even check the return value given it'll always be `true`?

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far!

File: Library/Homebrew/search.rb (hunk 2 above)
Comment (apainintheneck) [reply Library/Homebrew/search.rb:157]: It'll be false if no search results are returned for the search term.

File: Library/Homebrew/cmd/install.rb (hunk 3 above)
Comment (apainintheneck) [reply Library/Homebrew/cmd/install.rb:299]: Yeah, I was lazy and originally went for the direct solution. I'm honestly not sure how necessary it is because to get here they have to know enough to use `brew install` at least once already.

I'd be fine with adding it back in but I'm afraid that it'll end up being even more verbose, since we're in theory including twice as much output as before.

```
$ brew install -n virtuabox
Warning: No available formula with the name "virtuabox". Did you mean virtuoso or virtualpg?
==> Searching for similarly named formulae and casks...
==> Formulae
virtuoso                                                                        virtualpg

To install virtuoso, run:
  brew install virtuoso

==> Casks
virtualbox ✔                                                                    virtualgl

To install virtualbox, run:
  brew install --cask virtualbox
```

File: Library/Homebrew/search.rb (hunk 2 above)
Comment (apainintheneck) [reply Library/Homebrew/search.rb]: I removed it during the refactor.

File: Library/Homebrew/cmd/install.rb [hunk 4]
```diff
@@ -278,48 +278,59 @@ def install
...
-      ofail "No formulae found in taps."
-    when 1
-      puts "This formula was found in a tap:"
-      puts taps_search_results
-      puts "To install it, run:\n  brew install #{taps_search_results.first}"
-    else
-      puts "These formulae were found in taps:"
-      puts Formatter.columns(taps_search_results)
-      puts "To install one of them, run (for example):\n  brew install #{taps_search_results.first}"
+    return if name.include?("/")
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/install.rb:298]: We don't seem to get good search results when the tap is specified so we might as well return early.

File: Library/Homebrew/cmd/install.rb [hunk 5]
```diff
@@ -278,48 +278,59 @@ def install
...
-      puts Formatter.columns(formulae_search_results)
-      puts "To install one of them, run (for example):\n  brew install #{formulae_search_results.first}"
-    end
 
-    if (reason = MissingFormula.reason(e.name))
+    reason = MissingFormula.reason(name, silent: true)
+    if !args.cask? && reason
       $stderr.puts reason
       return
     end
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/install.rb:296]: I don't see much reason to continue if a missing formula is found assuming they weren't looking for a cask.

File: Library/Homebrew/cmd/search.rb [hunk 6]
```diff
@@ -129,29 +130,21 @@ def search_pull_requests(query, args)
...
-    remote_results = search_taps(query, silent: true)
-
-    local_formulae = search_formulae(string_or_regex)
-    remote_formulae = remote_results[:formulae]
-    all_formulae = local_formulae + remote_formulae
-
-    local_casks = search_casks(string_or_regex)
-    remote_casks = remote_results[:casks]
-    all_casks = local_casks + remote_casks
-
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/search.rb:142]: Moved this to its own function so that it can be reused over in the install command.

**Comment by apainintheneck** [comment]
Now it looks like this.

```
$brew install -n google
Warning: No available formula with the name "google". Did you mean googler or goose?
==> Searching for similarly named formulae and casks...
==> Formulae
aws-google-auth                                       google-benchmark                                      google-java-format                                    google-sql-tool                                       googletest
google-authenticator-libpam                           google-go                                             google-sparsehash                                     googler                                               goose

To install aws-google-auth, run:
  brew install aws-google-auth

==> Casks
google-ads-editor                            google-chat                                  google-cloud-sdk                             google-earth-pro                             google-web-designer                          moefe-google-translate
google-analytics-opt-out                     google-chat-electron                         google-drive                                 google-japanese-ime                          googleappengine
google-assistant                             google-chrome                                google-drive-file-stream                     google-trends                                marshallofsound-google-play-music-player

To install google-ads-editor, run:
  brew install --cask google-ads-editor
```

I'm wondering if it might be a good idea to limit the number of search results. We don't need the search results to be complete or thorough in this command.

```
$brew install -n git-utils
Warning: No available formula with the name "git-utils". Did you mean eot-utils?
git-utils was deleted from homebrew/core in commit f29c64de4a1:
  git-utils: remove formula

To show the formula before removal, run:
  git -C "$(brew --repo homebrew/core)" show f29c64de4a1^:Formula/git-utils.rb

If you still use this formula, consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
```

```
$ brew install -n not_a_tap/name
Warning: No available formula with the name "not_a_tap/name".
```

**Comment by MikeMcQuaid** [comment]
> To install aws-google-auth, run:
>  brew install aws-google-auth

Maybe want to make this have `--formula` to be consistent with `--cask` below?

> I'm wondering if it might be a good idea to limit the number of search results. We don't need the search results to be complete or thorough in this command.

Maybe? Can you produce any circumstances in which the unlimited version seems silly? If not, just leave it as-is (or for future PR at least).

File: Library/Homebrew/cmd/install.rb (hunk 3 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/install.rb]: Thanks ❤️

File: Library/Homebrew/cmd/install.rb [hunk 7]
```diff
@@ -278,48 +278,57 @@ def install
     # formula was found, but there's a problem with its implementation).
     $stderr.puts e.backtrace if Homebrew::EnvConfig.developer?
     ofail e.message
-  rescue FormulaOrCaskUnavailableError => e
-    if e.name == "updog"
+  rescue FormulaOrCaskUnavailableError, Cask::CaskUnavailableError => e
+    # formula name or cask token
+    name = e.try(:name) || e.token
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:283]: I know that this is mostly existing code but: I wonder if we could punt pretty much the whole `rescue` block into a new method (perhaps in `search.rb`?) which can be called separately for formulae/casks. It feels like there's a lot of logic in here, more than you'd expect for exception handling. Would also allow this to be tested, too.

Given this isn't your mess: feel free to punt to a future PR, this is not blocking.

File: Library/Homebrew/cmd/install.rb (hunk 4 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/install.rb:298]:
```suggestion
    # We don't seem to get good search results when the tap is specified
    # so we might as well return early.
    return if name.include?("/")
```

**Review by MikeMcQuaid — APPROVED** [review]
Looks good to me! Some non-blocking comments for cleanup, can happen pre or post-merge, up to you.

**Comment by apainintheneck** [comment]
> > To install aws-google-auth, run:
> > brew install aws-google-auth
> 
> Maybe want to make this have `--formula` to be consistent with `--cask` below?

I mean it's not functionally necessary so... Plus, it'll make more sense without it for Linux users.

> > I'm wondering if it might be a good idea to limit the number of search results. We don't need the search results to be complete or thorough in this command.
> 
> Maybe? Can you produce any circumstances in which the unlimited version seems silly? If not, just leave it as-is (or for future PR at least).

The worst case is probably searching for something generic but it's not the end of the world. Let's show everything until people complain about it.

```
$ brew install -n google
Warning: No available formula with the name "google". Did you mean googler or goose?
==> Searching for similarly named formulae and casks...
==> Formulae
aws-google-auth                   google-java-format                googletest
google-authenticator-libpam       google-sparsehash                 goose
google-benchmark                  google-sql-tool
google-go ✔                       googler

To install aws-google-auth, run:
  brew install aws-google-auth

==> Casks
google-ads-editor                                  google-drive
google-analytics-opt-out                           google-drive-file-stream
google-assistant                                   google-earth-pro
google-chat                                        google-japanese-ime
google-chat-electron                               google-japanese-ime-dev
google-chrome                                      google-trends
google-chrome-beta                                 google-web-designer
google-chrome-canary                               googleappengine
google-chrome-dev                                  marshallofsound-google-play-music-player
google-cloud-sdk                                   moefe-google-translate

To install google-ads-editor, run:
  brew install --cask google-ads-editor
```

**Comment by apainintheneck** [comment]
Also, the cask search is kind of slow in comparison with formulae and hitting the Github API. I think I figured out why and I'll handle that in another PR.

**Comment by apainintheneck** [comment]
#### On this branch

```
/u/l/H/L/Homebrew (add-casks-to-install-search|✔) $ hyperfine 'brew search --cask google'
Benchmark 1: brew search --cask google
  Time (mean ± σ):      2.970 s ±  0.066 s    [User: 1.227 s, System: 1.072 s]
  Range (min … max):    2.902 s …  3.099 s    10 runs
 ```

#### On master
```
/u/l/H/L/Homebrew (master|✔) $ hyperfine 'brew search --cask google'
Benchmark 1: brew search --cask google
  Time (mean ± σ):      6.687 s ±  0.097 s    [User: 3.751 s, System: 1.903 s]
  Range (min … max):    6.586 s …  6.907 s    10 runs
```

This is on my old iMac but you get the idea.

https://github.com/Homebrew/brew/blob/ed3789a0bb34464a37acd224f196f906f8d73b6c/Library/Homebrew/extend/os/mac/search.rb#L40

Apparently, this line was very slow.

File: Library/Homebrew/cask/cask.rb [hunk 8]
```diff
@@ -38,6 +38,16 @@ def self.all
...
 
+    def self.full_names
+      Tap.flat_map do |tap|
+        next tap.cask_tokens.blank?
+        next tap.cask_tokens if tap.user == "Homebrew"
+
+        name = tap.name
+        tap.cask_tokens.map { |tok| "#{name}/#{tok}" }
+      end.flatten
+    end
```
Comment (apainintheneck) [inline Library/Homebrew/cask/cask.rb:49]: This just mimics the behavior of `Cask.all.map(&:full_name)` but is significantly faster.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> I mean it's not functionally necessary so... Plus, it'll make more sense without it for Linux users.

Sure but: neither is `--cask`? Note: this feedback is not blocking.

> The worst case is probably searching for something generic but it's not the end of the world. Let's show everything until people complain about it.

👍🏻 

> Apparently, this line was very slow.

Oof! Nice work!

**Comment by apainintheneck** [comment]
> > I mean it's not functionally necessary so... Plus, it'll make more sense without it for Linux users.
> 
> Sure but: neither is `--cask`? Note: this feedback is not blocking.

I thought if there was any naming conflict that it would default to the formula. Is that not true?

File: Library/Homebrew/extend/os/mac/search.rb [hunk 9]
```diff
@@ -37,8 +37,7 @@ def search_casks(string_or_regex)
         results = cask_tokens.extend(Searchable)
                              .search(string_or_regex)
 
-        cask_names = Cask::Cask.all.map(&:full_name)
-        results += DidYouMean::SpellChecker.new(dictionary: cask_names)
+        results += DidYouMean::SpellChecker.new(dictionary: cask_tokens)
```
Comment (apainintheneck) [inline Library/Homebrew/extend/os/mac/search.rb:40]: A quick explanation of why this `cask_names` calculation isn't needed anymore. Essentially, `cask_names` and `cask_tokens` return almost identical results but, of course, `cask_names` is much slower.

### `cask_names`
https://github.com/Homebrew/brew/blob/ed3789a0bb34464a37acd224f196f906f8d73b6c/Library/Homebrew/extend/os/mac/search.rb#L40

For each cask in a tap we call `Cask#full_name` which either returns the token if it's a core tap or the whole path otherwise (`user/repo/token`).

https://github.com/Homebrew/brew/blob/ed3789a0bb34464a37acd224f196f906f8d73b6c/Library/Homebrew/cask/cask.rb#L115-L120

https://github.com/Homebrew/brew/blob/ed3789a0bb34464a37acd224f196f906f8d73b6c/Library/Homebrew/tap.rb#L102

### `cask_tokens`

https://github.com/Homebrew/brew/blob/ed3789a0bb34464a37acd224f196f906f8d73b6c/Library/Homebrew/extend/os/mac/search.rb#L33-L35

As you can see it returns essentially the same result. It removes the `user/repo` part from core taps and otherwise keeps everything the same. That's why we can use it for both.

**Comment by MikeMcQuaid** [comment]
> I thought if there was any naming conflict that it would default to the formula. Is that not true?

It would but it'll print a warning message which is a bit yucky.

**Comment by MikeMcQuaid** [comment]
Thanks again @apainintheneck!
