### PR TITLE
dev-cmd/vendor-gems: fix creation of broken symlinks

### LINKED ISSUE #16205: BrewTestBot adding back broken symlinks
### `brew doctor` output

Please check "Debug Info" step here - https://github.com/vuejs/vitepress/actions/runs/6835197697/job/18588720961

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 3 weeks ago
Core tap JSON: 11 Nov 15:56 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit zen3
Clang: 14.0.0
Git: 2.42.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.2.0-1015-azure x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

Running vite on GitHub actions is breaking. I wasn't explicitly using brew in CI. This was fixed in #15950 but later regressed by the bot in https://github.com/Homebrew/brew/commit/c35b049b3cd1615fce0597d24f9ccd686a128db0

Related issue: https://github.com/Homebrew/brew/issues/15928

### What happened (include all command output)?

Getting:

```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Error: ELOOP: too many symbolic links encountered, stat '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { errno: -40, code: 'ELOOP', syscall: 'stat', path: '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/gems/mechanize-2.9.1/mechanize-2.9.1' }
```

### What did you expect to happen?

No error.

### Reproduction

You can check the workflow file in https://github.com/vuejs/vitepress/actions/runs/6835197697/job/18588720961 but the reproduction provided in #15928 might still apply.

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

When the target symlink already points to an existing directory, the
`#ln_sf` call creates the symlink inside the intended target directory
(which is not what we intend to do here).

Let's fix that.

Closes #16205

### CODE REVIEW

File: Library/Homebrew/dev-cmd/vendor-gems.rb [hunk 1]
```diff
@@ -59,12 +59,16 @@ def vendor_gems
...
-            if (source = Pathname.glob("#{gem}-*/").first)
-              FileUtils.ln_sf source, gem
-            end
+            source = Pathname.glob("#{gem}-*/").first
+            next if source.blank?
+
+            target = Pathname.new(gem)
+            next if target.exist? && target.symlink? && (target.realpath == source.realpath)
+
+            FileUtils.ln_sf source, gem
```
Comment (Bo98) [inline Library/Homebrew/dev-cmd/vendor-gems.rb:71]: In the case of a version update, we probably need to remove the existing symlink first to avoid a similar issue happening.

**Review by Bo98 — COMMENTED** [review]
Thanks, good catch!

File: Library/Homebrew/dev-cmd/vendor-gems.rb (hunk 1 above)
Comment (carlocab) [reply Library/Homebrew/dev-cmd/vendor-gems.rb]: I always thought that the existing symlink is broken in the case of version updates, but I guess I'm not actually certain about that.

Let's just always remove the symlink, which is probably the intention of `ln_sf`.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Whoops, didn't mean to kick off auto-merge. @Bo98 feel free to revert if you feel it's warranted.

**Comment by MikeMcQuaid** [comment]
Thanks @carlocab!

File: Library/Homebrew/dev-cmd/vendor-gems.rb (hunk 1 above)
Comment (Bo98) [reply Library/Homebrew/dev-cmd/vendor-gems.rb]: > I always thought that the existing symlink is broken in the case of version updates, but I guess I'm not actually certain about that.

In theory it should, but seems safer to not rely on it when there's an simple way to not to.

**Comment by Bo98** [comment]
Seems fine
