### PR TITLE
sync installed_as_dependency when changing installed_on_request

### LINKED ISSUE #21751: `brew tab --no-installed-on-request` does not work as expected
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4135badeddc3899aa2e89d3ea1caee320c55d299
Last commit: 6 days ago
Branch: stable
Core tap JSON: 17 Mar 13:24 UTC
Core cask tap JSON: 17 Mar 13:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 28
HOMEBREW_EDITOR: code --wait
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 4.0.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.1/bin/ruby
CPU: 14-core 64-bit arm_brava
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.3.1-arm64
CLT: 26.3.0.0.1.1771626560
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I did routine `update`, `upgrade`, `cleanup` combo, ant got a message:

```shellsession
$ brew cleanup
Warning: Skipping sqlite: most recent version 3.51.3 not installed
```

Which led me to https://github.com/Homebrew/homebrew-core/issues/272250#issuecomment-4070239188. I then ran `brew reinstall sqlite` as mentioned, terminated it due to network issues (which left a `3.52.0.reinstall` folder in the Cellar), and reran.

Then I ran `brew bundle dump --global --force`, and found `sqlite` in `~/.Brewfile`.

I have met similar issues before (#18754) so I thought `brew tab --no-installed-on-request` would fix its status, but after another dump I still saw `sqlite`.

And I realized `installed_as_dependency` is set to `false`, which is likely due to my termination above:

```shellsession
$ jq .installed_as_dependency /opt/homebrew/Cellar/sqlite/3.51.3/INSTALL_RECEIPT.json
false
```

(`sqlite` is installed as a dependency on my system.)

```shellsession
$ brew uses --installed sqlite
corepack          deno              mpv               node              python@3.14       vapoursynth       yt-dlp
```

And according to the implementation, I would indeed get `sqlite` dumped regardless of how I change `installed_on_request`:

https://github.com/Homebrew/brew/blob/28749a77fa2d2e85d74e51b2fe1d0820d5431a93/Library/Homebrew/bundle/formula_dumper.rb#L62-L64

### What happened (include all command output)?

I need to manually edit `INSTALL_RECEIPT.json` to correct `sqlite`'s installation status.

### What did you expect to happen?

I see 3 potential issues here:

1. Reinstall (of termination of it) should not change its installation status (either `installed_as_dependency` or `installed_on_request`), at least this is how I expected
2. As the title says, `brew tab --no-installed-on-request` in this scenario made no actual effect, `brew bundle` still did its thing
3. I'm not familiar with all usage of these two status fields, but they seem mutually exclusive, so should not be two separate fields which could go out of sync like in my scenario.

### Step-by-step reproduction instructions (by running `brew` commands)

```shellsession
$ brew install cowsay
$ brew bundle dump --global --force
$ grep cowsay ~/.Brewfile
brew "cowsay"
$ brew tab --no-installed-on-request cowsay
$ grep cowsay ~/.Brewfile
brew "cowsay"
```

### PR DESCRIPTION
**Pull request by ooye-sanket**
When marking a formula as not installed on request, also set
`installed_as_dependency` to `true`, to ensure `brew bundle dump`
correctly excludes it.

Previously, `brew tab --no-installed-on-request` had no effect on
`brew bundle dump` because the dump logic in `brew.rb` checks both fields:

    f[:installed_on_request?] || !f[:installed_as_dependency?]

Setting `installed_on_request` to `false` alone was not enough if
`installed_as_dependency` was also `false` — the second condition would
still evaluate to `true`, causing the formula to be included in the dump.

Fixes #21751

@MikeMcQuaid can you please review it!!

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [ ] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@ooye-sanket thanks for the PR! I actually think the bigger change we should make is get rid of `installed_as_dependency` altogether; replace all call sites with `installed_on_request` and stop storing it in new Tabs for both formulae and casks.

**Comment by ooye-sanket** [comment]
Thanks @MikeMcQuaid!

I'd love to take on the bigger refactor. Before I start, could you clarify the approach?

- Should `installed_on_request` become the single source of truth (i.e., `!installed_on_request` replaces every `installed_as_dependency` check)?
- Should we keep reading the old `installed_as_dependency` from existing tab JSON files for backward compatibility, or drop that as well?
- Should this be a separate PR from the current one, or should I update this PR?

**Comment by MikeMcQuaid** [comment]
> * Should `installed_on_request` become the single source of truth (i.e., `!installed_on_request` replaces every `installed_as_dependency` check)?

Yep!

> * Should we keep reading the old `installed_as_dependency` from existing tab JSON files for backward compatibility, or drop that as well?

No, think we can skip/drop that too.

> * Should this be a separate PR from the current one, or should I update this PR?

Can update this PR!

**Comment by ooye-sanket** [comment]
Hi @MikeMcQuaid, I've updated the PR with the full refactor as you suggested!

Here's what was done:
- Removed `installed_as_dependency` entirely from `AbstractTab` and `Tab` (no longer stored in new tab JSON files)
- Replaced all call sites with `!installed_on_request`  `installed_on_request` is now the single source of truth
- Updated `formula_installer.rb`, `cask/installer.rb`, `install.rb`, `reinstall.rb`, `upgrade.rb`, `bundle/brew.rb`, `cmd/leaves.rb`, `cmd/list.rb`, `formula.rb`, `cask/tab.rb` and all related test files and fixtures
- Kept the `--installed-as-dependency` CLI flag in `brew list` and `brew leaves` as-is since it's a user-facing option

Could you confirm if this approach looks correct, or if there's anything I may have missed or handled incorrectly? Happy to make any adjustments!

File: Library/Homebrew/cmd/list.rb [hunk 1]
```diff
@@ -136,7 +136,7 @@ def run
 
             statuses = []
             statuses << "installed on request" if args.installed_on_request? && tab.installed_on_request
-            statuses << "installed as dependency" if args.installed_as_dependency? && tab.installed_as_dependency
+            statuses << "installed as dependency" if args.installed_as_dependency? && !tab.installed_on_request
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/list.rb:141]: Could add a commented-out `odeprecated` for the `args.installed_as_dependency?` so we can deprecate it in a future release.

**Review by MikeMcQuaid — COMMENTED** [review]
Looks great, nice work @ooye-sanket! One more tiny suggestion.

**Comment by ooye-sanket** [comment]
@MikeMcQuaid Added the commented-out odeprecated in cmd/list.rb as suggested. Ready for re-review!

**Comment by ooye-sanket** [comment]
@MikeMcQuaid Rebased onto latest upstream/main, resolved all conflicts (absorbed loaded_from_internal_api additions), and added the commented-out odeprecated in cmd/list.rb as suggested. Ready for re-review!

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks! Looks good when CI is 🟢!

**Comment by ooye-sanket** [comment]
Hey @MikeMcQuaid the syntax CI check is failing, could you help point out what needs fixing? i tried a lot not getting the cause

**Comment by MikeMcQuaid** [comment]
@ooye-sanket You need to run `brew style --fix`.

**Review by MikeMcQuaid — COMMENTED** [review]
Waiting on author answering question.

**Comment by ooye-sanket** [comment]
Hey @MikeMcQuaid, apologies for the delayed response  I had an unexpected personal situation come up where I needed to be present, so I was away for a bit. I've now rebased onto the latest upstream/main, resolved the tab.rb conflict, and fixed all brew style --fix offenses CI is now green!
Ready for re-review whenever you get a chance.

**Comment by MikeMcQuaid** [comment]
@ooye-sanket Will re-review when CI is 🟢.

**Comment by ooye-sanket** [comment]
Hey @MikeMcQuaid, CI is finally green! 
All tests passing now. Ready for re-review! 🙏

**Review by MikeMcQuaid — APPROVED** [review]
Thanks, nice work here!
