### PR TITLE
fix: ignore broken kegs during gcc linkage test

### LINKED ISSUE #19500: `brew doctor` fails with "is not a directory" error
### `brew doctor` output

```shell
Error: /home/linuxbrew/.linuxbrew/Cellar/llama.cpp/4889 is not a directory
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.24-188-gc67f24b
ORIGIN: https://github.com/Homebrew/brew
HEAD: c67f24b7a84346344aa68e718e735317ee8dddf2
Last commit: 4 hours ago
Branch: master
Core tap HEAD: 0a204c42d59d536c67756a175697d229efd15282
Core tap last commit: 64 minutes ago
Core tap JSON: 15 Mar 05:45 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: quad-core 64-bit haswell
Clang: N/A
Git: 2.48.1 => /bin/git
Curl: 8.9.1 => /bin/curl
Kernel: Linux 6.13.5-200.fc41.x86_64 x86_64 GNU/Linux
OS: Fedora release 41 (Forty One)
Host glibc: 2.40
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 14.2.0_1
xorg: N/A
```

### What were you trying to do (and why)?

Trying to understand why `brew install -s` started "Tapping homebrew/cask" all of a sudden.

### What happened (include all command output)?

Maybe the error starts to occur when `brew update` fails with an error about too many open files.

### What did you expect to happen?

Explain how to fix.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
➜  ~ brew doctor                                                 
Error: /home/linuxbrew/.linuxbrew/Cellar/llama.cpp/4889 is not a directory
➜  ~ sudo ls /home/linuxbrew/.linuxbrew/Cellar/llama.cpp     
4882
➜  ~ sudo ls /home/linuxbrew/.linuxbrew/Cellar/llama.cpp/4889
ls: cannot access '/home/linuxbrew/.linuxbrew/Cellar/llama.cpp/4889': No such file or directory
```

### PR DESCRIPTION
**Pull request by botantony**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

If my theory is correct, this pr should close #19500 but unfortunately I cannot test it. If someone uses Linux, please, apply this patch, delete a few kegs manually (directories like `$HOMEBREW_PREFIX/Cellar/<formula>/<version>` and try to run `brew doctor`

### CODE REVIEW

File: Library/Homebrew/extend/os/linux/diagnostic.rb [hunk 1]
```diff
@@ -143,13 +143,24 @@ def check_gcc_dependent_linkage
...
-              paths = binary.rpaths
-              versioned_linkage = paths.any? { |path| path.match?(%r{lib/gcc/\d+$}) }
-              unversioned_linkage = paths.any? { |path| path.match?(%r{lib/gcc/current$}) }
-
-              versioned_linkage && !unversioned_linkage
+            # Keg.new() may raise an error if it is not a directory.
+            # As the result `brew doctor` may display `Error: <keg> is not a directory`
+            # instead of proper `doctor` information.
+            # There are other checks that test that, we can skip broken kegs.
+            list_element = dependent # HACK: `brew style` comlains about `begin` otherwise
```
Comment (Bo98) [inline Library/Homebrew/extend/os/linux/diagnostic.rb:150]: Are you sure? I've never seen a false positive regarding `begin` before?

File: Library/Homebrew/extend/os/linux/diagnostic.rb [hunk 2]
```diff
@@ -143,13 +143,24 @@ def check_gcc_dependent_linkage
...
+              keg.binary_executable_or_library_files.any? do |binary|
+                paths = binary.rpaths
+                versioned_linkage = paths.any? { |path| path.match?(%r{lib/gcc/\d+$}) }
+                unversioned_linkage = paths.any? { |path| path.match?(%r{lib/gcc/current$}) }
+
+                versioned_linkage && !unversioned_linkage
+              end
+              # It would be nice to add error type to differentiate between
+              # `#{path} is not a valid keg` and `#{path} is not a directory` errors
+            rescue
```
Comment (Bo98) [inline Library/Homebrew/extend/os/linux/diagnostic.rb:162]: A better approach is to make those errors return a `InvalidKegError` or something and catch that.

File: Library/Homebrew/extend/os/linux/diagnostic.rb [hunk 3]
```diff
@@ -143,13 +143,24 @@ def check_gcc_dependent_linkage
...
+              list_element
```
Comment (Bo98) [inline Library/Homebrew/extend/os/linux/diagnostic.rb:163]: This doesn't make sense - it should be `true` or `false`. Probably `false` given the error wouldn't really be correct otherwise.

File: Library/Homebrew/extend/os/linux/diagnostic.rb [hunk 4]
```diff
@@ -143,13 +143,24 @@ def check_gcc_dependent_linkage
           return if gcc_dependents.empty?
 
           badly_linked = gcc_dependents.select do |dependent|
-            keg = Keg.new(dependent.prefix)
```
Comment (carlocab) [inline Library/Homebrew/extend/os/linux/diagnostic.rb:146]: I think the original code will work fine if you just replace
```ruby
dependent.prefix
```
here with
```ruby
dependent.any_installed_prefix
```
If you want to be sure, you can also try
```ruby
next unless dependent.any_installed_prefix.directory?
```

File: Library/Homebrew/extend/os/linux/diagnostic.rb [hunk 5]
```diff
@@ -143,6 +143,12 @@ def check_gcc_dependent_linkage
           return if gcc_dependents.empty?
 
           badly_linked = gcc_dependents.select do |dependent|
+            # Keg.new() may raise an error if it is not a directory.
+            # As the result `brew doctor` may display `Error: <keg> is not a directory`
+            # instead of proper `doctor` information.
+            # There are other checks that test that, we can skip broken kegs.
+            next if !dependent.prefix.exist? || !dependent.prefix.directory?
+
             keg = Keg.new(dependent.prefix)
```
Comment (carlocab) [inline Library/Homebrew/extend/os/linux/diagnostic.rb:152]: Let's do this so we don't have to assume `dependent` is `optlinked`:
```suggestion
            dependent_prefix = dependent.any_installed_prefix
            # Keg.new() may raise an error if it is not a directory.
            # As the result `brew doctor` may display `Error: <keg> is not a directory`
            # instead of proper `doctor` information.
            # There are other checks that test that, we can skip broken kegs.
            next if !dependent_prefix.exist? || !dependent_prefix.directory?

            keg = Keg.new(dependent_prefix)
```

**Review by carlocab — APPROVED** [review]
Happy to merge once suggestion below is applied. Thanks!

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by MikeMcQuaid — APPROVED** [review]
