### PR TITLE
Speed up tab completion

### LINKED ISSUE #20: tab-completing formula names is very slow
# Please follow the general troubleshooting steps first:

- [*] Ran `brew update` and retried your prior step?
- [*] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

tab-completion of formula names is very slow (many seconds), after updating to brew 0.9.9. I only have the core tap installed.

I'm actually unsure if these completions were already slow before, as I hadn't triggered one for a while before this latest update.

### PR DESCRIPTION
**Pull request by tdsmith**
Is using `find` here kosher? This is, like, unbelievably faster than what we had before, which was I think quadratic in the number of formulas when considering taps, which was pretty hilarious after we split out homebrew-core.

Fixes #20.

### CODE REVIEW

**Comment by tdsmith** [comment]
Would appreciate some review from past bash completion contributors @rhendric, @bfontaine, @robsonpeixoto, @hivehand if time allows!

File: etc/bash_completion.d/brew [hunk 1]
```diff
@@ -47,21 +47,20 @@ __brew_complete_formulae ()
...
-        file=${file/"Formula/"/}
-        file=${file/"HomebrewFormula/"/}
-        file=${file#${lib}/Taps/}
-        file=${file%.rb}
-        file=${file/homebrew-/}
-        tf="${tf} ${file}"
-    done
+    
+    # capture tap/Formula/foo.rb, tap/HomebrewFormula/foo.rb
+    local ff=$(find $taps -depth 4 -path '*Formula/*rb' | sed -E "s|$taps/([^/]+)/homebrew-([^/]+)/(Homebrew)?Formula/(.*)\.rb|\1-\2/\4|")
```
Comment (mikemcquaid) [inline etc/bash_completion.d/brew]: Seems like you could just run `find` once and strip the results each time you need/don't. It's also worth noting `sed -E` will behave differently on Linux, I believe (if you care)

**Comment by xu-cheng** [comment]
How about just using `brew search` to get full list like zsh competition script does?

**Comment by bfontaine** [comment]
I won’t have time to check this before tomorrow :/

File: etc/bash_completion.d/brew (hunk 1 above)
Comment (robsonpeixoto) [inline etc/bash_completion.d/brew]: @mikemcquaid I have tested with `gnu-sed` and work well.

**Comment by tdsmith** [comment]
Using `brew search` like @xu-cheng suggested is much neater and leaves all the tricky knowledge bits up to `brew`:

```bash
__brew_complete_formulae ()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local formulas=$(brew search)
    local shortnames=$(echo "$formulas" | grep / | cut -d / -f 3)
    COMPREPLY=($(compgen -W "$formulas $shortnames" -- "$cur"))
}
```

and it is slightly faster, unless HOMEBREW_ANALYTICS is set; 20 completions takes 5.2 s without HOMEBREW_ANALYTICS and 10.1 s with HOMEBREW_ANALYTICS; 250 ms/call is probably enough to be noticeable.

**Comment by tdsmith** [comment]
Either way, it seems to be the right thing to do right now, and we can work on ANALYTICS latency later.

File: etc/bash_completion.d/brew (hunk 1 above)
Comment (tdsmith) [inline etc/bash_completion.d/brew]: Thanks!

File: etc/bash_completion.d/brew [hunk 2]
```diff
@@ -45,23 +45,9 @@ __brewcomp ()
...
-        file=${file/"HomebrewFormula/"/}
-        file=${file#${lib}/Taps/}
-        file=${file%.rb}
-        file=${file/homebrew-/}
-        tf="${tf} ${file}"
-    done
-
-    COMPREPLY=($(compgen -W "$ff $af $tf" -- "$cur"))
+    local formulas=$(brew search)
+    local shortnames=$(echo "$formulas" | grep / | cut -d / -f 3)
```
Comment (UniqMartin) [inline etc/bash_completion.d/brew]: Do you mind adding quotes to those assignments, i.e. `="$(<stuff>)"` instead of `=$(<stuff>)`? I'd like to have them for consistency with most of the other Shell code we have (looking at `brew.sh` right now).

Comment (tdsmith) [inline etc/bash_completion.d/brew]: I don't mind; do they do something?

Comment (UniqMartin) [inline etc/bash_completion.d/brew]: In theory they keep the output of the command together as a single argument, in practice Bash does some special casing for `local` and probably a few others. Always quoting when things are supposed to remain a single unit is easier to read in my opinion, because you don't have to remember those special cases all the time. In most other contexts, the result would be different without quoting, e.g.:

```
printf "[%s]\n" x=$(ls)
printf "[%s]\n" x="$(ls)"
```
