### PR TITLE
audit: ignore group write bit

### LINKED ISSUE #7068: Should `brew audit` complain about incorrect file permissions?
Should `brew audit` actually complain about incorrect file permissions for formulas when the permissions aren't actually committed by Git? (I have them changed because I use `brewdo` but need group-write permissions to the tap for using Git there in an ergonomic manner.)

### PR DESCRIPTION
**Pull request by alexreg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally? (Well, actually no, but I get failures normally, and PR introduces no new ones as far as I can tell.)

-----

Fixes #7068.

### CODE REVIEW

**Comment by alexreg** [comment]
This PR is in response to the above issue and specifically https://github.com/Homebrew/brew/issues/7068#issuecomment-589988567. Please let me know if this is the sort of solution you'd like. (It seems reasonable to me, and fairly conservative.)

File: Library/Homebrew/dev-cmd/audit.rb [hunk 1]
```diff
@@ -244,9 +244,11 @@ def audit_style
...
       # Under normal circumstances (umask 0022), we expect a file mode of 644. If
       # the user's umask is more restrictive, respect that by masking out the
-      # corresponding bits. (The also included 0100000 flag means regular file.)
-      wanted_mode = 0100644 & ~File.umask
+      # corresponding bits. (The also-included 0100000 flag means regular file.)
+      # We do not care about the group write bit here, since some brew setups
+      # (e.g., brewdo) make it desirable for it to be set.
       actual_mode = formula.path.stat.mode
+      wanted_mode = (0100644 | (actual_mode & 0020)) & ~File.umask
       unless actual_mode == wanted_mode
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/audit.rb]:
```suggestion
      if actual_mode != wanted_mode
```

File: Library/Homebrew/dev-cmd/audit.rb [hunk 2]
```diff
@@ -244,9 +244,11 @@ def audit_style
     def audit_file
       # Under normal circumstances (umask 0022), we expect a file mode of 644. If
       # the user's umask is more restrictive, respect that by masking out the
-      # corresponding bits. (The also included 0100000 flag means regular file.)
-      wanted_mode = 0100644 & ~File.umask
+      # corresponding bits. (The also-included 0100000 flag means regular file.)
+      # We do not care about the group write bit here, since some brew setups
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/audit.rb]:
```suggestion
      # We do not care about the group write bit to allow users to choose it.
```

File: Library/Homebrew/dev-cmd/audit.rb [hunk 3]
```diff
@@ -244,9 +244,11 @@ def audit_style
...
+      # (e.g., brewdo) make it desirable for it to be set.
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/audit.rb]:
```suggestion
```

File: Library/Homebrew/dev-cmd/audit.rb [hunk 4]
```diff
@@ -244,9 +244,11 @@ def audit_style
...
       actual_mode = formula.path.stat.mode
+      wanted_mode = (0100644 | (actual_mode & 0020)) & ~File.umask
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/audit.rb]: Can this be simplified a bit? It's a bit hairy as-is.

File: Library/Homebrew/dev-cmd/audit.rb (hunk 3 above)
Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: I removed the bracketed bit here, but if you'd like me to remove everything after the comma in this sentence, just let me know.

File: Library/Homebrew/dev-cmd/audit.rb (hunk 4 above)
Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Yeah, it is... Sadly, I don't think so. The obvious way to understand it is that `actual_mode & 0020` select the group write bit from the actual file mode (i.e., gives either `0020` or `0000`) and then sets the corresponding bit on `0100644` if so. i.e., it takes `0100644` and adds the group write bit *if and only if* the group write bit is set on the actual fine -- which makes it `0100664` instead. I think it's right that `& ~File.umask` should remain as the outermost bit operation, right? Anyway, if you want me to put another comment in for this, or rework it into a form you have in mind, let me know. :-)

**Comment by alexreg** [comment]
Okay, amended per your comments; just left your last comment unresolved for now, so you can let me know your thoughts. Is the above test failure spurious or something? It doesn't seem like it has anything to do with my changes at least.

File: Library/Homebrew/dev-cmd/audit.rb (hunk 4 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: What about just checking the individual bits?

File: Library/Homebrew/dev-cmd/audit.rb [hunk 5]
```diff
@@ -244,10 +244,11 @@ def audit_style
     def audit_file
       # Under normal circumstances (umask 0022), we expect a file mode of 644. If
       # the user's umask is more restrictive, respect that by masking out the
-      # corresponding bits. (The also included 0100000 flag means regular file.)
-      wanted_mode = 0100644 & ~File.umask
+      # corresponding bits. (The also-included 0100000 flag means regular file.)
+      # We do not care about the group write bit in order to allow users to choose it.
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/audit.rb]: 👍

File: Library/Homebrew/dev-cmd/audit.rb (hunk 4 above)
Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: @MikeMcQuaid Yep, that occurred to me too, but `wanted_mode` is used for the diagnostic message just below, which makes this calculation quite convenient I think.

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: I think the message should change too. It's no longer particularly accurate if we're going to ignore the group bit.

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Fair enough. At the moment it obviously it "conservatively" suggests new permissions by reflecting whatever the group write bit already is. What sort of message would you like to see?

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: Probably just two separate messages for world read and only user write?

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Okay, sounds fair. I'll see what I can do now.

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Wait, so to confirm... 
* We *want* user-write (i.e., error if not set).
* We don't care whether or not group-write is set (i.e., never error on this).
* We *do not want* other-write (i.e., error if set).

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: Yep, sounds right to me!

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Great. This is what I implemented. I'll just adjust the tests now and push.

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: Ah, the problem is now: what if the above conditions are all satisfied, but the umask is more restrictive? Should we honour that or not? If so, it means a 4th problem message potentially, which awkward, since it would effectively make the previous ones redundant.

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: (Per the above, if we want to respect the umask, I think my previous approach works best. Otherwise, we can go with yours.)

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: I'm not sure I fully understand how we currently honour or do not the umask. Can you explain a case in which it would affect an audit failure and what your opinion is on what we should do? Thanks ❤️

Comment (alexreg) [reply Library/Homebrew/dev-cmd/audit.rb]: As I understand, the current behaviour is basically that the umask is used to "mask out" (clear) certain bits when incorrect permissions are found and a chmod is suggested (with a numeric rather than a symbolic argument). The Wikipedia page on umask has an interesting sentence:

> Generally, the mask only affects file permissions during the creation of new files and has no effect when file permissions are changed in existing files, however, the chmod command will check the mask when the chmod options are specified using symbolic mode and a reference to a class of users is not specified.

Obviously, we are not dealing with the creation of files here. The question is, is our situation analagous to a symbolic change without a reference to a class of users (i.e., something like `+r` as opposed to `g-w`, the latter making a reference to the class of users `g`). I would say no, so that we can probably just not worry about the umask. What do you think?

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/audit.rb]: > I would say no, so that we can probably just not worry about the umask. What do you think?

Agreed!

**Comment by alexreg** [comment]
@MikeMcQuaid Pushed a new version just now, following our discussion. Hope this is closer to the ideal solution. :-)

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @alexreg!

**Comment by alexreg** [comment]
@mikemcquaid No problem; thanks for reviewing.
