### PR TITLE
dev-cmd/extract: trim version to only digits/decimals for class & file names

### LINKED ISSUE #16881: `brew extract` creates a class name with `@` symbol instead of `AT`
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  go-task
  mc
  coursier
  vault

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo user/local-protobuf21) checkout
  git -C $(brew --repo user/local-mc) checkout
  git -C $(brew --repo user/local-minio) checkout
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.12-19-gb1990ed
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1990ed4b6668bf5dc0993807e9525cf1c08051a
Last commit: 3 hours ago
Core tap HEAD: cd31c9956bd24474f7d4d2f2bf697f4a042e70b5
Core tap last commit: 42 minutes ago
Core tap JSON: 12 Mar 11:37 UTC
Core cask tap JSON: 12 Mar 11:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to create a local tap to install an older version of minio.

### What happened (include all command output)?

1. Created a new tap
```sh
brew tap-new local-minio
```

2. Extracted the desired version
```sh
brew extract --version RELEASE.2024-03-05T04-48-44Z minio/stable/minio user/local-minio
```

3. Ran `brew install`
```sh
brew install minio@release.2024-03-05t04-48-44z
```
```
Error: user/local-minio/minio@release.2024-03-05t04-48-44z: undefined method `<' for nil:NilClass
```

After checking the formula with `brew edit` found out that the name of the class was
```rb
class Minio@release20240305T044844Z < Formula
```
which was causing the error.

### What did you expect to happen?

Expected the formula to install.

### Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew tap-new local-minio
brew extract --version RELEASE.2024-03-05T04-48-44Z minio/stable/minio user/local-minio
brew install minio@release.2024-03-05t04-48-44z
```

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
When generating a class name for a formula, remove any non-digit characters following the `@` if present. Allows a command like `brew extract --version` to handle versions that don't start with digits. Fixes #16881.

```
brew(main):001> Formulary.class_s("minio@RELEASE.2024-03-05T04-48-44Z")
=> "MinioAT20240305t044844z"
```

### CODE REVIEW

**Comment by Bo98** [comment]
> minio@RELEASE.2024-03-05T04-48-44Z

Should `brew extract be outputting these names at all? There's a few places that assume numerical `@` versions: https://github.com/Homebrew/brew/blob/30e2ae10a38181972d21d67422143d3d9ff8a724/Library/Homebrew/formula.rb#L513-L516

**Comment by EricFromCanada** [comment]
Good point. I've updated this to have `extract` convert versions to just digits with decimals.

**Review by Bo98 — APPROVED** [review]
Thanks!

File: Library/Homebrew/dev-cmd/extract.rb [hunk 1]
```diff
@@ -122,12 +122,15 @@ def run
         # e.g. Foo version 1.2.3 becomes FooAT123 and resides in Foo@1.2.3.rb.
         class_name = Formulary.class_s(name)
 
-        # Remove any existing version suffixes, as a new one will be added later
+        # The version can only contain digits with decimals in between.
+        version.to_s.sub!(/\D*(.+?)\D*$/, "\\1").gsub!(/\D+/, ".")
```
Comment (Bo98) [inline Library/Homebrew/dev-cmd/extract.rb:126]: `to_s` may return a copy so the `sub!` changes may be lost here

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/extract.rb:126]:
```suggestion
        version_string = version.to_s
        												.sub(/\D*(.+?)\D*$/, "\\1")
        												.gsub(/\D+/, ".")
```

File: Library/Homebrew/dev-cmd/extract.rb [hunk 2]
```diff
@@ -122,12 +122,15 @@ def run
...
+
+        # Remove any existing version suffixes, as a new one will be added later.
         name.sub!(/\b@(.*)\z\b/i, "")
         versioned_name = Formulary.class_s("#{name}@#{version}")
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/extract.rb:130]:
```suggestion
        versioned_name = Formulary.class_s("#{name}@#{version_string}")
```

File: Library/Homebrew/dev-cmd/extract.rb [hunk 3]
```diff
@@ -122,12 +122,15 @@ def run
...
         result.sub!("class #{class_name} < Formula", "class #{versioned_name} < Formula")
 
-        # Remove bottle blocks, they won't work.
+        # Remove bottle blocks, as they won't work.
         result.sub!(BOTTLE_BLOCK_REGEX, "")
 
         path = destination_tap.path/"Formula/#{name}@#{version.to_s.downcase}.rb"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/extract.rb:136]:
```suggestion
        path = destination_tap.path/"Formula/#{name}@#{version_string}.rb"
```

**Review by MikeMcQuaid — APPROVED** [review]
Looks good with suggestions applied, thanks @EricFromCanada!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @EricFromCanada!
