### PR TITLE
extract: ignore syntax errors during load

### LINKED ISSUE #11593: Error when using "brew extract": "Calling `cellar` in a bottle block is disabled"
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.0-45-gff48561
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff48561df1f23101e5f76648be7dafde5a1856f8
Last commit: 77 seconds ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 62c780c8e41726f9034652a79d2ca205386961f7
Core tap last commit: 22 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/will/.pyenv/shims/python3.9-config
  /Users/will/.pyenv/shims/python-config
  /Users/will/.pyenv/shims/python3-config

(note: I cannot remove this warning as I need pyenv installed on this system)
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use brew extract to extract and install a specific version of a package

### What happened (include all command output)?
```
% brew tap-new tmp/tmp
Initialized empty Git repository in /usr/local/Homebrew/Library/Taps/tmp/homebrew-tmp/.git/
[main (root-commit) 6c4d9e9] Create tmp/tmp tap
 ...
% brew extract --version=14.17.1 node tmp/tmp
==> Searching repository history
Error: node: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb:15
```
### What did you expect to happen?

I expected the formula to be extracted without errors.

### Step-by-step reproduction instructions (by running `brew` commands)

See above. I also tried doing a `brew update-reset` before running the above commands. This error is reproducible for every developer I have talked to who is running a script we use to set up our systems. As of last month or so the script was working fine so my assumption this is something that broke in Homebrew recently.

### PR DESCRIPTION
**Pull request by gromgit**
Deprecated syntax can happen when stepping back in time, so we shouldn't start by blocking everything that doesn't meet current Homebrew syntax standards. Closes #11593.

Before:
```bash
$ brew extract -d -v --version=14.15.1 node@14 gromgit/tmp
==> Searching repository history
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.17.3 from revision f90d04c against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
[...]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.15.4 from revision e2c833d against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
Error: node@14: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb:14

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:84:in `rescue in block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:77:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:383:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:180:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:496:in `from_contents'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:229:in `block in formula_at_revision'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:38:in `with_monkey_patch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:229:in `formula_at_revision'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:158:in `block in extract'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:138:in `loop'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/extract.rb:138:in `extract'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
After:
```bash
$ brew extract -d -v --version=14.15.1 node@14 gromgit/tmp
==> Searching repository history
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.17.3 from revision f90d04c against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
[...]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.15.4 from revision e2c833d against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.15.4 from revision 700c6c1 against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
[...]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.15.2 from revision 6102dd7 against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Writing formula for node from revision bccda0e to:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gromgit/homebrew-tmp/Formula/node@14.15.1.rb
```

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
w.r.t. writing a test for this, is it acceptable to `brew extract` a core formula as above, or should I create a new formula using deprecated syntax?

**Comment by carlocab** [comment]
Nice.

> w.r.t. writing a test for this, is it acceptable to `brew extract` a core formula as above, or should I create a new formula test fixture using deprecated syntax?

I think extracting any old core formula that currently errors out is fine.

**Comment by gromgit** [comment]
On second thought, better to do it "in-house", so I've changed `extract_spec.rb` accordingly.

Before:
```
$ brew tests
[...]
  2) brew extract when extracting a formula retrieves the deprecated-syntax version of formula
     Failure/Error:
       expect { brew "extract", "testball", target[:name], "--version=0.1" }
         .to output(/^#{path}$/).to_stdout
         .and not_to_output.to_stderr
         .and be_a_success

          expected block to output /^\/home\/linuxbrew\/.linuxbrew\/tmp\/homebrew-tests-20210718-372941-14v78m3\/prefix\/Library\/Taps\/homebrew\/homebrew-foo\/Formula\/testball@0.1.rb$/ to stdout, but output "==> Searching repository history\n"

       ...and:

             expected block to not output to stderr, but output "Error: testball: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.\nPlease report this issue to the
 homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:\n  /home/linuxbrew/.linuxbrew/tmp/homebrew-tests-20210718-372941-14v78m3/prefix/Library/Taps/homebrew/homebrew-core/Formula/testball.rb:10\n\n"

          ...and:

             expected #<Proc:0x0000000006cbb780@/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/dev-cmd/extract_spec.rb:74> to be a success
     # ./test/dev-cmd/extract_spec.rb:74:in `block (3 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/integration_test.rb:49:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:219:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:218:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
[...]
```
After:
```
(no extract_spec errors)
```

**Comment by gromgit** [comment]
Also, credit to @alebcay for pointing the way on this. Would be good to "deprecate" `brew yank` after this. :grinning:

**Comment by gromgit** [comment]
Sorry, forgot to rerun `brew style`, now I get this:
```
test/dev-cmd/extract_spec.rb:18:9: W: Useless assignment to variable - formula_file.
        formula_file = setup_test_formula "testball", bottle_block: <<~EOS
        ^^^^^^^^^^^^
```
Any suggestions on how to deal with this? I really do want to run `setup_test_formula` twice to replace the formula.

**Comment by alebcay** [comment]
I didn't even know that `ignore_errors: true` was an option until yesterday 😄 I'm not sure to what extent errors can be ignored with this set to true, but at least it seems to work for the particular error mentioned in the linked issue.

File: Library/Homebrew/test/dev-cmd/extract_spec.rb [hunk 1]
```diff
@@ -14,36 +14,49 @@
...
+        # Start with deprecated bottle syntax
+        setup_test_formula "testball", bottle_block: <<~EOS
+
+          bottle do
+            cellar :any
+          end
+        EOS
         system "git", "add", "--all"
         system "git", "commit", "-m", "testball 0.1"
+        # Remove it for next version
```
Comment (Rylan12) [inline Library/Homebrew/test/dev-cmd/extract_spec.rb:26]: Just a non-blocking suggestion to clarify the comment

```suggestion
        # Replace the contents with a valid formula for the next version
```

**Review by Rylan12 — APPROVED** [review]
Thanks, @gromgit and @alebcay!

**Review by Rylan12 — APPROVED** [review]

File: Library/Homebrew/test/dev-cmd/extract_spec.rb [hunk 2]
```diff
@@ -53,7 +66,17 @@
         .and not_to_output.to_stderr
         .and be_a_success
       expect(path).to exist
-      expect(Formulary.factory(path).version).to be == "0.2"
+      expect(Formulary.factory(path).version).to be == "0.3"
+    end
+
+    it "retrieves the deprecated-syntax version of formula", :integration_test do
```
Comment (MikeMcQuaid) [inline Library/Homebrew/test/dev-cmd/extract_spec.rb:72]: I think it'd be good to only have a single `integration_test` in this file (as they are super slow)

**Review by MikeMcQuaid — APPROVED** [review]
Great work!

File: Library/Homebrew/test/dev-cmd/extract_spec.rb (hunk 2 above)
Comment (gromgit) [reply Library/Homebrew/test/dev-cmd/extract_spec.rb:72]: Fish out of water here. Should I remove `:integration_test` from all except `"retrieves the specified version of formula"`? As I understand it, that's probably the most-used `extract` variant.

Comment (Rylan12) [reply Library/Homebrew/test/dev-cmd/extract_spec.rb:72]: I think it would be ideal if the one integration test covered as many of the cases individually as possible. So, maybe run `brew extract --version=0.1` so it tests both checking out a specific version _and_ ignoring the old syntax issues

Comment (gromgit) [reply Library/Homebrew/test/dev-cmd/extract_spec.rb:72]: Ah OK, thanks @Rylan12, will conflate as suggested.

While we're on the subject, what's the effective difference between a test case tagged with `:integration_test`, and one without?

Comment (Rylan12) [reply Library/Homebrew/test/dev-cmd/extract_spec.rb]: The `brew` method called in (most if not all) integration tests spins up a complete `brew` instance (i.e. by shelling out to `brew.rb`) instead of just calling the methods being tested directly. The downside is that this adds a lot of time. It's essentially like running `brew extract` (or whatever) directly from the command line instead of calling a method from within an already-up ruby instance.

I know that `:integration_test` needs to be specified in order to use the `brew` method, but it's possible that specifying it also causes some extra things to be done in preparation for the test that might also slow it down. Not 100% sure about that, though.

Comment (MikeMcQuaid) [reply Library/Homebrew/test/dev-cmd/extract_spec.rb]: Yup, I agree with everything @Rylan12 said! Sorry for being unclear here @gromgit.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again @gromgit!
