### PR TITLE
bump-cask-pr: fix duplicate PR checking with comma versions

### LINKED ISSUE #16271: `brew bump-cask-pr` is not correctly finding existing pull requests
### `brew doctor` output

```shell
-
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.22-4-g0ed0d9b
ORIGIN: git@github.com:Homebrew/brew.git
HEAD: 0ed0d9bafc033b1dd542e0751cbd54b5901d2513
Last commit: 26 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3fb6da5fc3a4f562b6c865b28ce311c12d2f8937
Core tap last commit: 9 minutes ago
Core tap branch: master
Core tap JSON: 12 Oct 05:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: code
HOMEBREW_GIT_EMAIL: email@bevankay.me
HOMEBREW_GIT_NAME: bevanjkay
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

We are seeing duplicate pull requests opened on `homebrew-cask-versions` and it seems that existing PRs are not being returned correctly during `brew bump-cask-pr` or `brew bump`.

### What happened (include all command output)?

`brew bump-cask-pr --no-browse --version 8u392-b08,openj9-0.41.0  semeru-jdk8-open`

Opens a PR where there is an existing PR (multiple).
https://github.com/Homebrew/homebrew-cask-versions/pulls?q=is%3Apr+semeru-jdk8-open+8u392-b08

### What did you expect to happen?

The command to return an error that an existing PR was found.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew bump-cask-pr --no-browse --version 8u392-b08,openj9-0.41.0  semeru-jdk8-open`
```

### PR DESCRIPTION
**Pull request by Bo98**
Fixes #16271

### CODE REVIEW

**Comment by apainintheneck** [comment]
Maybe I'm misunderstanding the fix here but it seems to still be missing the closed PRs for the example given in the issue.

```console
$ brew bump-cask-pr --dry-run --version 8u392-b08  semeru-jdk8-open
Error: These closed pull requests may be duplicates:
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18540
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18524
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18514
Duplicate PRs should not be opened. Use --force to override this error.
$ brew bump-cask-pr --dry-run --version 8u392-b08,openj9-0.41.0  semeru-jdk8-open
==> Downloading https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u392-b08_openj9-0.41.0/ibm-semeru-open-jdk_x64_mac_8u392b08_openj9-0.41.
Already downloaded: /Users/kevinrobell/Library/Caches/Homebrew/downloads/a73924189f4d419f4e7f48dd47ef7d130f34c3ac127d8cfbdd8b0f6f95a07499--ibm-semeru-open-jdk_x64_mac_8u392b08_openj9-0.41.0.pkg
==> replace /version\s+["']8u392\-b08,openj9\-0\.41\.0["']/m with "version \"8u392-b08,openj9-0.41.0\""
==> brew audit --cask --online semeru-jdk8-open
==> brew style --fix semeru-jdk8-open.rb
==> try to fork repository with GitHub API
==> git add /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/semeru-jdk8-open.rb
==> git checkout --no-track -b bump-semeru-jdk8-open-8u392-b08-openj9-0.41.0 origin/master
==> git commit --no-edit --verbose --message='semeru-jdk8-open 8u392-b08,openj9-0.41.0' -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Ca
==> git push --set-upstream FORK_URL bump-semeru-jdk8-open-8u392-b08-openj9-0.41.0:bump-semeru-jdk8-open-8u392-b08-openj9-0.41.0
==> git checkout --quiet -
==> create pull request with GitHub API (base branch: master)
```

File: Library/Homebrew/dev-cmd/bump-cask-pr.rb [hunk 1]
```diff
@@ -174,6 +170,15 @@ def bump_cask_pr
     GitHub.create_bump_pr(pr_info, args: args)
   end
 
+  sig { params(version: Cask::DSL::Version, cask: Cask::Cask).returns(Cask::DSL::Version) }
+  def shortened_version(version, cask:)
+    if version.before_comma == cask.version.before_comma
```
Comment (bevanjkay) [inline Library/Homebrew/dev-cmd/bump-cask-pr.rb:175]:
```suggestion
    if version.before_comma == cask.version
```

**Comment by Bo98** [comment]
> Maybe I'm misunderstanding the fix here but it seems to still be missing the closed PRs for the example given in the issue.

You will need to reset the state of your repo to before the PRs were merged to see the effect of the fix. That matches the state the duplicate PRs were created (otherwise they would be empty diffs).

File: Library/Homebrew/dev-cmd/bump-cask-pr.rb (hunk 1 above)
Comment (Bo98) [reply Library/Homebrew/dev-cmd/bump-cask-pr.rb:175]: That doesn't sound like it would ever be equal unless you are removing the comma in the bump.

The fix here was simply to share the existing logic used to title the commit/PR with the search functionality. They were previously not aligned so the search would of course not find the differently titled PR.

Comment (bevanjkay) [reply Library/Homebrew/dev-cmd/bump-cask-pr.rb:175]: I was seeing the same issue where it wasn't working now, but should moving forward as your comment below implies.

Comment (bevanjkay) [reply Library/Homebrew/dev-cmd/bump-cask-pr.rb:175]: Aren't we now returning the whole version as the shortened version of the `before_comma` matches for the cask and the bump? Shouldn't we always return the before_comma?

**Review by apainintheneck — APPROVED** [review]
LGTM!

I was able to reproduce the expected behavior after reseting the cask versions repo back a few days.

```console
$ brew bump-cask-pr --dry-run --version 8u392-b08,openj9-0.41.0  semeru-jdk8-open
Error: These closed pull requests may be duplicates:
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18540
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18524
semeru-jdk8-open 8u392-b08 https://github.com/Homebrew/homebrew-cask-versions/pull/18514
Duplicate PRs should not be opened. Use --force to override this error.
```

**Comment by apainintheneck** [comment]
> Your example would probably fail on a non-dry-run from an empty commit. Maybe that particular scenario should be made more explicit to make it also fail on dry runs.

That's another good point.

**Comment by MikeMcQuaid** [comment]
Great work @Bo98!
