### PR TITLE
cmd/info: only display keg info if tap matches

### LINKED ISSUE #19294: Brew info reports an incorrect formula URL from a tap
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 47ef1a3b0b742a78be35c016df6a0279d6035ebb
Last commit: 9 days ago
Branch: stable
Core tap JSON: 12 Feb 17:09 UTC
Core cask tap JSON: 12 Feb 17:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BUNDLE_USER_CACHE: /Users/jason.karns/.cache/bundler
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_UPDATE_TO_TAG: set
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.48.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: 16.2
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to find the url for a formula that i have installed in order to share it with colleagues.

The utility I wanted to share was `git-sync`, but the one I have installed is from a tap, not core. There is a conflicting formula on core titled `git-sync`.

### What happened (include all command output)?

I ran:

```
$ brew info git-sync
==> git-sync: stable 4.4.0 (bottled), HEAD
Clones a git repository and keeps it synchronized with the upstream
https://github.com/kubernetes/git-sync
Conflicts with:
  git-extras (because both install `git-sync` binaries)
Installed
/opt/homebrew/Cellar/git-sync/1.0.0 (7 files, 1.8MB) *
  Built from source on 2025-02-12 at 12:07:43
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/git-sync.rb
License: Apache-2.0
==> Dependencies
Build: go ✘
Required: coreutils ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 44 (30 days), 81 (90 days), 331 (365 days)
install-on-request: 44 (30 days), 82 (90 days), 331 (365 days)
build-error: 0 (30 days)
```

To get the formula URL. But I know this to be _not_ the formula that I have installed. Despite `brew info` reporting that it _is_ installed.

I eventually found the tap formula and was able to reproduce the bug whereby brew reports a formula as installed that is decidedly not installed.

### What did you expect to happen?

I expected `brew info git-sync` to perhaps include a note that a conflicting formula (from a tap) is already installed. But at the very least, I expected `brew info git-sync` to tell me that it was _not_ installed because the core formula is indeed not installed. In addition to it incorrectly stating it's installed, it even gives installation date/method that are from the _tap's_ formula, not the core formula.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Ensure it's not installed: `brew rm git-sync`
2. Inspect that brew says it's not installed: `brew info git-sync`
3. Install from the tap: `brew install jacobwgillespie/tap/git-sync`
4. See that brew now incorrectly reports git-sync installed: `brew info git-sync`
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #19294.

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]
Seems fine though do we want to handle the case where a tab tap is `nil` any differently?

File: Library/Homebrew/cmd/info.rb [hunk 1]
```diff
@@ -298,7 +298,7 @@ def info_formula(formula)
         kegs = [
           *heads.sort_by { |keg| -keg.tab.time.to_i },
           *versioned.sort_by(&:scheme_and_version),
-        ]
+        ].select { |keg| keg.tab.tap == formula.tap }
```
Comment (ZhongRuoyu) [inline Library/Homebrew/cmd/info.rb:301]: > Seems fine though do we want to handle the case where a tab tap is `nil` any differently?

Not sure when that'll happen, but I guess we can do something like this in case it ever does:

```suggestion
        ].select { |keg| (tap = keg.tab.tap).nil? || tap == formula.tap }
```

**Review by MikeMcQuaid — COMMENTED** [review]
I think this should probably be reverted. We don't have many(/any?) other commands where we require fully scoping formulae from taps like this. Instead it feels like we should use the actual formula from the tap if the opt-linked keg is from that tap.

Thoughts?

**Comment by jasonkarns** [comment]
@MikeMcQuaid I think agree. And that would also improve the cohesiveness issue I commented above. If I have (tap) formula X installed, and I say `brew info X`, it's most likely the case that I want to see the info for the formula that's actually installed.

The downside, then, is that `info` reports on different formula based on the state of my system. Which seems like it shouldn't be the case. (Info _seems_ like it should be effectively stateless, aside from including installation date details.) I'd also be concerned that switching to the tap formula would make it impossible (?) to see info on the shadowed/core formula? It's rarely my desire to see the core formula info when I have a tap that's shadowing it, but perhaps others have differing needs?

**Comment by jrobotham-square** [comment]
FYI We're seeing this change break some of our internal tooling that uses `brew info` under the hood to decide if a tool installed from one of our taps has already been installed.  (it's not using the fully qualified tap name when it runs `brew info`)

We should be able to work around it, but I suspect this is a breaking change that may affect many others.

**Comment by jasonkarns** [comment]
@jrobotham-square  I'm curious how your scripts have been detecting whether the tool that's installed is from core or your tap? (That was the bug this originally attempted to address.)

**Comment by Bo98** [comment]
For scripts you should be using `--json` as we don't guarantee stable output in the CLI output, though seems to follow the old behaviour and is thus now incosistent with this new behaviour.

A possible solution here is to:
* Keep this new behaviour for explicit `homebrew/core/<name>`
* Make `brew info <formula>` check for installed formulae and use those taps' formulae if it's installed (still loading the latest version from the tap itself for version info rather than the file in the install directory)
* Update `--json` to match the above

I think that covers all cases?

**Comment by jrobotham-square** [comment]
> I'm curious how your scripts have been detecting whether the tool that's installed is from core or your tap? (That was the bug this originally attempted to address.)

Short answer -  I don't think our internal tooling was actually doing this properly and we've probably just been lucky it hasn't bitten us earlier.   (it's some tooling our team has inherited)

> For scripts you should be using --json as we don't guarantee stable output in the CLI output, though seems to follow the old behaviour and is thus now incosistent with this new behaviour.

Yeah - makes sense - being coupled to the `brew info` console output isn't great.



FWIW Our script currently has a mix of fully qualified references and short names.   I think we've been relying on this bug for it to work up until now.
I think the best path forward for us is to always use the full reference.

**Comment by MikeMcQuaid** [comment]
> * Make `brew info <formula>` check for installed formulae and use those taps' formulae if it's installed (still loading the latest version from the tap itself for version info rather than the file in the install directory)
> * Update `--json` to match the above

This seems ideal for now. Reverting this until then in https://github.com/Homebrew/brew/pull/19324 until then.



> The recent trajectory of homebrew has been to promote more third party taps and less in core. (Removing build options and whatnot such that homebrew core is the 80% happy path, and pushing customization into taps.)

I disagree with this statement.

> While this PR fixes the core bug (brew-info providing false information), it doesn't improve the overall cohesive use of brew with the ever-growing-presence of 3rd party taps.

The only real "fix" here is something we've recommended for a long time but should consider adding more warnings and/or documentation for: using the same names as homebrew/core formulae in taps is simply a bad idea with a lot of rough edges, some of which we can improve, some we cannot.

**Comment by jasonkarns** [comment]
> > The recent trajectory of homebrew has been to promote more third party taps and less in core. (Removing build options and whatnot such that homebrew core is the 80% happy path, and pushing customization into taps.)
> 
> I disagree with this statement.

I should have couched this in more equivocating terms. I didn't mean to speak for homebrew team. This was the inference I took from a lot of gh issues being closed with, effectively, "make/use a tap". My only reason to mention this: it is my understanding that taps are still an expected and supported mechanism for distributing tools that don't receive broad community use. And that third party taps aren't being deprecated or discouraged as a feature. (If they are, then homebrew would have little incentive to ensure core commands and features continue to play well with taps.)

> using the same names as homebrew/core formulae in taps is simply a bad idea with a lot of rough edges, some of which we can improve, some we cannot.

Understood. Though it's worth mentioning that in this case, the git-sync formula in the tap was created over a year before the conflicting one was added to core. (git-sync added to https://github.com/jacobwgillespie/homebrew-tap in [June 2021](https://github.com/jacobwgillespie/homebrew-tap/commit/eeaaa9edc791dcf540774a3114fac7097f5ff242); kubernetes' git-sync added to core in [Aug 2022](https://github.com/Homebrew/homebrew-core/commit/f491eb97067f559c395f6f9128b2610c7f37fd38)). It doesn't make sense for third party taps to squat on formula names; so I'm not suggesting that the tap should or could have reserved "git-sync" for itself. However, I think it is worth recognizing that if name conflicts between core and taps cause such issues, we shouldn't assume that the core formula came first. In such cases as this, the tap formula existed first and was working fine. (Indeed, it was following the recommended practice of choosing a unique name that did _not_ conflict with core.) And then through no fault of and no change by the tap, suddenly it was in conflict with one from core and causing issues.

That implies that the addition of _new_ formula in core can effectively break existing workflows (brew commands and scripts using them) involving taps. That seems problematic.

**Comment by MikeMcQuaid** [comment]
> However, I think it is worth recognizing that if name conflicts between core and taps cause such issues, we shouldn't assume that the core formula came first.

We shouldn't but tap providers should consider if it's worthwhile continuing to maintain something that homebrew/core does with the same name, particularly given the previously stated issues.

> And then through no fault of and no change by the tap, suddenly it was in conflict with one from core and causing issues.

This is the nature of a relatively fast-moving rolling release package manager like Homebrew. See also: we deprecate things and these also require changes from taps to maintain identical end-user behaviour

> That implies that the addition of _new_ formula in core can effectively break existing workflows (brew commands and scripts using them) involving taps. That seems problematic.

Break? No, I don't think so. Cause suboptimal workflows/output? Yes. Given how taps and kegs are implemented: I don't really see any solution to this requiring a huge migration for _all_ taps when seems much worse than the status-quo.
