### PR TITLE
cli_parser: Dont raise FormulaUnavailableError

### LINKED ISSUE #5672: brew help install not printing help info
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to view the help information for the brew install command. 

# What happened (include command output)

The command appears to try and find a formula with the name help rather than printing the help information. When running `brew help <command>` using other commands the output works as expected. This began happening after running `brew update`

<details>
  <summary>Command output</summary>
  <pre>
  
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 2.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1920eecb7104301647af0bcf548144f2d85f4e27
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf83fb79eaa1a6726e9401bcd1c41841c5cf7df6
Core tap last commit: 29 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/______/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 10.0.1
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
CLT headers: 10.1.0.0.1.1539992718
$ brew help install
Error: No available formula with the name "help" 
  
  </pre>
</details>

# What you expected to happen

I expected the command to print the help information to the shell.

# Step-by-step reproduction instructions (by running `brew` commands)

brew help install

### PR DESCRIPTION
**Pull request by GauthamGoli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Fixes #5672

### CODE REVIEW

File: Library/Homebrew/cli_parser.rb [hunk 1]
```diff
@@ -162,6 +162,8 @@ def formula_options
             end
           end
         end
+      rescue FormulaUnavailableError
+        []
```
Comment (GauthamGoli) [inline Library/Homebrew/cli_parser.rb]: Just need to ignore this exception here. Found no alternative.

Comment (GauthamGoli) [reply Library/Homebrew/cli_parser.rb]: This can lead to some tricky buggy cases. 
What if the user passes multiple formulae names with a single invalid name ?
`ARGV.formulae` in that case would throw an exception and none of the formula options would get declared. 
@MikeMcQuaid  I think we could modify `ARGV.formulae` 's code to better handle this.

Comment (MikeMcQuaid) [reply Library/Homebrew/cli_parser.rb]: @GauthamGoli Yes, that seems like a good idea. As we discussed I think almost all of https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ARGV.rb would move to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cli_parser.rb instead.
