### PR TITLE
compilers: prefer gcc 5 on linux

### LINKED ISSUE #10170: ENV.cc and ENV.cxx is not correctly set when depending on gcc formula
## What you were trying to do (and why)

Trying to install a meson-based formula (https://github.com/Homebrew/linuxbrew-core/pull/21946) on linux with gcc@7.
The issues is also present on macOS.

## What happened (include command output)

ENV["CC"], ENV["CXX"], ENV.cc, ENV.cxx is incorrectly set in the install and test block.

The wrong compiler is defined.
- On Mac it is always set to clang/clang++, even if I define `depends_on "gcc@x"` in the formula.
- On Linux it is always set to the biggest gcc installed: if gcc@10 is installed on the system, ENV.cc is always gcc-10.

`meson` (but maybe other build tools) will pick up the wrong compiler.
Some tests blocks are run with the wrong compiler too, as we use ENV.cc a lot.

## What you expected to happen

ENV["CC"], ENV["CXX"], ENV.cc, ENV.cxx should point to the gcc formula defined in the formula.

## Note

This issue might not be a bug but a design choice. In that case I would like to change that behaviour.

### PR DESCRIPTION
**Pull request by iMichka**
Fixes #10170 by preferring gcc@5 on linux
This makes sure ENV.cc and ENV.cxx is correctly set:

If a formula does not explicitely depend on a brewed gcc,
ENV.cc is set to gcc-5 (system gcc-5 or brewed gcc-5) with this change,
even if other gcc versions are installed on the system.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Follow up PR from #10454 with just a part of the logic, to simplify the discussion.

**Comment by sjackman** [comment]
The tests need to be fixed up. The result of `CompilerSelector#compiler` is now expected to differ on Linux and macOS. Other than that, looks good to me! Thanks, Michka.

File: Library/Homebrew/test/compiler_selector_spec.rb [hunk 1]
```diff
@@ -42,9 +42,20 @@
...
 
-    it "returns gcc-6 if gcc formula offers gcc-6" do
+    it "returns gcc-6 (on mac) gcc-5 (on linux) if gcc formula offers gcc-6" do
       software_spec.fails_with(:clang)
       allow(Formulary).to receive(:factory).with("gcc").and_return(double(version: "6.0"))
+      if OS.mac?
+        expect(selector.compiler).to eq("gcc-6")
+      else
+        expect(selector.compiler).to eq("gcc-5")
+      end
```
Comment (sjackman) [inline Library/Homebrew/test/compiler_selector_spec.rb:52]:
```suggestion
      if OS.linux?
        expect(selector.compiler).to eq("gcc-5")
      else
        expect(selector.compiler).to eq("gcc-6")
      end
```
Both macOS and generic return `gcc-6`.

Comment (iMichka) [reply Library/Homebrew/test/compiler_selector_spec.rb]: Yes, it's a little bit confusing at first, but makes sense.

**Review by MikeMcQuaid — APPROVED** [review]
Looks good once CI is passing.

**Comment by iMichka** [comment]
Yes, I need to check the logic for linux, I am unsure why I am getting gcc-7 here.

**Comment by iMichka** [comment]
Found it, it's due to the fact that in the test we mock `non_apple_gcc_version` in the `before` step.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by sjackman** [comment]
Thank you, Michka!
