### PR TITLE
download_strategy: strip query string from basename

### LINKED ISSUE #13107: Cask android-studio on Apple Silicon Mac fails to install

### PR DESCRIPTION
**Pull request by Bo98**
Fixes Homebrew/homebrew-cask#121725.

### CODE REVIEW

File: Library/Homebrew/download_strategy.rb [hunk 1]
```diff
@@ -355,7 +355,7 @@ def parse_basename(url)
       return path.basename.to_s[/[^?&]+#{Regexp.escape(ext)}/] if ext
     end
 
-    File.basename(uri_path)
+    File.basename(uri_path)[/[^?&]+/]
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:358]:
```suggestion
    # strip query string
    File.basename(uri_path)[/[^?&]+/]
```

File: Library/Homebrew/download_strategy.rb [hunk 2]
```diff
@@ -355,7 +355,7 @@ def parse_basename(url)
       return path.basename.to_s[/[^?&]+#{Regexp.escape(ext)}/] if ext
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:355]: Might be nice to extract `[^?&]+` somewhere? It's used in three places.

**Comment by SMillerDev** [comment]
Would using the content disposition header fix this?

**Comment by Bo98** [comment]
We do - this is a fallback.
