### PR TITLE
global brewfile location defaults to user conf dir

### LINKED ISSUE #20628: Initial brew bundle dump --global ignores XDG_CONFIG_HOME
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 26.
We do not provide support for this pre-release version.

This is a Tier 2 configuration:
  https://docs.brew.sh/Support-Tiers#tier-2
You can report Tier 2 unrelated issues to Homebrew/* repositories!
Read the above document instead before opening any issues or PRs.
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9da27e1ac280ce720dfcbe6d5dac0dab2dcfc508
Last commit: 24 hours ago
Branch: stable
Core tap JSON: 03 Sep 08:03 UTC
Core cask tap JSON: 03 Sep 08:03 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: edit
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.0-arm64
CLT: 26.0.0.0.1.1755155385
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew bundle dump --global`

### What happened (include all command output)?

Successfully creates a new `$HOME/.Brewfile`.

### What did you expect to happen?

Creates `$XDG_CONFIG_HOME/homebrew/Brewfile` (defined in my `.zprofile`).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The issue (bug?) appears to be the following code requires a Brewfile already exists:

https://github.com/Homebrew/brew/blob/ab980dc3b7e3f17cae49466a1c110b6ac3abeb83/Library/Homebrew/bundle/brewfile.rb#L27-L33

Where I assume:

https://github.com/Homebrew/brew/blob/ab980dc3b7e3f17cae49466a1c110b6ac3abeb83/Library/Homebrew/bundle/brewfile.rb#L19

Comes from:

https://github.com/Homebrew/brew/blob/ab980dc3b7e3f17cae49466a1c110b6ac3abeb83/bin/brew#L152-L157

I'm not sure what the fix should be. If either environment variable was explicitly defined I'd expect it to be used or else follow the current behavior. Alternatively checking for the existence of `$HOMEBREW_USER_CONFIG_HOME` would be preferable to the Brewfile itself.
```

### PR DESCRIPTION
**Pull request by rrotter**
If dir $HOMEBREW_USER_CONFIG_HOME exists, place global Brewfile there,
unless ~/.Brewfile already exists AND $HOMEBREW_USER_CONFIG_HOME/Brewfile
does not.

This resolves #20628. This intentionally requires the user to have created `~/.config/homebrew`, and assumes that user intent is _not_ to use it for the Brewfile dump if it's not there. The reason being, is that I'm assuming we don't want to create `~/.homebrew/` for the user if it does not exist (when XDG_CONFIG_HOME is unset), and we should ideally treat HOMEBREW_USER_CONFIG_HOME the same no matter how it was populated.

Another alternative would be to semi-deprecate `~/.Brewfile`: use it if it's there, but never create it.

(See also https://github.com/Homebrew/homebrew-bundle/pull/1549, where I created this bug. There was some discussion about this issue there, and the current behavior was settled on as the option that changed existing behavior the least.)

Closes https://github.com/Homebrew/brew/pull/20658

### CODE REVIEW

**Comment by rrotter** [comment]
Added tests and rebased. The docs in `cmd/bundle.rb` seem sufficient as-is. They could be more precise, but the `--global` description is already 3 lines long.

File: Library/Homebrew/bundle/brewfile.rb [hunk 1]
```diff
@@ -24,7 +24,8 @@ def self.path(dash_writes_to_stdout: false, global: false, file: nil)
           else
             raise "'HOMEBREW_BUNDLE_FILE' cannot be specified with '--global'" if env_bundle_file.present?
 
-            if user_config_home && File.exist?("#{user_config_home}/Brewfile")
+            if user_config_home.present? && Dir.exist?(user_config_home) && \
```
Comment (MikeMcQuaid) [inline Library/Homebrew/bundle/brewfile.rb:32]:
```suggestion
            home_brewfile = Bundle.exchange_uid_if_needed! do
              "#{Dir.home}/.Brewfile"
            end
            user_config_home_brewfile = "#{user_config_home}/Brewfile"
            if user_config_home.present? && Dir.exist?(user_config_home) && \
               (File.exist?(user_config_home_brewfile) || !File.exist?(home_brewfile))
              user_config_home_brewfile
            else
              home_brewfile
            end
```

**Review by MikeMcQuaid — APPROVED** [review]
Had to make one tweak but should be good now, thanks again @rrotter!

**Review by krsjenswbp — COMMENTED** [review]
thanks
