### PR TITLE
utils/fork: handle termsig in safe_fork

### LINKED ISSUE #10661: Error: Status neither has `exitstatus` nor `termsig`.
**`brew config` output**

HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f39001507019da7747deba1099576bb1dbcabdad
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
all_proxy: socks5://127.0.0.1:1235
http_proxy: http://127.0.0.1:1234
https_proxy: http://127.0.0.1:1234
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

**`brew doctor` output**

❯ brew doctor
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

brew upgrade

**What happened (include all command output)?**

==> Upgrading rabbitmq 3.8.11 -> 3.8.12
==> Downloading https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.12/rabbitmq-server-generic-unix-3.8.12.tar.xz
Already downloaded: /Users/lidashuang/Library/Caches/Homebrew/downloads/04d6b767c386e6df0fd6e2308cddd690b997e283ebf39808f5ca7d42c6cf967b--rabbitmq-server-generic-unix-3.8.12.tar.xz
==> /usr/bin/unzip -qq -j /opt/homebrew/Cellar/rabbitmq/3.8.12/plugins/rabbitmq_management-3.8.12.ez rabbitmq_management-3.8.12/priv/www/cli/rabbitmqadmin
Error: Status neither has `exitstatus` nor `termsig`.
/opt/homebrew/Library/Homebrew/exceptions.rb:596:in `initialize'
/opt/homebrew/Library/Homebrew/utils/fork.rb:11:in `new'
/opt/homebrew/Library/Homebrew/utils/fork.rb:11:in `rewrite_child_error'
/opt/homebrew/Library/Homebrew/utils/fork.rb:90:in `block (3 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils.rb:423:in `ignore_interrupts'
/opt/homebrew/Library/Homebrew/utils/fork.rb:66:in `block (2 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/opt/homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/opt/homebrew/Library/Homebrew/formula_installer.rb:913:in `build'
/opt/homebrew/Library/Homebrew/formula_installer.rb:466:in `install'
/opt/homebrew/Library/Homebrew/upgrade.rb:102:in `upgrade_formula'
/opt/homebrew/Library/Homebrew/upgrade.rb:36:in `block in upgrade_formulae'
/opt/homebrew/Library/Homebrew/upgrade.rb:33:in `each'
/opt/homebrew/Library/Homebrew/upgrade.rb:33:in `upgrade_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:175:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'

**What did you expect to happen?**

==> Upgrading rabbitmq 3.8.11 -> 3.8.12

**Step-by-step reproduction instructions (by running `brew` commands)**

❯ brew upgrade

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

When `safe_fork` fails due to application termination rather than exist, `exitstatus` will be nil. Instead we should pass more of the object, as it has other methods like `termsig` for those cases. When you pass `ErrorDuringExecution` a `Process::Status` object, it will handle that and provide proper information on the failure, rather than choking because the passed exit status is nil.

It is unfortunately impossible to create a `Process::Status` object without using `Marshal.load`. There is no security risk though as this isn't user input.

Fixes #10661.

### CODE REVIEW

File: Library/Homebrew/utils/fork.rb [hunk 1]
```diff
@@ -51,7 +53,7 @@ def self.safe_fork
           # to rescue them further down.
           if e.is_a?(ErrorDuringExecution)
             error_hash["cmd"] = e.cmd
-            error_hash["status"] = e.status.exitstatus
+            error_hash["status"] = Base64.encode64(Marshal.dump(e.status))
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/fork.rb:56]:
```suggestion
            error_hash["status"] = e.status&.exitstatus
```

and instead never assume that this is non-`nil`.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
I'd rather we didn't use `Marshall` here, sorry 😭

File: Library/Homebrew/utils/fork.rb (hunk 1 above)
Comment (Bo98) [reply Library/Homebrew/utils/fork.rb:56]: Fair enough on Marshal, but the problem isn't `status` being nil. It's `exitstatus` being nil. If `exitstatus` is nil, then we need to use `termsig` (see `ErrorDuringExecution`). So will have to change around the API a bit.

Comment (MikeMcQuaid) [reply Library/Homebrew/utils/fork.rb:56]: Changing API around seems fine to me. As long as we assume non-zero status code I don't think preserving this is super critical (but I'll happily see a more comprehensive fix)

**Comment by Bo98** [comment]
This way should be the cleanest/least disruptive.

File: Library/Homebrew/utils/fork.rb [hunk 2]
```diff
@@ -51,7 +51,10 @@ def self.safe_fork
           # to rescue them further down.
           if e.is_a?(ErrorDuringExecution)
             error_hash["cmd"] = e.cmd
-            error_hash["status"] = e.status.exitstatus
+            error_hash["status"] = {
+              exitstatus: e.status.exitstatus,
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/fork.rb:55]: Can `.status` ever be `nil`?

File: Library/Homebrew/exceptions.rb [hunk 3]
```diff
@@ -582,16 +582,27 @@ def initialize(cmd, status:, output: nil, secrets: [])
...
     when Integer
       status
+    when Hash
+      status["exitstatus"]
     else
       status&.exitstatus
     end
 
+    termsig = case status
+    when Integer
```
Comment (MikeMcQuaid) [inline Library/Homebrew/exceptions.rb:592]:
```suggestion
    when Integer, NilClass
```

File: Library/Homebrew/exceptions.rb [hunk 4]
```diff
@@ -582,16 +582,27 @@ def initialize(cmd, status:, output: nil, secrets: [])
...
+      nil
+    when Hash
+      status["termsig"]
+    else
+      status&.termsig
```
Comment (MikeMcQuaid) [inline Library/Homebrew/exceptions.rb:597]:
```suggestion
      status.termsig
```

File: Library/Homebrew/exceptions.rb [hunk 5]
```diff
@@ -582,16 +582,27 @@ def initialize(cmd, status:, output: nil, secrets: [])
     exitstatus = case status
     when Integer
```
Comment (MikeMcQuaid) [inline Library/Homebrew/exceptions.rb:583]:
```suggestion
    when Integer, NilClass
```

File: Library/Homebrew/exceptions.rb [hunk 6]
```diff
@@ -582,16 +582,27 @@ def initialize(cmd, status:, output: nil, secrets: [])
...
       status
+    when Hash
+      status["exitstatus"]
     else
       status&.exitstatus
```
Comment (MikeMcQuaid) [inline Library/Homebrew/exceptions.rb:588]:
```suggestion
      status.exitstatus
```

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far, nice work on this cleanup!

File: Library/Homebrew/utils/fork.rb (hunk 2 above)
Comment (Bo98) [reply Library/Homebrew/utils/fork.rb:55]: I don't think so. Technically from an API standpoint it could be an integer (or now, a hash) though - it just never has come up as the only thing calling `ErrorDuringExecution` with an integer or hash is the `safe_fork` code itself.

File: Library/Homebrew/exceptions.rb (hunk 3 above)
Comment (Bo98) [reply Library/Homebrew/exceptions.rb:592]: Looking at this again, I think an early `raise` for a nil `status` seems appropriate.

File: Library/Homebrew/utils/fork.rb (hunk 2 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/utils/fork.rb]: I think being extra safe on this would make sense and not making any assumptions about the presence or type of `status`

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/utils/fork.rb (hunk 2 above)
Comment (Bo98) [reply Library/Homebrew/utils/fork.rb]: Yeah I've added a `Process::Status` type check now.
