### PR TITLE
download_strategy: fix mirrors not working

### LINKED ISSUE #15169: custom download strategy no longer works after commit fbf474a3fd107b636eb397b0aa247f7e03f2dc72
### `brew doctor` output

```shell
Your system is ready to brew.
```


### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.11-95-gd15f571
ORIGIN: https://github.com/Homebrew/brew
HEAD: d15f571eb6a994e7ca689721a54c5c6bff4219a0
Last commit: 28 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 29bc842d5cdffde2917bce61a1d4eb742cf6d987
Core tap last commit: 7 hours ago
Core tap branch: master
Core tap JSON: 06 Apr 17:27 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
```


### What were you trying to do (and why)?

I try to "brew install" a private repo, with a custom download strategy configured. 

The download strategy is taken from https://dev.to/jhot/homebrew-and-private-github-repositories-1dfh. 

The strategy used is GitHubPrivateRepositoryReleaseDownloadStrategy.

If I roll back the commit, referenced by fbf474a3fd107b636eb397b0aa247f7e03f2dc72, it works. 

### What happened (include all command output)?

```
❯ brew reinstall handelsblattgroup/tap/kundetools                                                                                                                                                                                                          
==> Fetching handelsblattgroup/tap/kundetools
==> Downloading https://github.com/handelsblattgroup/kunde2go-tools/releases/download/v3.0.0/kunde2go-tools_Darwin_x86_64.tar.gz
Error: Failed to download resource "kundetools"
Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.11-95-gd15f571\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/handelsblattgroup/kunde2go-tools/releases/download/v3.0.0/kunde2go-tools_Darwin_x86_64.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 404
server: GitHub.com
date: Fri, 07 Apr 2023 14:17:13 GMT
content-type: text/plain; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
content-length: 9
x-github-request-id: 9484:FD42:57B0878:591A642:643025E8
```

### What did you expect to happen?

❯ brew reinstall handelsblattgroup/tap/kundetools                                                                                                                                                                                                          
==> Fetching handelsblattgroup/tap/kundetools
==> Downloading https://github.com/handelsblattgroup/kunde2go-tools/releases/download/v3.0.0/kunde2go-tools_Darwin_x86_64.tar.gz
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/7e981c9e344d9fd5524ce1dc953191b2beceb8efba5c8283a53c1a0e4fbc4856--kunde2go-tools_Darwin_x86_64.tar.gz
==> Reinstalling handelsblattgroup/tap/kundetools
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kundetools/3.0.0: 6 files, 13.6MB, built in 4 seconds
==> Running `brew cleanup kundetools`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew up
brew reinstall handelsblattgroup/tap/kundetools
```

### PR DESCRIPTION
**Pull request by Bo98**
Fixes #15169.
Partially covers #15816.
Should cover #16078.

### CODE REVIEW

File: Library/Homebrew/download_strategy.rb [hunk 1]
```diff
@@ -488,7 +488,12 @@ def resolve_url_basename_time_file_size(url, timeout: nil)
     @resolved_info_cache ||= {}
     return @resolved_info_cache[url] if @resolved_info_cache.include?(url)
 
-    parsed_output = curl_headers(url.to_s, wanted_headers: ["content-disposition"], timeout: timeout)
+    begin
+      parsed_output = curl_headers(url.to_s, wanted_headers: ["content-disposition"], timeout: timeout)
+    rescue ErrorDuringExecution
+      return [url, parse_basename(url), nil, nil, false]
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:494]: Required by your change but just a drive-by thought that this is a _horrendous_ return signature that's dying to be a e.g. `Hash` or `Struct`.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense, thanks @Bo98.

File: Library/Homebrew/download_strategy.rb (hunk 1 above)
Comment (Bo98) [reply Library/Homebrew/download_strategy.rb:494]: Yeah, agreed. Takes me a moment to understand everytime I look at it.

It's also difficult to change without breaking custom download strategies, so probably worth doing with a larger refactor with better public API.
