### PR TITLE
info: print requirements

### LINKED ISSUE #775: Requirements Are Not Listed in `brew info` Output
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug report

`brew info mpv` does not mention the Python3 [dependency](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb#L17). Is this intentional? `brew deps mpv` works correctly.

```
~ $ brew info mpv
mpv: stable 0.19.0, HEAD
Free, open source, and cross-platform media player
https://mpv.io
/Users/user/.homebrew/Cellar/mpv/0.19.0 (349 files, 32.9M) *
  Built from source on 2016-08-21 at 20:06:29 with: --with-bundle --without-jpeg --without-little-cms2 --without-lua
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb
==> Dependencies
Build: pkg-config ✔
Required: libass ✔, ffmpeg ✔
Recommended: jpeg ✘, little-cms2 ✘, lua ✘, youtube-dl ✔
Optional: libarchive ✘, libcaca ✘, libdvdread ✘, libdvdnav ✘, libbluray ✘, libaacs ✘, vapoursynth ✘, uchardet ✘
==> Options
--with-bundle
	Enable compilation of the .app bundle.
--with-libaacs
	Build with libaacs support
--with-libarchive
	Build with libarchive support
--with-libbluray
	Build with libbluray support
--with-libcaca
	Build with libcaca support
--with-libdvdnav
	Build with libdvdnav support
--with-libdvdread
	Build with libdvdread support
--with-uchardet
	Build with uchardet support
--with-vapoursynth
	Build with vapoursynth support
--with-x11
	Build with x11 support
--without-jpeg
	Build without jpeg support
--without-little-cms2
	Build without little-cms2 support
--without-lua
	Build without lua support
--without-youtube-dl
	Build without youtube-dl support
--HEAD
	Install HEAD version
==> Caveats
zsh completion has been installed to:
  /Users/user/.homebrew/share/zsh/site-functions

.app bundles were installed.
Run `brew linkapps mpv` to symlink these to /Applications.
```

### PR DESCRIPTION
**Pull request by apjanke**
Picking up #770
Closes #775
Closes Homebrew/homebrew-core#4049

### CODE REVIEW

**Comment by apjanke** [comment]
One bummer: requirements like MinimumMacOS have specific version numbers attached to them, but they're not included in the output yet. How much do we care about this?

screen shot 2016-09-18 at 12 17 09 am

**Comment by apjanke** [comment]
I've added another commit with a `display_s` method in `Requirement`. (`display` for "thing to display to users"; `_s` for "string", which seems to be a conventional Ruby suffix.) Implemented it for the `:java`, `:ruby`, `:perl`, `language_module`, `minimum_macos` and `maximum_macos` requirements.

Output examples:

```
==> Requirements
Recommended: ruby = 1.8 ✔

==> Requirements
Required: ruby = 1.8 ✔, pygments.rb => :ruby ✘

==> Requirements
Optional: x11 ✔, perl = 5.5 ✔

==> Requirements
Required: lpeg => :lua ✘, luaexpat => :lua ✘, luafilesystem => :lua ✘

==> Requirements
Required: java = 1.7+ ✔
```

**Comment by apjanke** [comment]
Amended to improve readability of min/max OS X requirements.

```
==> Requirements
Required: MinimumMacOS = 10.7 ✔

==> Requirements
Required: MaximumMacOS = 10.6 ✘
```

**Comment by apjanke** [comment]
For testing, here's formulae to try out. They exercise the various requirements and their options.

```
phantomjs
valgrind
libstfl
sile
sbt
imagemagick
```

**Comment by zmwangx** [comment]
Nit: I think "optional requirements"

```
==> Requirements
Optional: x11
```

are very very weird...

**Comment by zmwangx** [comment]
Not sure we can do any better though.

**Comment by apjanke** [comment]
Hah. Yeah, that does sound weird. (Especially because that means the default is a "required requirement"?)  But I think that's a consequence of the terminology Homebrew has already chosen. Probably better to make this just a UI change that sticks with the established wording for now.

**Comment by zmwangx** [comment]
Got a better word than "requirements"?

**Comment by apjanke** [comment]
Been thinking about it a bit, and so far, no. Anything I've come up with is too technical-sounding.

Plus, changing that word now would mean a more extensive code change. Would rather just make this UI change as is, and figure out a better word later after discussion with everyone, if it matters.

**Comment by zmwangx** [comment]
> changing that word now would mean a more extensive code change

I was just thinking about a better word to stick in

```
==> _______
Required: MinimumMacOS = 10.7 ✔
Optional: x11
```

but can't think of anything either.

**Comment by Eitot** [comment]
Why the distinction between dependencies and requirements?

**Comment by apjanke** [comment]
That's a good question!

In Homebrew-speak, a Dependency is a dependency on another specific formula that can be installed by Homebrew; it's pretty simple. And a Requirement is a dependency on something that can be provided from outside Homebrew, or satisfied in multiple ways, like `:x11` being provided by XQuartz, or Perl being installed, or a minimum/maximum version of OS X or Xcode, or even another formula being installed with particular language options.

This is why zmwangx and I were talking about the wording for this stuff; It's not immediately clear. We're interested in suggestions on how to word this more intuitively or document it better.

**Comment by apjanke** [comment]
Put another way: Dependencies are things that `brew` can take care of automatically for you, and Requirements are things that you will (probably) have to deal with manually yourself.

File: Library/Homebrew/requirements/maximum_macos_requirement.rb [hunk 1]
```diff
@@ -16,4 +16,9 @@ def message
       versions newer than #{@version.pretty_name} due to an upstream incompatibility.
     EOS
   end
+
+  def display_s
+    "MaximumMacOS = #{@version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/maximum_macos_requirement.rb]: Maybe just `macOS < `?

File: Library/Homebrew/requirements/minimum_macos_requirement.rb [hunk 2]
```diff
@@ -13,4 +13,8 @@ def initialize(tags)
   def message
     "OS X #{@version.pretty_name} or newer is required."
   end
+
+  def display_s
+    "MinimumMacOS = #{@version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/minimum_macos_requirement.rb]: Maybe just `macOS > `?

File: Library/Homebrew/requirements/perl_requirement.rb [hunk 3]
```diff
@@ -25,4 +25,12 @@ def message
   def inspect
     "#<#{self.class.name}: #{name.inspect} #{tags.inspect} version=#{@version.inspect}>"
   end
+
+  def display_s
+    if @version
+      "#{name} = #{@version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/perl_requirement.rb]: `>` rather than `=`, no?

File: Library/Homebrew/requirements/ruby_requirement.rb [hunk 4]
```diff
@@ -25,4 +25,12 @@ def message
   def inspect
     "#<#{self.class.name}: #{name.inspect} #{tags.inspect} version=#{@version.inspect}>"
   end
+
+  def display_s
+    if @version
+      "#{name} = #{@version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/ruby_requirement.rb]: `>` rather than `=`, no?

File: Library/Homebrew/requirements/java_requirement.rb [hunk 5]
```diff
@@ -42,4 +42,12 @@ def message
   def inspect
     "#<#{self.class.name}: #{name.inspect} #{tags.inspect} version=#{@version.inspect}>"
   end
+
+  def display_s
+    if @version
+      "#{name} = #{@version}"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/java_requirement.rb]: `>` rather than `=`, no? Also this should probably differentiate between `1.7` and `1.7+`

File: Library/Homebrew/cmd/info.rb [hunk 6]
```diff
@@ -161,4 +169,11 @@ def decorate_dependencies(dependencies)
     end
     deps_status * ", "
   end
+
+  def decorate_requirements(requirements)
+    req_status = requirements.collect do |req|
+      req.satisfied? ? pretty_installed(req.display_s) : pretty_uninstalled(req.display_s)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/info.rb]: As over 80 characters I'd just make this an `if/else` and pull the `req.display_s` into a variable.

File: Library/Homebrew/cmd/info.rb [hunk 7]
```diff
@@ -161,4 +169,11 @@ def decorate_dependencies(dependencies)
...
+    end
+    req_status * ", "
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/info.rb]: I'd prefer `.join` here.

File: Library/Homebrew/cmd/info.rb [hunk 8]
```diff
@@ -146,6 +146,14 @@ def info_formula(f)
       end
     end
 
+    unless f.requirements.to_a.empty?
+      ohai "Requirements"
+      %w[build required recommended optional].map do |type|
+        reqs = f.requirements.select(&:"#{type}?")
+        puts "#{type.capitalize}: #{decorate_requirements(reqs)}" unless reqs.to_a.empty?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/info.rb]: `next if reqs.to_a.empty?`

File: Library/Homebrew/cmd/info.rb [hunk 9]
```diff
@@ -45,7 +45,7 @@ def print_info
       end
     else
       ARGV.named.each_with_index do |f, i|
-        puts unless i.zero?
+        puts unless i == 0
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/info.rb]: Rubocop disagrees.

File: Library/Homebrew/cmd/info.rb (hunk 6 above)
Comment (apjanke) [inline Library/Homebrew/cmd/info.rb]: Anything wrong with keeping the `?:` if just pulling `req.display_s` out to a variable gets it under 80 characters?

File: Library/Homebrew/requirements/maximum_macos_requirement.rb (hunk 1 above)
Comment (apjanke) [inline Library/Homebrew/requirements/maximum_macos_requirement.rb]: Done.

```
Required: macOS <= 10.6 ✘
```

File: Library/Homebrew/requirements/minimum_macos_requirement.rb (hunk 2 above)
Comment (apjanke) [inline Library/Homebrew/requirements/minimum_macos_requirement.rb]: Done. Using `>=` instead of `>`, since that matches the version specified in the requirement.

```
Required: macOS >= 10.7 ✔
```

File: Library/Homebrew/requirements/perl_requirement.rb (hunk 3 above)
Comment (apjanke) [inline Library/Homebrew/requirements/perl_requirement.rb]: Actually, `>=`, I think. Done.

File: Library/Homebrew/requirements/ruby_requirement.rb (hunk 4 above)
Comment (apjanke) [inline Library/Homebrew/requirements/ruby_requirement.rb]: Also `>=`, i think. Done.
```
Required: ruby >= 1.9 ✔
```

File: Library/Homebrew/requirements/java_requirement.rb (hunk 5 above)
Comment (apjanke) [inline Library/Homebrew/requirements/java_requirement.rb]: Would be `>=` or `=`, depending on whether the `+` is present. Done.

```
Required: java = 1.6 ✘

Required: java >= 1.6 ✔
```

File: Library/Homebrew/cmd/info.rb (hunk 9 above)
Comment (apjanke) [inline Library/Homebrew/cmd/info.rb]: Fixed.

File: Library/Homebrew/cmd/info.rb (hunk 8 above)
Comment (apjanke) [inline Library/Homebrew/cmd/info.rb]: Done.

File: Library/Homebrew/cmd/info.rb (hunk 7 above)
Comment (apjanke) [inline Library/Homebrew/cmd/info.rb]: Done.

**Comment by apjanke** [comment]
Addressed Mike's review. Now the displays look like this.

```
==> Requirements
Build: git ✔, xcode ✔
Required: macOS >= 10.7 ✔

==> Requirements
Required: macOS >= 10.6 ✔, macOS <= 10.11 ✔

==> Requirements
Recommended: ruby >= 1.8 ✔

==> Requirements
Required: lpeg => :lua ✘, luaexpat => :lua ✘, luafilesystem => :lua ✘

==> Requirements
Required: java >= 1.6 ✔

==> Requirements
Optional: x11 ✔, perl >= 5.5 ✔
```

File: Library/Homebrew/requirements/maximum_macos_requirement.rb (hunk 1 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/maximum_macos_requirement.rb]: Do you think `<=` is as understood as `<`? I wasn't sure but happy to defer to you here.

File: Library/Homebrew/requirements/minimum_macos_requirement.rb (hunk 2 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/minimum_macos_requirement.rb]: Do you think `<=` is as understood as `<`? I wasn't sure but happy to defer to you here.

File: Library/Homebrew/cmd/info.rb (hunk 6 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/info.rb]: Fine with that if under 80 chars

File: Library/Homebrew/requirements/minimum_macos_requirement.rb (hunk 2 above)
Comment (zmwangx) [inline Library/Homebrew/requirements/minimum_macos_requirement.rb]: Oh definitely, plus the fact that `>` (strictly greater than) is just wrong here.

**Comment by MikeMcQuaid** [comment]
> Required: lpeg => :lua ✘, luaexpat => :lua ✘, luafilesystem => :lua ✘

This is the only bit that still reads a bit weird. Maybe `lpeg (lua)` or even `lpeg (lua module)`?

File: Library/Homebrew/requirements/minimum_macos_requirement.rb (hunk 2 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/requirements/minimum_macos_requirement.rb]: @zmwangx Obviously I'd mean making the `>` value correct 😆

**Comment by apjanke** [comment]
Yeah, I think `lpeg (lua module)` reads better. Amended to do so.

Now displays as:

```
$ brew info sile
sile: stable 0.9.4, HEAD
...
==> Requirements
Required: lpeg (lua module) ✘, luaexpat (lua module) ✘, luafilesystem (lua module) ✘
```

**Comment by MikeMcQuaid** [comment]
👍 when 💚; a few style complaints currently.

**Comment by MikeMcQuaid** [comment]
Thanks @apjanke!
