### PR TITLE
Prevent users from uninstalling casks with dependents

### LINKED ISSUE #21067: Cask uninstaller doesn't check for dependent casks
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.0.1-43-g6b1d775
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6b1d775bddd9190f5e67d7178c11e9890eec352b
Last commit: 2 hours ago
Branch: main
Core tap HEAD: 85cb7f5f8fc4bb105aea71bc0d1dbbae410c1dce
Core tap last commit: 28 minutes ago
Core tap JSON: 13 Nov 15:47 UTC
Core cask tap HEAD: 08763d7af1116e82a8f035f6a79f51d102ec2771
Core cask tap last commit: 29 minutes ago
Core cask tap JSON: 13 Nov 15:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.V6V2wJ3XHq/org.xquartz:0
HOMEBREW_DOWNLOAD_CONCURRENCY: 1
HOMEBREW_EDITOR: nvim
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 17.0.0 build 1700
Git: 2.51.2 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.1-arm64
CLT: 26.1.0.0.1.1761104275
Xcode: 26.1.1
Rosetta 2: false
```

### What were you trying to do (and why)?

I was working on `dotnet-sdk@*` casks to allow installation of multiple SDKs at the same time. I modified `dotnet-sdk@*` so that these casks depend on main `dotnet-sdk`. Here's the patch for `dotnet-sdk@9`:

```diff
diff --git a/Casks/d/dotnet-sdk@8.rb b/Casks/d/dotnet-sdk@8.rb
index 91abad7b7c5..31f02e5b883 100644
--- a/Casks/d/dotnet-sdk@8.rb
+++ b/Casks/d/dotnet-sdk@8.rb
@@ -26,31 +26,11 @@ cask "dotnet-sdk@8" do
     end
   end
 
-  conflicts_with cask: [
-    "dotnet-runtime",
-    "dotnet-runtime@preview",
-    "dotnet-sdk",
-    "dotnet-sdk@9",
-    "dotnet-sdk@preview",
-  ]
-  depends_on macos: ">= :ventura"
+  depends_on cask: "dotnet-sdk"
 
   pkg "dotnet-sdk-#{version.csv.first}-osx-#{arch}.pkg"
-  binary "/usr/local/share/dotnet/dotnet"
-
-  uninstall pkgutil: [
-    "com.microsoft.dotnet.*#{version.major_minor}*#{arch}",
-    "com.microsoft.dotnet.sharedhost*#{arch}",
-    "com.microsoft.netstandard.pack.targeting.*",
-  ]
-
-  zap pkgutil: "com.microsoft.dotnet.*",
-      delete:  [
-        "/etc/paths.d/dotnet",
-        "/etc/paths.d/dotnet-cli-tools",
-      ],
-      trash:   [
-        "~/.dotnet",
-        "~/.nuget",
-      ]
+
+  uninstall pkgutil: "com.microsoft.dotnet.*#{version.major_minor}*#{arch}"
+
+  # No zap stanza required
 end
```

It works perfectly fine, `dotnet-sdk@8` uninstallation only removes this specific SDK and nothing else. However, nothing stops users from removing `dotnet-sdk` casks

### What happened (include all command output)?

I was testing how it handles uninstallation of `dotnet-sdk` if other SDKs are installed:
```
$ brew uninstall dotnet-sdk
==> Uninstalling Cask dotnet-sdk
==> Uninstalling packages with `sudo` (which may request your password)...
com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.10.0.0.component.osx.arm64
Password:
com.microsoft.dotnet.pack.targeting.10.0.0.component.osx.arm64
com.microsoft.dotnet.dev.10.0.100.component.osx.arm64
com.microsoft.dotnet.pack.apphost.10.0.0.component.osx.arm64
com.microsoft.dotnet.hostfxr.10.0.0.component.osx.arm64
com.microsoft.dotnet.sharedhost.component.osx.arm64
com.microsoft.netstandard.pack.targeting.2.1.0.component.osx.x64
==> Unlinking Binary '/opt/homebrew/bin/dotnet'
==> Purging files for version 10.0.100 of Cask dotnet-sdk
$ brew info dotnet-sdk@9
==> dotnet-sdk@9: 9.0.307
https://www.microsoft.com/net/core#macos
Installed
/opt/homebrew/Caskroom/dotnet-sdk@9/9.0.307 (209.7MB)
  Installed on 2025-11-14 at 16:05:04
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/d/dotnet-sdk@9.rb
==> Name
.NET SDK
==> Description
Developer platform
==> Dependencies
dotnet-sdk (cask)
==> Artifacts
dotnet-sdk-9.0.307-osx-arm64.pkg (Pkg)
==> Downloading https://formulae.brew.sh/api/cask/dotnet-sdk@9.json
==> Analytics
install: 143 (30 days), 143 (90 days), 143 (365 days)
$ dotnet --list-sdks
zsh: command not found: dotnet --list-sdks
```
The SDK is still present but not the binary

### What did you expect to happen?

I expected it to output an error, similar to what you see if you try to uninstall a formula that has casks dependents:
```
$ brew install --cask beutl
==> Downloading https://github.com/b-editor/beutl/releases/download/v1.0.7/Beutl.osx_arm64.app.zip
==> Downloading from https://release-assets.githubusercontent.com/github-production-release-asset/307580320/8d65aad3-e020-4ee9-81b2-f18210a2c5
####################################################################################################################################### 100.0%
==> Installing dependencies: ffmpeg@6
==> Fetching downloads for: ffmpeg@6
==> Downloading https://ghcr.io/v2/homebrew/core/ffmpeg/6/manifests/6.1.3_3
####################################################################################################################################### 100.0%
==> Fetching ffmpeg@6
==> Downloading https://ghcr.io/v2/homebrew/core/ffmpeg/6/blobs/sha256:6d3ff4c67c5c91eb0fbbcca3fada74cb41218f952d4e3339615f1f2ac5e90762
####################################################################################################################################### 100.0%
==> Installing ffmpeg@6
==> Pouring ffmpeg@6--6.1.3_3.arm64_tahoe.bottle.tar.gz
🍺  /opt/homebrew/Cellar/ffmpeg@6/6.1.3_3: 285 files, 52.3MB
==> Installing Cask beutl
==> Moving App 'Beutl.app' to '/Applications/Beutl.app'
🍺  beutl was successfully installed!
$ brew uninstall ffmpeg@6
Error: Refusing to uninstall /opt/homebrew/Cellar/ffmpeg@6/6.1.3_3
because it is required by beutl, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies ffmpeg@6
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Apply `dotnet-sdk@8` patch and remove `conflicts_with "dotnet-sdk@8"` from `dotnet-sdk`
$ brew install dotnet-sdk@8
# This should install both `dotnet-sdk` and `dotnet-sdk@8`
$ brew uninstall dotnet-sdk
$ brew info dotnet-sdk@8
# `dotnet-sdk@8` is installed, you can check it by running `ls /usr/local/share/dotnet/sdk`
$ dotnet
zsh: command not found: dotnet
```

### PR DESCRIPTION
**Pull request by botantony**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----
Closes #21067

### CODE REVIEW

File: Library/Homebrew/cask/uninstall.rb [hunk 1]
```diff
@@ -19,5 +21,24 @@ def self.uninstall_casks(*casks, binaries: false, force: false, verbose: false)
...
+        d = CaskDependent.new(dependent)
+        dependencies = d.recursive_requirements.filter_map { |r| r.cask if r.is_a?(CaskDependent::Requirement) }
+        next unless dependencies.intersect?(requireds)
+
+        dependents << dependent.token
+      end
+
+      return if dependents.empty?
+
+      DependentsMessage.new(requireds, dependents, named_args:).output
```
Comment (Rylan12) [inline Library/Homebrew/cask/uninstall.rb]: Can `requireds` be filtered down to only the casks that actually have installed dependents? Looks like right now it's all casks that were requested to be uninstalled, if I'm reading correctly
