### PR TITLE
Warn when changing branch on update

### LINKED ISSUE #877: Warn when auto-changing branch?
Homebrew automatically (sometimes unexpectedly) doing some git stuff when updating seems to come up in the issue tracker pretty regularly. In #737, @MikeMcQuaid [mentions]() that this is going to be improved at some point. In the meantime, though, I wonder if it would be worth emitting a warning explaining that Homebrew is checking out `master`, and explaining that setting `HOMEBREW_DEVELOPER` will prevent this behaviour?

Is this a good idea?

### PR DESCRIPTION
**Pull request by penman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

See #877 for motivation behind this.

Fixes #877.

### CODE REVIEW

File: Library/Homebrew/cmd/update.sh [hunk 1]
```diff
@@ -242,6 +242,15 @@ EOS
   INITIAL_BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null)"
   if [[ "$INITIAL_BRANCH" != "$UPSTREAM_BRANCH" && -n "$INITIAL_BRANCH" ]]
   then
+
+    if [[ -z "$HOMEBREW_DEVELOPER" ]]
+    then
+      opoo <<EOS
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/update.sh]: Let's just go for: `echo "Checking out $UPSTREAM_BRANCH in $DIR..."`

and, either here or a sensible place below, do:
```bash
  echo "To checkout $INITIAL_BRANCH in $DIR run:"
  echo "  'cd $DIR && git checkout $INITIAL_BRANCH"
```

 Want to avoid recommending setting `HOMEBREW_DEVELOPER` for now; I've got a solution incoming for this problem.

**Comment by penman** [comment]
Updated the message based on @MikeMcQuaid's feedback.

I've left the Bash `opoo` definition, even though it's no longer used, because it'll probably be useful at some point.

**Comment by penman** [comment]
Using a `Pathname` seems like it might be a mistake. I'll change it back to a string tomorrow and then we won't have to worry as much about errors in distant parts of the codebase.

File: Library/Homebrew/brew.sh [hunk 2]
```diff
@@ -1,20 +1,35 @@
...
+  highlight 33 Warning >&2 # yellow
+  echo -n ": " >&2
+  o "$@" >&2
+}
+
+onoe() {
+  highlight 31 Error >&2 # red
+  echo -n ": " >&2
+  o "$@" >&2
+}
```
Comment (MikeMcQuaid) [inline Library/Homebrew/brew.sh]: I reckone you can revert all this stuff for now.

**Comment by MikeMcQuaid** [comment]
Some stuff to strip out but otherwise 👍

File: Library/Homebrew/cmd/update.sh [hunk 3]
```diff
@@ -242,6 +242,14 @@ EOS
   INITIAL_BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null)"
   if [[ "$INITIAL_BRANCH" != "$UPSTREAM_BRANCH" && -n "$INITIAL_BRANCH" ]]
   then
+
+    if [[ -z "$HOMEBREW_DEVELOPER" ]]
+    then
+      echo "Checking out $UPSTREAM_BRANCH in $DIR..."
+      echo "To checkout $INITIAL_BRANCH in $DIR run:"
+      echo "  'cd $DIR && git checkout $INITIAL_BRANCH"
```
Comment (zmwangx) [inline Library/Homebrew/cmd/update.sh]: To be pedantic, you need to quote `$DIR` and `$INITIAL_BRANCH` for robustness:

```bash
echo "  cd $(printf %q "$DIR") && git checkout $(printf %q "$INITIAL_BRANCH")"
```

But I guess I'm just being pedantic.

P.S. In Zsh the completely robust version (with even nicer output than the Bash version above) would be

```zsh
cd "${(qq)DIR}" && git checkout "${(qq)INITIAL_BRANCH}"
```

This is one of the things I dislike about Bash: wimpy parameter expansion.

Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/update.sh]: Not quoting in `echo` is fine, I think, but thanks for the review anyway @zmwangx; definitely would rather have pedantry than the other extreme!

**Comment by MikeMcQuaid** [comment]
Thanks again @penman!
