### PR TITLE
Fix #6533 - Add support for zsh ZDOTDIR

### LINKED ISSUE #6533: bundle dump fails when ZDOTDIR defined
```
 I  (master)% b bundle dump --force
Error: No such file or directory @ rb_sysopen - /Users/davidosomething/.zshrc

 I  (master)% touch ~/.zshrc

 I  (master)% b bundle dump --force

(success)
```

When `$ZDOTDIR` is defined in `.zshenv`, allowing user to place `.zshrc` in a different directory from `.zshenv`, `brew bundle dump` fails. The ruby syscall always tries to open `.zshrc` from `$HOME`. Creating a temporary `.zshrc` in `$HOME` is a workaround.

### PR DESCRIPTION
**Pull request by davidosomething**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

See #6533 for context

Added one test spec where I set the ZDOTDIR env var
I'm not a ruby developer so please review prudently!

### CODE REVIEW

File: Library/Homebrew/utils/shell.rb [hunk 1]
```diff
@@ -39,6 +39,7 @@ def export_value(key, value, shell = preferred)
 
     # return the shell profile file based on user's preferred shell
     def profile
+      return ENV.fetch("ZDOTDIR", "~") + "/.zshrc" if preferred.eql? "zsh"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/shell.rb]:
```suggestion
      return "#{ENV["ZDOTDIR"]}/.zshrc" if preferred == "zsh" && ENV["ZDOTDIR"].present?
      
```

File: Library/Homebrew/test/utils/shell_spec.rb [hunk 2]
```diff
@@ -19,8 +19,15 @@
...
 
+    it "returns /tmp/.zshrc for Zsh if ZDOTDIR is /tmp" do
+      ENV["SHELL"] = "/bin/zsh"
+      ENV["ZDOTDIR"] = "/tmp"
+      expect(subject.profile).to eq("/tmp/.zshrc")
+    end
+
     it "returns ~/.zshrc for Zsh" do
       ENV["SHELL"] = "/bin/zsh"
+      ENV["ZDOTDIR"] = nil
```
Comment (MikeMcQuaid) [inline Library/Homebrew/test/utils/shell_spec.rb]:
```suggestion
```

**Comment by MikeMcQuaid** [comment]
Thanks for the PR @davidosomething! A few suggestions (which may fix the tests but if not I'll make more).

File: Library/Homebrew/test/utils/shell_spec.rb (hunk 2 above)
Comment (davidosomething) [reply Library/Homebrew/test/utils/shell_spec.rb]: For some reason this test, without unsetting ZDOTDIR, worked on my machine where ZDOTDIR is set in zsh. I expected it to fail when run without edits.

Does `brew test` run the tests in an isolated bash shell or something?

Comment (MikeMcQuaid) [reply Library/Homebrew/test/utils/shell_spec.rb]: > Does `brew test` run the tests in an isolated bash shell or something?

Yes.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @davidosomething!
