### PR TITLE
prune: preserve some directories

### LINKED ISSUE #4926: brew prune remove the folder generated by brew upgrade which they are empty
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) : 

After i do brew upgrade , always i do brew cleanup and brew prune
but when i do brew prune it delete 4 folders : 
/usr/local/share/man/man8
/usr/local/share/man/man4
/usr/local/share/man/man2
/usr/local/share/locale

and they get generated again after i run brew upgrade ,
brew upgrade generate the folders and they are empty evreytime i run it , and brew prune delete them again

- What happened (include command output)

Pruned 0 symbolic links and 4 directories from /usr/local

- What you expected to happen

brew upgrade dont generate the folders if they are empty , or brew prune dont remove folder from /usr/local

- Step-by-step reproduction instructions (by running `brew` commands)

brew upgrade
( nothing to show )

brew prune
Pruned 0 symbolic links and 4 directories from /usr/local

brew config : 
HOMEBREW_VERSION: 1.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d639559c4de48faad79d3ecb1ec84dc851ea66f2
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1f61565d16a9ae26ca506cd9468e6ba482ff9e3
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: N/A

brew doctor : 
Your system is ready to brew.

### PR DESCRIPTION
**Pull request by alebcay**
Some directories, while empty, are created in brew upgrade and
should be kept.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #4926.

### CODE REVIEW

File: Library/Homebrew/keg.rb [hunk 1]
```diff
@@ -81,23 +81,24 @@ def to_s
       opt
     ]).map { |dir| HOMEBREW_PREFIX/dir }
   ).freeze
+  PRESERVED_DIRECTORIES = (%w[
```
Comment (MikeMcQuaid) [inline Library/Homebrew/keg.rb]: Do we need an extra variable here? Can the `MUST_BE_WRITABLE_DIRECTORIES` or `MUST_EXIST_DIRECTORIES` be used instead?

Comment (alebcay) [reply Library/Homebrew/keg.rb]: At least on my machine, `MUST_BE_WRITABLE_DIRECTORIES` includes `lib/python3.7` and company. If we're okay with preserving those too, we can definitely just use that. `MUST_EXIST_DIRECTORIES` only has `bin etc include lib sbin share var Frameworks opt`; would the subdirectories that we're trying to preserve (e.g. `share/man/man[1-8]`) be kept?

Comment (MikeMcQuaid) [reply Library/Homebrew/keg.rb]: @alebcay Let's use `MUST_BE_WRITABLE_DIRECTORIES` 👍. Apologies for earlier confusion.

**Comment by MikeMcQuaid** [comment]
Thanks @alebcay!

**Comment by xhaythemx** [comment]
Even though the pr is merged the problem is still
