### PR TITLE
cmd/update: stop Git's fsmonitor when needed

### LINKED ISSUE #13521: brew compatibility with git 2.37
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43d4a715d56a63af23ecdf491db94032125683e0
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.5gdXZIrfnK/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gnupg
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Seems like after `brew upgrade` the file: /opt/homebrew/var/homebrew/locks/update remains and until I delete it manually I get:

### What happened (include all command output)?

Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.

### What did you expect to happen?

well, `brew upgrade` should remove the file after it's done?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# append "fsmonitor = true" in [core] of ~/.gitconfig
brew upgrade
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Git's fsmonitor daemon will prevent our update lock file from being
released if it is running before a `brew update`.

Let's fix that by stopping it whenever necessary so our update lock is
released upon completion.

Fixes #13521.

### CODE REVIEW

File: Library/Homebrew/cmd/update.sh [hunk 1]
```diff
@@ -556,6 +556,12 @@ EOS
     [[ -d "${DIR}/.git" ]] || continue
     cd "${DIR}" || continue
 
+    # Git's fsmonitor daemon will not release our lock unless we stop it.
+    if git fsmonitor--daemon status &>/dev/null
+    then
+      git fsmonitor--daemon stop 2>/dev/null
```
Comment (bayandin) [inline Library/Homebrew/cmd/update.sh:562]: Will it stop the daemon globally or only for the repo?

Alternatively, we can set `core.fsmonitor = false` in `.git/config` (I suppose this should exclude repo from being monitored).

Comment (carlocab) [reply Library/Homebrew/cmd/update.sh:562]: > Will it stop the daemon globally or only for the repo?

Only for the repo, so we need to do it after `cd`ing to it.

> Alternatively, we can set `core.fsmonitor = false` in `.git/config` (I suppose this should exclude the repo from monitored ones).

Yes, but there seem to be some benefits from running the daemon, so it would be nice to keep it going if possible.

**Comment by timtyrrell** [comment]
In case I can provide something of value, I was having this issue over two weeks ago after updating to Git 2.37 and enabling `core.fsmonitor`. I can only provide the messages that I shared with colleagues back when I had the problem. When trying to perform a `brew update` I would get the following message and it appeared to hang indefinitely until I disabled fsmonitor and rebooted.

```
“Error: Another active Homebrew update process is already in progress.”
```

This feels like a remnant, when I run `brew reinstall neovim` I see the following but it does not prevent the reinstall, the key part being `cp: /Users/ttyrrell/Library/Caches/Homebrew/neovim--git/.git/./fsmonitor--daemon.ipc is a socket (not copied).`

```
❯ brew reinstall neovim
==> Downloading https://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/767bbf65a5cd06d3b39aa08f8d1f811a2f5803df0b94552a2b595242a461ec9c--libvterm-0.1.4.tar.gz
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/ttyrrell/Library/Caches/Homebrew/neovim--git
From https://github.com/neovim/neovim
   871ff8d62..1a2560c2d  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 13 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 1a2560c2d test(old): set 'display' to an empty string (#19450)
==> Reinstalling neovim
cp: /Users/ttyrrell/Library/Caches/Homebrew/neovim--git/.git/./fsmonitor--daemon.ipc is a socket (not copied).
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovim-20220720-18907-irgiv6/deps-build
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovim-20220720-18907-irgiv6/deps-build
==> make install PREFIX=/private/tmp/neovim-20220720-18907-irgiv6/deps-build LDFLAGS=-static
==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib
==> cmake --build build
==> cmake --install build
🍺  /opt/homebrew/Cellar/neovim/HEAD-1a2560c_1: 1,610 files, 22.7MB, built in 54 seconds
==> Running `brew cleanup neovim`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by timtyrrell** [comment]
@carlocab  I did have it configured globally, yes. Should I try to reproduce the issue locally before applying the patch? Also, can you link to patching instructions? I haven't done it before with this project.

**Comment by Bo98** [comment]
> This feels like a remnant, when I run `brew reinstall neovim` I see the following but it does not prevent the reinstall, the key part being `cp: /Users/ttyrrell/Library/Caches/Homebrew/neovim--git/.git/./fsmonitor--daemon.ipc is a socket (not copied).`

This makes sense. I wonder if it's worth us disabling `fsmonitor` for resources like that we download. Or if there is a benefit of keeping it enabled: handle that file better.

This is however a separate issue.

---

For the `brew update` issue I reckon the first-time startup of the fsmonitor daemon process is inheriting the file lock we've created. We could fix this by adding an explicit unlock, find some way to set CLOEXEC on the FD, or pipe close the lock FD when executing any external commands.

**Comment by carlocab** [comment]
> Should I try to reproduce the issue locally before applying the patch?

Yes, please.

> Also, can you link to patching instructions? I haven't done it before with this project.

Check your current `HOMEBREW_VERSION` given by `brew config`, you'll need it later.

If you have `gh` installed:
```
cd "$(brew --repository)"
gh pr checkout 13586
```
If you don't:
```
cd "$(brew --repository)"
git fetch origin pull/13586/head:git-fsmonitor
git checkout git-fsmonitor
```
and then see if you can still reproduce the issue.

When you're done, don't forget to do
```
git -C "$(brew --repository)" checkout master
```
or
```
git -C "$(brew --repository)" checkout 3.5.5
```
depending on whether you're on the `master` branch or on a tagged release of `brew`. The `HOMEBREW_VERSION` entry will look something like `3.5.5-19-g8a2efb1` if you were on the `master` branch, and just `3.5.5` if you were on a tagged release.

**Comment by timtyrrell** [comment]
@carlocab I will reenable fsmonitor now. Bad timing, I am about to get away from my computer for a few days but will report back and try the patch if I see the issue 🤞 

```
❯ brew --version
Homebrew 3.5.5
Homebrew/homebrew-core (git revision 6074e6e7f64; last commit 2022-07-20)
Homebrew/homebrew-cask (git revision 88febe2098; last commit 2022-07-20)
```

**Comment by carlocab** [comment]
> I wonder if it's worth us disabling `fsmonitor` for resources like that we download. Or if there is a benefit of keeping it enabled: handle that file better.

It makes sense given how we use these resources, yes.

File: Library/Homebrew/cmd/update.sh (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/update.sh:562]: Given we're hiding the output anyway: wondering if we should just unconditionally run `git fsmonitor--daemon stop` as it's not any slower than running `git fsmonitor--daemon status`?

Comment (carlocab) [reply Library/Homebrew/cmd/update.sh:562]: Yes, running `stop` unconditionally is indeed much better.

**Comment by timtyrrell** [comment]
Got back from my vacation. I do not have the patch installed. Zero issues updating brew yesterday, today I am. FYI, that is only an alias: `alias brew-outdated="brew update && echo 'OUTDATED:' && brew outdated"`

```
❯ brew reinstall neovim
==> Downloading https://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/767bbf65a5cd06d3b39aa08f8d1f811a2f5803df0b94552a2b595242a461ec9c--libvterm-0.1.4.tar.gz
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/ttyrrell/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/ttyrrell/Library/Caches/Homebrew/neovim--git
From https://github.com/neovim/neovim
   1a2560c2d..2a9c9371b  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 60 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 2a9c9371b vim-patch:9.0.0073: too many files recognized as bsdl (#19504)
==> Reinstalling neovim
cp: /Users/ttyrrell/Library/Caches/Homebrew/neovim--git/.git/./fsmonitor--daemon.ipc is a socket (not copied).
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovim-20220726-11407-xgqh68/deps-build
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovim-20220726-11407-xgqh68/deps-build
==> make install PREFIX=/private/tmp/neovim-20220726-11407-xgqh68/deps-build LDFLAGS=-static
==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib
==> cmake --build build
==> cmake --install build
🍺  /opt/homebrew/Cellar/neovim/HEAD-2a9c937_1: 1,617 files, 22.6MB, built in 50 seconds
==> Running `brew cleanup neovim`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
❯ gst
## tt/remove-jasmine...origin/tt/remove-jasmine
❯ nn
❯ brew-outdated
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
❯ brew-outdated
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
```

```
❯ brew --version
Homebrew 3.5.6
Homebrew/homebrew-core (git revision 4a3e893b8a9; last commit 2022-07-25)
Homebrew/homebrew-cask (git revision 56a3f3d1fb; last commit 2022-07-25)
```

I will install the patch.

**Comment by timtyrrell** [comment]
Patch installed, still have the issue, I will reboot. Also:

```
❯ git --no-pager config --global --get-all core.fsmonitor
true
```

**Comment by timtyrrell** [comment]
I have the issue again, after a reboot this morning but it seems like my homebrew branch in `/opt/homebrew` keeps switching to `stable` so I can't get a good read on it :/ 
I should have output the branch name in the logs but it was in my shell prompt so I didn't think of it

<details>
<summary>today's log</summary>

``` sh
❯ gh pr checkout 13586
Switched to branch 'git-fsmonitor'
❯ ps -p $(lsof -t +d $(brew --prefix)/var/homebrew/locks)
ps: option requires an argument -- p
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
❯ brew update
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/cask-fonts).
==> New Formulae
cargo-depgraph                                          chain-bench                                             dura                                                    page                                                    tlsx
==> New Casks
polypad                                                                                       shop-different                                                                                workman
==> Outdated Formulae
harfbuzz                                       jpeg-xl                                        libtiff                                        node                                           redis                                          webp

You have 6 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
❯ gh pr checkout 13586
Switched to branch 'git-fsmonitor'
❯ brew outdated
harfbuzz (4.4.1) < 5.0.1
jpeg-xl (0.6.1) < 0.6.1_1
libtiff (4.4.0) < 4.4.0_1
node (18.6.0) < 18.7.0
redis (7.0.3) < 7.0.4
webp (1.2.3) < 1.2.3_1
❯ brew upgrade
==> Upgrading 6 outdated packages:
libtiff 4.4.0 -> 4.4.0_1
redis 7.0.3 -> 7.0.4
harfbuzz 4.4.1 -> 5.0.1
webp 1.2.3 -> 1.2.3_1
jpeg-xl 0.6.1 -> 0.6.1_1
node 18.6.0 -> 18.7.0
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg-turbo/manifests/2.1.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg-turbo/blobs/sha256:0fe5fd23465784fe56f97c29589a72eacc21f8fb75f8c84e69da724637aee262
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:0fe5fd23465784fe56f97c29589a72eacc21f8fb75f8c84e69da724637aee262?se=2022-07-28T13%3A40%3A00Z&sig=EpN25QUEX2fqxJu8DKUlw9PF%2FlZngVXm5hsebO10jkU%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.4.0_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/blobs/sha256:15921731edaae9d13ca572f3e2b58e07ca6f90429cc5f1bdff56aaf061abe2e2
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:15921731edaae9d13ca572f3e2b58e07ca6f90429cc5f1bdff56aaf061abe2e2?se=2022-07-28T13%3A40%3A00Z&sig=9tAAje%2Bc0dN7Wrq3Za8Eeq%2BlXOsA5uF9yxOcDvVPk1Q%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/redis/manifests/7.0.4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:5fd4a4cdd769fdebc82dc5ea1b06edb2464039b38c09355f29e8e70804eb8477
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5fd4a4cdd769fdebc82dc5ea1b06edb2464039b38c09355f29e8e70804eb8477?se=2022-07-28T13%3A40%3A00Z&sig=ZmtqKPpmdrE4LAX6o5Mgt5f%2FjXC5%2FAn4QQ7cvpZDw4Q%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/harfbuzz/manifests/5.0.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/harfbuzz/blobs/sha256:a0dca1f19cf2006cd24181af5d97959d41aca06c4bdf165c754cc5d27c64eb53
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a0dca1f19cf2006cd24181af5d97959d41aca06c4bdf165c754cc5d27c64eb53?se=2022-07-28T13%3A40%3A00Z&sig=KbZqCfWpqSGqFSXABflaCBIXIFhYOX3MsS0wF70KrFI%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/webp/manifests/1.2.3_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/webp/blobs/sha256:c421bfcdd0b6e294554c8db1361880f1c2336421f33d7429b5e2882635982599
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c421bfcdd0b6e294554c8db1361880f1c2336421f33d7429b5e2882635982599?se=2022-07-28T13%3A40%3A00Z&sig=fIOA35G5m9YVyiWuuov1ehgt8rJDlQBZkhBZPrKzq0M%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg-xl/manifests/0.6.1_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/jpeg-xl/blobs/sha256:a603bfaffbd444d11e882f8d72beaf3833cbf91473c4bb8c964c00bd94b07d65
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a603bfaffbd444d11e882f8d72beaf3833cbf91473c4bb8c964c00bd94b07d65?se=2022-07-28T13%3A40%3A00Z&sig=OpU1dW%2BpNEhYwQ2kW1cgVOVjzbCKAhjPSZF7jYKq1p8%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/node/manifests/18.7.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:5bc3bbc7796679a30ef86748accee8170fad11bccea0fcc1fc129f2a51b4b6fa
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5bc3bbc7796679a30ef86748accee8170fad11bccea0fcc1fc129f2a51b4b6fa?se=2022-07-28T13%3A40%3A00Z&sig=BkddjWuh0jmmEeRIyasRLu4C8eondMEXiDlTg%2BPni54%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Upgrading libtiff
  4.4.0 -> 4.4.0_1

==> Installing dependencies for libtiff: jpeg-turbo
==> Installing libtiff dependency: jpeg-turbo
==> Pouring jpeg-turbo--2.1.3.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/jpeg-turbo/2.1.3: 44 files, 2.5MB
==> Installing libtiff
==> Pouring libtiff--4.4.0_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libtiff/4.4.0_1: 249 files, 4.8MB
==> Running `brew cleanup libtiff`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/libtiff/4.4.0... (249 files, 4.8MB)
==> Upgrading redis
  7.0.3 -> 7.0.4

==> Pouring redis--7.0.4.arm64_monterey.bottle.tar.gz
==> Caveats
To restart redis after an upgrade:
  brew services restart redis
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/redis/bin/redis-server /opt/homebrew/etc/redis.conf
==> Summary
🍺  /opt/homebrew/Cellar/redis/7.0.4: 14 files, 2.6MB
==> Running `brew cleanup redis`...
Removing: /opt/homebrew/Cellar/redis/7.0.3... (14 files, 2.6MB)
Removing: /Users/ttyrrell/Library/Caches/Homebrew/redis--7.0.3... (1001.9KB)
==> Upgrading harfbuzz
  4.4.1 -> 5.0.1

==> Pouring harfbuzz--5.0.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/harfbuzz/5.0.1: 68 files, 8.6MB
==> Running `brew cleanup harfbuzz`...
Removing: /opt/homebrew/Cellar/harfbuzz/4.4.1... (68 files, 7.6MB)
Removing: /Users/ttyrrell/Library/Caches/Homebrew/harfbuzz--4.4.1... (1.9MB)
==> Upgrading webp
  1.2.3 -> 1.2.3_1

==> Pouring webp--1.2.3_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/webp/1.2.3_1: 41 files, 2.2MB
==> Running `brew cleanup webp`...
Removing: /opt/homebrew/Cellar/webp/1.2.3... (41 files, 2.2MB)
==> Upgrading jpeg-xl
  0.6.1 -> 0.6.1_1

==> Pouring jpeg-xl--0.6.1_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/jpeg-xl/0.6.1_1: 61 files, 12.3MB
==> Running `brew cleanup jpeg-xl`...
Removing: /opt/homebrew/Cellar/jpeg-xl/0.6.1... (61 files, 12.1MB)
==> Upgrading node
  18.6.0 -> 18.7.0

==> Pouring node--18.7.0.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/node/18.7.0: 1,934 files, 47.7MB
==> Running `brew cleanup node`...
Removing: /opt/homebrew/Cellar/node/18.6.0... (1,931 files, 47.6MB)
Removing: /Users/ttyrrell/Library/Caches/Homebrew/node--18.6.0... (12.8MB)
==> Caveats
==> redis
To restart redis after an upgrade:
  brew services restart redis
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/redis/bin/redis-server /opt/homebrew/etc/redis.conf
❯
❯ brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
❯ ps -p $(lsof -t +d $(brew --prefix)/var/homebrew/locks)
  PID TTY           TIME CMD
34162 ttys022    0:00.08 /opt/homebrew/Cellar/git/2.37.1/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
34172 ttys022    0:00.01 /opt/homebrew/Cellar/git/2.37.1/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
34173 ttys022    0:00.01 /opt/homebrew/Cellar/git/2.37.1/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
34174 ttys022    0:00.01 /opt/homebrew/Cellar/git/2.37.1/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
```

</details>

**Comment by carlocab** [comment]
@timtyrrell I've pushed a new version. Try that one:
```
cd "$(brew --repository)"
git checkout git-fsmonitor
git pull
```

**Comment by timtyrrell** [comment]
@carlocab I wonder what the best way to test this is? Maybe killing the processes are not enough?

``` sh
❯ cd "$(brew --repository)"
git checkout git-fsmonitor
git pull
Switched to branch 'git-fsmonitor'
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), 1.23 KiB | 140.00 KiB/s, done.
From github.com:carlocab/brew
 * branch                git-fsmonitor -> FETCH_HEAD
Updating f9e853192..c42169249
Fast-forward
 Library/Homebrew/cmd/update.sh | 9 +++------
 1 file changed, 3 insertions(+), 6 deletions(-)
❯
❯ brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
❯ kill $(lsof -t +d $(brew --prefix)/var/homebrew/locks)
❯ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
❯ brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
```

**Comment by carlocab** [comment]
> I wonder what the best way to test this is?

You tested it the way I would, so I don't have better ideas.

> Maybe killing the processes are not enough?

Probably. I guess we'll have to set `core.fsmonitor = false` in each Homebrew repository.

**Comment by carlocab** [comment]
@timtyrrell Try this one.

**Comment by timtyrrell** [comment]
@carlocab I am a bit confused, seems `brew update` is switching me to `stable`?

``` sh
❯ cd "$(brew --repository)"
git checkout git-fsmonitor
git pull
Switched to branch 'git-fsmonitor'
From github.com:carlocab/brew
 * branch                git-fsmonitor -> FETCH_HEAD
Already up to date.
❯ git branch
* git-fsmonitor
  master
  stable
❯ brew update
Already up-to-date.
❯ git branch
  git-fsmonitor
  master
* stable

/opt/homebrew stable                                                                                                                     2.7.6
❯
```

**Comment by timtyrrell** [comment]
Although:

``` sh
❯ git --no-pager config --file $HOMEBREW_REPOSITORY/.git/config --get-all core.fsmonitor
false

/opt/homebrew stable                                                                                                                     2.7.6
❯
```

**Comment by Bo98** [comment]
I still feel force stopping seems like a workaround at best.

If we don't want to change how we handle file locking, something like this might work:

```diff
diff --git a/Library/Homebrew/brew.sh b/Library/Homebrew/brew.sh
index cbe08846a..76daa0899 100644
--- a/Library/Homebrew/brew.sh
+++ b/Library/Homebrew/brew.sh
@@ -178,7 +178,7 @@ curl() {
 }
 
 git() {
-  "${HOMEBREW_LIBRARY}/Homebrew/shims/shared/git" "$@"
+  "${HOMEBREW_LIBRARY}/Homebrew/shims/shared/git" "$@" 200>&-
 }
 
 # Search given executable in PATH (remove dependency for `which` command)
diff --git a/Library/Homebrew/cmd/update.sh b/Library/Homebrew/cmd/update.sh
index 0269d73ed..e2485d507 100644
--- a/Library/Homebrew/cmd/update.sh
+++ b/Library/Homebrew/cmd/update.sh
@@ -34,7 +34,7 @@ git() {
   then
     GIT_EXECUTABLE="$("${HOMEBREW_LIBRARY}/Homebrew/shims/shared/git" --homebrew=print-path)"
   fi
-  "${GIT_EXECUTABLE}" "$@"
+  "${GIT_EXECUTABLE}" "$@" 200>&-
 }
 
 git_init_if_necessary() {
@@ -769,7 +769,7 @@ EOS
      [[ ! -f "${HOMEBREW_CACHE}/all_commands_list.txt" ]] ||
      [[ -n "${HOMEBREW_DEVELOPER}" && -z "${HOMEBREW_UPDATE_AUTO}" ]]
   then
-    brew update-report "$@"
+    brew update-report "$@" 200>&-
     return $?
   elif [[ -z "${HOMEBREW_UPDATE_AUTO}" && -z "${HOMEBREW_QUIET}" ]]
   then
```

> I am a bit confused, seems brew update is switching me to stable?

You might need to enable developer mode.

**Comment by carlocab** [comment]
> I still feel force stopping seems like a workaround at best.

Same, but I'm not sure how else to fix it.

> If we don't want to change how we handle file locking

I don't know how to fix this, unfortunately. Feel free to push to my branch if you have an implementation in mind.

**Comment by carlocab** [comment]
I plan to merge this soon as a workaround, since `brew update` being broken is giving users a bad time.

We can experiment with better solutions in a follow-up.

File: Library/Homebrew/cmd/update.sh [hunk 2]
```diff
@@ -556,6 +556,9 @@ EOS
     [[ -d "${DIR}/.git" ]] || continue
     cd "${DIR}" || continue
 
+    # Git's fsmonitor prevents the release of our locks
+    git config --bool core.fsmonitor false
```
Comment (jgavris) [inline Library/Homebrew/cmd/update.sh:560]: Will this work for `fsmonitor` processes that are outside of Homebrew's repo? If you enabled the monitor in a separate directory? This might be overkill (pun intended), but maybe `update` can kill the `fsmonitor` daemon during an update. The better solution seems like introspecting what causes this message 'Another active Homebrew update process is already in progress' which seems to be caused by (without deeply looking at `brew`'s source, finding `homebrew` in the open processes path). 

```sh
λ ps | grep brew
93281 ttys002    0:01.07 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
11139 ttys005    0:01.32 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
89381 ttys007    0:00.30 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
28329 ttys008    0:00.24 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
16062 ttys011    0:00.50 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
23004 ttys012    0:00.02 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
23007 ttys012    0:00.01 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
23013 ttys012    0:00.02 /opt/homebrew/Cellar/git/2.37.0/libexec/git-core/git fsmonitor--daemon run --detach --ipc-threads=8
24442 ttys012    0:00.00 grep brew
```

**Comment by Bo98** [comment]
> Same, but I'm not sure how else to fix it.

Just realised you went the `git config` way. That seems fine then.

File: Library/Homebrew/cmd/update.sh (hunk 2 above)
Comment (Bo98) [reply Library/Homebrew/cmd/update.sh:560]: > Will this work for `fsmonitor` processes that are outside of Homebrew's repo? If you enabled the monitor in a separate directory?

Do these actually cause issues? I assumed the issue was caused by the initial spawning of the daemon inheriting the file descriptors from `update.sh` which wouldn't happen if it was spawned from another process, but I never managed to test if that was the case. If this theory is correct, this is in part our issue since we should ideally have close-on-exec behaviour for lock descriptors but don't.

If it's instead the case that the daemon just holds on to any file no matter what, then that feels more like a general Git bug since that behaviour sounds very problematic and uncontrollable.

Comment (jgavris) [reply Library/Homebrew/cmd/update.sh:560]: Whether the `fsmonitor` is inside a homebrew git directory or another user owned directory shouldn't be a concern of doing a `git pull` on the directory. It's only monitoring the files there. I also don't think we should need to kill the monitor or have the lock be concerned with it. It might just be a matter of more carefully choosing names for the lockfiles.

Comment (jgavris) [reply Library/Homebrew/cmd/update.sh:560]: I have the monitor setup globally, though it does feel invasive to have `brew` change the config there. I don't suppose it matters for brew managed git repos though, so not terribly concerned.

```
λ git config --global core.fsmonitor
true
```
