### PR TITLE
formula_auditor: prohibit patches in new core formulae only

### LINKED ISSUE #10216: brew test-bot doesn't allow formulae with patches
# Bug report

## What you were trying to do (and why)

I'm the maintainer of Guile Homebrew Tap, a tap to install Guile dependencies. I was adding a new formula which has an embedded (END) patch.

https://github.com/aconchillo/homebrew-guile

## What happened (include command output)

The github workflows (that comes with `brew tap-new`) complain that a formulae can't contain patches and that they should be submitted upstream. This seems weird as adding patches seems like a common use case, not all patches can be sent upstream as mentioned in homebrew documentation.

Note that this was working a few months ago.

## What you expected to happen

I was hoping for `brew audit` to not complain on patches.

Here's the output of one of the failures: https://github.com/aconchillo/homebrew-guile/runs/1642488881?check_suite_focus=true#step:7:32

Apologies if I should have sent/reported this somewhere else but I didn't really know where.

Thanks in advance.

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----
New formulae in non-core taps should be allowed to specify `patch` blocks. See https://github.com/Homebrew/brew/issues/10216 for further discussion.

I briefly looked through the tests but could not find anything that currently tests this audit anyways, so I did not change anything related to tests.

Fixes #10216

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]
Makes sense to me

File: Library/Homebrew/formula_auditor.rb [hunk 1]
```diff
@@ -495,7 +495,7 @@ def audit_specs
         end
 
         next if spec.patches.empty?
-        next unless @new_formula
+        next unless @new_formula && @core_tap
```
Comment (MikeMcQuaid) [inline Library/Homebrew/formula_auditor.rb:498]:
```suggestion
        next if !@new_formula && !@core_tap
```

Comment (Rylan12) [reply Library/Homebrew/formula_auditor.rb:498]:
```suggestion
        next if !@new_formula || !@core_tap
```

Right?

**Review by Rylan12 — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/formula_auditor.rb (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/formula_auditor.rb]: Yup but that's why I hate `unless &&`: it's not trivial (for me at least) to figure out how to "flip" it 😁
