### PR TITLE
`brew install--ask` for casks 

### LINKED ISSUE #19831: `--ask` with Casks is ignored and prints "Download Size: 0B"
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.32-67-g0e7f19f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0e7f19f2f1a7ab83f7e9bef77a46be2002cbbafe
Last commit: 2 days ago
Branch: master
Core tap HEAD: c5d6780e88e659af88a296bc48a956bf3915a983
Core tap last commit: 17 minutes ago
Core tap JSON: 27 Apr 21:49 UTC
Core cask tap HEAD: 13814e583add732538324958d56a9c73c433d14b
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 27 Apr 21:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.3/bin/ruby
CPU: deca-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3.1-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I was experimenting with using `--ask` with a Cask. I wanted to see if the feature works with casks.

### What happened (include all command output)?

The cask (VLC) got installed despite of the `--ask` and "Download Size: 0B" is displayed:

```console
% brew install --ask vlc
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/13814e5
Already downloaded: /Users/adminaccount/Library/Caches/Homebrew/downloads/9e67acc8920997e3012d53b421748f007a4f90c0f76305be00881ebac612afad--vlc.rb
==> Downloading https://get.videolan.org/vlc/3.0.21/macosx/vlc-3.0.21-arm64.dmg
Already downloaded: /Users/adminaccount/Library/Caches/Homebrew/downloads/e2ffc2227a3584ed5e470185778fa4199b87faf3295dd8e8bc79acc6e75bb4c3--vlc-3.0.21-arm64.dmg
==> Installing Cask vlc
==> Moving App 'VLC.app' to '/Applications/VLC.app'
==> Linking Binary 'vlc.wrapper.sh' to '/opt/homebrew/bin/vlc'
🍺  vlc was successfully installed!
==> Looking for bottles...
Formulae (0): 

Download Size: 0B
Install Size:  0B
==> Do you want to proceed with the installation? [Y/y/yes/N/n/no]
n
% brew install vlc
Warning: Not upgrading vlc, the latest version is already installed
```

### What did you expect to happen?

The initial expectation was to display the download size and prompt the user (like with formulas). After some inspection, I think the current expected behavior should be to display an error message (like when using `--ask --cask`):

```console
% brew install --ask --cask vlc
Usage: brew install [options] formula|cask [...]

[...]

Error: Invalid usage: Options --cask and --ask are mutually exclusive.
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --ask vlc
```

### PR DESCRIPTION
**Pull request by tyuwags**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

resolves #19831

### CODE REVIEW

File: Library/Homebrew/cmd/install.rb [hunk 1]
```diff
@@ -218,6 +218,7 @@ def run
         end
 
         if casks.any?
+          opoo "Option --ask is not compatible with casks." if args.options_only.include? "--ask"
           if args.dry_run?
             if (casks_to_install = casks.reject(&:installed?).presence)
               ohai "Would install #{::Utils.pluralize("cask", casks_to_install.count, include_count: true)}:"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/install.rb:224]: What about printing these dry run messages followed by the prompt? I know you can't do download sizes but maintaining the prompt behaviour seems nicer.

Comment (tyuwags) [reply Library/Homebrew/cmd/install.rb:224]: Normally, the ask option was only working for formulae, it was an error that with casks, it would show a prompt.
I can make another prompt specifically for casks just asking if the user wants to continue with the casks name without printing the download size

**Review by MikeMcQuaid — APPROVED** [review]
Thanks @tyuwags, great work!
