### PR TITLE
`resolve_latest_keg` should return the latest HEAD keg when no stable kegs exist

### LINKED ISSUE #11741: brew link fails with multiple HEAD installations
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.2-76-g12d272a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12d272abe8b091cb079372ab7db8a0eab30384de
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48b3156e29e9082dab02ed2070621052271f716b
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/vitor/.pyenv/shims/python3.9-config
  /Users/vitor/.pyenv/shims/python-config
  /Users/vitor/.pyenv/shims/python3-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew link` on a recently installed HEAD formula.

### What happened (include all command output)?

```ruby
Error: undefined method `rack' for nil:NilClass
/opt/homebrew/Library/Homebrew/cmd/link.rb:61:in `block in link'
/opt/homebrew/Library/Homebrew/cmd/link.rb:60:in `each'
/opt/homebrew/Library/Homebrew/cmd/link.rb:60:in `link'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

For either `brew link` to work on the most recent `HEAD` (`cleanup` removed the right one, so `link` should be able to know it too) or for an explanatory error message to show.

### Step-by-step reproduction instructions (by running `brew` commands)

The following will create a mock directory structure (which works like the real thing for this purpose), followed by the command which produces the error:

```bash
mkdir -p "$(brew --Cellar)/show-rack-error/HEAD-"{1111111,2222222}
brew link show-rack-error
```

The directory structure will be:

```
show-rack-error
    ├── HEAD-1111111
    └── HEAD-2222222
```

### PR DESCRIPTION
**Pull request by cnnrmnn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Closes #11741.

Currently, `resolve_latest_keg` has the following behavior:
- If only one keg exists (HEAD or stable), return that keg.
- Otherwise, return the latest stable keg.

This behavior doesn't handle the case where there are multiple HEAD kegs, but no stable kegs. This PR adds the following behavior to `resolve_latest_keg`:
- If there are HEAD kegs but no stable kegs, return the latest HEAD keg.

### CODE REVIEW

**Comment by cnnrmnn** [comment]
The test is failing on CI (but passing for me locally) because at the moment, [comparing two HEAD versions returns 0](https://github.com/Homebrew/brew/blob/0fc7762e997432694cff49a7065f88ea0e3b6eba/Library/Homebrew/version.rb#L549). I suspect the best way to deal with this would be in `resolve_latest_keg`. We could use `HeadVersion#commit` to determine which version is newer. Alternatively, a less sophisticated approach would be picking the keg with the most recently modified directory. What do you think? @Rylan12

**Comment by Rylan12** [comment]
I can take a closer look late tomorrow night (might not be until Friday—traveling today).

`Formula#latest_head_version` uses the modification time of the tab to determine which HEAD version is the latest:

https://github.com/Homebrew/brew/blob/0fc7762e997432694cff49a7065f88ea0e3b6eba/Library/Homebrew/formula.rb#L549-L558

I think it would be appropriate to use the same logic here (ideally this could be done without duplicating code but it's possible some refactoring would need to be done to support that)

**Comment by cnnrmnn** [comment]
> I think it would be appropriate to use the same logic here (ideally this could be done without duplicating code but it's possible some refactoring would need to be done to support that)

Thanks for pointing me towards `Formula#latest_head_version`. Will use same logic for this issue.

File: Library/Homebrew/cli/named_args.rb [hunk 1]
```diff
@@ -324,7 +324,11 @@ def resolve_latest_keg(name)
         # Return keg if it is the only installed keg
         return kegs if kegs.length == 1
 
-        kegs.reject { |k| k.version.head? }.max_by(&:version)
+        stable_kegs = kegs.reject { |k| k.version.head? }
+
+        return kegs.max_by { |keg| Tab.for_keg(keg).source_modified_time } if stable_kegs.blank?
```
Comment (cnnrmnn) [inline Library/Homebrew/cli/named_args.rb:329]: I included the `source_modified_time` code here directly since it is so brief. If you think this should be encapsulated elsewhere for use in `resolve_latest_keg` and `latest_head_version`, I'm happy to make changes. @Rylan12

**Review by carlocab — APPROVED** [review]
Makes sense to me. Thanks @cnnrmnn!

File: Library/Homebrew/cli/named_args.rb (hunk 1 above)
Comment (Rylan12) [reply Library/Homebrew/cli/named_args.rb:329]: @cnnrmnn I think this is fine. I'm not sure it really makes much sense to extract what's essentially `#source_modified_time` to its own method.

Just making sure, the [`revision` secondary sort from `Formula#latest_head_version`](https://github.com/Homebrew/brew/blob/5ea678bbc7307f476b0f01ac727099300db95f83/Library/Homebrew/formula.rb#L556) isn't necessary here, right?

Comment (cnnrmnn) [reply Library/Homebrew/cli/named_args.rb:329]: I'm not sure that the `revision` secondary sort is needed anywhere we're dealing exclusively with `HEAD` versions. If you check out the [parsing function for `PkgVersion`](https://github.com/Homebrew/brew/blob/5ea678bbc7307f476b0f01ac727099300db95f83/Library/Homebrew/pkg_version.rb#L20), you'll see that it parses the revision using a regex. `HEAD` paths (e.g., `HEAD-6974ce8`) matched to that regex will always set `revision` to nil. Any `HEAD` version should have a revision equal to `0` since `to_i` is called on the parsed `nil` `revision`.

Comment (Rylan12) [reply Library/Homebrew/cli/named_args.rb:329]: Gotcha makes sense. So it could probably be removed from `latest_head_version` too, right? Probably not worth doing but just curious if there's a difference.

Comment (cnnrmnn) [reply Library/Homebrew/cli/named_args.rb:329]: > So it could probably be removed from latest_head_version too, right?

Yep, should be fine to remove. I can do that in a quick PR as to not confuse anyone dealing with that code in the future.

Comment (Rylan12) [reply Library/Homebrew/cli/named_args.rb:329]: You definitely don't need to but it probably wouldn't hurt. Plus it will expose more maintainers to it in case anyone knows something we're missing and it turns out it _is_ necessary

Comment (cnnrmnn) [reply Library/Homebrew/cli/named_args.rb:329]: @Rylan12 Did some quick digging, and found [a spec](https://github.com/Homebrew/brew/blob/cd900ef71eeecb621faba88aabc641fe93325fe6/Library/Homebrew/test/formula_spec.rb#L347) that tests `HEAD` versions with revisions. Do you know if there's any scenario where a `HEAD` version would actually have a revision?

I would think so given that the above tests exists, but I'm still curious. If you don't know, I can do a little more digging and restore the secondary sort here if appropriate.

Comment (Rylan12) [reply Library/Homebrew/cli/named_args.rb:329]: Ah, good call. If you do `brew install --HEAD` on a formula that's specified a `revision` it _will_ show up as `HEAD-6974ce8_3` (which means there will be a revision), so I think it _does_ need to be added here.

Comment (cnnrmnn) [reply Library/Homebrew/cli/named_args.rb:329]: Gotcha, will push a fix shortly.
