### PR TITLE
os/linux/elf: fix file descriptor leak

### LINKED ISSUE #19177: "too many open files" sometimes when installing a formula on Linux (same as #9120)
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23facb219df8615680636ef12103bb3313f44e2a
Last commit: 3 days ago
Branch: stable
Core tap JSON: 30 Jan 21:38 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: 16-core 64-bit skylake
Clang: 19.1.7
Git: 2.43.0 => /bin/git
Curl: 8.5.0 => /bin/curl
Kernel: Linux 6.8.0-52-generic x86_64 GNU/Linux
OS: Ubuntu 24.04.1 LTS (noble)
Host glibc: 2.39
/usr/bin/gcc: 13.3.0
/usr/bin/ruby: 3.2.3
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

I was trying to install the `qemu` formula.

### What happened (include all command output)?

Homebrew downloaded quite a few bottles, and started installing them, but failed along the way with "too many  open files".

Now, it says all over this page that my issue will be immediately closed if I can't reproduce it, so maybe you're going to close this, since the issue *usually* resolves by re-running the same `brew install` command. Sometimes it gets further, then still fails, and a third try is necessary.

Note that is a duplicate of #9120, but I can't reopen that. It was closed saying only 1 person has ever complained, so let me add my voice as a complainant. This doesn't happen *every* time, but it does happen frequently.

Following a comment there, I can see that my ulimit is low:
```
$ ulimit -Hn
1048576
$ ulimit -Sn
1024
```

This is a standard install of Ubuntu 24.04, nothing spooky.

### What did you expect to happen?

The install process should have completed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install qemu`
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

On Linux, we occasionally see `EMFILE` ("too many open files") errors especially when installing a large formula like `llvm`. Currently, this can be reliably reproduced in a Homebrew/brew GitHub codespace (where `ulimit -n` seems to be 1024 by default) with `brew install geeqie`, with the following error message:

    Error: Too many open files @ rb_sysopen - /home/linuxbrew/.linuxbrew/Cellar/llvm/20.1.8/bin/tblgen-lsp-server

The reason is that each instance of `PatchELF::Patcher` keeps the ELF file open. We prepend the `ELFShim` module to the `Pathname` class and cache the patcher as an instance variable, which means that the ELF file remains open so long as the `Pathname` instance is still alive even if we don't need to access the ELF metadata anymore. When performing certain checks (e.g., linkage), we also store these `Pathname` instances, so the number of open file descriptors simply keeps increasing.

We can fix that by not caching the patcher and only use it when necessary. We create a patcher instance whenever we need to read or write ELF metadata, and reading of metadata is consolidated into the existing `ELFShim::Metadata` class so that we don't repeatedly create patcher instances.

A fix for a file descriptor leak issue in patchelf.rb has been submitted at https://github.com/david942j/patchelf.rb/pull/48. Together with that, this fixes #19177, #19866, #20223, #20302.

### CODE REVIEW

File: Library/Homebrew/os/linux/elf.rb [hunk 1]
```diff
@@ -164,35 +164,53 @@ class Metadata
...
+      @dylib_id, @needed = if @dynamic_elf
+        [patcher.soname, patcher.needed]
+      else
+        [nil, []]
+      end
 
-    def needed_libraries(path)
-      return [nil, []] unless path.dynamic_elf?
+      @interpreter = patcher.interpreter
+      @rpath = patcher.rpath || patcher.runpath
```
Comment (ZhongRuoyu) [inline Library/Homebrew/os/linux/elf.rb]: Whoops

```suggestion
      @rpath = patcher.runpath || patcher.rpath
```

**Comment by MikeMcQuaid** [comment]
@ZhongRuoyu Might be nice to bump this file to `typed: strict` when possible.
