### PR TITLE
Remove portable ruby bin from PATH

### LINKED ISSUE #21109: `brew cleanup` reinstalls and removes portable ruby
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6b691d839ee05869772f1a233bf8173ccaeea51
Last commit: 2 days ago
Branch: stable
Core tap JSON: 18 Nov 23:40 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_DOWNLOAD_CONCURRENCY: 40
HOMEBREW_EDITOR: vim
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 3.4.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7/bin/ruby
CPU: 20-core 64-bit alderlake
Clang: N/A
Git: 2.43.0 => /bin/git
Curl: 8.5.0 => /bin/curl
Kernel: Linux 6.6.87.2-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 24.04.3 LTS (noble)
WSL: 2 (Microsoft Store)
Host glibc: 2.39
Host libstdc++: 6.0.33
/usr/bin/gcc: 13.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@12: N/A
gcc: N/A
xorg: N/A
```

### What were you trying to do (and why)?

`brew cleanup` for regular maintenance.

### What happened (include all command output)?

```shell
$ brew cleanup
Removing: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7... (1,580 files, 44.0MB)
==> This operation has freed approximately 44.0MB of disk space.

$ brew cleanup
==> Downloading https://ghcr.io/v2/homebrew/core/portable-ruby/blobs/sha256:3cca179476f84b0055766aa976005e3d45da635f0bc7616984675e2232db1eb4
Already downloaded: /home/jacktose/.cache/Homebrew/portable-ruby-3.4.7.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-3.4.7.x86_64_linux.bottle.tar.gz
Removing: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7... (1,580 files, 44.0MB)
==> This operation has freed approximately 44.0MB of disk space.

$ brew cleanup
==> Downloading https://ghcr.io/v2/homebrew/core/portable-ruby/blobs/sha256:3cca179476f84b0055766aa976005e3d45da635f0bc7616984675e2232db1eb4
Already downloaded: /home/jacktose/.cache/Homebrew/portable-ruby-3.4.7.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-3.4.7.x86_64_linux.bottle.tar.gz
Removing: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.7... (1,580 files, 44.0MB)
==> This operation has freed approximately 44.0MB of disk space.

# and so on ...
```

### What did you expect to happen?

I'm not sure when homebrew needs portable ruby or not, but `cleanup` shouldn't remove it if it is needed for regular use (including for `cleanup`).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew cleanup
brew cleanup
```

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

Fixes #21109

This PR removes portable Ruby from PATH as parts of brew are written expecting only system paths like
https://github.com/Homebrew/brew/blob/07a983c338fe0df4409d75c04318c81f654805a4/Library/Homebrew/extend/os/linux/cleanup.rb#L15

I am not entirely sure on `setup_gem_environment!` change, but it restores original behavior before https://github.com/Homebrew/brew/commit/60fa3682364e8a65582ff808089e77eab1983baa#diff-a1a5395d198aee1fb8c45c74bf9dd49ef5734887a17ee84000badc7d58b82e98L43 (called via `install_bundler!`)

This mainly is used to avoid a failing test (utils/ruby_check_version_script_spec.rb).

Though maybe the test shouldn't be using Ruby from PATH as that is not how we interact with the script. We usually call the script like `<path/to/ruby> ruby_check_version_script_spec.rb ...` so it doesn't matter whether or not portable Ruby is on the PATH.

---

EDIT: After thinking over above, will just adjust test rather than adding `setup_gem_environment!`. Also in line with the Copilot review that `setup_gem_environment!` has side effects that we may not have intended.

May need to keep an eye out for unexpected failures though if any code is expecting portable Ruby on PATH.

### CODE REVIEW

File: Library/Homebrew/utils/gems.rb [hunk 1]
```diff
@@ -37,6 +37,7 @@ def self.bundler_definition
   private_class_method :bundler_definition
 
   def self.valid_gem_groups
+    setup_gem_environment!
```
Comment (cho-m) [inline Library/Homebrew/utils/gems.rb]: Although this restores original behavior, I am not sure if original behavior was intentional.

Alternative could be to just adjust testcase
https://github.com/Homebrew/brew/blob/07a983c338fe0df4409d75c04318c81f654805a4/Library/Homebrew/test/utils/ruby_check_version_script_spec.rb#L10

Something like following would also fix test:
```diff
-        quiet_system "#{HOMEBREW_LIBRARY_PATH}/utils/ruby_check_version_script.rb", required_ruby_version
+        quiet_system RUBY_PATH, "#{HOMEBREW_LIBRARY_PATH}/utils/ruby_check_version_script.rb", required_ruby_version
```

Given we always run script with a Ruby as first argument (not via shebang), e.g.

https://github.com/Homebrew/brew/blob/07a983c338fe0df4409d75c04318c81f654805a4/Library/Homebrew/extend/os/linux/cleanup.rb#L21-L22

https://github.com/Homebrew/brew/blob/07a983c338fe0df4409d75c04318c81f654805a4/Library/Homebrew/utils/ruby.sh#L20-L21
