### PR TITLE
os/linux/ld: harden `brewed_ld_so_diagnostics` against `TypeError`

### LINKED ISSUE #17828: systemd brew.rb "Error: no implicit conversion of false into String" error
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.3.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c3ae0327c01aab461531bfc0fcdfb4dd3a779205
Last commit: 4 days ago
Core tap JSON: 22 Jul 16:06 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 16-core 64-bit zen3
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install `eza` to try it out

### What happened (include all command output)?

Auto update kicked in and lots of dependencies were installed.  Here is the full output:

```
$ brew install eza
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:40a1dbc25bb1a8bbdf0bba53d3f16c45416be12d4c6d48b4530f90b2a77d64ce
######################################################################## 100.0%
==> Pouring portable-ruby-3.3.3.x86_64_linux.bottle.tar.gz
==> Auto-updated Homebrew!
Updated 3 taps (common-fate/granted, homebrew/core and homebrew/cask).
==> New Formulae
age-plugin-se  cortexso       envelope       kubevpn        nerdfetch      pulsarctl      tdb            wcurl
ansible@9      cotila         frizbee        lando-cli      nsync          qrtool         terrahash
asak           cyme           ftnchek        libgit2@1.7    openbao        rustup         terramaid
awsdac         dnsgen         h26forge       litmusctl      otree          ryelang        testscript
chkbit         ecs-deploy     iowow          llgo           porter         soapyhackrf    tinymist
clang-uml      egctl          kaskade        mako           pug            subliminal     topfew
==> New Casks
airdash                                 font-dotum                              longplay
avbeam                                  font-dotumche                           loop
ball                                    font-fragment-mono-sc                   monarch
blip                                    font-gulim                              monokle
boosteroid                              font-gulimche                           navicat-premium-lite
charmstone                              font-gungsuh                            notchnook
clash-verge-rev                         font-gungsuhche                         orka-desktop
crashplan                               font-maname                             pia
dockdoor                                font-palemonasmufi-bold                 plugdata@nightly
duplicateaudiofinder                    font-palemonasmufi-bolditalic           positron
ea                                      font-palemonasmufi-italic               productive
font-afacad-flux                        font-palemonasmufi-regular              replit
font-alumni-sans-sc                     font-sixtyfour-convergence              retroarch-metal@nightly
font-batang                             getoutline                              roblox
font-batangche                          gitkraken-on-premise-serverless         sq-mixpad
font-beiruti                            impel                                   teamspeak-client@beta
font-big-shoulders-display-sc           inkdown                                 tella
font-big-shoulders-inline-display-sc    ivacy                                   twingate
font-big-shoulders-inline-text-sc       jagex                                   wd-security
font-big-shoulders-stencil-display-sc   k8studio                                yaak
font-big-shoulders-stencil-text-sc      kando
font-big-shoulders-text-sc              lazycat

You have 32 outdated formulae installed.

==> Downloading https://ghcr.io/v2/homebrew/core/eza/manifests/0.18.22
################################################################################################################# 100.0%
==> Fetching dependencies for eza: ca-certificates, openssl@3, libssh2 and libgit2
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2024-07-02
################################################################################################################# 100.0%
==> Fetching ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:73eb1a6bf9a5e12ee3f1acd295a4aaa28f08a9125a
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.3.1
################################################################################################################# 100.0%
==> Fetching openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:d84029bfaf8a5452329d7e2535ba32d720b361b398e46051
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libssh2/manifests/1.11.0_1
################################################################################################################# 100.0%
==> Fetching libssh2
==> Downloading https://ghcr.io/v2/homebrew/core/libssh2/blobs/sha256:57746d26d6d96b0ba3a7b7021b8f13a466685e8a2172fa49bf
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libgit2/manifests/1.8.1
################################################################################################################# 100.0%
==> Fetching libgit2
==> Downloading https://ghcr.io/v2/homebrew/core/libgit2/blobs/sha256:66c64820e1f7ce0ec927b8195f2748f4bc11065488c59a33ea
################################################################################################################# 100.0%
==> Fetching eza
==> Downloading https://ghcr.io/v2/homebrew/core/eza/blobs/sha256:b28101804c418f7ab0460a97abb68f7f8e0e92c0949864e548206f
################################################################################################################# 100.0%
==> Installing dependencies for eza: ca-certificates, openssl@3, libssh2 and libgit2
==> Installing eza dependency: ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2024-07-02
Already downloaded: /home/joshua/.cache/Homebrew/downloads/f1e786c502c23070efef1c7716aeaea181b28fd0cdbc5327d6d7c243b49e7700--ca-certificates-2024-07-02.bottle_manifest.json
==> Pouring ca-certificates--2024-07-02.all.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/ca-certificates/2024-07-02: 4 files, 246.9KB
==> Installing eza dependency: openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.3.1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/667f7ac7d51b399107e055b7908f1922fcabba24c7d9d22f2b2d90a07c7c079c--openssl@3-3.3.1.bottle_manifest.json
==> Pouring openssl@3--3.3.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.3.1: 6,992 files, 38.9MB
==> Installing eza dependency: libssh2
==> Downloading https://ghcr.io/v2/homebrew/core/libssh2/manifests/1.11.0_1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/48ca0c7785b21630a4817c59b72205609ccb0575e7abc64d64af2e61a60b5b0a--libssh2-1.11.0_1.bottle_manifest.json
==> Pouring libssh2--1.11.0_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libssh2/1.11.0_1: 199 files, 1.4MB
==> Installing eza dependency: libgit2
==> Downloading https://ghcr.io/v2/homebrew/core/libgit2/manifests/1.8.1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/84b074c6d1ee51616dfba962c9b638aeda6093080b5ebf82e6a02017bce44215--libgit2-1.8.1.bottle_manifest.json
==> Pouring libgit2--1.8.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libgit2/1.8.1: 106 files, 6.7MB
==> Installing eza
==> Pouring eza--0.18.22.x86_64_linux.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/eza/0.18.22: 15 files, 1.2MB
==> Running `brew cleanup eza`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Upgrading 9 dependents of upgraded formulae:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
awscli 2.15.22 -> 2.17.14, krb5 1.21.2 -> 1.21.3, libtirpc 1.3.3 -> 1.3.4, libfido2 1.14.0_1 -> 1.15.0, python@3.11 3.11.7_2 -> 3.11.9_1, python@3.12 3.12.2_1 -> 3.12.4, glib 2.78.4 -> 2.80.4, node 21.6.2 -> 22.5.1, systemd 255.3 -> 255.7
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/manifests/1.21.3
################################################################################################################# 100.0%
==> Fetching dependencies for krb5: ncurses and libedit
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/manifests/6.5
################################################################################################################# 100.0%
==> Fetching ncurses
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/blobs/sha256:7c49662d0f319baec24475d38210b2f9c754b2ec1d21a4a3ff
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libedit/manifests/20240517-3.1
################################################################################################################# 100.0%
==> Fetching libedit
==> Downloading https://ghcr.io/v2/homebrew/core/libedit/blobs/sha256:a5eda364492fa30e07098bea7259d970c221dffce51f570594
################################################################################################################# 100.0%
==> Fetching krb5
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:f5b4cafedb315e92a31a0a5d87e33f7826952bcc5c093ba65817c
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtirpc/manifests/1.3.4
################################################################################################################# 100.0%
==> Fetching libtirpc
==> Downloading https://ghcr.io/v2/homebrew/core/libtirpc/blobs/sha256:ddd04177b907c57c70393dae0ce340dd1fa73c3824adfac4a
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.11/manifests/3.11.9_1
################################################################################################################# 100.0%
==> Fetching dependencies for python@3.11: readline, sqlite, xz and expat
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.2.10
################################################################################################################# 100.0%
==> Fetching readline
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:65181d2c0a9bd1d91ded6f7ec4a69b1110f65e875b332947e
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.46.0
################################################################################################################# 100.0%
==> Fetching sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:59a0e215241a611985229353273a803339372c7a075f040fe30
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.6.2
################################################################################################################# 100.0%
==> Fetching xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:ab97999c22de61b2efa61c2a3f62d28085ce3f15601035955e41b8d
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/expat/manifests/2.6.2
################################################################################################################# 100.0%
==> Fetching expat
==> Downloading https://ghcr.io/v2/homebrew/core/expat/blobs/sha256:00d8e476d4e3ec9c02be088eb7c9d5cee7376c2206f00a90229f
################################################################################################################# 100.0%
==> Fetching python@3.11
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.11/blobs/sha256:4ffd5b6e60fc5100aec5a090dada86a238631f1bb76e72
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/manifests/2.17.14
################################################################################################################# 100.0%
==> Fetching dependencies for awscli: pycparser, cffi and cryptography
==> Downloading https://ghcr.io/v2/homebrew/core/pycparser/manifests/2.22
################################################################################################################# 100.0%
==> Fetching pycparser
==> Downloading https://ghcr.io/v2/homebrew/core/pycparser/blobs/sha256:0f591e2eca1cf20abf29c606294f0f8b1b2efde60a4cade1
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/cffi/manifests/1.16.0_1-1
################################################################################################################# 100.0%
==> Fetching cffi
==> Downloading https://ghcr.io/v2/homebrew/core/cffi/blobs/sha256:75989e551855be635a6ee550fd5ef2f02738ed44fee5eef0393e6
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/cryptography/manifests/42.0.8
################################################################################################################# 100.0%
==> Fetching cryptography
==> Downloading https://ghcr.io/v2/homebrew/core/cryptography/blobs/sha256:f82da8a29e4dfcfd6740a347ff6f2fbc3ddea6bec7db1
################################################################################################################# 100.0%
==> Fetching awscli
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:e3f21d0f120d1c2b4cc32bb61a60c4af1513f8ea57097e19dae
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.4
################################################################################################################# 100.0%
==> Fetching python@3.12
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/blobs/sha256:bedb3292805ced1e74ed691dab49345acec453be9c8d3d
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/glib/manifests/2.80.4
################################################################################################################# 100.0%
==> Fetching dependencies for glib: pcre2 and util-linux
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/manifests/10.44
################################################################################################################# 100.0%
==> Fetching pcre2
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/blobs/sha256:cbddfbb9921fa2894640db7f0395ea8a79ce5209ebe5ae670076
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/util-linux/manifests/2.40.2-1
################################################################################################################# 100.0%
==> Fetching util-linux
==> Downloading https://ghcr.io/v2/homebrew/core/util-linux/blobs/sha256:773c91eea7c86a3a5a18ae1b43a43c9346b190ccf7640bb
################################################################################################################# 100.0%
==> Fetching glib
==> Downloading https://ghcr.io/v2/homebrew/core/glib/blobs/sha256:75af431b3cf94313eb31f3e6433ca3e39b42d1cfe538bc7bc92c5
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/systemd/manifests/255.7
################################################################################################################# 100.0%
==> Fetching dependencies for systemd: libcap and zstd
==> Downloading https://ghcr.io/v2/homebrew/core/libcap/manifests/2.70
################################################################################################################# 100.0%
==> Fetching libcap
==> Downloading https://ghcr.io/v2/homebrew/core/libcap/blobs/sha256:9d86081b10083f63884005f73bc6f595ab79c91a05e8fcc355a
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.6
################################################################################################################# 100.0%
==> Fetching zstd
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:0e6ddbd4c969bb84261f12b759fb78a828d6f734c9e515793c6ac
################################################################################################################# 100.0%
==> Fetching systemd
==> Downloading https://ghcr.io/v2/homebrew/core/systemd/blobs/sha256:ed07a1bb6e5cb4b7b4f9e0337c780d2769a7eed8c5d1b2af61
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libfido2/manifests/1.15.0
################################################################################################################# 100.0%
==> Fetching libfido2
==> Downloading https://ghcr.io/v2/homebrew/core/libfido2/blobs/sha256:c7ebead53de6c6dd99885d4b3fb94cf0c753995a280824cb0
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/node/manifests/22.5.1
################################################################################################################# 100.0%
==> Fetching dependencies for node: c-ares, icu4c and libnghttp2
==> Downloading https://ghcr.io/v2/homebrew/core/c-ares/manifests/1.32.2
################################################################################################################# 100.0%
==> Fetching c-ares
==> Downloading https://ghcr.io/v2/homebrew/core/c-ares/blobs/sha256:ec264c2ede66cd30bc90008b99059ff75404f4c598c210386d3
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/74.2
################################################################################################################# 100.0%
==> Fetching icu4c
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:2b881638861905a1a730cdd618966dfcb548685314d86addd1ad
################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libnghttp2/manifests/1.61.0
################################################################################################################# 100.0%
==> Fetching libnghttp2
==> Downloading https://ghcr.io/v2/homebrew/core/libnghttp2/blobs/sha256:3e377888fc08a7cf4e86db0d8a513727f2ab54bea032fb4
################################################################################################################# 100.0%
==> Fetching node
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:afee4b16ed769334039fbce1b018f9882043fd5096366c716b7df
################################################################################################################# 100.0%
==> Upgrading krb5
  1.21.2 -> 1.21.3
==> Installing dependencies for krb5: ncurses and libedit
==> Installing krb5 dependency: ncurses
==> Downloading https://ghcr.io/v2/homebrew/core/ncurses/manifests/6.5
Already downloaded: /home/joshua/.cache/Homebrew/downloads/b2f8ce4e08b15832435170efd265346225ee388d5baab3d5c50e3a77c5673b5a--ncurses-6.5.bottle_manifest.json
==> Pouring ncurses--6.5.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/ncurses/6.5: 4,037 files, 10.9MB
==> Installing krb5 dependency: libedit
==> Downloading https://ghcr.io/v2/homebrew/core/libedit/manifests/20240517-3.1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/67f15ebf6a83422adb37138bcc6e4b513415c9eea86e56f88888328ad3763a66--libedit-20240517-3.1.bottle_manifest.json
==> Pouring libedit--20240517-3.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libedit/20240517-3.1: 55 files, 795.5KB
==> Installing krb5
==> Pouring krb5--1.21.3.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/krb5/1.21.3: 164 files, 5.3MB
==> Running `brew cleanup krb5`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/krb5/1.21.2... (163 files, 5.3MB)
Removing: /home/joshua/.cache/Homebrew/krb5_bottle_manifest--1.21.2... (14.3KB)
Removing: /home/joshua/.cache/Homebrew/krb5--1.21.2... (1.6MB)
==> Upgrading libtirpc
  1.3.3 -> 1.3.4
==> Pouring libtirpc--1.3.4.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.4: 86 files, 1MB
==> Running `brew cleanup libtirpc`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.3... (85 files, 1MB)
Removing: /home/joshua/.cache/Homebrew/libtirpc_bottle_manifest--1.3.3... (2.7KB)
Removing: /home/joshua/.cache/Homebrew/libtirpc--1.3.3... (285.0KB)
==> Upgrading python@3.11
  3.11.7_2 -> 3.11.9_1
==> Installing dependencies for python@3.11: readline, sqlite, xz and expat
==> Installing python@3.11 dependency: readline
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.2.10
Already downloaded: /home/joshua/.cache/Homebrew/downloads/4ddd52803319828799f1932d4c7fa8d11c667049b20a56341c0c19246a1be93b--readline-8.2.10.bottle_manifest.json
==> Pouring readline--8.2.10.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/readline/8.2.10: 51 files, 2MB
==> Installing python@3.11 dependency: sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.46.0
Already downloaded: /home/joshua/.cache/Homebrew/downloads/7d6bff4676b4f32a64f5d9436491b1eedb27a559ef4ff63aaaa62834a981bcd0--sqlite-3.46.0.bottle_manifest.json
==> Pouring sqlite--3.46.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.46.0: 13 files, 6.2MB
==> Installing python@3.11 dependency: xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.6.2
Already downloaded: /home/joshua/.cache/Homebrew/downloads/0f02a3a463ce4e72f92871751d9ba7b872ca8090348074d46ffb523fd67e1c7b--xz-5.6.2.bottle_manifest.json
==> Pouring xz--5.6.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.6.2: 97 files, 2.0MB
==> Installing python@3.11 dependency: expat
==> Downloading https://ghcr.io/v2/homebrew/core/expat/manifests/2.6.2
Already downloaded: /home/joshua/.cache/Homebrew/downloads/aef02777a16b814ca6284e98d9bfea8a80b97c8cbba6d78eca020ede9a5a6fcc--expat-2.6.2.bottle_manifest.json
==> Pouring expat--2.6.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/expat/2.6.2: 23 files, 897.7KB
==> Installing python@3.11
==> Pouring python@3.11--3.11.9_1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.9_1/bin/python3.11 -Im ensurepip
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.9_1/bin/python3.11 -Im pip install -v --no-index --upgrade --isolated --target=/home/linuxb
🍺  /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.9_1: 2,891 files, 67.6MB
==> Running `brew cleanup python@3.11`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.7_2... (2,887 files, 68.1MB)
Removing: /home/joshua/.cache/Homebrew/python@3.11_bottle_manifest--3.11.7_2... (24KB)
==> Upgrading awscli
  2.15.22 -> 2.17.14
==> Installing dependencies for awscli: pycparser, cffi and cryptography
==> Installing awscli dependency: pycparser
==> Downloading https://ghcr.io/v2/homebrew/core/pycparser/manifests/2.22
Already downloaded: /home/joshua/.cache/Homebrew/downloads/eeea4f104b2e432de9839123571bf8ac17b912aa138005099f4e97992d3e56b3--pycparser-2.22.bottle_manifest.json
==> Pouring pycparser--2.22.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/pycparser/2.22: 74 files, 1.3MB
==> Installing awscli dependency: cffi
==> Downloading https://ghcr.io/v2/homebrew/core/cffi/manifests/1.16.0_1-1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/eb1e9d6f4f724404e336e6bd8af635bd56b992b0d8a67c5665a2ed7f91938b46--cffi-1.16.0_1-1.bottle_manifest.json
==> Pouring cffi--1.16.0_1.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/cffi/1.16.0_1: 70 files, 2.3MB
==> Installing awscli dependency: cryptography
==> Downloading https://ghcr.io/v2/homebrew/core/cryptography/manifests/42.0.8
Already downloaded: /home/joshua/.cache/Homebrew/downloads/7643b8ac8661f16ddc31cf18e8da95547f3bd206bc55e05e0d6c234dcf3fb69f--cryptography-42.0.8.bottle_manifest.json
==> Pouring cryptography--42.0.8.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/cryptography/42.0.8: 212 files, 9.0MB
==> Installing awscli
==> Pouring awscli--2.17.14.x86_64_linux.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /home/linuxbrew/.linuxbrew/share/awscli/examples

Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/awscli/2.17.14: 14,199 files, 134.4MB
==> Running `brew cleanup awscli`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/awscli/2.15.22... (14,356 files, 142.1MB)
Removing: /home/joshua/.cache/Homebrew/awscli_bottle_manifest--2.15.22-1... (18.9KB)
==> Upgrading python@3.12
  3.12.2_1 -> 3.12.4
==> Pouring python@3.12--3.12.4.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.4/bin/python3.12 -Im ensurepip
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.4/bin/python3.12 -Im pip install -v --no-index --upgrade --isolated --target=/home/linuxbre
🍺  /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.4: 2,878 files, 72MB
==> Running `brew cleanup python@3.12`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.2_1... (2,934 files, 73.8MB)
==> Upgrading glib
  2.78.4 -> 2.80.4
==> Installing dependencies for glib: pcre2 and util-linux
==> Installing glib dependency: pcre2
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/manifests/10.44
Already downloaded: /home/joshua/.cache/Homebrew/downloads/22ed791461c5bf400adde8c3b432c1230866aa1db3c5cb81e06a6ff21cac96ee--pcre2-10.44.bottle_manifest.json
==> Pouring pcre2--10.44.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/pcre2/10.44: 241 files, 7.3MB
==> Installing glib dependency: util-linux
==> Downloading https://ghcr.io/v2/homebrew/core/util-linux/manifests/2.40.2-1
Already downloaded: /home/joshua/.cache/Homebrew/downloads/635c3a4838ab534b3fed900de735d2527a71bca53917fcc61cc683223c724e8a--util-linux-2.40.2-1.bottle_manifest.json
==> Pouring util-linux--2.40.2.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.40.2: 443 files, 25.7MB
==> Installing glib
==> Pouring glib--2.80.4.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/glib/2.80.4: 534 files, 40.6MB
==> Running `brew cleanup glib`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/glib/2.78.4... (463 files, 26.4MB)
Removing: /home/joshua/.cache/Homebrew/glib_bottle_manifest--2.78.4... (14.7KB)
==> Upgrading systemd
  255.3 -> 255.7
==> Installing dependencies for systemd: libcap and zstd
==> Installing systemd dependency: libcap
==> Downloading https://ghcr.io/v2/homebrew/core/libcap/manifests/2.70
Already downloaded: /home/joshua/.cache/Homebrew/downloads/80b42fc9ee5a2eb07ec446c4eea630ca9dd23771146473c938f036854cdac290--libcap-2.70.bottle_manifest.json
==> Pouring libcap--2.70.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libcap/2.70: 102 files, 477.5KB
==> Installing systemd dependency: zstd
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.6
Already downloaded: /home/joshua/.cache/Homebrew/downloads/29403e0df5404d8aeca0e750ac135ec9ef44fc5eeb6df69170ed602acabf0ffb--zstd-1.5.6.bottle_manifest.json
==> Pouring zstd--1.5.6.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.6: 32 files, 2.9MB
==> Installing systemd
==> Pouring systemd--255.7.x86_64_linux.bottle.tar.gz
Error: no implicit conversion of false into String
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:13:in `brewed_ld_so_diagnostics'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:23:in `sysconfdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:44:in `library_paths'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:165:in `find_full_lib_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `block in initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:213:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:213:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:222:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:115:in `block in check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/forwardable.rb:240:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:108:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:32:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:32:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2894:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2894:in `block in undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2893:in `undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2301:in `runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:828:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:238:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:210:in `upgrade_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:120:in `block in upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:119:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:119:in `upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:367:in `check_installed_dependents'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:320:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
  ```

### What did you expect to happen?

`eza` gets installed without any errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I cannot reproduce because eza did actually intall
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I think this is a bug in Ruby, but I've no idea how to track it down. I
can reproduce it intermittently in a codespace when `brew install`ing a
large number of formulae.

To work around this:
- cache the return value of `brewed_ld_so_diagnostics` so that we can
  limit the number of calls to `IO.popen`
- retry once when we see a `TypeError`

Closes #17828.

### CODE REVIEW

**Comment by Bo98** [comment]
Hmm definitely a hack alright, but at least we're getting closer by narrowing it down to this so thanks for finding it! I wonder if it's something specific to this or if it's just from this having a higher hit rate from the lack of caching.

Good to know it's reproducible in Codespaces. How consistently are you seeing this? What commands are you running that give a reasonable hit rate?

I'm willing to spend some time this afternoon to track down the precise (potentially Ruby) bug here.

File: Library/Homebrew/os/linux/ld.rb [hunk 1]
```diff
@@ -7,13 +7,35 @@ module Linux
...
+
+        # Check for `#nil?` here because @brewed_ld_so_diagnostics could be a blank string.
+        return @brewed_ld_so_diagnostics unless @brewed_ld_so_diagnostics.nil?
+
         brewed_ld_so = HOMEBREW_PREFIX/"lib/ld.so"
-        return "" unless brewed_ld_so.exist?
+        unless brewed_ld_so.exist?
+          @brewed_ld_so_diagnostics = ""
+          return @brewed_ld_so_diagnostics
+        end
```
Comment (Bo98) [inline Library/Homebrew/os/linux/ld.rb:20]: Does this behave correctly on fresh installs where this might not exist initially but does after the first dependency install?

`ld.so` should normally exist (it's created in the "global post-install") so doesn't seem like we want to cache the no-result.

**Comment by carlocab** [comment]
> How consistently are you seeing this? What commands are you running that give a reasonable hit rate?

I've seen it twice in the past two days (but that's also the number of times I've tried using a codespace to test something). I definitely triggered it with a `brew install gnupg`, and I also triggered it while running
```
brew install --only-dependencies --verbose --formula --build-bottle na-trium-144/webcface/webcface@2
```
to test out Homebrew/discussions#5607.

> I'm willing to spend some time this afternoon to track down the precise (potentially Ruby) bug here.

File: Library/Homebrew/os/linux/ld.rb (hunk 1 above)
Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb]: Haven't checked a fresh install, but not caching it seems the right move.

File: Library/Homebrew/os/linux/ld.rb [hunk 2]
```diff
@@ -7,13 +7,36 @@ module Linux
...
+
+        # Check for `#nil?` here because @brewed_ld_so_diagnostics could be a blank string.
+        return @brewed_ld_so_diagnostics unless @brewed_ld_so_diagnostics.nil?
+
         brewed_ld_so = HOMEBREW_PREFIX/"lib/ld.so"
         return "" unless brewed_ld_so.exist?
 
         ld_so_output = Utils.popen_read(brewed_ld_so, "--list-diagnostics")
-        return "" unless $CHILD_STATUS.success?
+        @brewed_ld_so_diagnostics = if $CHILD_STATUS.success?
```
Comment (Bo98) [inline Library/Homebrew/os/linux/ld.rb:20]: Ok reading this again has reminded me now why this wasn't cached. When we run `brew install hello` on a new system with an old glibc: the install cycle (ignoring `gcc` stuff) will be roughly: `linux-headers@5.15` then `glibc` then `hello`.

The first formula will set `ld.so` to system glibc and the second install will set `ld.so` to brewed `glibc`. So we may cache based on system glibc when it has changed under us to be a different glibc, which could result in failed linkage checks for the third formula if the system glibc is too old.

Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb:20]: But we can cache it if system `glibc` is new enough, right?

Comment (Bo98) [reply Library/Homebrew/os/linux/ld.rb:20]: Probably. Though `readlink` should be cheaper than checking that.

Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb:20]: Didn't see your latest edit -- could you sketch roughly what the `readlink` check should look like?

Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb]: Cached with a key based on the output of `#readlink` instead.

File: Library/Homebrew/os/linux/ld.rb [hunk 3]
```diff
@@ -7,13 +7,28 @@ module Linux
...
+          ld_so_output if $CHILD_STATUS.success?
+        end
+
+        @brewed_ld_so_diagnostics[brewed_ld_so_target].to_s
+      rescue TypeError
+        # Workaround for intermittent `Error: no implicit conversion of false into String`
+        unless @retried_brewed_ld_so_diagnostics&.fetch(brewed_ld_so_target, false)
+          @retried_brewed_ld_so_diagnostics ||= T.let({}, T.nilable(T::Hash[Pathname, T::Boolean]))
+          @retried_brewed_ld_so_diagnostics[brewed_ld_so_target] = true
+          sleep 0.5
```
Comment (MikeMcQuaid) [inline Library/Homebrew/os/linux/ld.rb:27]: Is the `sleep` needed here? Would be nice to make it as low as possible or even remove if possible.

File: Library/Homebrew/os/linux/ld.rb [hunk 4]
```diff
@@ -7,13 +7,28 @@ module Linux
...
-        return "" unless $CHILD_STATUS.success?
+        brewed_ld_so_target = brewed_ld_so.readlink
+        @brewed_ld_so_diagnostics[brewed_ld_so_target] ||= begin
+          ld_so_output = Utils.popen_read(brewed_ld_so, "--list-diagnostics")
+          ld_so_output if $CHILD_STATUS.success?
+        end
+
+        @brewed_ld_so_diagnostics[brewed_ld_so_target].to_s
+      rescue TypeError
+        # Workaround for intermittent `Error: no implicit conversion of false into String`
```
Comment (MikeMcQuaid) [inline Library/Homebrew/os/linux/ld.rb:23]:
```suggestion
        # Workaround for intermittent `Error: no implicit conversion of false into String`
        # link to issue with more context
```

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks @carlocab, looks good so far!

File: Library/Homebrew/os/linux/ld.rb (hunk 4 above)
Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb:23]:
```suggestion
        # Workaround for intermittent `Error: no implicit conversion of false into String`
        # https://github.com/Homebrew/brew/issues/17828
```

File: Library/Homebrew/os/linux/ld.rb (hunk 3 above)
Comment (carlocab) [reply Library/Homebrew/os/linux/ld.rb:28]: Given that the source of the bug is not clear, the `sleep` may or may not be needed. It seems much safer to leave it in, especially since this code path is traversed at most once for all users, and at most twice for users with an old system `glibc`.

And given that this seems to happen on a long-running (i.e. several minutes long) `brew install` call, another half second doesn't really make much of a difference.

**Comment by Bo98** [comment]
Haven't managed to even hit this once yet. I even did:
`brew ruby -e '1000.times { OS::Linux::Ld.brewed_ld_so_diagnostics }'`

With that said, this isn't even the only call site that triggers a `TypeError` anyway (https://github.com/Homebrew/brew/issues/15037) so probably doesn't make sense special casing that here. The higher likelihood of it happening her is probably be tied to the high call rate so we can probably slim this down to the cache changes which are good to have.

I will still try to track down the `TypeError` since it has been happening for years now.

**Comment by carlocab** [comment]
> this isn't even the only call site that triggers a `TypeError` anyway (#15037)

This backtrace suggests that the call site is close by (or possibly even refactored into `OS::Linux::Ld`), though: https://github.com/Homebrew/brew/issues/15037#issuecomment-1480774221

Not sure about the first one. But I'll drop the `retry` logic and see if it helps.

**Comment by Bo98** [comment]
`ld.so` popen is very new - was done a few months ago.

**Comment by carlocab** [comment]
> `ld.so` popen is very new - was done a few months ago.

Yup, but the second backtrace references `dynamically_linked_libraries` -- of which part has been refactored into here.

> Initial backtrace in that issue mentioned GCC post-install which also has several popen calls.

Wonder if we should just stop passing `Pathname`s to `Utils.popen_read`, which seems to be something in common across all of these.

**Comment by Bo98** [comment]
Possibly. A piece of information I'd love to know is if the `TypeError` is happening before, during or after the block is called.
