### PR TITLE
fix: fall back to stable deps when head_dependencies is absent

### LINKED ISSUE #21760: Installing from HEAD fails to download dependencies
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4135badeddc3899aa2e89d3ea1caee320c55d299
Last commit: 7 days ago
Branch: stable
Core tap JSON: 18 Mar 16:51 UTC
Core cask tap JSON: 18 Mar 16:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 16
HOMEBREW_EDITOR: hx
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 4.0.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.53.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.7.4-arm64
CLT: 26.3.0.0.1.1771626560
Xcode: 26.3
Metal Toolchain: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

Installing a formula from `HEAD`. I can reproduce the issue with every formula I tried, hence a bug report in this repo instead of `homebrew-core`.

I can reproduce not only on my system, but VMs which are clean except for Homebrew, on both Sequoia and Tahoe.

### What happened (include all command output)?

When trying to download dependencies, Homebrew acts as if they had already been downloaded but it cannot find them, failing the installation on the first one. Examples:

### vim

```console
$ brew install --HEAD vim
✔︎ JSON API formula.jws.json                                                                                                      Downloaded   32.0MB/ 32.0MB
✔︎ JSON API cask.jws.json                                                                                                         Downloaded   15.4MB/ 15.4MB
==> Fetching downloads for: vim
✔︎ API Source vim.rb                                                                                                              Verified      4.3KB/  4.3KB
✔︎ Formula vim (HEAD-c4d2122)
==> Installing vim dependency: lua@5.4
==> Pouring lua@5.4--5.4.8.arm64_sequoia.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/vm/Library/Caches/Homebrew/downloads/319790450e6fd3eefe99d4ce72adbda59e2b025e7110e65429910c7a239e02ce--lua@5.4--5.4.8.arm64_sequoia.bottle.tar.gz
```

### helix

```console
$ brew install --HEAD helix
==> Fetching downloads for: helix
✔︎ API Source helix.rb                                                                                                            Verified      2.1KB/  2.1KB
✔︎ Formula helix (HEAD-510edb5)
==> Installing dependencies for helix: libgit2, llvm@21 and rust
==> Installing helix dependency: libgit2
==> Pouring libgit2--1.9.2_1.arm64_sequoia.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/vm/Library/Caches/Homebrew/downloads/7c8f40716a7e08e3bbab11478c88b2247cb117a99596b980ae78d6fae0125c55--libgit2--1.9.2_1.arm64_sequoia.bottle.tar.gz
```

### mpv

```console
$ brew install --HEAD mpv
==> Fetching downloads for: mpv
✔︎ API Source mpv.rb                                                                                                              Verified      4.0KB/  4.0KB
✔︎ Formula mpv (HEAD-5f9e1bc)
==> Installing dependencies for mpv: docutils, ninja, meson, libarchive, shaderc, vulkan-headers, vulkan-loader, libplacebo, mujs, libsamplerate, mpg123, libsndfile, rubberband, uchardet, vapoursynth and molten-vk
==> Installing mpv dependency: docutils
==> Pouring docutils--0.22.4.all.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/vm/Library/Caches/Homebrew/downloads/44bd28cafc9d1a9d4c9accd07040697bc0f06442e93dd304f3c083dbd7ca7c4e--docutils--0.22.4.all.bottle.tar.gz
```

---

Running `brew fetch` to download all the dependencies before installing works. Workaround:

```console
$ brew fetch "${(@f)$(HOMEBREW_NO_ENV_HINTS=1 brew deps --include-build mpv)}" && brew install --HEAD mpv
```

### What did you expect to happen?

For dependencies to be fetched automatically and the installation to proceed without error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --HEAD vim
```

### PR DESCRIPTION
**Pull request by costajohnt**
- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open Pull Requests for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes?
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. Claude Code was used as a coding assistant for investigation and implementation. All code was reviewed and verified manually, including running the test suite locally.

## What does this PR do?

When `Formula#dependencies_hash` generates the API JSON, it intentionally omits `head_dependencies` when they're identical to stable deps (to save space). `FormulaStructGenerator#generate_formula_struct_hash` treated this absence as "no dependencies," passing `nil` to `process_dependencies_and_requirements` which returned empty arrays. This broke HEAD installs for any formula that inherits stable dependencies.

The fix falls back to `stable_dependency_hash` when `hash["head_dependencies"]` is nil, restoring the correct behavior where HEAD inherits stable deps unless explicitly overridden.

Fixes #21760

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense, thanks @costajohnt!

File: Library/Homebrew/api/formula/formula_struct_generator.rb [hunk 1]
```diff
@@ -164,8 +164,9 @@ def generate_formula_struct_hash(hash, bottle_tag: Homebrew::SimulateSystem.curr
             :stable,
           )
 
+          head_dependency_hash = hash["head_dependencies"] || stable_dependency_hash
```
Comment (Rylan12) [inline Library/Homebrew/api/formula/formula_struct_generator.rb:168]:
```suggestion
          # hash["head_dependencies"] is always present unless the stable and head deps are identical
          head_dependency_hash = hash["head_dependencies"] || stable_dependency_hash
```

**Comment by Rylan12** [comment]
Note to self: this should also fix the same issue with `HOMEBREW_REALLY_USE_INTERNAL_API` once this gets through the formulae.brew.sh re-generation
