### PR TITLE
cabextract: WARNING lines aren't fatal

### LINKED ISSUE #2689: Nested CAB containers fail on Warnings
- [X] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae?
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

I'm trying to install [this font cask formula](https://github.com/joeyhoer/homebrew-extras/blob/master/Casks/font-microsoft-office.rb), but homebrew cannot properly detect the nested container. *Note:* I've confirmed this is an issue with homebrew, not cask.

I've determined that the issue is a result of `cabextract` writing warnings (in addition to errors) to stderr. [Homebrew attempts to validate the cab file with `.stderr.empty?`](https://github.com/Homebrew/brew/blob/19347f3b87917368d7157fe5007d506a4db0c7db/Library/Homebrew/cask/lib/hbc/container/cab.rb#L13) which prevents the correct container type from being detected, and thus throws an error.

When the test is run:

    # Write only stderr to stdout
    $ cabextract -t -- ~/Library/Caches/Homebrew/Cask/font-microsoft-office--latest/ppviewer.cab 2>&1 >/dev/null
    /Library/Caches/Homebrew/Cask/font-microsoft-office--latest/ppviewer.cab: WARNING; possible 5968 extra bytes at end of file.

but the file is actually valid, with no errors, and returns a clean exit code:

    $ cabextract -t -- ~/Library/Caches/Homebrew/Cask/font-microsoft-office--latest/ppviewer.cab
     …
     All done, no errors.

### PR DESCRIPTION
**Pull request by mistydemeo**
Fixes #2689.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

As reported in #2689, it's possible for `cabextract` to issue non-fatal `WARNING`s to stderr. Right now cask's cab support treats that as an error, but it seems safe to filter that out. I confirmed the formula @joeyhoer was trying to install works with this patch.

### CODE REVIEW

File: Library/Homebrew/cask/lib/hbc/container/cab.rb [hunk 1]
```diff
@@ -8,9 +8,10 @@ class Cab < Base
       def self.me?(criteria)
         cabextract = which("cabextract")
 
+        # Ignores lines containing WARNING, but fails on other errors.
         criteria.magic_number(/^(MSCF|MZ)/n) &&
           !cabextract.nil? &&
-          criteria.command.run(cabextract, args: ["-t", "--", criteria.path.to_s]).stderr.empty?
+          criteria.command.run(cabextract, args: ["-t", "--", criteria.path.to_s]).stderr.split("\n").reject { |l| l.include? "WARNING" }.empty?
```
Comment (reitermarkus) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: The exit status is still `0` when there are warnings, right? If so, I think we can rely on the `exit_status` instead of checking the `stderr` output.

Also – highly unlikely to happen – this would fail if the file path contained “WARNING” and the exit code was non-zero.

Comment (mistydemeo) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: Hah, good point! I'll change it to an exit status check.

Just to make sure, is this an `stderr` check because errors can exit 0?

Comment (reitermarkus) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: > Just to make sure, is this an `stderr` check because errors can exit 0?

I really don't know, sorry.

Then again, I think we could remove this whole check, since it is also unlikely that the magic number matches, but it isn't a `cab` container. In the “worst” case, it will then fail when extracting it.

Comment (mistydemeo) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: Good idea, removed the check.

**Comment by reitermarkus** [comment]
Actually I meant removing everything except for the magic number check.

**Comment by mistydemeo** [comment]
Oh, of course! Removed.

File: Library/Homebrew/cask/lib/hbc/container/cab.rb [hunk 2]
```diff
@@ -8,9 +8,7 @@ class Cab < Base
       def self.me?(criteria)
         cabextract = which("cabextract")
```
Comment (reitermarkus) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: This is not needed anymore.

Comment (mistydemeo) [inline Library/Homebrew/cask/lib/hbc/container/cab.rb]: Removed.
