### PR TITLE
Fix autoremoving formulae still needed by dependencies

### LINKED ISSUE #21511: brew cleanup says libthai can be removed, but at the same time it is needed by pango
### `brew config` AND `brew doctor` output OR `brew gist-logs <formula>` link

```shell
brew config
HOMEBREW_VERSION: 5.0.13-26-g7788a02
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7788a02932f30f66b18b1caecbc239c4d954d88f
Last commit: 3 hours ago
Branch: main
Core tap JSON: 03 Feb 09:13 UTC
Core cask tap JSON: 03 Feb 09:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.NNI39sRQTP/org.xquartz:0
HOMEBREW_DOWNLOAD_CONCURRENCY: 16
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.18.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 26.2-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: N/A
Rosetta 2: false



brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  fontsmoothingadjuster
  zeronet

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  antigen
  icu4c@77
  tldr
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

I try to clean unnecessary packages. I think it is related to this commit:

https://github.com/Homebrew/homebrew-core/commit/d00616124646e6547a82839883c8a3c5aa6f3dd3

### What happened (include all command output)?

```
brew cleanup
==> Autoremoving 4 unneeded formulae:
cyrus-sasl
libdatrie
libthai
pydantic
Error: Refusing to uninstall /opt/homebrew/Cellar/libdatrie/0.2.14 and /opt/homebrew/Cellar/libthai/0.1.30
because they are required by pango, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies
```

### What did you expect to happen?

That will remove the unnecessary packages

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew cleanup
```

### PR DESCRIPTION
**Pull request by jpmsantana**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

-----

The logic that unneeded says a package is unnamed is different to how uninstall dependencies check work. That's a good explanation on how this package appears in one side and not the other.

Claude Code assisted me when working on this PR.

Fixes #21511

### CODE REVIEW

File: Library/Homebrew/cleanup.rb [hunk 1]
```diff
@@ -780,6 +781,13 @@ def self.autoremove(dry_run: false)
 
       removable_formulae = Utils::Autoremove.removable_formulae(formulae, casks)
 
+      kegs = removable_formulae.filter_map(&:any_installed_keg)
+      if kegs.any? && (result = InstalledDependents.find_some_installed_dependents(kegs, casks:))
+        required_kegs, = result
+        required_names = required_kegs.to_set(&:name)
+        removable_formulae = removable_formulae.reject { |f| required_names.include?(f.name) }
+      end
```
Comment (MikeMcQuaid) [inline Library/Homebrew/cleanup.rb]: This logic should live in https://github.com/Homebrew/brew/blob/main/Library/Homebrew/utils/autoremove.rb.

It looks like there's already an attempt at the same logic in here so it's unclear why it's not working?

Comment (jpmsantana) [reply Library/Homebrew/cleanup.rb]: Gave it some extra look and found that the `bottled_formulae_with_no_formula_dependents` was working like this:

- For each formula, it calls `installed_runtime_formula_dependencies` and adds those to a `formulae_to_keep` list.
- Then it does `formulae - formulae_to_keep` to find removable ones.

For two Formula objects to be considered "the same", Ruby checks both the `name` and `active_spec_sym`. That said, `formulae` comes from `Formula.installed`, while `formulae_to_keep` is built from `installed_runtime_formula_dependencies`, which creates fresh objects via `Formulary.resolve()`. If these two instances end up with a different `active_spec_sym` (e.g. one says `:stable`, the other says `:head`), Ruby considers them not equal — even though they represent the same formula. That causes the silent error, as far as I understood.

Transferring the solution there.

**Review by MikeMcQuaid — APPROVED** [review]
