### PR TITLE
cask_reason will suggest `brew cask uninstall`

### LINKED ISSUE #6260: Cask uninstall fallback/suggestions
# A detailed description of the proposed feature

When attempting to uninstall a cask with incorrect syntax a generic error message is displayed:

```shell
$ brew uninstall discord
Error: No such keg: /usr/local/Cellar/discord
```

A more useful error message might be to suggest the correct syntax:

```shell
$ brew uninstall discord
Found a cask named "discord" instead. Try `brew cask uninstall discord`
```

This would be just like the error-handling behavior exhibited when incorrectly installing a cask:

```shell
$ brew install discord
Error: No available formula with the name "discord-canary"
Found a cask named "discord-canary" instead.
```

# The motivation for the feature

I was removing a brew-installed application that stopped working and I was stumped for much longer than I would have imagined when seeing the error message above. Although I was well-aware of the need to specify `cask` when installing, I don't remember ever needing to use it when uninstalling.

I thought, because the app had totally broken, that some permissions issues might be preventing uninstall. And so I tried with the `--force` flag, which has does not fail and so has no output whatsoever. Then I was even more confused for a bit.

# How the feature would be relevant to at least 90% of Homebrew users

Any user that forgets `cask` syntax should be provided some hint towards using `brew` with success.

# What alternatives to the feature have been considered

As there should be no namespace conflicts, it might even be more beneficial to users to simply fallback to removing the cask installed application, rather than forcing the syntax change.

### PR DESCRIPTION
**Pull request by zachauten**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
Closes #6260

### CODE REVIEW

**Comment by zachauten** [comment]
Still a work in progress, just opening the pull request to get some suggestions. @MikeMcQuaid I know you mentioned not wanting to use `Homebrew.args` in #6247, would you mind explaining the reasoning behind that?

I'm using it here temporarily out of convenience because this PR introduces a second conditional that depends on the command brew was called with (`brew uninstall` uses `Cask::Caskroom.casks` while `brew install` & `brew info` use `Cask::CaskLoader.load`)

File: Library/Homebrew/extend/os/mac/missing_formula.rb [hunk 1]
```diff
@@ -14,20 +19,33 @@ def blacklisted_reason(name)
...
+
+        name if Cask::Caskroom.casks.any? { |cask| cask.to_s == name }
+        raise Cask::CaskUnavailableError, name
+      end
+
+      # how to handle multiple formulae where only one is installed as a cask?
+      def suggest_command(cask, command)
+        case command
+        when "install" || "uninstall"
+          "Try \"brew cask #{command} #{cask}\".\n"
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/os/mac/missing_formula.rb]: Use `<<~EOS` instead of hardcoding `n` and escaping `"`. I'd also recommend using backticks or a new line when suggesting commands.

File: Library/Homebrew/extend/os/mac/missing_formula.rb [hunk 2]
```diff
@@ -14,20 +19,33 @@ def blacklisted_reason(name)
...
       end
+
+      def find_cask(name, installed)
+        return Cask::CaskLoader.load(name) unless installed
+
+        name if Cask::Caskroom.casks.any? { |cask| cask.to_s == name }
+        raise Cask::CaskUnavailableError, name
+      end
+
+      # how to handle multiple formulae where only one is installed as a cask?
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/os/mac/missing_formula.rb]: I'm not sure I understand this?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid I know you mentioned not wanting to use `Homebrew.args` in #6247, would you mind explaining the reasoning behind that?

It's global state that's better passed explicitly to the class rather than handled implicitly like this. That will make it easier to test and refactor in future.

File: Library/Homebrew/extend/os/mac/missing_formula.rb (hunk 2 above)
Comment (zachauten) [reply Library/Homebrew/extend/os/mac/missing_formula.rb]: Sorry, that was just a note to myself that I forgot to remove. I was considering the use case where someone is uninstalling multiple formulae at once and one or more of them is an installed cask, and how that should be handled.

**Comment by MikeMcQuaid** [comment]
Looks great, thanks again @zachauten!
