### PR TITLE
linux/diagnostic: fix `rpath` returning `nil`.

### LINKED ISSUE #13762: brew doctor -> undefined method `split' for nil:NilClass
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.10-51-g7617109
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7617109d43060aa0225f774bad9971bcbd166e15
Last commit: 10 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 08444116f4472540d4738e1c85b338e534fa86f0
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit zen3
Clang: 14.0.6
Git: 2.37.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/xxx/.local/bin/ansible-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  six
Error: undefined method `split' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:156:in `block (2 levels) in check_gcc_dependent_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:155:in `any?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:155:in `block in check_gcc_dependent_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:153:in `select'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:153:in `check_gcc_dependent_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I always run brew doctor after my upgrades and for a couple of days now it's been throwing above mentioned error.

### What happened (include all command output)?

`brew doctor`

> Error: undefined method `split' for nil:NilClass

### What did you expect to happen?

Some warnings but no errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew doctor`
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #13762.

There's still a bug in the GCC linkage check, but I'll need a bit more
time to work on a fix. This at least makes sure `brew doctor` will not
return the error in the issue linked above.

### CODE REVIEW

File: Library/Homebrew/os/linux/elf.rb [hunk 1]
```diff
@@ -97,7 +97,7 @@ def rpath
   # An array of runtime search path entries, such as:
   # ["/lib", "/usr/lib", "/usr/local/lib"]
   def rpaths
-    rpath.split(":")
+    rpath&.split(":").to_a
```
Comment (MikeMcQuaid) [inline Library/Homebrew/os/linux/elf.rb:100]:
```suggestion
    Array(rpath&.split(":"))
```

might be cleaner

**Review by MikeMcQuaid — APPROVED** [review]
Looks good! Suggested but optional style tweak, take it or leave it.

**Comment by black-snow** [comment]
Thanks for the quick help - looking forward to it
