### PR TITLE
uses: properly handle untapped formulae in recursive dependency expansion

### LINKED ISSUE #1776: `brew uses` with `--include-optional` doesn't return used formula
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

When I run `brew uses` with `--include`, it doesn't find a formula that is actually used.

```
$ brew uses --installed --include-build --recursive unixodbc
homebrew/php/php70

$ brew uses --installed --include-build --include-optional --recursive unixodbc

$
```

Notice that unixodc is used by php70, but when I run the `uses` command with `--include-optional`, the command no longer shows php70 as using unixodbc.

`brew config`:

```
$ brew config
HOMEBREW_VERSION: 1.1.6-2-gfc11f633b2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fc11f633b29e6a2c9c4d49d5fd5452549b328193
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0a6cce09b2ff3e50128d2e0d3887b12f5bf78368
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_65, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

`brew doctor` (I can't upgrade Xcode because I'm still on El Capitan):

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Found Ruby file outside beeftornado/rmtree tap formula directory
(/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/Formula):
  /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/brew-rmtree.rb

Warning: Your Xcode (8.1) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
```

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #1776.

If any known formula had a dependency on an untapped tap, `Formula#recursive_dependencies` would throw an exception, which would be caught by the outer exception handler, causing the rest of the dependencies for that formula to be skipped and incomplete output to be generated.

To fix this, I added a check to avoid analysing the dependencies of formulae from uninstalled taps.

Additionally, I removed the aforementioned outer exception handler added in 5fdb89a, because the only other place that should be capable of throwing such an exception is the
statement that was surrounded by another wider exception handler in Homebrew/legacy-homebrew#40682. I verified that the example failures in https://github.com/Homebrew/legacy-homebrew/issues/40636 have still not returned even with this change.

Also, `TapDependency#tap` previously returned a `String`, but a `Tap` instance seemed more sensible and useful, so I changed it. I couldn't find anywhere this method was actually used, so the change
shouldn't break anything.

### CODE REVIEW

File: Library/Homebrew/cmd/uses.rb [hunk 1]
```diff
@@ -47,48 +47,49 @@ def uses
...
-              ignores.any? { |ignore| dep.send(ignore) } && !includes.any? { |include| dep.send(include) }
-            end
-            reqs = f.requirements.reject do |req|
-              ignores.any? { |ignore| req.send(ignore) } && !includes.any? { |include| req.send(include) }
+
+            # If a tap isn't installed, we can't find the dependencies of one
+            # its formulae, and an exception will be thrown if we try.
+            if dep.is_a?(TapDependency) && !dep.tap.installed?
+              Dependency.keep_but_prune_recursive_deps
             end
```
Comment (alyssais) [inline Library/Homebrew/cmd/uses.rb]: Because I removed an enclosing block and outdented its contents, the diff is a bit messy, so I'll highlight my actual code changes here.

This is where I added the check to avoid the exception when a dependency is untapped.

File: Library/Homebrew/cmd/uses.rb [hunk 2]
```diff
@@ -47,48 +47,49 @@ def uses
...
+          begin
+            dep.to_formula.full_name == ff.full_name
+          rescue
+            dep.name == ff.name
+          end
+        end
+
+        reqs.any? do |req|
+          req.name == ff.name || [ff.name, ff.full_name].include?(req.default_formula)
         end
```
Comment (alyssais) [inline Library/Homebrew/cmd/uses.rb]: This is where I removed the `rescue FormulaUnavailableError` that is no longer necessary.

**Comment by alyssais** [comment]
Not sure what to do about the coverage. There's already an integration test and all I did to most of the diff was change its indentation.

File: Library/Homebrew/cmd/uses.rb (hunk 1 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/uses.rb]: For anyone else following along: https://github.com/Homebrew/brew/pull/1784/files?w=1 makes it a lot easier to follow.

**Comment by MikeMcQuaid** [comment]
Great work again @alyssais!

File: Library/Homebrew/cmd/uses.rb (hunk 2 above)
Comment (MikeMcQuaid) [inline Library/Homebrew/cmd/uses.rb]: Unfortunately it looked like it still was so need to revert this 😭
