### PR TITLE
Anonymous OCI registry mirror support 

### LINKED ISSUE #16669: Docker registry token defaults to "A"
### `brew doctor` output

```shell
bash-3.2$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
bash-3.2$ brew config
HOMEBREW_VERSION: >=4.1.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap JSON: 14 Feb 20:32 UTC
Core cask tap JSON: 14 Feb 20:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_ARTIFACT_DOMAIN: https://myrepository.com/artifactory/homebrew-remote
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.2 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Connect to a private repository using anonymous access

### What happened (include all command output)?

The default Authorization: Bearer token sent is QQ== ("A"). As a result anonymous access fails.

> bash-3.2$ brew install openjdk@17 --verbose
> ==> Downloading https://myrepository.com/artifactory/homebrew-remote/v2/homebrew/core/openjdk/17/manifests/17.0.9
> Already downloaded: /Users/homebrew/Library/Caches/Homebrew/downloads/6274f55d293c4208920a5d52b3b06d4a9dedb0e7139b671f4f66fada2abbc486--openjdk@17-17.0.9.bottle_manifest.json
> ==> Fetching openjdk@17
> ==> Downloading https://myrepository.com/artifactory/homebrew-remote/v2/homebrew/core/openjdk/17/blobs/sha256:41eda5749bf9032865a1168a0306a5b089f3098433dc1b95eebe82bedb98f023
> /usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.6\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --header Authorization:\ Bearer\ QQ== --remote-time --output /Users/homebrew/Library/Caches/Homebrew/downloads/0979b1d425479e75863f78205c409052fa471b62c25cf53cdb97a96be46c5152--openjdk@17--17.0.9.arm64_ventura.bottle.tar.gz.incomplete --location https://myrepository.com/artifactory/homebrew-remote/v2/homebrew/core/openjdk/17/blobs/sha256:41eda5749bf9032865a1168a0306a5b089f3098433dc1b95eebe82bedb98f023
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0   101    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 401
> Error: openjdk@17: Failed to download resource "openjdk@17"
> Download failed: https://myrepository.com/artifactory/homebrew-remote/v2/homebrew/core/openjdk/17/blobs/sha256:41eda5749bf9032865a1168a0306a5b089f3098433dc1b95eebe82bedb98f023

### What did you expect to happen?

The request does not attempt to send an auth header because there is no token setup. Why is the default token "A"?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Configure brew to use a private repository using HOMEBREW_ARTIFACT_DOMAIN
2. Attempt to install a package
3. The install fails since an invalid auth header is sent
```

### PR DESCRIPTION
**Pull request by byjrack**
Fixes #16669

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?

Currently an Authorization header is added to all requests for CurlGithubPackageDownload.  It includes the contents of an `ARTIFACT_TOKEN` auth var or "A" which is used for access to ghcr.io.  This causes an issue though if you host a private mirror of GHCR where auth is optional.  This adds a conditional where for 7 of the 8 cases it adds the header, but for the 1 where you have a `DOMAIN` set and not `TOKEN`s it will skip adding the header.

- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).

I couldn't figure out a great way to test this given the environmental aspects, but I am up for suggestions and can tweak the PR to fit.

- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by byjrack** [comment]
So may need a pointer on this one.  Was able to get the `style` stuff taken care of, but not sure if I follow the issue with the tests output.  Is that because i didn't add a new test for this specific scenario?

**Comment by byjrack** [comment]
Any maintainer have any pointers on what changes I need to add for the failed CI task?  Happy to give it another shot, but not sure I am following what is being flagged.

**Comment by MikeMcQuaid** [comment]
Was just a flaky test issue, resolved after rerun.

Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @byjrack!

File: Library/Homebrew/download_strategy.rb [hunk 1]
```diff
@@ -705,7 +705,12 @@ def initialize(url, name, version, **meta)
     meta[:headers] ||= []
     # GitHub Packages authorization header.
     # HOMEBREW_GITHUB_PACKAGES_AUTH set in brew.sh
-    meta[:headers] << "Authorization: #{HOMEBREW_GITHUB_PACKAGES_AUTH}"
+    # If using a private GHCR mirror with no Authentication set than do not add the header. In all other cases add it.
```
Comment (EricFromCanada) [inline Library/Homebrew/download_strategy.rb:708]:
```suggestion
    # If using a private GHCR mirror with no Authentication set then do not add the header. In all other cases add it.
```

**Review by carlocab — APPROVED** [review]
