### PR TITLE
shellenv: check that Homebrew's prefix precedes `/usr/bin`

### LINKED ISSUE #11851: brew shellenv does not return any output
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.6-102-g9fe6427
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fe642759c9c4772d50cee279665422f7f403530
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 922c1e06b378613fd5ebb980d8ee6bd4d1143574
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/dweller/bin/sub -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  phpize
  git-receive-pack
  python3
  phar.phar
  pip3
  phar
  rsync
  git-upload-archive
  php
  tidy
  git-shell
  git-upload-pack
  git
  php-config

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to configure my shell PATH

### What happened (include all command output)?

`brew shellenv` returns no output

```
~ /opt/homebrew/bin/brew shellenv
~
```

### What did you expect to happen?

export shell environment configurations

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/opt/homebrew/bin/brew shellenv
```

### LINKED ISSUE #11883: brew broken in tmux from shellenv
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0e63fb8200d54e365cfb20eb8c7a98620b23b42f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c4568afa9224efb2a343c40f8cd00366c1512227
Core tap last commit: 26 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.1 build (parse error)
Git: 2.32.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-27-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libva-internal

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  //home/ANT.AMAZON.COM/rothgar/.cargo/bin/cargo-install-update-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libvdpau
  six
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
Warning: Use libvdpau instead of deprecated linuxbrew/xorg/libvdpau
Warning: Use wayland-protocols instead of deprecated linuxbrew/xorg/wayland-protocols
Warning: Use wayland instead of deprecated linuxbrew/xorg/wayland
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Open a terminal and then start a tmux session.

### What happened (include all command output)?

The initial terminal works but the tmux session does not have brew available or any brew commands in path

It appears to be related to #11789
If I unset `HOMEBREW_SHELLENV_PREFIX` in my zshrc then the shellenv command works and brew is available inside tmux.

homebrew

### What did you expect to happen?

Ability to still run brew inside a tmux session.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Please see attached gif.

1. open a terminal
1. open tmux

It works if I
1. open a terminal
1. `unset HOMEBREW_SHELLENV_PREFIX` inside .zshrc
1. open tmux
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Some setups (e.g. a default `tmux` session) will result in a user
starting multiple nested login shells. This is a problem for the way we
currently handle `shellenv` because a login shell invokes
`/usr/libexec/path_helper` which will prepend the contents of
`/etc/paths` and `/etc/paths.d` to `PATH`. In particular, the second
login shell will place `brew` further down the `PATH` than desired in a
non-`/usr/local` prefix, since `brew shellenv` will no longer produce
output the second time around.

Let's fix this by replacing the check that `brew` is in `PATH` with a
check that `${HOMEBREW_PREFIX}/bin` precedes `/usr/bin` in `PATH`.

Fixes #11851
Fixes #11883
Fixes Homebrew/discussions#2547.

See also:
- Homebrew/discussions#2237
- https://superuser.com/questions/544989/does-tmux-sort-the-path-variable

### CODE REVIEW

File: Library/Homebrew/cmd/shellenv.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@
 # shellcheck disable=SC2154
 homebrew-shellenv() {
   if [[ "${HOMEBREW_SHELLENV_PREFIX}" == "${HOMEBREW_PREFIX}" ]] &&
-     [[ "$(PATH="${HOMEBREW_PATH}" command -v brew)" == "${HOMEBREW_PREFIX}/bin/brew" ]]
+     [[ "${HOMEBREW_PATH%%/usr/bin:*}" == *"${HOMEBREW_PREFIX}/bin"* ]]
```
Comment (XuehaiPan) [inline Library/Homebrew/cmd/shellenv.sh:14]:
```suggestion
     [[ "$(PATH="${HOMEBREW_PATH}" command -v brew)" == "${HOMEBREW_PREFIX}/bin/brew" ]] &&
     [[ "${HOMEBREW_PATH%%/usr/bin:*}" == *"${HOMEBREW_PREFIX}/bin"* ]]
```

It's still worth to check the `brew` executable, because `HOMEBREW_SHELLENV_PREFIX` can be inherited to the child process. `brew shellenv` could produce empty output on multiple installation setup.

Comment (carlocab) [reply Library/Homebrew/cmd/shellenv.sh:14]: This would matter when
```bash
[[ "$(PATH="${HOMEBREW_PATH}" command -v brew)" == "${HOMEBREW_PREFIX}/bin/brew" ]]
```
false but
```bash
[[ "${HOMEBREW_PATH%%/usr/bin:*}" == *"${HOMEBREW_PREFIX}/bin"* ]]
```
is true. Could you give an example when this is the case? It clearly only applies if you have multiple installations of `brew`, as you point out.

Comment (XuehaiPan) [reply Library/Homebrew/cmd/shellenv.sh:14]: Some users set `PATH` to a fixed value at the beginning of their shell profile rather than prepend or append entries to it. Then they run `eval "$(brew shellenv)"` to get the remaining paths (e.g. `MANPATH`).

Comment (XuehaiPan) [reply Library/Homebrew/cmd/shellenv.sh:14]:
```suggestion
     [[ ":${HOMEBREW_PATH%%/usr/bin:*}:" == *":${HOMEBREW_PREFIX}/bin:"* ]]
```

Comment (carlocab) [reply Library/Homebrew/cmd/shellenv.sh:14]: > Some users set `PATH` to a fixed value at the beginning of their shell profile rather than prepend or append entries to it. Then they run `eval "$(brew shellenv)"` to get the remaining paths (e.g. `MANPATH`).

I'm confused -- how would this make
```bash
[[ "$(PATH="${HOMEBREW_PATH}" command -v brew)" == "${HOMEBREW_PREFIX}/bin/brew" ]]
```
be false but
```bash
[[ "${HOMEBREW_PATH%%/usr/bin:*}" == *"${HOMEBREW_PREFIX}/bin"* ]]
```
be true?

The typical case of the scenario you're describing is that they're either both true or both false. There is the odd case where the first is true but the second is false, but that's for a user that's deliberately putting `/usr/bin` ahead of `${HOMEBREW_PREFIX}/bin`, so I doubt that user is calling `brew shellenv`.

As for your suggestion: I'm not sure it's correct since I don't strip `:` in front of `/usr/bin` on purpose, so the left-hand side will usually look something like `:foo:bar:baz::`. It probably won't matter because of the `*` globs on either side, but then I'm not sure what it really adds.

**Review by MikeMcQuaid — APPROVED** [review]

File: Library/Homebrew/cmd/shellenv.sh (hunk 1 above)
Comment (XuehaiPan) [reply Library/Homebrew/cmd/shellenv.sh:14]: In shell profile:

```bash
export PATH="/prefix2/bin:/prefix1/bin:...:/usr/bin:..."
eval "$(/prefix1/bin/brew shellenv)"
eval "$(/prefix2/bin/brew shellenv)"
```

the `PATH` is set to fixed value first, then be updated by `eval ...`.

```console
shlvl1 $ # brew in prefix2 is default and `HOMEBREW_SHELLENV_PREFIX` is prefix2

shlvl1 $ eval "$(/prefix1/bin/brew shellenv)"
shlvl1 $ # now brew in prefix1 is default and `HOMEBREW_SHELLENV_PREFIX` is prefix1

shlvl1 $ bash -l

shlvl2 $
```

in the child process, the first shellenv command will output empty result.

------

The two `:` added to the right side is to match the exact entry we want.

Comment (carlocab) [reply Library/Homebrew/cmd/shellenv.sh:14]: How about just checking whether `$HOMEBREW_PREFIX/bin` comes first in `PATH`, as it would after doing `eval $(brew shellenv)`?

Comment (XuehaiPan) [reply Library/Homebrew/cmd/shellenv.sh:14]: > How about just checking whether `$HOMEBREW_PREFIX/bin` comes first in `PATH`, as it would after doing `eval $(brew shellenv)`?

If so, we will not need the variable `HOMEBREW_SHELLENV_PREFIX` anymore. It was introduced for making `eval "$(brew shellenv)"` idempotent.

```bash
eval "$(brew shellenv)"
export PATH="${HOMEBREW_PREFIX}/opt/formula/bin:${PATH}"  # add some keg-only formula to PATH

...

eval "$(brew shellenv)"  # added by `echo 'eval "$(brew shellenv)"' >> ~/.profile`
```

Comment (carlocab) [reply Library/Homebrew/cmd/shellenv.sh]: Ok, let's check that it comes first in `PATH`. Not having to carry around `HOMEBREW_SHELLENV_PREFIX` is nice to have.

**Review by MikeMcQuaid — APPROVED** [review]
