### PR TITLE
cmd/list.rb: --formula and --cask as default option on TTY

### LINKED ISSUE #8910: zsh completion error for brew list
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

type `brew list --` and press tab for completion

## What happened (include command output)

<details>
  <summary>An error shows then the completion comes out</summary>
  <pre>
$ brew list --zsh: command not found: __brew_installed_casks
--cask       -- list installed Casks
--full-name  -- print formulae with fully-qualified names
--multiple   -- only show formulae with multiple versions installed
--pinned     -- list all versions of pinned formulae
--unbrewed   -- files in brew --prefix not controlled by brew
--versions   -- list all installed versions of a formula
  </pre>
</details>

## What you expected to happen

Should not have error

## Step-by-step reproduction instructions (by running `brew` commands)

1. open a new terminal
2. type `brew list --`
3. press tab key

First step is important. I found that if I type `brew cask` and press tab, the function `__brew_installed_casks` defined in `completions/zsh/_brew_cask` will be loaded, so the error wouldn't show.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.5.6-2-gb8a9327
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8a93279fd31b0569a9046f61df0da0121ce4df5
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff6bc4c14783b56dbd2686e1ee866aec5ad3185c
Core tap last commit: 60 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 11.0 build 1100
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.2, 1.8.0_265
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  chunkwm
</pre>

### PR DESCRIPTION
**Pull request by Akylzhan**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----
Added clarifications suggested in https://github.com/Homebrew/brew/issues/8668#issuecomment-689895068

Fixes #8910

### CODE REVIEW

**Comment by reitermarkus** [comment]
I suggested this: https://github.com/Homebrew/brew/issues/8668#issuecomment-692151553

**Comment by reitermarkus** [comment]
Basically:

- Show everything when `stdout` is a TTY.
- When `stdout` is not a TTY, show only formulae and print a warning that this behaviour is deprecated and `--formulae` should be passed explicitly.

**Comment by Akylzhan** [comment]
> Basically:
> 
> * Show everything when `stdout` is a TTY.
> * When `stdout` is not a TTY, show only formulae and print a warning that this behaviour is deprecated and `--formulae` should be passed explicitly.

Sorry, did not notice your comment. But I have replied here https://github.com/Homebrew/brew/issues/8668#issuecomment-703309088
Also, will update manpages tomorrow

File: Library/Homebrew/cmd/list.rb [hunk 1]
```diff
@@ -86,7 +86,13 @@ def list
         ls_args << "-r" if args.r?
         ls_args << "-t" if args.t?
 
-        safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        if !$stdout.tty? && !args.formula?
+          puts "Explicitly passed --formula since no TTY detected."
```
Comment (reitermarkus) [inline Library/Homebrew/cmd/list.rb:90]:
```suggestion
          opoo "Calling `brew ls` to only list formulae is deprecated, pass `--formula` explicitly instead."
```

Comment (Akylzhan) [reply Library/Homebrew/cmd/list.rb]: Oh, thanks, done

**Comment by reitermarkus** [comment]
Probably the `bash`/`zsh` completions need to be changed to use `--formula`.

**Comment by Akylzhan** [comment]
Also, I have a question, how to modify manpages? Should I write the changes in docs/ folder and then apply `brew man`?

**Comment by reitermarkus** [comment]
Yes, just run `brew man` and commit the changes.

**Comment by Akylzhan** [comment]
Also, how to test only list_spec.rb? `brew tests only=list_spec.rb` does not work if I am in `test/cmd` folder

**Comment by reitermarkus** [comment]
`brew tests --only=cmd/list`

File: Library/Homebrew/cmd/list.rb [hunk 2]
```diff
@@ -86,7 +86,13 @@ def list
         ls_args << "-r" if args.r?
         ls_args << "-t" if args.t?
 
-        safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        if !$stdout.tty? && !args.formula?
+          odeprecated "`brew list` to only list formulae", "`brew list --formula`"
+          safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        else
+          safe_system "ls", *ls_args, HOMEBREW_CELLAR
```
Comment (reitermarkus) [inline Library/Homebrew/cmd/list.rb:93]:
```suggestion
          safe_system "ls", *ls_args, HOMEBREW_CELLAR unless args.cask?
```

Comment (reitermarkus) [inline Library/Homebrew/cmd/list.rb:93]: This will always print formulae, even if *only* `--cask` is passed.

File: Library/Homebrew/cmd/list.rb [hunk 3]
```diff
@@ -33,9 +33,9 @@ def list_args
              description: "Show the versions of pinned formulae, or only the specified (pinned) "\
                           "formulae if <formula> are provided. See also `pin`, `unpin`."
       switch "--formula", "--formulae",
-             description: "List only formulae."
+             description: "List only formulae. `This is the default action on non TTY.`"
```
Comment (reitermarkus) [inline Library/Homebrew/cmd/list.rb:36]: Remove the backticks.

File: Library/Homebrew/cmd/list.rb (hunk 2 above)
Comment (Akylzhan) [reply Library/Homebrew/cmd/list.rb:93]: I have thought that it does not go after this line of code: https://github.com/Homebrew/brew/blob/f84b9a02753e240b4701a6969d0f912c32e61240/Library/Homebrew/cmd/list.rb#L60

Comment (reitermarkus) [reply Library/Homebrew/cmd/list.rb:93]: You're right.

File: Library/Homebrew/cmd/list.rb [hunk 4]
```diff
@@ -86,7 +86,13 @@ def list
         ls_args << "-r" if args.r?
         ls_args << "-t" if args.t?
 
-        safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        if !$stdout.tty? && !args.formula?
+          odeprecated "`brew list` to only list formulae", "`brew list --formula`"
+          safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        else
+          safe_system "ls", *ls_args, HOMEBREW_CELLAR
+          print list_casks(args: args) unless args.formula?
```
Comment (reitermarkus) [inline Library/Homebrew/cmd/list.rb:94]:
```suggestion
         list_casks(args: args) unless args.formula?
```

Comment (Akylzhan) [reply Library/Homebrew/cmd/list.rb]: Hm, it throws error because it return list_casks and not list Cellar, right?

**Review by MikeMcQuaid — APPROVED** [review]
CI is 💚. I'm 👍🏻 once @reitermarkus is.

**Comment by MikeMcQuaid** [comment]
Merging as this fixes #8910. 

Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Akylzhan!

File: Library/Homebrew/cmd/list.rb [hunk 5]
```diff
@@ -86,7 +86,13 @@ def list
         ls_args << "-r" if args.r?
         ls_args << "-t" if args.t?
 
-        safe_system "ls", *ls_args, HOMEBREW_CELLAR
+        if !$stdout.tty? && !args.formula?
+          odeprecated "`brew list` to only list formulae", "`brew list --formula`"
```
Comment (scpeters) [inline Library/Homebrew/cmd/list.rb:90]: this `odeprecated` call was converted to `odisabled` in #9209; I've opened https://github.com/Homebrew/brew/pull/9357 to revert that change so it will remain `odeprecated` for 2.6.0
