### PR TITLE
shellenv: export FPATH so child zsh shells inherit fpath

### LINKED ISSUE #21879: `brew shellenv` idempotency check skips `fpath` setup in child/nested zsh shells
### `brew doctor` output

```
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```
HOMEBREW_VERSION: 5.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3a946229d190966cd725d5cc65e272d279a398ed
Last commit: 31 hours ago
Branch: stable
Core tap JSON: 01 Apr 04:58 UTC
Core cask tap JSON: 01 Apr 04:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /var/run/com.apple.launchd.nHdvo6frK8/org.xquartz:0
HOMEBREW_DOWNLOAD_CONCURRENCY: 36
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 18
Homebrew Ruby: 4.0.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.2_1/bin/ruby
CPU: 18-core 64-bit dunno
Clang: 21.0.0 build 2100
Git: 2.50.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.4-arm64
CLT: 26.3
Xcode: 26.4
Rosetta 2: false
```

### What were you trying to do (and why)?

I have `eval "$(brew shellenv zsh)"` in both my `~/.zprofile` (as recommended) and `~/.zshrc`. I use Zellij (a terminal multiplexer) inside Ghostty. Zellij spawns non-login zsh shells for its panes, so only `~/.zshrc` runs — not `~/.zprofile`.

I expected `eval "$(brew shellenv zsh)"` in my `.zshrc` to set up zsh completions for brew-installed tools (bat, zellij, ripgrep, etc.) by adding `/opt/homebrew/share/zsh/site-functions` to `fpath`.

### What happened (include all command output)?

`brew shellenv zsh` produces **no output** in Zellij panes (and in any nested/child zsh shell), because `PATH` already contains `/opt/homebrew/bin` — inherited from the parent shell's environment.

The [early return in `shellenv.sh`](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/cmd/shellenv.sh#L8-L11) skips **all** output, including the zsh-specific `fpath[1,0]=` line:

```sh
if [[ "${HOMEBREW_PATH%%:"${HOMEBREW_PREFIX}"/sbin*}" == "${HOMEBREW_PREFIX}/bin" ]]
then
  return
fi
```

The problem is that `PATH` is an exported environment variable that child shells inherit, but `fpath`/`FPATH` is a zsh array that is **not** inherited. So the idempotency check (which only inspects `PATH`) incorrectly assumes `fpath` is also already configured.

This means zsh completions for all Homebrew-installed tools are broken in:
- Terminal multiplexer panes (Zellij, tmux)
- Nested zsh shells (`zsh` inside `zsh`)
- Any non-login child shell that inherits `PATH` from a parent where `brew shellenv` already ran

```
# In a nested zsh (or Zellij/tmux pane):
$ echo "$(brew shellenv zsh)" | wc -c
       0

$ echo $fpath | tr ' ' '\n' | grep homebrew
# (no output)

# fpath is missing /opt/homebrew/share/zsh/site-functions
# so completions for brew-installed tools don't work
```

### What did you expect to happen?

`brew shellenv zsh` should always emit the `fpath[1,0]=` line for zsh, even when the `PATH` idempotency check passes. The `fpath` setup is not redundant in child shells — unlike `PATH`, `fpath` is not inherited through the environment.

Ideally the early return should only skip the `PATH`/env-var exports that are actually inherited, and still emit the `fpath` line (and arguably re-check `MANPATH`/`INFOPATH` too, though those are less commonly affected).

### Step-by-step reproduction instructions (by running `brew` commands)

```sh
# 1. Start a zsh login shell (simulates initial terminal launch)
zsh -l

# 2. Confirm brew shellenv works and fpath is set
eval "$(brew shellenv zsh)"
echo $fpath | tr ' ' '\n' | grep homebrew
# /opt/homebrew/share/zsh/site-functions  ← present

# 3. Start a nested non-login zsh (simulates tmux/zellij pane)
zsh

# 4. PATH is inherited, but fpath is not
echo $PATH | tr ':' '\n' | grep homebrew
# /opt/homebrew/bin     ← inherited
# /opt/homebrew/sbin    ← inherited

echo $fpath | tr ' ' '\n' | grep homebrew
# (no output)           ← NOT inherited

# 5. brew shellenv is a no-op because PATH check passes
eval "$(brew shellenv zsh)"
echo $fpath | tr ' ' '\n' | grep homebrew
# (still no output)     ← bug: fpath was never set

# 6. Confirm brew shellenv produces zero output
echo "$(brew shellenv zsh)" | wc -c
# 0
```

**Workaround:** Manually add to `.zshrc`:
```zsh
fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)
```

Related: https://github.com/orgs/Homebrew/discussions/2547, https://github.com/Homebrew/brew/pull/11930

### PR DESCRIPTION
**Pull request by sumanthratna**
zsh's fpath is not an exported environment variable, so child shells (tmux/Zellij panes, nested zsh) lose Homebrew's completions path. The shellenv idempotency check only inspects PATH, which IS inherited, so it early-returns and never emits the fpath line. Exporting FPATH after setting fpath ensures child zsh shells inherit it.

Fixes Homebrew/brew#21879

Supersedes Homebrew/brew#21884

-----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests (excluding integration tests) for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

-----

### CODE REVIEW

File: Library/Homebrew/cmd/shellenv.sh [hunk 1]
```diff
@@ -27,6 +22,17 @@ homebrew-shellenv() {
...
   fi
 
+  if [[ "${HOMEBREW_PATH%%:"${HOMEBREW_PREFIX}"/sbin*}" == "${HOMEBREW_PREFIX}/bin" ]]
+  then
+    # PATH is already set but zsh's fpath is not inherited by child shells.
+    if [[ "${HOMEBREW_SHELL_NAME}" == "zsh" ]] || [[ "${HOMEBREW_SHELL_NAME}" == "-zsh" ]]
+    then
+      echo "fpath[1,0]=\"${HOMEBREW_PREFIX}/share/zsh/site-functions\";"
+      echo "export FPATH;"
+    fi
```
Comment (carlocab) [inline Library/Homebrew/cmd/shellenv.sh]: We've already done `export FPATH;` below. Why do we still need to do this?

Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/shellenv.sh]: Agreed.

File: Library/Homebrew/test/cmd/shellenv_spec.rb [hunk 2]
```diff
@@ -2,9 +2,9 @@
 # frozen_string_literal: true
 
 RSpec.describe "brew shellenv", type: :system do
-  it "prints export statements", :integration_test do
-    expect { brew_sh "shellenv" }
-      .to output(/.*/).to_stdout
+  it "prints export statements including FPATH for zsh", :integration_test do
+    expect { brew_sh "shellenv", "zsh" }
+      .to output(/export FPATH/).to_stdout
```
[the remark this answers is not in the document]
Comment (MikeMcQuaid) [reply Library/Homebrew/test/cmd/shellenv_spec.rb]: Don't change this test.

**Comment by MikeMcQuaid** [comment]
> * AI was used to generate or assist with generating this PR. _Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes_.

@sumanthratna you didn't use anything at all here? are you sure?

File: Library/Homebrew/cmd/shellenv.sh (hunk 1 above)
Comment (sumanthratna) [reply Library/Homebrew/cmd/shellenv.sh]: The `export FPATH;` that you've highlighted is for the early-return path (when $PATH is set, presumably because `eval "$(./bin/brew shellenv zsh)")` has already been run). 

The `export FPATH;` below is for the "full output" branch, where `eval "$(./bin/brew shellenv zsh)"` hasn't been run yet and so `HOMEBREW_PREFIX` is not in `PATH`

Comment (carlocab) [reply Library/Homebrew/cmd/shellenv.sh]: Yes, I understand. What I'm saying is that we don't need to print the `fpath` entry anymore when returning early because the full output already does `export FPATH`

**Comment by sumanthratna** [comment]
> > * AI was used to generate or assist with generating this PR. _Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes_.
> 
> @sumanthratna you didn't use anything at all here? are you sure?

sorry I forgot the checkbox; fixed. For this PR, I used Opus 4.6 with high reasoning, with context (a) from original issue, (b) output of below
```zsh
$ echo $FPATH
$ zsh
$ echo $FPATH
$ eval "$(./bin/brew shellenv zsh)"
$ echo $FPATH
```

File: Library/Homebrew/cmd/shellenv.sh (hunk 1 above)
Comment (sumanthratna) [reply Library/Homebrew/cmd/shellenv.sh]: Thanks for the catch, you're right, fixing

**Comment by sumanthratna** [comment]
Hi @MikeMcQuaid @carlocab gentle bump to see if you have any other feedback here?

**Comment by carlocab** [comment]
My comment from https://github.com/Homebrew/brew/pull/21910#discussion_r3035298263 still applies. You made a change in 505e9ddb8896d2cad393018f6116dd1fb09b6e0b, but that doesn't seem to address the comment fully.

**Comment by sumanthratna** [comment]
Thanks @carlocab I re-read your message and realized what you meant. I didn't know that zsh preserves the export attribute of `FPATH` when inherited from the parent environment but I validated with `typeset -p FPATH` and it's true. 

Can you take another look whenever you get a chance? And thanks again for the help

File: Library/Homebrew/test/cmd/shellenv_spec.rb [hunk 3]
```diff
@@ -3,8 +3,8 @@
 
 RSpec.describe "brew shellenv", type: :system do
   it "prints export statements", :integration_test do
-    expect { brew_sh "shellenv" }
-      .to output(/.*/).to_stdout
+    expect { brew_sh "shellenv", "zsh", "HOMEBREW_PATH" => "/usr/bin:/usr/sbin" }
+      .to output(/export FPATH/).to_stdout
```
Comment (carlocab) [inline Library/Homebrew/test/cmd/shellenv_spec.rb]: Revert this change please.

**Review by carlocab — COMMENTED** [review]
One more suggestion, and I think this should be ready.

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by GunniBusch** [comment]
@sumanthratna Thanks a lot ❤️! This fixes autocompletions inside codex. I always thought the issue was in codex not using a login shell.

**Comment by mhanberg** [comment]
I have no idea why, but the line added in this PR, when run inside tmux, never returns. i ran the commands all one by one and they all return immediately except for `export FPATH`, which seems to hang indefinitely. I'm not sure why it only happens inside tmux. It doesn't to matter if you initialized brew in the base terminal before hand or wait until you launch a tmux window and then run it.

I can open a new issue i that is preferable.

**Comment by MikeMcQuaid** [comment]
@mhanberg Given how many people use `tmux`, `zsh` and `brew`: this seems highly likely to be specific to your setup. We'll review a PR to fix (not revert) this but I don't think an issue makes sense, sorry.

**Comment by mhanberg** [comment]
@MikeMcQuaid sorry for the noise. I went on a vision quest and determined that it was a confluence of zsh from nixpkgs + portable ruby + demons that was causing crowdstrike to give my shell startup the hug of death. I just reverted to using `/bin/zsh` (which is code signed in a way that crowdstrike says "carry on") and all seems working.

Apologies!
