### PR TITLE
edit: auto-tap core/cask repos when not installed

### LINKED ISSUE #21585: `brew edit` with developer mode off triggers it, don't tap main repos and breaks future edits
### `brew doctor` output

```shell
N/A (deprecated casks and one deprecated icu4c, dependency of another formula)
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 5.0.14-59-g45db1ce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 45db1ce2ebbf2fcb08ab91652e884e8df8e0f248
Last commit: 28 hours ago
Branch: main
Core tap JSON: 17 Feb 01:55 UTC
Core cask tap JSON: 17 Feb 01:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 20
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.53.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.7.3-arm64
CLT: 26.2.0.0.1.1764812424
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I tried to `brew edit` a formula to test a change before submitting it. Homebrew wasn't in developer mode.

### What happened (include all command output)?

I tried a first `brew edit`, it opened the formula in an editor, but also toggled the developer mode on.

```
brew edit qsv
Warning: edit is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

Editing /opt/homebrew/opt/qsv/.brew/qsv.rb
Warning: Using codium because no editor was set in the environment.
This may change in the future, so we recommend setting `$EDITOR`
or `$HOMEBREW_EDITOR` to your preferred text editor.
```

It seems it created a copy of the formula alone somewhere. Any modification done to this file would anyway not work as Homebrew would still try to install from the API.

Subsequent `brew edit` command would fail, probably because as developer mode was toggled on, it now would like to find Formulas in Taps, and Core wasn't clones as a Tap when developer mode was toggled on.

```
brew edit qsv
Warning: edit is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

Usage: brew edit [options] [formula|cask|tap ...]

Open a formula, cask or tap in the editor set by $EDITOR or
$HOMEBREW_EDITOR, or open the Homebrew repository for editing if no argument
is provided.

      --formula, --formulae        Treat all named arguments as formulae.
      --cask, --casks              Treat all named arguments as casks.
      --print-path                 Print the file path to be edited, without
                                   opening an editor.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: qsv doesn't exist on disk.
Run brew create --set-name qsv $URL to create a new formula!
```

After that, I could sometimes "fix" things by toggling developer mode off again, but sometimes doing it fixes nothing.

User can also force tap with `brew tap --force homebrew/core`

### What did you expect to happen?

Several possibilities:
- Either the edit should work directly, without needing developer mode
- Or if developer mode is required, when triggered like that, it should tap core/casks
- Either way, subsequent edits shouldn't end up broken

With or without the above, written instructions could also be a solution to manage the case of edits with developer mode off: block edits and state to the user they need to be in developer mode and tap core/casks or something along that line.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- Have a Homebrew install not in developer mode (preferably that never was in developer mode, fresh install without taps)
- Try to edit a formula
- It could open a copy of the formula, in `/opt/homebrew/opt/qsv/.brew/`, but will also toggle developer mode on
- Subsequent tries of edit will fail (see the above)
- From there, user can try to play around manual tap, toggle developer mode off and so on.
```

### PR DESCRIPTION
**Pull request by tiluckdave**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

-----

- [x] AI was used to generate or assist with generating this PR. *Cursor was used to navigate and understand the codebase. It also helped with the code. Bug analysis, fix design, and testing were done manually.*

-----

Fixes #21585.

`brew edit` auto-enables developer mode but doesn't clone the taps, leaving users with a misleading `brew create` error. This fix adds auto-tap before `to_paths` in `edit.rb` when the formula/cask is API-known, but the tap isn't installed.

Verified end-to-end with `brew edit --print-path wget` on an install without taps.

### CODE REVIEW

File: Library/Homebrew/dev-cmd/edit.rb [hunk 1]
```diff
@@ -53,6 +53,14 @@ def run
             [HOMEBREW_REPOSITORY]
           end
         else
+          args.named.each do |name|
+            if !args.cask? && !CoreTap.instance.installed? && Homebrew::API.formula_names.include?(name)
+              CoreTap.instance.install(force: true)
+            elsif !args.formula? && !CoreCaskTap.instance.installed? && Homebrew::API.cask_tokens.include?(name)
```
[the remark this answers is not in the document]
Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/edit.rb]: I agree with this. It should exclude any names with `/` in them that don't start with `homebrew/core/` or `homebrew/cask/` respectively.

File: Library/Homebrew/dev-cmd/edit.rb [hunk 2]
```diff
@@ -53,6 +53,14 @@ def run
...
+              CoreCaskTap.instance.install(force: true)
+            end
```
[the remark this answers is not in the document]
Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/edit.rb]: Don't need to add this.

File: Library/Homebrew/test/cli/named_args_spec.rb [hunk 3]
```diff
@@ -358,6 +358,25 @@ def setup_unredable_cask(name)
 
       expect(described_class.new("foo", "baz").to_paths(only: :cask)).to eq [cask_path, Cask::CaskLoader.path("baz")]
     end
+
+    context "with without_api: true" do
```
[the remark this answers is not in the document]
Comment (MikeMcQuaid) [reply Library/Homebrew/test/cli/named_args_spec.rb]: Agreed.

File: Library/Homebrew/dev-cmd/edit.rb [hunk 4]
```diff
@@ -53,6 +53,15 @@ def run
             [HOMEBREW_REPOSITORY]
           end
         else
+          args.named.each do |name|
+            bare_name = File.basename(name, ".rb")
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/edit.rb]: I don't think this is right as it'll tap if you do `some/tap/formula` and `formula` exists in Homebrew/core.

Also just occurred to me: you should verify the `brew doctor` output after this auto-tapping too.

Thanks!

Comment (tiluckdave) [reply Library/Homebrew/dev-cmd/edit.rb]: How about `bare_name = name.delete_prefix("#{CoreTap.instance.name}/").delete_prefix("#{CoreCaskTap.instance.name}/")`
Even after this, if the name contains /, the API will reject it!

Also, `brew doctor` is clean after auto-tap.

Comment (MikeMcQuaid) [reply Library/Homebrew/dev-cmd/edit.rb]: Yup that make sense but only delete `CoreTap` or `CoreCaskTap` for formulae and cask respectively.

File: Library/Homebrew/dev-cmd/edit.rb [hunk 5]
```diff
@@ -53,6 +53,17 @@ def run
...
         else
+          args.named.each do |name|
+            formula_name = name.delete_prefix("#{CoreTap.instance.name}/")
+            cask_token = name.delete_prefix("#{CoreCaskTap.instance.name}/")
+
+            if !args.cask? && !CoreTap.instance.installed? && Homebrew::API.formula_names.include?(formula_name)
+              CoreTap.instance.install(force: true)
+            elsif !args.formula? && !CoreCaskTap.instance.installed? && Homebrew::API.cask_tokens.include?(cask_token)
+              CoreCaskTap.instance.install(force: true)
+            end
```
Comment (MikeMcQuaid) [inline Library/Homebrew/dev-cmd/edit.rb]:
```suggestion
            if !args.cask? && !CoreTap.instance.installed? &&
               Homebrew::API.formula_names.include?(name.delete_prefix("#{CoreTap.instance.name}/"))
              CoreTap.instance.install(force: true)
            elsif !args.formula? && !CoreCaskTap.instance.installed? &&
                  Homebrew::API.cask_tokens.include?(name.delete_prefix("#{CoreCaskTap.instance.name}/"))
              CoreCaskTap.instance.install(force: true)
            end
```
