### PR TITLE
audit: fix false-positive for '--with-check' from 'depends_on "check"…

### LINKED ISSUE #170: audit: false positive when using 'depends_on "check"'
If you have an optional dependency on a formula named "check", the automatically constructed `--with-check` option will trigger `audit`'s complaint about the deprecated `--with-check`, even though it's different semantics in this case. We should probably ignore that particular `--with-check`.

```
$ brew audit --strict gst-plugins-good
gst-plugins-good:
  * Use '--with-test' instead of '--with-check'. Migrate '--with-check' with `deprecated_option`.
Error: 1 problem in 1 formula
[✘ /usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ grep 'depends_on "check"' Formula/*
Formula/gst-plugins-good.rb:    depends_on "check" => :optional
Formula/gst-plugins-good.rb:    depends_on "check"
Formula/libstrophe.rb:  depends_on "check"
Formula/libu2f-server.rb:  depends_on "check" => :build
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew audit --strict libstrophe
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [X] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #170

`audit` always complains about `--with-check`, but that's legit if it is referring to an optional dependency on a formula named "check".

### CODE REVIEW

File: Library/Homebrew/cmd/audit.rb [hunk 1]
```diff
@@ -391,7 +391,9 @@ def audit_options
       end
 
       if o.name =~ /^with(out)?-(?:checks?|tests)$/
-        problem "Use '--with#{$1}-test' instead of '--#{o.name}'. Migrate '--#{o.name}' with `deprecated_option`."
+        unless formula.deps.optional.include? Dependency.new("check", [:optional])
```
Comment (xu-cheng) [inline Library/Homebrew/cmd/audit.rb]: How about:
```ruby
formula.deps.any? { |d| d.name == "check" && (d.optional? || d.recommended?) }
```

Note, the `recommended?` is used to fix the false positive of `--without-check`.

Comment (mikemcquaid) [inline Library/Homebrew/cmd/audit.rb]: 👍

Comment (apjanke) [inline Library/Homebrew/cmd/audit.rb]: Yeah. Changed to use that.
