### PR TITLE
Install cached bottles if `curl --head` fails

### LINKED ISSUE #15302: Installing cached bottles now requires an Internet connection after #15117
### `brew doctor` output

**NOTE:** This is the `brew doctor` output on my laptop (where I can reproduce the issue) but the `brew doctor` output on the CI machine is clear.

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tcl-tk
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.15-10-g0841d1a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0841d1a25ef06c1c68d2d28ee77979e81a8dccde
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: deb1fd1f4212dfbfb26cd668d6aa49a17a3f9445
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 24 Apr 18:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

We have CI that tests a tool that installs bottled formulae from a private tap.

The CI doesn't have access to the private tap so we set it up with the bottles it should install by seeding the cache:
```
cp bottles/* $(brew --cache)/downloads
```

Then it just runs `brew install X Y Z`.

### What happened (include all command output)?

This was working prior to #15117 and has now stopped working (presumably because of the addition of `result.assert_success!`).

It fails to use the cached location if `resolve_url_basename_time_file_size` fails.

### What did you expect to happen?

I expected it to be able to use the cached file.

After all,
1. [We use the cached bottle regardless of how the URL is resolved](https://github.com/Homebrew/brew/blob/0841d1a25ef06c1c68d2d28ee77979e81a8dccde/Library/Homebrew/download_strategy.rb#L422-L423)
2. [We fail open when attempting to invalidate the cache by comparing the bottle's mtime to the URL's Last-Modified header](https://github.com/Homebrew/brew/blob/0841d1a25ef06c1c68d2d28ee77979e81a8dccde/Library/Homebrew/download_strategy.rb#L418-L419)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall socat
brew fetch socat --force-bottle
# turn off Wi-Fi
brew install socat --force-bottle
```

### PR DESCRIPTION
**Pull request by boblail**
Fixes #15302

Prior to #15117, if `curl --head` failed for any reason, `brew install` would've installed previously-downloaded bottles.

If that was an unintended side-effect of #15117, then this PR restores the previous behavior.

If it was intended, is there a way to `brew install` a bottle from the filesystem — i.e. a no-network install provided that the given bottle matches the formula's expectations?

------

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

### CODE REVIEW

File: Library/Homebrew/download_strategy.rb [hunk 1]
```diff
@@ -406,18 +406,27 @@ def fetch(timeout: nil)
...
       ohai "Downloading #{url}"
 
-      resolved_url, _, url_time, _, is_redirection =
-        resolve_url_basename_time_file_size(url, timeout: end_time&.remaining!)
+      fresh =
+        if version.respond_to?(:latest?)
+          !version.latest?
+        else
+          true
+        end
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:414]:
```suggestion
      fresh = if version.respond_to?(:latest?)
        !version.latest?
      else
        true
      end
```

File: Library/Homebrew/download_strategy.rb [hunk 2]
```diff
@@ -406,18 +406,27 @@ def fetch(timeout: nil)
...
+
+      resolved_url, _, last_modified, _, is_redirection =
+        begin
+          resolve_url_basename_time_file_size(url, timeout: end_time&.remaining!)
+        rescue ErrorDuringExecution
+          raise unless cached_location.exist? && fresh # rubocop:disable Style/UnlessLogicalOperators
+
+          [nil, nil, nil, nil, nil]
+        end
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:423]:
```suggestion
      resolved_url, _, last_modified, _, is_redirection = begin
        resolve_url_basename_time_file_size(url, timeout: end_time&.remaining!)
      rescue ErrorDuringExecution
        raise if !cached_location.exist? || !fresh
      end
```

File: Library/Homebrew/download_strategy.rb [hunk 3]
```diff
@@ -406,18 +406,27 @@ def fetch(timeout: nil)
...
       meta[:headers]&.delete_if { |header| header.start_with?("Authorization") } if is_redirection
 
-      fresh = if cached_location.exist? && url_time
-        url_time <= cached_location.mtime
-      elsif version.respond_to?(:latest?)
-        !version.latest?
-      else
-        true
-      end
+      # Cache is no longer fresh if Last-Modified postdates the file's timestamp
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_strategy.rb:428]:
```suggestion
      # Cache is no longer fresh if Last-Modified is after the file's timestamp
```

File: Library/Homebrew/download_strategy.rb (hunk 2 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/download_strategy.rb:423]: Are you sure the `[nil, nil, nil, nil, nil]` is required?

Not sure if the `raise` is correct here but don't want to disable RuboCop here, please rewrite the code instead of disabling the cop.

**Review by MikeMcQuaid — COMMENTED** [review]
Thanks for the PR @boblail! A few comments.

File: Library/Homebrew/download_strategy.rb (hunk 2 above)
Comment (boblail) [reply Library/Homebrew/download_strategy.rb:423]: Ah! I'll fiddle with the factoring. I did
```
raise unless cached_location.exist? && fresh
```
b/c Rubocop wanted me not to use `&&` in an `unless`
but if I do
```
raise if !(cached_location.exist? && fresh)
```
Rubocop wants me to switch `if !` to `unless`
I could do
```
raise if !cached_location.exist? || !fresh
```
but that feels hardest to read.

I'll play with it!

Comment (boblail) [reply Library/Homebrew/download_strategy.rb]: @MikeMcQuaid, I just noticed your suggestion at the top of this 🤦‍♂️. I accepted your suggestions and tested them locally — they look good 👍 

I have no qualms merging
```ruby
raise if !cached_location.exist? || !fresh
```
but I wanted to have a go at making it more readable.

What do you think of this refactor? https://github.com/boblail/brew/pull/284/files (Feel free to merge or close.)

Comment (MikeMcQuaid) [reply Library/Homebrew/download_strategy.rb]: > What do you think of this refactor? https://github.com/boblail/brew/pull/284/files (Feel free to merge or close.)

Looks great! I have ✅ but don't have permissions to merge.

Comment (boblail) [reply Library/Homebrew/download_strategy.rb]: Awesome, thanks! I'm going to squash commits now on this branch.

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again @boblail, another great PR!

**Comment by boblail** [comment]
Thanks, @MikeMcQuaid! — and thanks for the quick turn-around, as usual!
