### PR TITLE
brew install will suggest brew cask install

### LINKED ISSUE #6245: Better suggestion in command line when running brew install instead of brew cask install
# A detailed description of the proposed feature

Running `brew install kdiff3` returns the following error message;
```
$ brew install kdiff3
Error: No available formula with the name "kdiff3" 
Found a cask named "kdiff3" instead.
```

Suggesting to reword the error message to better guide the user to the correct command;
```
$ brew install kdiff3
Error: No available formula with the name "kdiff3" 
Found a cask named "kdiff3".
Try "brew cask install kdiff3", instead?
```

# The motivation for the feature

I use Homebrew frequently but do not often need to run `brew cask install`.  Every time I see the above error It takes me a bit to figure out I just need to run `brew cask install` instead.  Messaging this on the command line might reduce confusion and save users time.

# How the feature would be relevant to at least 90% of Homebrew users

I imagine many Homebrew users, especially casual or first time users, may benefit from more helpful and explicate messaging.

# What alternatives to the feature have been considered

I see that there have been issues filed to merge the funcionality of `brew install` and `brew cask install` like https://github.com/Homebrew/brew/issues/5716 but these seems to be a lighter touch, only effecting messaging.

### PR DESCRIPTION
**Pull request by zachauten**
If the user tries to install a cask using brew install
then brew will suggest the user tries 'brew cask install'

closes #6245

- [ x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by zachauten** [comment]
Still need to write tests, figured I'd open a draft pull request so people could look at a potential solution for #6245. One thing I noticed is that the `show_info` parameter sort of achieves the same thing as `attempted_command = Homebrew.args.argv[0]`, so it might not be necessary anymore?

**Comment by MikeMcQuaid** [comment]
> One thing I noticed is that the `show_info` parameter sort of achieves the same thing as `attempted_command = Homebrew.args.argv[0]`, so it might not be necessary anymore?

Yeh, that might be better. I was going to suggest passing a parameter explicitly that would alter the text output.

File: Library/Homebrew/missing_formula.rb [hunk 1]
```diff
@@ -8,8 +8,8 @@
 module Homebrew
   module MissingFormula
     class << self
-      def reason(name, silent: false, show_info: false)
-        cask_reason(name, silent: silent, show_info: show_info) || blacklisted_reason(name) ||
```
Comment (zachauten) [inline Library/Homebrew/missing_formula.rb]: I changed the order of these because there was a test that was calling `cask_reason` before `blacklisted_reason`,  and as `Homebrew.args.argv` was nil because it's a test an Error was being thrown. Not sure if there's a more elegant way to deal with that but I'm open to suggestions.
 https://github.com/Homebrew/brew/blob/e0c645bab1a71ff97eaedecd5558946ce5c2e88d/Library/Homebrew/test/missing_formula_spec.rb#L6

File: Library/Homebrew/extend/os/mac/missing_formula.rb [hunk 2]
```diff
@@ -14,12 +14,16 @@ def blacklisted_reason(name)
         end
       end
 
-      def cask_reason(name, silent: false, show_info: false)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/extend/os/mac/missing_formula.rb]: I think this version is nicer rather than using `Homebrew.args`

Comment (zachauten) [reply Library/Homebrew/extend/os/mac/missing_formula.rb]: Sorry, I think I misunderstood your previous comment! I'll revert it.

**Comment by MikeMcQuaid** [comment]
Thanks @zachauten!
