### PR TITLE
cmd/list: Constrain `-lrt` options to formulae

### LINKED ISSUE #10116: brew list -l produces short output for casks, doesn't print totals as claimed in help
# Bug report

NOTE: This is the same issue as #9033.  PR https://github.com/Homebrew/brew/pull/9035 was filed to close that issue, but does not seem to fix the problems I listed.  `git log --grep '#9033'` shows that https://github.com/Homebrew/brew/pull/9035 has made it to my /usr/local but the problems I listed in #9033 are still present.  I'm duplicating the issue here but have checked and updated the details.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Obtaining long form output of all installed packages and casks.

## What happened (include command output)

The long `ls -l` output for formulae was mixed with short `ls` output for casks.

<details>
  <summary>Command output</summary>
  <pre>
rb@Silverbird$ brew list -l
total 0
drwxr-xr-x  3 rb  staff  96 Dec 16 18:16 ansible
drwxr-xr-x  3 rb  staff  96 Nov 27 07:38 aom
drwxr-xr-x  3 rb  staff  96 Dec  4  2018 autoconf
...
drwxr-xr-x  3 rb  staff  96 Dec 22 13:48 zstd
adium                                 font-freefont                         protonvpn
...
font-dejavu-sans-mono-nerd-font       protonmail-bridge
  </pre>
</details>

## What you expected to happen

1. `brew help list` says “If the output is to a terminal, a total sum for all the file sizes is printed before the long listing.” There wasn't one.

2. Formulae and casks listed in the same long format *or* an error if `-l` only works with `--formula`.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew list -l`

## Output of `brew config` and `brew doctor` commands

(Note, brew doctor says there are updated command line tools, even if I update them. Maybe it assumes I'm on latest mac OS?)

<pre>
rb@Silverbird$ brew config
HOMEBREW_VERSION: 2.7.0-39-gd6692d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6692d2883a34fdb1e39e0001b3caf7ff681c7a0
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2be111d6b85b6a72565b4883cafb4f171c6e6b8f
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacsclient --alternate-editor='bbedit -w'
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
rb@Silverbird$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  s3-backer
  s3fs
</pre>

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

- Fixes #10116 (part two).

- These are documented as only working on formulae, but users expect the same options (long format, reverse order or sort by modified time) to be passed to both formulae and casks in the default `brew list`. The output looks weird as they're not. Hence, constrain these to be `--formula`-only.

- This was added originally in 5adb76a5babdccd2c4edfb8752ac979ed14716ca, but disappeared later (I've not yet dug through and found why).

- This also fixes the CLI parser's handling of error messages for short options (assuming they're only a single character). Before, the error messages for this missing `--formula` option on `brew list -l` was `Error: Invalid usage: `--l` cannot be passed without `--formula`.`. ~I don't much like this code, but I'll revisit it later - I have to run for a 🚌 🚏 now!~

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
👏🏻 ❤️

**Comment by Rylan12** [comment]
FYI @MikeMcQuaid you added these `depends_on` lines in https://github.com/Homebrew/brew/pull/9035 and then promptly removed them (four hours later) in https://github.com/Homebrew/brew/pull/9038. Just want to make sure that we don't re-introduce any issues that then cause this to be removed once again.

**Comment by issyl0** [comment]
@Rylan12 Both work with these changes:

```
➜ brew list -l
[...]
Error: Invalid usage: `-l` cannot be passed without `--formula`.
➜ brew list ruby --versions
ruby 2.7.2
```

File: Library/Homebrew/cli/parser.rb [hunk 1]
```diff
@@ -533,8 +533,8 @@ def formulae(argv)
 
     class OptionConstraintError < UsageError
       def initialize(arg1, arg2, missing: false)
-        arg1 = "--#{arg1.tr("_", "-")}"
-        arg2 = "--#{arg2.tr("_", "-")}"
+        arg1 = dashes(arg1) + arg1.tr("_", "-")
+        arg2 = dashes(arg2) + arg2.tr("_", "-")
```
Comment (Rylan12) [inline Library/Homebrew/cli/parser.rb:537]: You might be able to use the [`name_to_option`](https://github.com/Homebrew/brew/blob/27afcf577989f9cbbc518bad3ebc15818555b328/Library/Homebrew/cli/parser.rb#L232-L238) method here

**Review by Rylan12 — APPROVED** [review]
Works for me too!

File: Library/Homebrew/cli/parser.rb (hunk 1 above)
Comment (Rylan12) [reply Library/Homebrew/cli/parser.rb:537]: Hmm, wait. It looks like this is already being called...

https://github.com/Homebrew/brew/blob/27afcf577989f9cbbc518bad3ebc15818555b328/Library/Homebrew/cli/parser.rb#L455

Maybe it doesn't do what I thought...

Comment (reitermarkus) [reply Library/Homebrew/cli/parser.rb:537]: The `tr("_", "-")` part is not correct for e.g. `--screen_saverdir`.

Comment (issyl0) [reply Library/Homebrew/cli/parser.rb:537]: Huh. That must have been broken before now. Can you give me a full example command that uses that so I can try to figure it out?

Comment (Rylan12) [reply Library/Homebrew/cli/parser.rb:537]: @issyl0 I think this will work for the [`check_constraints` method](https://github.com/Homebrew/brew/blob/27afcf577989f9cbbc518bad3ebc15818555b328/Library/Homebrew/cli/parser.rb#L431-L440) which will remove the need for this:

```ruby
      def check_constraints
        @constraints.each do |primary, secondary, constraint_type|
          primary_passed = option_passed?(primary)
          secondary_passed = option_passed?(secondary)
          if :mandatory.equal?(constraint_type) && primary_passed && !secondary_passed
            raise OptionConstraintError.new(name_to_option(primary), name_to_option(secondary))
          end
          raise OptionConstraintError.new(name_to_option(primary), name_to_option(secondary), missing: true) if secondary_passed && !primary_passed
        end
      end
```

Comment (issyl0) [reply Library/Homebrew/cli/parser.rb:537]: I think the issue @reitermarkus raised was pre-existing as I didn't change any of the code for the `arg.tr("_", "-")` stuff, so we can tackle that in another PR!

Comment (Rylan12) [reply Library/Homebrew/cli/parser.rb]: It looks like these are the options that will have this issue:

- `--input_methoddir`
- `--internet_plugindir`
- `--audio_unit_plugindir`
- `--vst_plugindir`
- `--vst3_plugindir`
- `--screen_saverdir`

They're all cask options. We may want to check in `name_to_option` to see if the option matched one of those. If so, don't do the `tr`. Separate PR makes sense I think

File: Library/Homebrew/cli/parser.rb [hunk 2]
```diff
@@ -433,9 +433,9 @@ def check_constraints
           primary_passed = option_passed?(primary)
           secondary_passed = option_passed?(secondary)
           if :mandatory.equal?(constraint_type) && primary_passed && !secondary_passed
-            raise OptionConstraintError.new(primary, secondary)
+            raise OptionConstraintError.new(name_to_option(primary), name_to_option(secondary))
           end
-          raise OptionConstraintError.new(primary, secondary, missing: true) if secondary_passed && !primary_passed
+          raise OptionConstraintError.new(name_to_option(primary), name_to_option(secondary), missing: true) if secondary_passed && !primary_passed
```
Comment (Rylan12) [inline Library/Homebrew/cli/parser.rb:438]:
```suggestion
        if secondary_passed && !primary_passed
          raise OptionConstraintError.new(name_to_option(primary), name_to_option(secondary), missing: true)
        end
```

**Review by Rylan12 — APPROVED** [review]
Oops, my bad with the suggestion. Otherwise looks good!

**Comment by issyl0** [comment]
No problem, I should have noticed that line was getting a bit long. I fixed it in a different way.

**Comment by issyl0** [comment]
Given this fixes a bug, I'm adding the critical label. 🟥

**Review by Rylan12 — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> FYI @MikeMcQuaid you added these `depends_on` lines in #9035 and then promptly removed them (two hours later) in #9038. Just want to make sure that we don't re-introduce any issues that then cause this to be removed once again.

@Rylan12 that was before disabling so should be fine 👍🏻 

Thanks @issyl0!
