### PR TITLE
Fix `brew formulae` and `brew casks` when the API is used

### LINKED ISSUE #15229: `brew casks` does not show casks from external taps unless HOMEBREW_NO_INSTALL_FROM_API is set
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.13-21-g2816c12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2816c1274fa1c29cdb1797222c23fc89e9b58e80
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b14bb2000244736319a529372f257198a5704c0c
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 14 Apr 15:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.QpHrGATtgF/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to list all casks available to install. This issue also affects zsh completions since it uses `brew casks` internally.

### What happened (include all command output)?

Only casks from the homebrew/cask tap were listed.

### What did you expect to happen?

All casks from all taps are listed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap homebrew/cask-fonts
brew casks | grep font-
export HOMEBREW_NO_INSTALL_FROM_API=1
brew casks | grep font-
```

### PR DESCRIPTION
**Pull request by Omoeba**
I'm not sure if this is an elegant solution but it gives an identical output to when `HOMEBREW_NO_INSTALL_FROM_API` is set, regardless of whether `homebrew/core` or `homebrew/cask` are tapped. Feel free to make any improvements.

Closes #15229

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

File: Library/Homebrew/cmd/casks.sh [hunk 1]
```diff
@@ -13,8 +13,11 @@ homebrew-casks() {
   if [[ -z "${HOMEBREW_NO_INSTALL_FROM_API}" &&
         -f "${HOMEBREW_CACHE}/api/cask_names.txt" ]]
   then
-    cat "${HOMEBREW_CACHE}/api/cask_names.txt"
-    echo
+    {
+      cat "${HOMEBREW_CACHE}/api/cask_names.txt"
+      echo
+      homebrew-items '*/Casks/*\.rb' '' 's|/Casks/|/|' '^homebrew/cask'
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/casks.sh:19]: I believe that we should exclude the main cask repo from `homebrew-items` output when using the API because if the local tap is out-of-date it might show some casks that have been deleted. This goes for `formula.sh` as well.

`homebrew-items()` is defined in `Library/Homebrew/items.sh`.

https://github.com/Homebrew/brew/blob/c265d3d330adb2707502e61cc93864fb9353a7bc/Library/Homebrew/items.sh#L22-L24

I wonder if we could just change `find_exclude_filter` to evaluate it as a regex instead of a name. Then, ignore `homebrew-cask` here and `homebrew-formula` in `formula.sh`. I haven't tried that though to see if it works.

**Review by apainintheneck — COMMENTED** [review]
Nice work so far. I left some comments about excluding the default cask and formula taps if they exist locally because they might be out-of-date.

It would also be nice to see some benchmarks here comparing what we have now with after this change since we're kind of combining the two current methods. I don't expect it to be slow but we might as well double check.

File: Library/Homebrew/cmd/casks.sh [hunk 2]
```diff
@@ -13,8 +13,11 @@ homebrew-casks() {
   if [[ -z "${HOMEBREW_NO_INSTALL_FROM_API}" &&
         -f "${HOMEBREW_CACHE}/api/cask_names.txt" ]]
   then
-    cat "${HOMEBREW_CACHE}/api/cask_names.txt"
-    echo
+    {
+      cat "${HOMEBREW_CACHE}/api/cask_names.txt"
+      echo
```
[the remark this answers is not in the document]
Comment (Omoeba) [reply Library/Homebrew/cmd/casks.sh:18]: The `echo` is necessary because otherwise the last line of `cask_names.txt` gets merged with the first line of the output of `homebrew-items`, creating an invalid cask name. During testing I found that `zy-player` and `0-ad` became the nonexistent `zy-player0-ad`.

File: Library/Homebrew/cmd/casks.sh (hunk 1 above)
Comment (Omoeba) [reply Library/Homebrew/cmd/casks.sh:19]: It does work per my testing but will changing `items.sh` cause breakage elsewhere?

File: Library/Homebrew/cmd/casks.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (apainintheneck) [reply Library/Homebrew/cmd/casks.sh:18]: That makes sense. Thanks for checking.

File: Library/Homebrew/cmd/casks.sh (hunk 1 above)
Comment (apainintheneck) [reply Library/Homebrew/cmd/casks.sh:19]: `items.sh` only defines the `homebrew-items` function which is only used in `casks.sh` and `formulae.sh` so it should be fine. Of course, we should double check that the output is the same when not using the API but that shouldn't be too difficult.

The idea of using `--regex` there to pass in multiple filter values doesn't really work as expected when I tried it partially because it doesn't accept empty values.

The best thing I can think of off the top of my head is something like this which should work but is quite ugly (I haven't tested this though).

<details>
<summary>Changes</summary>

```diff
diff --git a/Library/Homebrew/cmd/casks.sh b/Library/Homebrew/cmd/casks.sh
index dfa9308e6..98db12e2d 100644
--- a/Library/Homebrew/cmd/casks.sh
+++ b/Library/Homebrew/cmd/casks.sh
@@ -16,9 +16,9 @@ homebrew-casks() {
     {
       cat "${HOMEBREW_CACHE}/api/cask_names.txt"
       echo
-      homebrew-items '*/Casks/*\.rb' '' 's|/Casks/|/|' '^homebrew/cask'
+      homebrew-items '*/Casks/*\.rb' '' '*/homebrew-cask/*' 's|/Casks/|/|'
     } | sort -u
   else
-    homebrew-items '*/Casks/*\.rb' '' 's|/Casks/|/|' '^homebrew/cask'
+    homebrew-items '*/Casks/*\.rb' '' '' 's|/Casks/|/|' '^homebrew/cask'
   fi
 }
diff --git a/Library/Homebrew/cmd/formulae.sh b/Library/Homebrew/cmd/formulae.sh
index babbff33e..f4ee7e11f 100644
--- a/Library/Homebrew/cmd/formulae.sh
+++ b/Library/Homebrew/cmd/formulae.sh
@@ -16,10 +16,10 @@ homebrew-formulae() {
     {
       cat "${HOMEBREW_CACHE}/api/formula_names.txt"
       echo
-      homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core'
+      homebrew-items '*\.rb' 'Casks' '*/homebrew-core/*' 's|/Formula/|/|'
     } | sort -u
     echo
   else
-    homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core'
+    homebrew-items '*\.rb' 'Casks' '' 's|/Formula/|/|' '^homebrew/core'
   fi
 }
diff --git a/Library/Homebrew/items.sh b/Library/Homebrew/items.sh
index 4c436fed3..3c2ad8f21 100644
--- a/Library/Homebrew/items.sh
+++ b/Library/Homebrew/items.sh
@@ -1,10 +1,11 @@
 homebrew-items() {
   local items
   local sed_extended_regex_flag
-  local find_include_filter="$1"
-  local find_exclude_filter="$2"
-  local sed_filter="$3"
-  local grep_filter="$4"
+  local find_path_include_filter="$1"
+  local find_name_exclude_filter="$2"
+  local find_path_exclude_filter="$3"
+  local sed_filter="$4"
+  local grep_filter="$5"
 
   # HOMEBREW_MACOS is set by brew.sh
   # shellcheck disable=SC2154
@@ -21,14 +22,15 @@ homebrew-items() {
   items="$(
     find "${HOMEBREW_REPOSITORY}/Library/Taps" \
       -type d \( \
-      -name "${find_exclude_filter}" -o \
+      -name "${find_name_exclude_filter}" -o \
       -name cmd -o \
       -name .github -o \
       -name lib -o \
       -name spec -o \
-      -name vendor \
+      -name vendor -o \
+      -path "${find_path_exclude_filter}" \
       \) \
-      -prune -false -o -path "${find_include_filter}" |
+      -prune -false -o -path "${find_path_include_filter}" |
       sed "${sed_extended_regex_flag}" \
         -e 's/\.rb//g' \
         -e 's_.*/Taps/(.*)/(home|linux)brew-_\1/_' \
```

</details>

If we don't care about total accuracy with completions, we could just skip this extra complexity. Otherwise, hopefully someone else can chime in with a better idea.

Comment (Omoeba) [reply Library/Homebrew/cmd/casks.sh:19]: Since `items.sh` is only used in `casks.sh` and `formulae.sh`, it should still be safe to use `--regex` by passing a value that never matches anything like `^\b$` instead of an empty one. It still isn't the cleanest solution but in my opinion it is a lot cleaner than adding multiple extra arguments to `items.sh`.

Comment (apainintheneck) [reply Library/Homebrew/cmd/casks.sh:19]: Yep, I agree with you. That makes more sense to me too.

File: Library/Homebrew/cmd/casks.sh [hunk 3]
```diff
@@ -13,8 +13,11 @@ homebrew-casks() {
...
+      homebrew-items '*/Casks/*\.rb' '' 's|/Casks/|/|' '^homebrew/cask'
+    } | sort -u
```
[the remark this answers is not in the document]
Comment (Omoeba) [reply Library/Homebrew/cmd/casks.sh:20]: The `sort -u` is used here to sort the names again because combining the 2 lists messes up the sorting. The `-u` can probably be removed once the core taps are filtered out though because there should be no more duplicates.

**Comment by Omoeba** [comment]
Switching to regex needed a few more changes than I expected due to the different `find` on macOS and Linux having different ways to turn on extended regex. `sort -u` is also replaced by `sort -f` because`-u` is now unnecessary thanks to the core taps being filtered out and `-f` is added to maintain a consistent order with `sort -uf` in `items.sh`. One interesting thing to note though is `brew formulae` returns an extra newline with the API enabled but `brew casks` doesn't. I'm not sure what causes it, whether it is dependent on the specific taps I have, or what negative effects it may cause for things like tab completion (if any). As always, feel free to make any edits.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me so far but interested in thoughts from @apainintheneck!

File: Library/Homebrew/cmd/casks.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (apainintheneck) [reply Library/Homebrew/cmd/casks.sh]: There can still be duplicates with the short names, right? It should be possible for two formulas to exist with the same name as long as they're in different taps. Not sure how big of a deal any duplication would be though.

File: Library/Homebrew/cmd/formulae.sh [hunk 4]
```diff
@@ -13,9 +13,13 @@ homebrew-formulae() {
...
-    cat "${HOMEBREW_CACHE}/api/formula_names.txt"
+    {
+      cat "${HOMEBREW_CACHE}/api/formula_names.txt"
+      echo
+      homebrew-items '*\.rb' '.*Casks.*|.*/homebrew/homebrew-core/.*' 's|/Formula/|/|' '^homebrew/core'
+    } | sort -f
     echo
   else
-    homebrew-items '*\.rb' 'Casks' 's|/Formula/|/|' '^homebrew/core'
+    homebrew-items '*\.rb' '.*Casks.*' 's|/Formula/|/|' '^homebrew/core'
```
Comment (apainintheneck) [inline Library/Homebrew/cmd/formulae.sh:23]:
```suggestion
    homebrew-items '*\.rb' '.*/Casks/.*' 's|/Formula/|/|' '^homebrew/core'
```

Nit: It might be nice to be a little more defensive here and with the regex above it too.

**Review by apainintheneck — APPROVED** [review]
I think this looks really good. The blank line seems to be a part of the `formula_names.txt` file as far as I can tell so that probably needs to get fixed somewhere else. Other than that I left a nit but I think this ready to merge as is.

File: Library/Homebrew/cmd/formulae.sh (hunk 4 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/formulae.sh:23]: Agreed.

File: Library/Homebrew/cmd/casks.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikeMcQuaid) [reply Library/Homebrew/cmd/casks.sh]: > It should be possible for two formulas to exist with the same name as long as they're in different taps.

Yes, this is definitely a thing that happens and is OK.

File: Library/Homebrew/cmd/formulae.sh (hunk 4 above)
Comment (Omoeba) [reply Library/Homebrew/cmd/formulae.sh:23]: I'm not sure why but adding slashes breaks the filtering and no longer excludes casks.

**Comment by Omoeba** [comment]
`sort -f` was changed to `sort -uf` to maintain the existing behavior of removing duplicate short names when there are formulae with the same name in `homebrew/core` and a custom tap.

File: Library/Homebrew/cmd/formulae.sh (hunk 4 above)
Comment (apainintheneck) [reply Library/Homebrew/cmd/formulae.sh:23]: It seems to be because we're not filtering by file but directory instead and the final slash is omitted. The following works for me locally. If I remember correctly, we don't currently use nesting but it will probably get added to the core repos in the future for git performance reasons.

```suggestion
    homebrew-items '*\.rb' '.*/Casks(/.*|$)' 's|/Formula/|/|' '^homebrew/core'
```

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution (hopefully of many)! Without people like you submitting PRs we couldn't run this project. You rock, @Omoeba!
