### PR TITLE
cmd/list: `-t` and `-r` support for some long options

### LINKED ISSUE #18421: `brew list --installed-on-request -tr` Can't sort by time
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.24
ORIGIN: https://github.com/Homebrew/brew
HEAD: 916044581862c32fc2365e8e9ff0b1507a98925e
Last commit: 4 days ago
Core tap JSON: 26 Sep 09:05 UTC
Core cask tap JSON: 26 Sep 11:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

run: `brew list --installed-on-request -tr`

### What happened (include all command output)?

It's not chronological, it's still alphabetical
image

### What did you expect to happen?

Sort by time

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew list --installed-on-request -tr`
```

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Should support use case and close #18421.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Nice!

File: Library/Homebrew/cmd/list.rb [hunk 1]
```diff
@@ -122,7 +122,13 @@ def run
 
           raise UsageError, "Cannot use #{flags.join(", ")} with formula arguments." unless args.no_named?
 
-          Formula.installed.sort.each do |formula|
+          formulae = if args.t?
+            Formula.installed.sort_by { |formula| test("M", formula.prefix.realpath) }.reverse!
```
Comment (cho-m) [inline Library/Homebrew/cmd/list.rb:126]:
```suggestion
            Formula.installed.sort_by { |formula| test("M", formula.rack) }.reverse!
```

Probably closer to what `ls` is doing.
