### PR TITLE
Fix race condition in concurrent downloads for duplicate URLs

### LINKED ISSUE #21425: Formula fails to download with concurrency enabled
### `brew doctor` output

```shell
==> brew doctor
```

### Verification

- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] My "`brew doctor` output" above says `Your system is ready to brew` or a definitely unrelated `Tier` message.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
==> brew config
HOMEBREW_VERSION: 5.0.10-65-ga36eea6
ORIGIN: https://github.com/Homebrew/brew
HEAD: a36eea6fe705eef966f0acd609e471c9b7541a6b
Last commit: 11 hours ago
Branch: main
Core tap HEAD: b0f1243ca3c85c75101842d5f7fbcda7a8f3d393
Core tap last commit: 86 minutes ago
Core tap JSON: 18 Jan 20:47 UTC
Core cask tap JSON: 18 Jan 20:47 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/brew/Library/Caches/Homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_CURL_PATH: /usr/bin/curl
HOMEBREW_DEVELOPER: set
HOMEBREW_DOWNLOAD_CONCURRENCY: 12
HOMEBREW_FAIL_LOG_LINES: 150
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_EMAIL: 1589480+BrewTestBot@users.noreply.github.com
HOMEBREW_GIT_NAME: BrewTestBot
HOMEBREW_GIT_PATH: /usr/bin/git
HOMEBREW_LOGS: /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/logs
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_COLOR: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/ruby
CPU: hexa-core 64-bit penryn
Clang: 17.0.0 build 1700
Git: 2.50.1 => /usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.2-x86_64
CLT: 26.2.0.0.1.1764812424
Xcode: 26.2
```

### What were you trying to do (and why)?

Install docbook as part of https://github.com/Homebrew/homebrew-core/pull/263408

### What happened (include all command output)?

The download failed:
```console
  ==> Fetching downloads for: docbook
  ✘ Formula docbook (5.2)
  Error: A `brew install --verbose --formula --build-bottle docbook` process has already locked /Users/brew/Library/Caches/Homebrew/downloads/6605b9548ee0cc64c64f63685f53396ccaf3c8b1c0f21f6abde7e27c492bebab--docbook-5.2.zip.incomplete.
```

### What did you expect to happen?

A succesful download

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cd $(brew --repo homebrew/core)
gh pr checkout -f 263408
brew install -s docbook
```

### PR DESCRIPTION
**Pull request by ooye-sanket**
Fix race condition in concurrent downloads for duplicate URLs

Root Cause:
The race condition occurs because download_queue.rb creates separate download futures for each Downloadable object. In the docbook formula, the same URL (docbook-5.2.zip) appears both as the main formula download and as a resource. Even though they point to the same file, they create different Downloadable objects, so both attempt to download simultaneously and lock the same .incomplete file.

Solution Approach:
Instead of tracking downloads by Downloadable object (which treats the formula and resource as separate downloads), I've implemented deduplication based on cached_location (the actual file path). This ensures that when multiple downloadables need the same file, they share a single download operation.

Result:
The docbook formula and its xml52 resource both need docbook-5.2.zip, but now only one download is initiated and both share it. No more lock conflicts!

When `HOMEBREW_DOWNLOAD_CONCURRENCY` is enabled and a formula has the same URL listed both as the main download and as a resource (e.g., docbook), concurrent download attempts would try to lock the same `.incomplete` file, causing an "operation in progress" error.

The issue was that `download_queue.rb` created separate download futures for each `Downloadable` object, even when multiple downloadables shared the same `cached_location` (file path). This resulted in race conditions when downloading identical files.

This commit fixes the issue by:
- Adding `@downloads_by_location` hash to track downloads by file path
- Deduplicating downloads based on `cached_location` instead of `Downloadable` object identity
- Ensuring multiple downloadables sharing the same file reuse the same download future

When the same file is needed by multiple downloadables, they now share a single download operation, preventing concurrent lock attempts on the same `.incomplete` file.

Fixes #21425

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew lgtm` (style, typechecking and tests) with your changes locally?

### CODE REVIEW

File: Library/Homebrew/download_queue.rb [hunk 1]
```diff
@@ -45,7 +46,7 @@ def enqueue(downloadable, check_attestation: false)
       targets = @symlink_targets.fetch(cached_location)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_queue.rb:46]: How does this overlap with the `symlink_targets` logic?

File: Library/Homebrew/download_queue.rb [hunk 2]
```diff
@@ -56,6 +57,8 @@ def enqueue(downloadable, check_attestation: false)
         end
         create_symlinks_for_shared_download(cached_location)
       end
+
+      downloads[downloadable] = T.must(@downloads_by_location[cached_location])
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_queue.rb]:
```suggestion
      downloads[downloadable] = @downloads_by_location.fetch(cached_location)
```

File: Library/Homebrew/download_queue.rb [hunk 3]
```diff
@@ -173,6 +176,7 @@ def fetch
       Context.current = context_before_fetch
 
       downloads.clear
+      @downloads_by_location.clear
```
Comment (MikeMcQuaid) [inline Library/Homebrew/download_queue.rb:179]: Do we definitely need all three of: `symlink_targets`, `downloads`, `@downloads_by_location`?

File: Library/Homebrew/download_queue.rb (hunk 1 above)
Comment (ooye-sanket) [reply Library/Homebrew/download_queue.rb:46]: `@symlink_targets` serves a different purpose - it tracks which downloadables need symlinks created after a shared download completes. It's used in `create_symlinks_for_shared_download()` to create symlinks for all the different downloadables pointing to the same cached file.

`@downloads_by_location` is new and specifically prevents duplicate concurrent downloads by ensuring only one download future exists per file path. They work together:
1. `@downloads_by_location` - ensures one download per file
2. `@symlink_targets` - tracks all downloadables needing that file for symlink creation

Both are needed because we still want to track each downloadable in the `downloads` hash for display/progress purposes, but we only want one actual download operation per file.

File: Library/Homebrew/download_queue.rb (hunk 3 above)
Comment (ooye-sanket) [reply Library/Homebrew/download_queue.rb:179]: Yes, all three are needed because they serve different purposes:

1. **`@symlink_targets`** (existing) - Maps `cached_location` → Set of downloadables that need symlinks created after download completes. Used by `create_symlinks_for_shared_download()`.

2. **`@downloads_by_location`** (new) - Maps `cached_location` → single download future. This is the key deduplication mechanism that prevents multiple concurrent downloads of the same file.

3. **`downloads`** (existing) - Maps individual `downloadable` → download future. Required for the UI/progress display in the `fetch` method (lines 68-176), which iterates over downloadables to show progress for each one.

*Why am I unable to reduce this:*
I can’t remove @downloads_by_location because it resolves the issue without it, duplicate downloads occur.
I can’t remove downloads since the entire fetch loop relies on iterating over individual downloadables for UI rendering.
I can’t remove @symlink_targets because it has a different lifecycle: it accumulates all downloadables that require a file, whereas @downloads_by_location only holds a single future.

File: Library/Homebrew/download_queue.rb (hunk 1 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/download_queue.rb:46]: > Both are needed because we still want to track each downloadable in the `downloads` hash for display/progress purposes, but we only want one actual download operation per file.

I think it might make more sense to make the output also "one per file" rather than "one per downloadable"? What do you think?

File: Library/Homebrew/download_queue.rb (hunk 3 above)
Comment (MikeMcQuaid) [reply Library/Homebrew/download_queue.rb:179]: > I can’t remove downloads since the entire fetch loop relies on iterating over individual downloadables for UI rendering.

Might be worth trying to use `downloads_by_location` or this?

Does `@symlink_targets` need cleared here? May be worth considering if it's worth having `attr_reader` for the instance variables?

**Comment by ooye-sanket** [comment]
> I think it might make more sense to make the output also "one per file" rather than "one per downloadable"? What do you think?

That makes sense 👍

Since the actual operation is already deduplicated to one download per file, showing output per file would be more accurate and simpler for users. Instead of rendering progress for each downloadable (formula + resource), we could render a single progress entry per cached_location.

I can refactor the fetch loop to iterate over `@downloads_by_location` directly and update the output to be “one per file” rather than “one per downloadable”, if that aligns with your preference. Happy to make that change.

**Comment by ooye-sanket** [comment]
> Does @symlink_targets need cleared here?

Good catch! Yes, `@symlink_targets` should also be cleared. After the downloads complete and symlinks are created, we don't need to keep that data around. I'll add:
```ruby
downloads.clear
@downloads_by_location.clear
@symlink_targets.clear
```

**Comment by ooye-sanket** [comment]
> May be worth considering if it's worth having attr_reader for the instance variables?

For `@downloads_by_location` and `@symlink_targets`, they're internal implementation details, so I don't think they need `attr_reader`. They're only used within the class methods. The existing `downloads` method already provides access to the downloads hash when needed.

**Comment by ooye-sanket** [comment]
@MikeMcQuaid should i implement: refactoring to use `downloads_by_location` directly. This will:
- Remove the `downloads` hash
- Show one progress line per file (instead of per downloadable)
- Add `@symlink_targets.clear` to cleanup
- Result in cleaner, simpler code

if yes, then I'll push the changes shortly.

**Comment by MikeMcQuaid** [comment]
@ooye-sanket yes, this sounds great, thank you so much 😍

**Comment by ooye-sanket** [comment]
@MikeMcQuaid Refactored as discussed! Changes:
   - Removed `downloads` hash completely
   - Now using `@downloads_by_location` directly in fetch loop
   - Output shows one line per file (e.g., "docbook-5.2.zip") instead of per downloadable
   - Added cleanup for all tracking hashes
   - Code is now simpler and more accurate to what's actually happening

**Comment by ooye-sanket** [comment]
> Thanks @ooye-sanket! Code looks good. Only issue now from local testing is we want to retain the existing format of e.g.
> 
> ```
> ==> Fetching downloads for: ffmpeg-full
> ✔︎ Bottle Manifest ffmpeg-full (8.0.1)                                                                                   Downloaded  108.1KB/108.1KB
> ✔︎ Bottle Manifest giflib (5.2.2)                                                                                        Downloaded   10.8KB/ 10.8KB
> ✔︎ Bottle giflib (5.2.2)                                                                                                 Downloaded  153.0KB/153.0KB
> ✔︎ Bottle Manifest highway (1.3.0)                                                                                       Downloaded    9.7KB/  9.7KB
> ✔︎ Bottle highway (1.3.0)                                                                                                Downloaded  896.7KB/896.7KB
> ✔︎ Bottle Manifest imath (3.2.2)                                                                                         Downloaded    7.4KB/  7.4KB
> ✔︎ Bottle imath (3.2.2)                                                                                                  Downloaded  194.3KB/194.3KB
> ✔︎ Bottle Manifest libdeflate (1.25)                                                                                     Downloaded    7.8KB/  7.8KB
> ✔︎ Bottle libdeflate (1.25)                                                                                              Downloaded  113.3KB/113.3KB
> ✔︎ Bottle Manifest openjph (0.26.0)                                                                                      Downloaded   12.2KB/ 12.2KB
> ✔︎ Bottle openjph (0.26.0)                                                                                               Downloaded  157.5KB/157.5KB
> ✔︎ Bottle Manifest openexr (3.4.4_1)                                                                                     Downloaded   15.6KB/ 15.6KB
> ✔︎ Bottle openexr (3.4.4_1)                               
> ```
> 
> rather than the new:
> 
> ```
> ✔︎ cask.jws.json                                                                                                         Downloaded   15.3MB/ 15.3MB
> ✔︎ formula.jws.json                                                                                                      Downloaded   32.0MB/ 32.0MB
> ==> Fetching downloads for: ffmpeg-full
> ✔︎ 7332868699be1d72494b42c0966eca2044bb87ceb55952d79068bdff04542aa6--ffmpeg-full-8.0.1-1.bottle_manifest.json            Downloaded  108.1KB/108.1KB
> ✔︎ 283773c4d2db4fe867419d7eea6811a6417889d78fad8871041c07f49b22d2a1--giflib-5.2.2.bottle_manifest.json                   Downloaded   10.8KB/ 10.8KB
> ✔︎ 995b62b1518a0deae8dd9c0016ee099e69ae5a0e54bed3370983a80522d71783--giflib--5.2.2.arm64_tahoe.bottle.tar.gz             Downloaded  153.0KB/153.0KB
> ✔︎ 9c45ed9405a2a0988cb2c80afd415bcdacca07ef87ac47c277905cb96a0b611e--highway-1.3.0.bottle_manifest.json                  Downloaded    9.7KB/  9.7KB
> ✔︎ aa8ca7b1c25da4f0dd9d753cee28095bc01fbefcb01490047e20bc6e949a599a--highway--1.3.0.arm64_tahoe.bottle.tar.gz            Downloaded  896.7KB/896.7KB
> ✔︎ 82322ae05e389eb5b059000e61d0a7acb8176046888dc2e15344c8fd7704ade4--imath-3.2.2.bottle_manifest.json                    Downloaded    7.4KB/  7.4KB
> ✔︎ 74571d1c82f2668cb71807eb96f5fb3b7be738c2caf8dede9226d35b4a8b83b2--imath--3.2.2.arm64_tahoe.bottle.tar.gz              Downloaded  194.3KB/194.3KB
> ```
> 
> if it's easier to do that by continuing to use `downloads` as before: no worries, feel free to go back to that. Given you're adding `downloadable_to_location` here anyway I don't mind what 3 variables are used as long as we can fix the issue you've fixed here _and_ preserve the (better) current output format. Users don't need to be told the actual filenames. If we're deduping: it's fine to just hide/lie in the output about something being downloaded for two formulae/resources/places.
> 
> Thanks again!

Thanks for the detailed feedback that makes sense!
I’ll push an updated revision shortly.

**Comment by ooye-sanket** [comment]
hey HELLO!! @MikeMcQuaid I've restored the `downloads` hash to preserve the original output format. 

The fix now works as follows:
- `@downloads_by_location` deduplicates downloads by file path (prevents the race condition)
- `downloads` hash maps each downloadable to the shared future (preserves the nice output format)
- Users see (e.g."Bottle giflib (5.2.2)") instead of raw cache filenames

This maintains the existing user experience while fixing the concurrent download issue. 
Ready for review!

**Comment by MikeMcQuaid** [comment]
Great work as usual, thanks @ooye-sanket! Hope to see more PRs from you.
