### PR TITLE
Fix range requests with `curl`

### LINKED ISSUE #10528: File is downloaded twice if remote server does not support ranges
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force` – not applicable
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

curl based fetcher seems to work in two stages: first by requesting file with range 0-1, and later by downloading the file with some info being discovered on first curl invocation.
however, if remote server does not support ranged downloads, file is downloaded twice, being completely discarded on first try.

It's easier to notice when server is also painfully slow (like portswigger's burp suite)

#### Output of command with `--verbose --debug`

```
❯ brew install --cask --verbose --debug burp-suite
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.7-154-g6c1bd25\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://portswigger.net/burp/releases/download\?product=community\&version=2020.12.1\&type=MacOsx
==> Downloading https://portswigger.net/burp/releases/download?product=community&version=2020.12.1&type=MacOsx
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.7-154-g6c1bd25\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://portswigger.net/burp/releases/download\?product=community\&version=2020.12.1\&type=MacOsx
```

it gets stuck on this stage. running that curl command in terminal shows that range header was ignored by remote server and curl is trying to download whole file.

### PR DESCRIPTION
**Pull request by cnnrmnn**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Closes #10528.

The primary issue that these changes fix is that the initial request sent to determine if a server supports range (partial) requests isn't a `HEAD` request. If the server doesn't support range requests, this downloads the entire file. Another request (the one that is actually meant to download the file) follows and downloads the entire file a second time. A minimal fix would be to add the `--head` flag to the first request, as suggested by @wilkmaciej.

The way that `curl_download` currently checks for range request support is a bit strange. It sends a range request asking for the first byte of the content and checks for the presence of the `Content-Range` header. The proper way to check for range request support is to send a normal (i.e., not range) `HEAD` request to the server and check for the presence of the `Accept-Ranges` header. If it is present and its value isn't `none`, the server supports range requests. These changes implement this methodology.

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I think you could also/alternatively use @sanford's work from #11252 to search for that '`Content-Range`' field in the header returned as part of cURL's response?  I readily concede that making the change to do that could always come later, though.

**Comment by cnnrmnn** [comment]
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I think you could also/alternatively use @sanford's work from #11252 to search for that '`Content-Range`' field in the header returned as part of cURL's response?  I readily concede that making the change to do that could always come later, though.  

I'd be happy to use that code once the PR is merged. For now, I don't see it as a huge issue since my header-parsing code is only a few lines.

File: Library/Homebrew/utils/curl.rb [hunk 1]
```diff
@@ -118,36 +118,40 @@ def curl(*args, print_stdout: true, **options)
       result
     end
 
-    def curl_download(*args, to: nil, partial: true, **options)
+    def parse_headers(headers)
+      return {} unless headers
+
+      headers.split("\n").to_h do |h|
+        partitioned = h.partition(": ")
+        [partitioned.first, partitioned.last]
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/curl.rb:126]: I may have misunderstood but wouldn't this be equivalent:
```suggestion
        h.partition(": ")
```

File: Library/Homebrew/utils/curl.rb [hunk 2]
```diff
@@ -118,36 +118,40 @@ def curl(*args, print_stdout: true, **options)
...
+      end
+    end
+
+    def curl_download(*args, to: nil, try_partial: true, **options)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/curl.rb:130]: Have all call-sites been updated to use `try_partial` instead of `partial` here?

File: Library/Homebrew/utils/curl.rb [hunk 3]
```diff
@@ -118,36 +118,40 @@ def curl(*args, print_stdout: true, **options)
...
-      else
-        supports_partial_download = false
       end
 
-      continue_at = if destination.exist? && supports_partial_download
-        "-"
-      else
-        0
-      end
+      args = ["--location", "--remote-time", "--output", destination] + args
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/curl.rb:150]:
```suggestion
      args = ["--location", "--remote-time", "--output", destination, *args]
```

File: Library/Homebrew/utils/curl.rb [hunk 4]
```diff
@@ -118,36 +118,40 @@ def curl(*args, print_stdout: true, **options)
...
+      # continue-at shouldn't be used with servers that don't support partial requests.
+      args = ["--continue-at", "-"] + args if destination.exist? && supports_partial
```
Comment (MikeMcQuaid) [inline Library/Homebrew/utils/curl.rb:152]:
```suggestion
      args = ["--continue-at", "-", *args] if destination.exist? && supports_partial
```

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far! Some minor style comments.

File: Library/Homebrew/utils/curl.rb (hunk 1 above)
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:126]: The array that `partition` returns contains the separator. `split` would be a better choice here, so I've made the change.

File: Library/Homebrew/utils/curl.rb [hunk 5]
```diff
@@ -118,36 +118,37 @@ def curl(*args, print_stdout: true, **options)
       result
     end
 
-    def curl_download(*args, to: nil, partial: true, **options)
+    def parse_headers(headers)
+      return {} unless headers
+
+      # Skip status code
+      headers.split("\r\n")[1..].to_h { |h| h.split(": ") }
```
Comment (Rylan12) [inline Library/Homebrew/utils/curl.rb:125]:
```suggestion
      headers.split("\r\n")[1..].to_h do |h|
        name, content = h.split(": ")
        [name.downcase, content]
      end
```

I think we need to downcase everything. I've seen some headers that have caps and some with lowercase (I think it depends on whether `HTTP/1.1` or `HTTP/2` is being used but I'm not an expert:

```console
$ curl -I https://example.com
HTTP/2 200
content-encoding: gzip
accept-ranges: bytes
age: 341342
cache-control: max-age=604800
content-type: text/html; charset=UTF-8
date: Fri, 14 May 2021 14:52:49 GMT
etag: "3147526947"
expires: Fri, 21 May 2021 14:52:49 GMT
last-modified: Thu, 17 Oct 2019 07:18:26 GMT
server: ECS (ord/4CD8)
x-cache: HIT
content-length: 648

$ curl -I https://go.microsoft.com/
HTTP/1.1 302 Moved Temporarily
Server: AkamaiGHost
Content-Length: 0
Location: https://www.microsoft.com/
Expires: Fri, 14 May 2021 14:54:36 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 14 May 2021 14:54:36 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
```

File: Library/Homebrew/utils/curl.rb [hunk 6]
```diff
@@ -118,36 +118,37 @@ def curl(*args, print_stdout: true, **options)
...
       end
 
-      continue_at = if destination.exist? && supports_partial_download
-        "-"
-      else
-        0
-      end
+      args = ["--location", "--remote-time", "--output", destination, *args]
+      # continue-at shouldn't be used with servers that don't support partial requests.
+      args = ["--continue-at", "-", *args] if destination.exist? && supports_partial
```
Comment (Rylan12) [inline Library/Homebrew/utils/curl.rb:149]:
```suggestion
      args.prepend "--location", "--remote-time", "--output", destination
      # continue-at shouldn't be used with servers that don't support partial requests.
      args.prepend "--continue-at", "-" if destination.exist? && supports_partial
```

This might be just a nitpicky style thing but I personally find this easier to understand

File: Library/Homebrew/utils/curl.rb [hunk 7]
```diff
@@ -118,36 +118,37 @@ def curl(*args, print_stdout: true, **options)
       result
     end
 
-    def curl_download(*args, to: nil, partial: true, **options)
+    def parse_headers(headers)
+      return {} unless headers
```
Comment (Rylan12) [inline Library/Homebrew/utils/curl.rb:122]:
```suggestion
      return {} unless headers.present?
```

**Review by Rylan12 — COMMENTED** [review]
Looks good! A few more minor suggestions

File: Library/Homebrew/utils/curl.rb (hunk 6 above)
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:149]: I also prefer it. Thanks :)

File: Library/Homebrew/utils/curl.rb (hunk 7 above)
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:122]: Why `present?`?

Comment (MikeMcQuaid) [reply Library/Homebrew/utils/curl.rb:122]: `if headers.blank?` is even nicer 😁

Comment (Rylan12) [reply Library/Homebrew/utils/curl.rb:122]: Using `present?` or `blank?` (they're opposites) checks not only for `nil` or falsey but also for empty strings, whitespace-only strings, etc. We usually prefer them because they can catch a few more edge cases.

Quick overview https://blog.appsignal.com/2018/09/11/differences-between-nil-empty-blank-and-present.html

Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:122]: Appreciate the link. Thanks :)

File: Library/Homebrew/utils/curl.rb (hunk 5 above)
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:125]: You are correct. From the HTTP/2 spec:
>Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion.  However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2.  A request or 
response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6).

In HTTP/1.x, header names are case insensitive.

Coincidentally, your changes also fix an issue where headers with no content would cause `parse_headers` to fail. `to_h` expects an array with two items, but `split(": ")` called on a header with no content would return an array with one item.

File: Library/Homebrew/utils/curl.rb [hunk 8]
```diff
@@ -118,36 +118,37 @@ def curl(*args, print_stdout: true, **options)
...
-        headers, _, http_status = range_stdout.partition("\r\n\r\n")
+      if try_partial
+        range_stdout = curl_output("--location", "--head", *args, **options).stdout
+        headers = parse_headers(range_stdout.split("\r\n\r\n").first)
 
-        supports_partial_download = http_status.to_i == 206 # Partial Content
-        if supports_partial_download &&
+        # Any value for `accept-ranges` other than none indicates that the server supports partial requests.
+        # Its absence indicates no support.
+        supports_partial = headers["accept-ranges"] && headers["accept-ranges"] != "none"
```
[the remark this answers is not in the document]
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:141]: Did you make this change because the default hash value isn't necessarily `nil`?

[the remark this answers is not in the document]
Comment (Rylan12) [reply Library/Homebrew/utils/curl.rb:141]: It should always be `nil`, but I'm thinking more about other edge cases.

Using `key?` means that there's no ambiguity about what we're trying to check for here. At the moment it probably doesn't make much of a difference but it's hypothetically possible that `header["accept-ranges"]` could end up being `false` which might incorrectly set `supports_partial`. Again, this specific example is hypothetical because it should always be a string for now, but I think using `key?` is a better long-term solution. We can be sure we're checking exactly what we want to check if that makes sense.

Plus, in my opinion at least, it makes understanding the line a little better because it now reads as "if `headers` has the key `accept-ranges` and the value is not `none`". There's no need to wonder if `headers["accept-ranges"]` is a boolean or anything like that.

File: Library/Homebrew/utils/curl.rb (hunk 6 above)
Comment (Rylan12) [reply Library/Homebrew/utils/curl.rb]: @cnnrmnn sorry, I just realized that I don't think this is the right thing to do here. Using `prepend` modifies the original `args` array meaning the scope of the prepending is beyond just within the `curl_download` method. I don't think we want this.

Here's what I mean:

```ruby
arr = ["b", "c"]

def foo(a)
  a.prepend "a"
  puts a.to_s
end

puts arr.to_s # prints `["b", "c"]`
foo arr       # prints `["a", "b", "c"]`
puts arr.to_s # prints `["a", "b", "c"]`
```

Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb]: Gotcha, no worries. Will revert.

File: Library/Homebrew/utils/curl.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (cnnrmnn) [reply Library/Homebrew/utils/curl.rb:141]: >It should always be nil, but I'm thinking more about other edge cases.

I suppose in this case it should always be nil, but you can [set the default value for a hash](https://docs.ruby-lang.org/en/2.0.0/Hash.html#method-i-default-3D).

> Using key? means that there's no ambiguity about what we're trying to check for here. At the moment it probably doesn't make much of a difference but it's hypothetically possible that header["accept-ranges"] could end up being false which might incorrectly set supports_partial. Again, this specific example is hypothetical because it should always be a string for now, but I think using key? is a better long-term solution. We can be sure we're checking exactly what we want to check if that makes sense.

Makes sense. Even without potential edge cases, I think it makes the code clearer (as you suggested). Thanks for the edit! :)

**Review by Rylan12 — COMMENTED** [review]
Looks good to me. Thanks again, @cnnrmnn!

**Review by Rylan12 — APPROVED** [review]
