### PR TITLE
shellenv: Fix shell detection

### LINKED ISSUE #7965: Assuming wrong shell in .profile
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Add Homebrew to my PATH as suggested by [the docs](https://docs.brew.sh/Homebrew-on-Linux#install)

## What happened (include command output)

`set: -g: invalid option` (more extensive but not relevant in my opinion as the issue is known)

## What you expected to happen

It adds it to my PATH

## Step-by-step reproduction instructions (by running `brew` commands)

1. Use GNOME
2. Set `fish` as your default shell, possibly making sure `$SHELL` is fish.
3. Run `echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> ~/.profile` (in Bash)
4. Log out and back in
5. Notice `.profile` error

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6d2c39579e22d0ee9baccdccdd8a12efb8b00304
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5c3e01d57e4bb18d4b338b6893800cfaa65bc197
Core tap last commit: 50 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.27.0 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-40-generic x86_64 GNU/Linux
OS: Ubuntu 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
</pre>

## Additional Context

GNOME sources `~/.profile` on login. I believe this is always with Bash and is not affected by the login shell.
Output of `ps --forest`:
```
    PID TTY          TIME CMD
  23877 tty2     00:00:00 gdm-x-session
  23879 tty2     00:00:00  \_ Xorg
  23903 tty2     00:00:00  \_ Xsession
  23908 tty2     00:00:00      \_ ps
```
It seems `brew shellenv` is impacted by `$SHELL`, and returns Fish env vars setup code.
Output:
```
$ brew shellenv
set -gx HOMEBREW_PREFIX "/home/linuxbrew/.linuxbrew";
set -gx HOMEBREW_CELLAR "/home/linuxbrew/.linuxbrew/Cellar";
set -gx HOMEBREW_REPOSITORY "/home/linuxbrew/.linuxbrew/Homebrew";
set -q PATH; or set PATH ''; set -gx PATH "/home/linuxbrew/.linuxbrew/bin" "/home/linuxbrew/.linuxbrew/sbin" $PATH;
set -q MANPATH; or set MANPATH ''; set -gx MANPATH "/home/linuxbrew/.linuxbrew/share/man" $MANPATH;
set -q INFOPATH; or set INFOPATH ''; set -gx INFOPATH "/home/linuxbrew/.linuxbrew/share/info" $INFOPATH;
```
This also happens in `.profile` as `SHELL` is set to Fish, however, as `.profile` is sourced with Bash, `eval $(brew shellenv)` errors as the returned commands are for Fish. A workaround:
```
$ SHELL=bash brew shellenv
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH}";
```
As this is not included in the docs, maybe `shellenv` should detect if it is running part of this GNOME source or use a different way of detecting the shell as using `SHELL` is not accurate in this context. If this wasn't added then maybe a warning in the docs should be included explaining this.

Full workaround:
Run `echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >> ~/.profile` instead (in Bash)

Workaround part of first installation (replacement for docs):
```
> bash
$ test -d ~/.linuxbrew && eval $(SHELL=/bin/bash ~/.linuxbrew/bin/brew shellenv)
$ test -d /home/linuxbrew/.linuxbrew && eval $(SHELL=/bin/bash /home/linuxbrew/.linuxbrew/bin/brew shellenv)
$ test -r ~/.bash_profile && echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
$ echo "eval \$(SHELL=/bin/bash $(brew --prefix)/bin/brew shellenv)" >>~/.profile
```

### PR DESCRIPTION
**Pull request by gromgit**
It currently switches on `$SHELL`, which points to the user's login shell. However, `shellenv` may be used in contexts where the running shell isn't `$SHELL` (e.g. setting up Homebrew variables in the sanitized environment of csh-based `cron` scripts), and Linux desktop environments may set up user sessions in ways that trip up the current algorithm (see #7965 for a case study). To work correctly in all circumstances and environments, its output should be determined by the context (calling shell) instead.

As far as I can tell, `/bin/ps -p <pid> -o comm=` produces the same output in both macOS and Linux, so this script should still be portable.

Fixes #7965.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Comment by maxim-belkin** [comment]
`/bin/ps -p $PPID -o comm=` doesn't work in two cases:
1. On a Mac when using Homebrew'd bash (returns `login`)
2. In Homebrew on Linux Docker container (returns `error: process ID out of range`)

File: Library/Homebrew/cmd/shellenv.sh [hunk 1]
```diff
@@ -6,16 +6,16 @@
 #:  Consider adding evaluation of this command's output to your dotfiles (e.g. `~/.profile`, `~/.bash_profile`, or `~/.zprofile`) with: `eval $(brew shellenv)`
 
 homebrew-shellenv() {
-  case "$SHELL" in
-    */fish|fish)
+  case "$(/bin/ps -p $PPID -o comm=)" in
```
Comment (maxim-belkin) [inline Library/Homebrew/cmd/shellenv.sh:9]:
```suggestion
  case "$(/bin/ps -hp $$ -o comm=)" in
```

Comment (gromgit) [reply Library/Homebrew/cmd/shellenv.sh:9]: That would always return `bash` (the `brew` process itself).

Comment (maxim-belkin) [reply Library/Homebrew/cmd/shellenv.sh:9]: It passes for me:
```
$ zsh
mbelkin@Gaia ~ % /bin/ps -p $$ -o comm=
zsh
mbelkin@Gaia ~ % 
```

Comment (maxim-belkin) [reply Library/Homebrew/cmd/shellenv.sh:9]: but neither your solution nor mine work in fish

**Comment by jonchang** [comment]
> `/bin/ps -p $PPID -o comm=` doesn't work in two cases:
> 
>     1. On a Mac when using Homebrew'd bash (returns `login`)
> 
>     2. In Homebrew on Linux Docker container (returns `error: process ID out of range`)

> but neither your solution nor mine work in fish

Do they work for you if you wrap it in a file e.g. `script.sh` and execute it that way?

If we can't figure out how to get this to work across shells I think we ought to just punt on this and say to users "sorry, we can't figure out how to set your shell environment" (if we can even detect this situation is happening)

File: Library/Homebrew/cmd/shellenv.sh (hunk 1 above)
Comment (maxim-belkin) [reply Library/Homebrew/cmd/shellenv.sh:9]: oh, got it! you're right I was trying to call it using different shells instead of calling it using bash. my bad!

**Comment by maxim-belkin** [comment]
> Do they work for you if you wrap it in a file e.g. `script.sh` and execute it that way?
> 
> If we can't figure out how to get this to work across shells I think we ought to just punt on this and say to users "sorry, we can't figure out how to set your shell environment" (if we can even detect this situation is happening)

Right. I was doing something like `fish shell.sh` and `zsh shell.sh` whereas I should've been doing `bash shell.sh` in different shells.

**Comment by jonchang** [comment]
I thought the Docker case was an issue but turns out `echo '/bin/ps -p $PPID -o comm=' > script.sh` is different from `echo "/bin/ps -p $PPID -o comm=" > script.sh` 😅

**Comment by jonchang** [comment]
Thanks for being awesome @gromgit and @maxim-belkin!
