### PR TITLE
cask/installer: Add Cask caveats to the end-of-operation summary

### LINKED ISSUE #11421: Cask caveats not shown in caveat summary
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.8-52-geb5f04a
ORIGIN: https://github.com/Homebrew/brew
HEAD: eb5f04a98a507d6cef67fc781fb9313378385b1e
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca683a631dee04a7cceb3140d721af8004ed85a5
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xS8zAkZjjT/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
XQuartz: 2.7.11 => /opt/X11
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew upgrade`

### What happened (include all command output)?

Caveats for `macfuse` got shown during install, but not in the caveats summary after the upgrade process finished. Only formula caveats (`gh`) were shown in the summary
```
❯ brew upgrade
==> Upgrading 7 outdated packages:
kube-linter 0.2.1 -> 0.2.2
gh 1.9.2 -> 1.10.2
pango 1.48.4 -> 1.48.5
mongodb/brew/mongosh 0.12.1 -> 0.13.1
shfmt 3.2.4 -> 3.3.0
node 16.1.0 -> 16.2.0
libx11 1.7.0 -> 1.7.1
==> Upgrading kube-linter 0.2.1 -> 0.2.2
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/manifests/0.2.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/blobs/sha256:831b22931fea72de98b288d96f2ff9c13ad078a88ab2600748434dbd7b8dfd65
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:831b22931fea72de98b288d96f2ff9c13ad078a88ab2600748434dbd7b8dfd65?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Pouring kube-linter--0.2.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/kube-linter/0.2.2: 5 files, 34.8MB
Removing: /usr/local/Cellar/kube-linter/0.2.1... (5 files, 34.6MB)
Removing: /Users/Max/Library/Caches/Homebrew/kube-linter--0.2.1... (9.8MB)
==> Upgrading gh 1.9.2 -> 1.10.2
==> Downloading https://ghcr.io/v2/homebrew/core/gh/manifests/1.10.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:4196fbac342d41cd1c05ab9319f955aed3563eaefd284b4ff141a07aecc9b7d8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:4196fbac342d41cd1c05ab9319f955aed3563eaefd284b4ff141a07aecc9b7d8?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Pouring gh--1.10.2.big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/gh/1.10.2: 89 files, 28.6MB
Removing: /usr/local/Cellar/gh/1.9.2... (89 files, 28.5MB)
==> Upgrading pango 1.48.4 -> 1.48.5
==> Downloading https://ghcr.io/v2/homebrew/core/libx11/manifests/1.7.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libx11/blobs/sha256:9998bb9f54cc7ee1c11cc5dd645efa2ab07542424dd978c87c2b12a59e736dcd
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:9998bb9f54cc7ee1c11cc5dd645efa2ab07542424dd978c87c2b12a59e736dcd?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pango/manifests/1.48.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pango/blobs/sha256:cabbacd4559bb2c843f6e4965f65c6baf5e66a554f127ee2341ac8919fd6e6e7
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:cabbacd4559bb2c843f6e4965f65c6baf5e66a554f127ee2341ac8919fd6e6e7?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Installing dependencies for pango: libx11
==> Installing pango dependency: libx11
==> Pouring libx11--1.7.1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libx11/1.7.1: 1,055 files, 7MB
==> Installing pango
==> Pouring pango--1.48.5.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.48.5: 64 files, 2.9MB
Removing: /usr/local/Cellar/pango/1.48.4... (64 files, 2.9MB)
==> Upgrading mongodb/brew/mongosh 0.12.1 -> 0.13.1
==> Downloading https://registry.npmjs.org/@mongosh/cli-repl/-/cli-repl-0.13.1.tgz
######################################################################## 100.0%
==> /usr/local/opt/node@14/bin/npm install -ddd --global --build-from-source --cache=/Users/Max/Library/Caches/Homebrew/npm_cache --prefix=/usr/local/Cellar/mongosh/0.13.1/libexec
🍺  /usr/local/Cellar/mongosh/0.13.1: 5,188 files, 30.9MB, built in 42 seconds
Removing: /usr/local/Cellar/mongosh/0.12.1... (5,230 files, 31MB)
==> Upgrading shfmt 3.2.4 -> 3.3.0
==> Downloading https://ghcr.io/v2/homebrew/core/shfmt/manifests/3.3.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/shfmt/blobs/sha256:789f53db9def4a6002efc5f37d0919a5c1e0deb104fdb29583d13392e36e5824
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:789f53db9def4a6002efc5f37d0919a5c1e0deb104fdb29583d13392e36e5824?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Pouring shfmt--3.3.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/shfmt/3.3.0: 7 files, 2.9MB
Removing: /usr/local/Cellar/shfmt/3.2.4... (7 files, 2.9MB)
==> Upgrading node 16.1.0 -> 16.2.0
==> Downloading https://ghcr.io/v2/homebrew/core/node/manifests/16.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:5a07b8c8ece7dedaa748a8f93ec08a416fc87977b7ddc04a4c0d30fa3784faa1
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5a07b8c8ece7dedaa748a8f93ec08a416fc87977b7ddc04a4c0d30fa3784faa1?se=2021-05-20T14%3A45%3A00Z&si
######################################################################## 100.0%
==> Pouring node--16.2.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/node/16.2.0: 2,784 files, 49MB
Removing: /usr/local/Cellar/node/16.1.0... (2,778 files, 48.9MB)
Removing: /Users/Max/Library/Caches/Homebrew/node--16.1.0... (13.1MB)
==> Upgrading libx11 1.7.1 -> 1.7.1
Removing: /usr/local/Cellar/libx11/1.7.0... (1,055 files, 7MB)
==> Casks with 'auto_updates' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
macfuse 4.1.0 -> 4.1.2
==> Upgrading macfuse
==> Caveats
You must reboot for the installation of macfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.1.2/macfuse-4.1.2.dmg
==> Downloading from https://github-releases.githubusercontent.com/1867347/bef7db00-b69c-11eb-8f46-85e4f7a57751?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH5
######################################################################## 100.0%
==> Uninstalling packages; your password may be necessary:
io.macfuse.installer.components.core
Password:
io.macfuse.installer.components.preferencepane
==> Running installer for macfuse; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is macFUSE
installer: Installing at base path /
installer: The install was successful.
==> Changing ownership of paths required by macfuse; your password may be necessary.
==> Purging files for version 4.1.0 of Cask macfuse
🍺  macfuse was successfully upgraded!
==> Caveats
==> gh
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

### What did you expect to happen?

Cask caveats to be listed together with formula caveats.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install / upgrade a mix of formula and casks with caveats, e.g. `gh` and `macfuse`
```

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

- Both formulae and casks can have caveats, but only formulae caveats were shown at the end of a bulk install/upgrade/reinstall operation via `Homebrew.messages.record_caveats`. This fixes that to show Cask caveats too, for consistency (scrolling up all of the multi-formulae-and-casks output to see caveats is time-consuming and users might miss them).
- In doing this I had to change how `Messages#record_caveats` works since the cask name is just a string, not an object.
- Fixes #11421.

----

Before:

```
➜ brew install macfuse kube-linter gh
==> Caveats
You must reboot for the installation of macfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.1.2/macfuse-4.1.2.dmg
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/9a9c1e4033ad7046b2404c776abebd5bb9bfb54169236eea695d82fd92b32f0d--macfuse-4.1.2.dmg
==> Installing Cask macfuse
==> Running installer for macfuse; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is macFUSE
installer: Installing at base path /
installer: The install was successful.
==> Changing ownership of paths required by macfuse; your password may be necessary.
🍺  macfuse was successfully installed!
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/manifests/0.2.2
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/7cbabba966f12048003fb1882bf5a6ace1b25902ebe86e8f049a3dfb6aad37d9--kube-linter-0.2.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/blobs/sha256:831b22931fea72de98b288d96f2ff9c13ad078a88ab2600748434dbd7b8dfd65
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/23466b6dae061ee7c1a1ecced21c2ecede51f364599549e766a32a5838cca98b--kube-linter--0.2.2.big_sur.bottle.tar.gz
==> Pouring kube-linter--0.2.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/kube-linter/0.2.2: 5 files, 34.8MB
==> Downloading https://ghcr.io/v2/homebrew/core/gh/manifests/1.11.0
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/ddad4ddc988804cf6037325a229259e1d5267e9203e69cf901f3e97c93395f7a--gh-1.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:34313bfaca6995d40836da15f3c1cf7579689f5ac1bdcf3e2e4e50ceb4cbb3e1
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/1eb3f40cf6fa82560f54b235fdedb761b36170a5b9d5c26b58be3d3b9afcb89b--gh--1.11.0.big_sur.bottle.tar.gz
==> Pouring gh--1.11.0.big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/gh/1.11.0: 89 files, 28.6MB
==> Caveats
==> gh
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

After

```
➜ brew install macfuse kube-linter gh
==> Caveats
You must reboot for the installation of macfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.1.2/macfuse-4.1.2.dmg
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/9a9c1e4033ad7046b2404c776abebd5bb9bfb54169236eea695d82fd92b32f0d--macfuse-4.1.2.dmg
==> Installing Cask macfuse
==> Running installer for macfuse; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is macFUSE
installer: Installing at base path /
installer: The install was successful.
==> Changing ownership of paths required by macfuse; your password may be necessary.
🍺  macfuse was successfully installed!
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/manifests/0.2.2
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/7cbabba966f12048003fb1882bf5a6ace1b25902ebe86e8f049a3dfb6aad37d9--kube-linter-0.2.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/kube-linter/blobs/sha256:831b22931fea72de98b288d96f2ff9c13ad078a88ab2600748434dbd7b8dfd65
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/23466b6dae061ee7c1a1ecced21c2ecede51f364599549e766a32a5838cca98b--kube-linter--0.2.2.big_sur.bottle.tar.gz
==> Pouring kube-linter--0.2.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/kube-linter/0.2.2: 5 files, 34.8MB
==> Downloading https://ghcr.io/v2/homebrew/core/gh/manifests/1.11.0
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/ddad4ddc988804cf6037325a229259e1d5267e9203e69cf901f3e97c93395f7a--gh-1.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:34313bfaca6995d40836da15f3c1cf7579689f5ac1bdcf3e2e4e50ceb4cbb3e1
Already downloaded: /Users/issyl0/Library/Caches/Homebrew/downloads/1eb3f40cf6fa82560f54b235fdedb761b36170a5b9d5c26b58be3d3b9afcb89b--gh--1.11.0.big_sur.bottle.tar.gz
==> Pouring gh--1.11.0.big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/gh/1.11.0: 89 files, 28.6MB
==> Caveats
==> macfuse
You must reboot for the installation of macfuse to take effect.
==> gh
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

### CODE REVIEW

File: Library/Homebrew/messages.rb [hunk 1]
```diff
@@ -36,7 +36,7 @@ def display_caveats(force: false)
 
     oh1 "Caveats"
     @caveats.each do |c|
-      ohai c[:formula], c[:caveats]
+      ohai c[:software], c[:caveats]
```
Comment (MikeMcQuaid) [inline Library/Homebrew/messages.rb:39]:
```suggestion
      ohai c[:package], c[:caveats]
```

File: Library/Homebrew/messages.rb [hunk 2]
```diff
@@ -15,8 +15,8 @@ def initialize
     @install_times = []
   end
 
-  def record_caveats(f, caveats)
-    @caveats.push(formula: f.name, caveats: caveats)
+  def record_caveats(software, caveats)
+    @caveats.push(software: software, caveats: caveats)
```
Comment (MikeMcQuaid) [inline Library/Homebrew/messages.rb:19]:
```suggestion
  def record_caveats(package, caveats)
    @caveats.push(package: package, caveats: caveats)
```

I've generally seen us use "package" to refer to either a formula or cask. This could be a documentation addition somewhere?

**Review by MikeMcQuaid — APPROVED** [review]
Looks great! Some style suggestions.

File: Library/Homebrew/cask/installer.rb [hunk 3]
```diff
@@ -56,6 +56,8 @@ def self.caveats(cask)
       caveats = cask.caveats
       return if caveats.empty?
 
+      Homebrew.messages.record_caveats(cask.to_s.downcase, caveats)
```
[the remark this answers is not in the document]
Comment (issyl0) [reply Library/Homebrew/cask/installer.rb]: I know nothing about casks - thanks!

File: Library/Homebrew/messages.rb (hunk 2 above)
Comment (issyl0) [reply Library/Homebrew/messages.rb]: That makes perfect sense. 🧠 💤

**Review by MikeMcQuaid — APPROVED** [review]
💖
