### PR TITLE
Skip build deps to avoid downloading bottles

### LINKED ISSUE #13040: `brew install` downloads build dependencies if `$HOMEBREW_INSTALL_FROM_API` is set
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.3-43-g6e1b6a3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6e1b6a3be7ce4f7a6349662ee7092fbf8f19d79c
Last commit: 5 hours ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
```

### `brew doctor` output

At first I thought `brew doctor` hanged, then I supplied `--debug` and wow, it's downloading the world. Honestly this is another bug to be fixed. Not sure how to skip `check_deleted_formula` so I can get the rest of check results.

```shell
$ brew doctor --debug
==> Checking check_access_directories
==> Checking check_brew_git_origin
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Checking check_broken_sdks
==> Checking check_casktap_integrity
==> Checking check_clt_minimum_version
==> Checking check_clt_up_to_date
==> Checking check_coretap_integrity
==> Checking check_deleted_formula
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.3-43-g6e1b6a3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/bottle/libtermkey.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.3-43-g6e1b6a3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/bottle/rubberband.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.3-43-g6e1b6a3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/bottle/cjson.json
...Skipping the rest...
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

This is less a showstopper than https://github.com//Homebrew/brew/issues/13039 but still pretty annoying.

Trying to install a formulae with `$HOMEBREW_INSTALL_FROM_API` set will bring build-only dependencies as well. Luckily only downloaded, not poured.

It looks to me this is just https://github.com//Homebrew/brew/issues/12357 manifested in another form, i.e. brew can't figure out the info needed without a local tap (most of the time).

### What happened (include all command output)?

```
$ brew install leaf-proxy 
==> Downloading https://ghcr.io/v2/homebrew/core/leaf-proxy/blobs/sha256:0954b0fd5638a747ba1512df
Already downloaded: /Users/kid/Library/Caches/Homebrew/downloads/e10182342d6b9193b4fd19216cdd0e3cce2d23d9b241ca300fc114b57356d585--leaf-proxy--0.4.2.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/rust/blobs/sha256:b377dbe44d8eed401316cba6a645e8
Already downloaded: /Users/kid/Library/Caches/Homebrew/downloads/287f203010ba81561e918b0a30aecf538c6965edb3a777aeceaf50378b4b78c7--rust--1.59.0.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:090acb6a5c51b9a3b74508e7a93e3
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:090acb6a5c51
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/blobs/sha256:7a28d090cbec60072c3df5c35be0f
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7a28d090cbec
######################################################################## 100.0%
==> Pouring leaf-proxy--0.4.2.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/leaf-proxy/0.4.2: 7 files, 6.2MB
==> Running `brew cleanup leaf-proxy`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

### What did you expect to happen?

Build dependencies should not be downloaded during installation, when bottles are available.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `export HOMEBREW_INSTALL_FROM_API=1`
2. `brew install leaf-proxy`
3. Notice how it downloads build dependencies (e.g. `rust`).
```

### PR DESCRIPTION
**Pull request by xxyzz**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This should fixes #13040.

### CODE REVIEW

File: Library/Homebrew/dependency.rb [hunk 1]
```diff
@@ -112,6 +112,8 @@ def expand(dependent, deps = dependent.deps, cache_key: nil, ignore_missing: fal
 
       deps.each do |dep|
         next if dependent.name == dep.name
+        # avoid downloading build dependency bottles
+        next if dep.build? && dependent.pour_bottle? && Homebrew::EnvConfig.install_from_api?
```
Comment (Bo98) [inline Library/Homebrew/dependency.rb:116]: Seems odd to me that it only happens in the fetch stage and only for API installs. Something must be done differently somewhere for this inconsistency to exist.

Comment (xxyzz) [reply Library/Homebrew/dependency.rb:116]: I think the correct fix should be createing the `Formula` object from json directly instead of from the downloaded bottle file IIUC, but that needs more work as the formula json API doesn't have any Linux dependencies.

Comment (Bo98) [reply Library/Homebrew/dependency.rb:116]: Ah so #12936 basically.

Comment (xxyzz) [reply Library/Homebrew/dependency.rb:116]: Yeah, exactly. Should I remove the first commit or close this pull request?

Comment (Bo98) [reply Library/Homebrew/dependency.rb:116]: I'm fine with at least the second commit as a short-term fix - it's consistent to what we have elsewhere.

I wouldn't object to the first commit - but I feel like there's something wrong elsewhere if it doesn't happen at install time and only at fetch time.

Comment (xxyzz) [reply Library/Homebrew/dependency.rb:116]: `dependent.deps` at here contains all the dependencies including build dependencies, this happens also when core tap is cloned
https://github.com/Homebrew/brew/blob/b533b380e5e48a2092a93fa843f4bfb4eda8ee20/Library/Homebrew/dependency.rb#L101

then at this line `to_formula` will cause an error
https://github.com/Homebrew/brew/blob/b533b380e5e48a2092a93fa843f4bfb4eda8ee20/Library/Homebrew/dependency.rb#L128

then start downloading bottle and retry
https://github.com/Homebrew/brew/blob/b533b380e5e48a2092a93fa843f4bfb4eda8ee20/Library/Homebrew/formula_installer.rb#L221-L228

The draft pr uses the huge json file(https://formulae.brew.sh/api/formula.json) but it lacks dependencies and the json file of each formula lacks dependencies for Linux. In order to create `Formula` from json, json files in formulae.brew.sh need more data.

But why not download the zip file of homebrew-core and use that as if the repo is cloned? It's about the same size of `formula.json`.

Comment (Bo98) [reply Library/Homebrew/dependency.rb:116]: Ok that makes sense. I'm fine with the PR then as a fix until we can get rid of the API fetch layer everywhere.

**Comment by xxyzz** [comment]
Could this pull request be merged as a temporary fix?

**Review by Bo98 — APPROVED** [review]
Yes, indeed. Thanks! Sorry for forgetting to merge this!
