### PR TITLE
utils/github: handle non-standard tap remotes

### LINKED ISSUE #10881: bump-formula-pr fails with non-standard tap names
### `brew config` output

HOMEBREW_VERSION: 3.0.7-33-g05f1c37
ORIGIN: https://github.com/Homebrew/brew
HEAD: 05f1c37ae0a551ca3936ca404a1fe2ee33bfd137
Last commit: 45 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e2d988b228eef0f998b6a775bd8d61af61b338ea
Core tap last commit: 3 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0 build 1100
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1

### `brew doctor` output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libmsiecf

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jmorris/.pyenv/shims/python3.5m-config
  /Users/jmorris/.pyenv/shims/python2-config
  /Users/jmorris/.pyenv/shims/python3.6m-config
  /Users/jmorris/.pyenv/shims/python3.7-config
  /Users/jmorris/.pyenv/shims/python2.7-config
  /Users/jmorris/.pyenv/shims/python3.7m-config
  /Users/jmorris/.pyenv/shims/python3.9-config
  /Users/jmorris/.pyenv/shims/python3.5-config
  /Users/jmorris/.pyenv/shims/python-config
  /Users/jmorris/.pyenv/shims/python3-config
  /Users/jmorris/.pyenv/shims/python3.6-config
  /Users/jmorris/.pyenv/shims/python3.8-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/vagrant.rb

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I have a private tap with a non-standard name that I keep some formulae in. I was trying to update my `unrar` formula using `bump-formula-pr --write` since it has a new version. I use `--write` because I don't want to go through the overhead of opening and accepting a PR and would prefer to make the commit manually.

### What happened (include all command output)?

It appears that `bump-formula-pr` tries to search for open PRs in the repo even though I don't want it to actually open a PR. I get the following error message:

```
Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]
```

Running `bump-formula-pr -d` gives this output:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/my/homebrew-tap/Formula/unrar.rb
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.7-33-g05f1c37\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=unrar\+repo\%3Amy\%2Fhomebrew-tap\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20210318-40473-wh29s7
Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:305:in `raise_error'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:237:in `open_rest'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:165:in `search'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:36:in `search_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:67:in `issues_for_formula'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:421:in `fetch_pull_requests'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:430:in `check_for_duplicate_pull_requests'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:458:in `check_open_pull_requests'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:149:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

This shows that `brew` is trying to search the repo "my/homebrew-tap" when the actual repo is at "J-M0/my-tap".

### What did you expect to happen?

`bump-formula-pr --write` would write the changes to my formula without interacting with GitHub at all

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap my/tap git@github.com:J-M0/my-tap.git
brew bump-formula-pr --write unrar --version 6.0.4
```

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes #10881

This PR adds a `Tap#remote_repo` method to extract the remote repository name from the tap remote url. This should be used instead of `Tap#full_name` for methods in the `Utils::GitHub` module so that those methods can be used on taps that use non-standard urls.

### CODE REVIEW

File: Library/Homebrew/tap.rb [hunk 1]
```diff
@@ -138,6 +138,14 @@ def remote
     @remote ||= path.git_origin
   end
 
+  # The remote repository name of this {Tap}.
+  # e.g. `user/homebrew-repo`
+  def remote_repo
+    raise TapUnavailableError, name unless installed?
+
+    @remote_repo ||= remote&.sub(%r{^https://github\.com/}, "")&.sub(/\.git$/, "")
```
Comment (MikeMcQuaid) [inline Library/Homebrew/tap.rb:146]:
```suggestion
    return unless remote

    @remote_repo ||= remote.delete_prefix("https://github.com/")
                           .delete_suffix(".git")
```

**Review by MikeMcQuaid — APPROVED** [review]
Nice work!
