### PR TITLE
fix(search.rb): fix regex regression in search

### LINKED ISSUE #19397: TypeError? Parameter 'name': Expected type String, got type Regexp
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [x] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [x] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.22-78-g38385c8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 38385c8cbfc84e0f5659c274149fde0853d2b354
Last commit: 9 hours ago
Branch: master
Core tap HEAD: c850c3a4e0aec8b4147d7c051b01fcc7ef005860
Core tap last commit: 16 minutes ago
Core tap JSON: 28 Feb 03:59 UTC
Core cask tap HEAD: f3125decf75edee0388b481fe04bca6cb40da45b
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 28 Feb 03:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: Solarized (dark)
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 30
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 1
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.48.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3.1-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: 16.2
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew search` with a regex

### What happened (include all command output)?

```sh
brew search '/^font(-)?patcher(@.*)?$/'
Error: Parameter 'name': Expected type String, got type Regexp with value /^font(-)?patcher(@.*)?$/
Caller: /opt/homebrew/Library/Homebrew/search.rb:72
Definition: /opt/homebrew/Library/Homebrew/formula.rb:2264 (Formula.fuzzy_search)
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/call_validation.rb:322:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/call_validation.rb:230:in `block in validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/call_validation.rb:227:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/search.rb:72:in `search_formulae'
/opt/homebrew/Library/Homebrew/search.rb:129:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:81:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11865/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

`brew search` with a regex, as it used to work and the `man`|`--help` indicate it will: `If text is flanked by slashes, it is interpreted as a regular expression.`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew search '/^font(-)?patcher(@.*)?$/'
```

### PR DESCRIPTION
**Pull request by toobuntu**
Fixes a regression in `brew search` which prevented using a regex for the search pattern after strict typing was added to `formula.rb` in commit a81239e. Now performs fuzzy search only if input is a string.

Closes #19397

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

File: Library/Homebrew/search.rb [hunk 1]
```diff
@@ -59,6 +59,8 @@ def self.search_descriptions(string_or_regex, args, search_type: :desc)
     end
 
     def self.search_formulae(string_or_regex)
+      string_or_regex = string_or_regex.source if string_or_regex.is_a?(Regexp)
+
       if string_or_regex.is_a?(String) && string_or_regex.match?(HOMEBREW_TAP_FORMULA_REGEX)
```
Comment (carlocab) [inline Library/Homebrew/search.rb:64]: This doesn't smell right, since `string_or_regex` seems like it could sometimes be a `Regexp`. For example, we wouldn't need to check `string_or_regex.is_a?(String)` below if we just converted `string_or_regex` to a `String` unconditionally.

The rest of this function likely needs refactoring if the right move is, indeed, to ensure that `string_or_regex` is always a `String`.

Comment (toobuntu) [reply Library/Homebrew/search.rb:64]: Good point about the superfluous string check below.

The issue is that `fuzzy_search` method (`formula.rb`) expects a parameter `name` of type `String`, but the `string_or_regex` variable in the `search_formulae` method (`search.rb`) can be either a `String` or a `Regexp`.

This change makes `brew search` work with a regex.

Comment (toobuntu) [reply Library/Homebrew/search.rb:64]: An alternative approach is to leave `search.rb` unmodified (abandon this PR) and instead modify `formula.rb` to allow type `String` or `Regexp`:

```diff
diff --git a/Library/Homebrew/formula.rb b/Library/Homebrew/formula.rb
index 1770c1344b..dcf897d823 100644
--- a/Library/Homebrew/formula.rb
+++ b/Library/Homebrew/formula.rb
@@ -2260,11 +2260,18 @@ class Formula
   end
 
   # Returns a list of approximately matching formula names, but not the complete match
-  sig { params(name: String).returns(T::Array[String]) }
-  def self.fuzzy_search(name)
+  sig { params(name_or_regex: T.any(String, Regexp)).returns(T::Array[String]) }
+  def self.fuzzy_search(name_or_regex)
+    # If input is a String, create a fuzzy Regexp pattern
+    pattern = if name_or_regex.is_a?(String)
+      /#{Regexp.escape(name_or_regex)}/i
+    else
+      name_or_regex
+    end
+
     @spell_checker ||= T.let(DidYouMean::SpellChecker.new(dictionary: Set.new(names + full_names).to_a),
                              T.nilable(DidYouMean::SpellChecker))
-    T.cast(@spell_checker.correct(name), T::Array[String])
+    T.cast(@spell_checker.correct(pattern), T::Array[String])
   end
 
   sig { params(name: T.any(Pathname, String)).returns(Formula) }
```

Comment (carlocab) [reply Library/Homebrew/search.rb:64]: Seems better, but
```ruby
T.cast(@spell_checker.correct(name_or_regex), T::Array[String])
```
seems like it should be
```ruby
T.cast(@spell_checker.correct(name_or_regex), T.any(T::Array[String], T::Array[Regexp]))
```
or
```ruby
T.cast(@spell_checker.correct(name_or_regex), T::Array[T.any(String, Regexp)])
```
CC @dduugg for thoughts.

Comment (carlocab) [reply Library/Homebrew/search.rb:64]: Ah, no, maybe I'm misreading what `@spell_checker.correct(name_or_regex` is supposed to be.

Comment (toobuntu) [reply Library/Homebrew/search.rb:64]: IIUC, it is supposed to return an array of strings (formulae and cask tokens), regardless whether the search pattern is a string or a regex. With the proposed change, `brew search` does seem to be working again in both cases.

Test:

```sh
patterns=(
  '/^domzilla(@.*)?/'
  domzilla
  '/^python(@.*)?$/'
  invalid-token
  '/invalid-token/'
)
for i in "${patterns[@]}"; do
  echo
  echo "pattern = $i"
  brew search "$i"
done

pattern = /^domzilla(@.*)?/
==> Casks
domzilla-caffeine ✔

pattern = domzilla
==> Casks
domzilla-caffeine ✔

pattern = /^python(@.*)?$/
==> Formulae
python@3.10 ✔             python@3.12 ✔             python@3.8
python@3.11               python@3.13 ✔             python@3.9

pattern = invalid-token
Error: No formulae or casks found for "invalid-token".

pattern = /invalid-token/
Error: No formulae or casks found for "/invalid-token/".
```

Comment (carlocab) [reply Library/Homebrew/search.rb:64]: Great; sounds good. Feel free to update this PR or open a new one.

Comment (toobuntu) [reply Library/Homebrew/search.rb]: Updated this PR

Comment (Bo98) [reply Library/Homebrew/search.rb]: `DidYouMean` does not support regexes AFAICT. `Formula.fuzzy_search` never returned a non-empty array for regexes so simply skipping the call under a regex makes sense to me. Fuzzy seraching when you already have a regex doesn't really make much sense.

**Comment by carlocab** [comment]
Pardon the review request from Copilot -- hadn't seen that option before so I'm curious about what it does.

**Review by carlocab — APPROVED** [review]
Seems reasonable to me as soon as the typechecking failure is fixed.

**Comment by toobuntu** [comment]
No idea about the `typecheck` error in `DidYouMean::SpellChecker#correct`, whether it should also be allowed to be a `Regexp`. That's upstream https://github.com/sorbet/sorbet/tree/33e70a6a58cbb03dc0440c9a88eddd1d404d0ed6/rbi/gems/didyoumean.rbi#L51

```rb
  sig {params(input: T.any(String, Symbol)).returns(T::Array[T.any(String, Symbol)])}
```

Perhaps Copilot is on to something.

**Comment by toobuntu** [comment]
Following @Bo98's comment, the following diff passes `brew typecheck` and gets `brew search` working again with regexes. By which I mean, to leave `formula.rb` unmodified from master and make the following change to `search.rb`:

```diff
diff --git a/Library/Homebrew/search.rb b/Library/Homebrew/search.rb
index b33a4ccbf1..343c11eef3 100644
--- a/Library/Homebrew/search.rb
+++ b/Library/Homebrew/search.rb
@@ -69,7 +69,11 @@ module Homebrew
 
       aliases = Formula.alias_full_names
       results = search(Formula.full_names + aliases, string_or_regex).sort
-      results |= Formula.fuzzy_search(string_or_regex).map { |n| Formulary.factory(n).full_name }
+      if string_or_regex.is_a?(String)
+        results |= Formula.fuzzy_search(string_or_regex).map do |n|
+          Formulary.factory(n).full_name
+        end
+      end
 
       results.filter_map do |name|
         formula, canonical_full_name = begin
```

Would this be the preferred approach now?

**Comment by MikeMcQuaid** [comment]
> Would this be the preferred approach now?

@toobuntu If it works for you locally and passes CI: yes, please!

**Comment by toobuntu** [comment]
> Thanks for this @toobuntu! Just before I merge: can you confirm explicitly this fixes the issue for you?

Confirming. Let me know if you want to add a test case, and, if so, please provide some guidance for it.

Here's my test script. The results are all as expected. Note the newly introduced incongruity between `pattern = vscodium` and `pattern =  /^vscodium(@.*)?$/`. Because we no longer call fuzzy search when passed a regex, it returns fewer results.

```sh
patterns=(
  '/^domzilla(@.*)?/'
  domzilla
  vscodium
  '/^vscodium(@.*)?$/'
  '/^ruby(@.*)?$/'
  invalid-token
  '/invalid-token(@.*)?/'
)
for i in "${patterns[@]}"; do
 echo
 echo "pattern = $i"
 brew search "$i"
done

pattern = /^domzilla(@.*)?/
==> Casks
domzilla-caffeine ✔

pattern = domzilla
==> Casks
domzilla-caffeine ✔

pattern = vscodium
==> Formulae
vscli

==> Casks
vscodium ✔                             vscodium@insiders

pattern = /^vscodium(@.*)?$/
==> Casks
vscodium ✔                             vscodium@insiders

pattern = /^ruby(@.*)?$/
==> Formulae
ruby ✔       ruby@2.7     ruby@3.0     ruby@3.1 ✔   ruby@3.2     ruby@3.3

pattern = invalid-token
Error: No formulae or casks found for "invalid-token".

pattern = /invalid-token(@.*)?/
Error: No formulae or casks found for "/invalid-token(@.*)?/".
```

**Comment by MikeMcQuaid** [comment]
Thanks for confirming and for the PR, you rock!
