### PR TITLE
use --time-cond when caching the formula api json

### LINKED ISSUE #13583: `Error: 767` on macOS Big Sur with `HOMEBREW_INSTALL_FROM_API`
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.5-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 3 days ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.7-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

On macOS Big Sur with `HOMEBREW_INSTALL_FROM_API` set and `homebrew/core` not tapped, most `brew` commands return an `Error: 767` due to trying to parse an empty JSON file. This is because `curl` version `7.64.1` included with macOS Big Sur writes a zero-byte file to `cached_formula_json_file` when using `--header "If-Modified-Since:<date>"` and receives a `304` response code (See `curl` [issue 382](https://github.com/curl/curl/issues/382)). This is not applicable to macOS Monterey (`curl` version `7.79.1`, which handles the `304` response without writing to the output file).

Deleting the zero-byte cached json file fixes the problem but only for the next `brew` run, when it will create a new zero-byte file that can't be parsed.

### What happened (include all command output)?

``` bash
❯ brew info rsync
Error: 767: unexpected token at ''
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/api/formula.rb:40:in `all_formulae'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:655:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:541:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:626:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:622:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:141:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

``` bash
❯ du -sh ~/Library/Caches/Homebrew/api/formula.json
  0B	/Users/shahn/Library/Caches/Homebrew/api/formula.json
❯ rm -f ~/Library/Caches/Homebrew/api/formula.json
```

``` bash
❯ brew info rsync
rsync: stable 3.2.4 (bottled)
Utility that provides fast incremental file transfer
https://rsync.samba.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rsync.rb
License: GPL-3.0-or-later
==> Dependencies
Required: lz4 ✘, openssl@1.1 ✘, popt ✘, xxhash ✘, zstd ✘
==> Analytics
install: 18,549 (30 days), 46,176 (90 days), 93,066 (365 days)
install-on-request: 17,966 (30 days), 44,628 (90 days), 89,570 (365 days)
build-error: 2 (30 days)
```

### What did you expect to happen?

I expected `brew` commands to work normally even though I have `HOMEBREW_INSTALL_FROM_API` set and `homebrew/core` untapped. I have a proposed fix and will submit a PR shortly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
export HOMEBREW_INSTALL_FROM_API=1
brew untap homebrew/core
brew info rsync
brew install rsync
```

### PR DESCRIPTION
**Pull request by steveh7812**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----
This is to fix #13583 by using `--time-cond "<date>"` instead of `--header "If-Modified-Since: <date>"` when refreshing the cached Formula API. This prevents older versions of `curl` (such as the Apple-supplied `curl` in macOS Big Sur) from writing a zero-byte .json file. My change will also skip the mtime comparison and overwrite the cache file if the cache file is empty, in order to automatically fix this issue on affected systems.

### CODE REVIEW

File: Library/Homebrew/api/formula.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def all_formulae
             if cached_formula_json_file.exist?
               last_modified = cached_formula_json_file.mtime.utc
               last_modified = last_modified.strftime("%a, %d %b %Y %H:%M:%S GMT")
-              curl_args = ["--header", "If-Modified-Since: #{last_modified}", *curl_args]
+              curl_args = ["--time-cond", last_modified, *curl_args] unless cached_formula_json_file.empty?
```
Comment (carlocab) [inline Library/Homebrew/api/formula.rb:36]: It seems like we can pass `cached_formula_json_file` to `--time-cond` to avoid having to get its `mtime`. Do we also want to use `--remote-time` here?

File: Library/Homebrew/api/formula.rb [hunk 2]
```diff
@@ -33,7 +33,7 @@ def all_formulae
             if cached_formula_json_file.exist?
```
Comment (carlocab) [inline Library/Homebrew/api/formula.rb:33]:
```suggestion
            if cached_formula_json_file.exist? && !cached_formula_json_file.empty?
```
It makes more sense to have this condition up here, no?

File: Library/Homebrew/api/formula.rb (hunk 1 above)
Comment (Rylan12) [reply Library/Homebrew/api/formula.rb:36]: `curl_download` adds `--remote-time` automatically

Comment (carlocab) [reply Library/Homebrew/api/formula.rb:36]: So I guess this whole `if` block can be something like
```ruby
if cached_formula_json_file.exist? && !cached_formula_json_file.empty?
  curl_args.unshift("--time-cond", cached_formula_json_file)
end
```
or even as a single line, if it fits the line length limit.

Comment (Rylan12) [reply Library/Homebrew/api/formula.rb:36]: Yep. Might need a `#to_s` on the `cached_formula_json_file`, I'm not sure off the top of my head.

File: Library/Homebrew/api/formula.rb (hunk 2 above)
Comment (steveh7812) [reply Library/Homebrew/api/formula.rb]: Yes, this makes more sense--fixed.

File: Library/Homebrew/api/formula.rb (hunk 1 above)
Comment (steveh7812) [reply Library/Homebrew/api/formula.rb]: This modified `if` block works, though as a one-liner it's too long for `brew style` to allow. I just pushed this change to my branch.

**Review by Rylan12 — APPROVED** [review]
Looks good to me! Thanks for the PR, @steveh7812!

**Review by carlocab — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great work @steveh7812!
